# Generated by Django 5.2.15 on 2026-07-10 04:07

import accident_report.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0020_add_watch_division'),
        ('vehicles', '0014_vehicle_bereich'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('report_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Berichts-Nr.')),
                ('severity', models.CharField(choices=[('leicht', 'Leichtverletzung'), ('meldepflichtig', 'Meldepflichtig (> 3 Tage AU)'), ('schwer', 'Schwerer Unfall'), ('tod', 'Tödlicher Unfall')], default='leicht', max_length=20, verbose_name='Schwere')),
                ('injured_name', models.CharField(blank=True, max_length=200, verbose_name='Name (falls extern / nicht im System)')),
                ('injured_birthdate', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('injured_function', models.CharField(blank=True, max_length=150, verbose_name='Funktion / Dienstgrad')),
                ('injured_contact', models.CharField(blank=True, max_length=200, verbose_name='Kontakt (Telefon / Anschrift)')),
                ('accident_date', models.DateField(verbose_name='Unfalldatum')),
                ('accident_time', models.TimeField(blank=True, null=True, verbose_name='Unfallzeit')),
                ('location', models.CharField(max_length=250, verbose_name='Unfallort')),
                ('activity_type', models.CharField(choices=[('einsatz', 'Einsatz'), ('uebung', 'Übung'), ('ausbildung', 'Aus-/Fortbildung'), ('dienstsport', 'Dienstsport'), ('arbeitsdienst', 'Arbeits-/Gerätedienst'), ('veranstaltung', 'Veranstaltung / Absicherung'), ('anfahrt', 'An-/Rückfahrt zum Dienst'), ('sonstiges', 'Sonstiges')], default='einsatz', max_length=20, verbose_name='Tätigkeit zum Unfallzeitpunkt')),
                ('activity_detail', models.CharField(blank=True, max_length=250, verbose_name='Bezug (Einsatz-Nr. / Bezeichnung)')),
                ('description', models.TextField(verbose_name='Unfallhergang')),
                ('cause', models.TextField(blank=True, verbose_name='Unfallursache')),
                ('injury_type', models.CharField(blank=True, max_length=250, verbose_name='Art der Verletzung')),
                ('body_part', models.CharField(blank=True, max_length=250, verbose_name='Betroffene Körperteile')),
                ('first_aid_given', models.BooleanField(default=False, verbose_name='Erste Hilfe geleistet')),
                ('first_aid_by', models.CharField(blank=True, max_length=200, verbose_name='Erste Hilfe durch')),
                ('doctor_visited', models.BooleanField(default=False, verbose_name='Ärztliche Behandlung')),
                ('doctor_hospital', models.CharField(blank=True, max_length=200, verbose_name='Arzt / Krankenhaus')),
                ('incapacity_expected', models.BooleanField(default=False, verbose_name='Arbeitsunfähigkeit zu erwarten')),
                ('witnesses', models.TextField(blank=True, verbose_name='Zeugen (Name, Kontakt)')),
                ('reported_to', models.CharField(blank=True, max_length=200, verbose_name='Gemeldet an')),
                ('reported_date', models.DateField(blank=True, null=True, verbose_name='Meldedatum')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('injured_person', models.ForeignKey(blank=True, help_text='Optional – bei Mitgliedern aus dem Personalstamm auswählen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accident_reports', to='personnel.person', verbose_name='Person (aus Personalstamm)')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accident_reports', to='vehicles.vehicle', verbose_name='Beteiligtes Fahrzeug')),
            ],
            options={
                'verbose_name': 'Unfallbericht',
                'verbose_name_plural': 'Unfallberichte',
                'ordering': ['-accident_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccidentReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('image', models.ImageField(upload_to=accident_report.models.accident_image_path, verbose_name='Bild')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accident_report.accidentreport', verbose_name='Unfallbericht')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_accident_images', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Unfallbericht-Bild',
                'verbose_name_plural': 'Unfallbericht-Bilder',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['report_number'], name='accident_re_report__e0febe_idx'),
        ),
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['accident_date'], name='accident_re_acciden_0ff781_idx'),
        ),
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['severity'], name='accident_re_severit_9eaced_idx'),
        ),
    ]
