# Generated by Django 5.2.15 on 2026-07-10 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_report', '0002_unfallbeauftragter_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_contact',
            field=models.CharField(blank=True, max_length=200, verbose_name='Melder – Kontakt (Telefon / E-Mail)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Melder – Vorname'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='reporter_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Melder – Nachname'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accident_report_accidentreport_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accident_report_accidentreport_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von'),
        ),
        migrations.AlterField(
            model_name='accidentreportimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_accident_images', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von'),
        ),
    ]
