# Generated by Django 5.2.15 on 2026-09-11 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accident_report', '0003_accidentreport_reporter_contact_and_more'),
        ('personnel', '0021_person_manage_ff_person'),
        ('vehicles', '0016_seed_call_sign_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentreport',
            name='blue_light_siren',
            field=models.BooleanField(default=False, verbose_name='Blaulicht und Einsatzhorn eingeschaltet'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='incident_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Einsatznummer'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='injuries_occurred',
            field=models.BooleanField(default=True, verbose_name='Verletzte (auch leicht)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_circumstances',
            field=models.JSONField(blank=True, default=list, verbose_name='Umstände Unfallgegner (Ziffer 12)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_damage',
            field=models.TextField(blank=True, verbose_name='Sichtbare Schäden am Fahrzeug des Unfallgegners'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_driver_license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Führerschein-Nr. Unfallgegner'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_driver_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fahrer/in Unfallgegner (falls abweichend)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_holder_address',
            field=models.CharField(blank=True, max_length=250, verbose_name='Anschrift Halter'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_holder_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Halter / Versicherungsnehmer'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_holder_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon Halter'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_impact_point',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('front_left', 'Front links'), ('front_right', 'Front rechts'), ('left', 'Seite links'), ('right', 'Seite rechts'), ('rear', 'Heck'), ('rear_left', 'Heck links'), ('rear_right', 'Heck rechts'), ('top', 'Dach / oben'), ('unknown', 'Unbekannt / mehrere')], max_length=20, verbose_name='Punkt des ersten Anstoßes (Unfallgegner)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_insurance_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Versicherungsschein-Nr.'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_insurer',
            field=models.CharField(blank=True, max_length=150, verbose_name='Versicherer'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_property_damage',
            field=models.BooleanField(default=False, verbose_name='Andere Sachschäden (außer an den Fahrzeugen)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_property_damage_detail',
            field=models.TextField(blank=True, verbose_name='Beschreibung der Sachschäden'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_vehicle_involved',
            field=models.BooleanField(default=False, verbose_name='Weiteres Fahrzeug beteiligt'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_vehicle_make',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marke, Typ'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='other_vehicle_plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kennzeichen Unfallgegner'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='own_circumstances',
            field=models.JSONField(blank=True, default=list, verbose_name='Umstände Dienstfahrzeug (Ziffer 12)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='own_damage',
            field=models.TextField(blank=True, verbose_name='Sichtbare Schäden am Dienstfahrzeug'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='own_driver_license_class',
            field=models.CharField(blank=True, max_length=20, verbose_name='Führerscheinklasse'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='own_driver_license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Führerschein-Nr.'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='own_driver_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fahrer/in Dienstfahrzeug'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='own_impact_point',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('front_left', 'Front links'), ('front_right', 'Front rechts'), ('left', 'Seite links'), ('right', 'Seite rechts'), ('rear', 'Heck'), ('rear_left', 'Heck links'), ('rear_right', 'Heck rechts'), ('top', 'Dach / oben'), ('unknown', 'Unbekannt / mehrere')], max_length=20, verbose_name='Punkt des ersten Anstoßes (Dienstfahrzeug)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='own_vehicle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Dienstfahrzeug (Funkrufname / Bezeichnung)'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='own_vehicle_plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kennzeichen Dienstfahrzeug'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='paper_report_completed',
            field=models.BooleanField(default=False, verbose_name='Europäischer Unfallbericht in Papierform ausgefüllt'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='police_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dienststelle / Tagebuch-Nr.'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='police_involved',
            field=models.BooleanField(default=False, verbose_name='Polizei hat den Unfall aufgenommen'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='report_type',
            field=models.CharField(choices=[('verkehrsunfall', 'Verkehrsunfall mit Dienstfahrzeug'), ('personenunfall', 'Unfall / Verletzung im Dienst (ohne Fahrzeugschaden)')], default='personenunfall', max_length=20, verbose_name='Art des Unfalls'),
        ),
        migrations.AddField(
            model_name='accidentreport',
            name='special_rights',
            field=models.BooleanField(default=False, verbose_name='Einsatzfahrt mit Sonder-/Wegerechten (§ 35 / § 38 StVO)'),
        ),
        migrations.AlterField(
            model_name='accidentreport',
            name='activity_detail',
            field=models.CharField(blank=True, max_length=250, verbose_name='Einsatzstichwort / Bezeichnung'),
        ),
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['report_type'], name='accident_re_report__9f69b5_idx'),
        ),
        migrations.AddIndex(
            model_name='accidentreport',
            index=models.Index(fields=['incident_number'], name='accident_re_inciden_e1208d_idx'),
        ),
    ]
