# Generated by Django 5.0.14 on 2025-10-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobilnummer des Ansprechpartners', max_length=50, verbose_name='Mobiltelefon'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='parts_department_phone',
            field=models.CharField(blank=True, help_text='Telefon Ersatzteilbestellung', max_length=50, verbose_name='Ersatzteil-Abteilung'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='service_email',
            field=models.EmailField(blank=True, help_text='E-Mail für Service-Anfragen', max_length=254, verbose_name='Service-E-Mail'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='support_hotline',
            field=models.CharField(blank=True, help_text='Technischer Support / Notfall-Hotline', max_length=50, verbose_name='Support-Hotline'),
        ),
    ]
