# Generated by Django 5.0.14 on 2025-11-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_base', '0002_add_vehicle_fields_to_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='module',
            field=models.CharField(choices=[('magazine', 'Magazin'), ('equipment', 'Ausrüstung'), ('clothing', 'Kleiderkammer'), ('medical', 'Rettungsdienst'), ('workshop', 'KFZ-Werkstatt'), ('height_rescue', 'Höhenrettung'), ('diving', 'Taucher'), ('it_hardware', 'IT-Hardware')], default='magazine', help_text='Zugehöriges Lager-Modul', max_length=50, verbose_name='Modul'),
        ),
    ]
