# Generated by Django 5.0.14 on 2025-10-23 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategorie-Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(default='📁', max_length=10, verbose_name='Icon (Emoji)')),
                ('color', models.CharField(default='#3B82F6', help_text='z.B. #3B82F6', max_length=7, verbose_name='Farbe (Hex)')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='wiki.wikicategory', verbose_name='Übergeordnete Kategorie')),
            ],
            options={
                'verbose_name': 'Wiki-Kategorie',
                'verbose_name_plural': 'Wiki-Kategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-Slug')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'In Prüfung'), ('published', 'Veröffentlicht'), ('archived', 'Archiviert')], default='draft', max_length=20, verbose_name='Status')),
                ('visibility', models.CharField(choices=[('public', 'Öffentlich (alle Nutzer)'), ('internal', 'Intern (angemeldete Nutzer)'), ('restricted', 'Eingeschränkt (nur bestimmte Rollen)')], default='internal', max_length=20, verbose_name='Sichtbarkeit')),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='Liste von Rollen-Namen für eingeschränkten Zugriff', verbose_name='Erlaubte Rollen')),
                ('description', models.TextField(blank=True, help_text='Für Suche und Übersichten (max. 200 Zeichen)', verbose_name='Kurzbeschreibung')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Liste von Tags für bessere Auffindbarkeit', verbose_name='Tags')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='wiki/covers/', verbose_name='Titelbild')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('view_count', models.IntegerField(default=0, verbose_name='Aufrufe')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt angesehen')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Geprüft am')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Gelöscht am')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='wiki.wikicategory', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='Gelöscht von')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='Geprüft von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Wiki-Seite',
                'verbose_name_plural': 'Wiki-Seiten',
                'ordering': ['-updated_at'],
                'permissions': [('publish_wiki_page', 'Can publish wiki page'), ('approve_wiki_page', 'Can approve wiki page for publication'), ('delete_any_wiki_page', 'Can delete any wiki page'), ('manage_wiki_categories', 'Can manage wiki categories'), ('view_draft_pages', 'Can view draft pages'), ('view_internal_pages', 'Can view internal pages')],
            },
        ),
        migrations.CreateModel(
            name='WikiBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('Text', [('heading_1', 'Überschrift 1'), ('heading_2', 'Überschrift 2'), ('heading_3', 'Überschrift 3'), ('paragraph', 'Absatz'), ('quote', 'Zitat')]), ('Listen & Aufzählungen', [('checklist', 'Checkliste')]), ('Medien', [('image', 'Bild'), ('video', 'Video'), ('file', 'Datei'), ('embed', 'Embed (URL)')]), ('Struktur', [('table', 'Tabelle'), ('columns', 'Spalten'), ('accordion', 'Akkordeon'), ('divider', 'Trennlinie')]), ('Hervorhebungen', [('callout', 'Hinweis-Box'), ('alert', 'Warnung/Alert'), ('code', 'Code-Block')])], max_length=20, verbose_name='Block-Typ')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('content', models.JSONField(default=dict, help_text='Block-spezifische Daten als JSON', verbose_name='Inhalt')),
                ('style_options', models.JSONField(blank=True, default=dict, help_text='Farbe, Ausrichtung, Größe, etc.', verbose_name='Style-Optionen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='wiki.wikipage', verbose_name='Wiki-Seite')),
            ],
            options={
                'verbose_name': 'Wiki-Block',
                'verbose_name_plural': 'Wiki-Blöcke',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WikiPageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='Versions-Nummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('blocks_snapshot', models.JSONField(help_text='Kompletter Block-Inhalt als JSON', verbose_name='Blocks-Snapshot')),
                ('change_summary', models.TextField(blank=True, verbose_name='Änderungs-Zusammenfassung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_revisions', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='wiki.wikipage', verbose_name='Wiki-Seite')),
            ],
            options={
                'verbose_name': 'Wiki-Revision',
                'verbose_name_plural': 'Wiki-Revisionen',
                'ordering': ['-version'],
                'unique_together': {('page', 'version')},
            },
        ),
    ]
