# Generated by Django 5.2.15 on 2026-06-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiblock',
            name='block_type',
            field=models.CharField(choices=[('Text', [('heading_1', 'Überschrift 1'), ('heading_2', 'Überschrift 2'), ('heading_3', 'Überschrift 3'), ('paragraph', 'Absatz'), ('quote', 'Zitat')]), ('Listen & Aufzählungen', [('checklist', 'Checkliste')]), ('Verlinkung', [('wiki_link', 'Wiki-Link')]), ('Medien', [('image', 'Bild'), ('video', 'Video'), ('file', 'Datei'), ('embed', 'Embed (URL)')]), ('Struktur', [('table', 'Tabelle'), ('columns', 'Spalten'), ('accordion', 'Akkordeon'), ('divider', 'Trennlinie')]), ('Hervorhebungen', [('callout', 'Hinweis-Box'), ('alert', 'Warnung/Alert'), ('code', 'Code-Block')])], max_length=20, verbose_name='Block-Typ'),
        ),
    ]
