# Generated by Django 5.2.15 on 2026-09-30 14:17

import django.db.models.deletion
import wiki.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_wikiblock_block_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Für Handbücher mit Kapiteln: die Seite, unter der diese Seite einsortiert wird', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='wiki.wikipage', verbose_name='Übergeordnete Seite'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='search_text',
            field=models.TextField(blank=True, editable=False, help_text='Automatisch aus den Blöcken erzeugter Text für die Suche', verbose_name='Volltext'),
        ),
        migrations.AlterField(
            model_name='wikiblock',
            name='block_type',
            field=models.CharField(choices=[('Text', [('heading_1', 'Überschrift 1'), ('heading_2', 'Überschrift 2'), ('heading_3', 'Überschrift 3'), ('paragraph', 'Absatz'), ('quote', 'Zitat')]), ('Listen & Aufzählungen', [('bullet_list', 'Aufzählung'), ('numbered_list', 'Nummerierte Liste'), ('checklist', 'Checkliste'), ('steps', 'Schritt-für-Schritt')]), ('Verlinkung', [('wiki_link', 'Wiki-Link')]), ('Medien', [('image', 'Bild'), ('video', 'Video'), ('file', 'Datei'), ('embed', 'Embed (URL)')]), ('Struktur', [('table', 'Tabelle'), ('columns', 'Spalten'), ('accordion', 'Akkordeon'), ('divider', 'Trennlinie')]), ('Hervorhebungen', [('callout', 'Hinweis-Box'), ('alert', 'Warnung/Alert'), ('code', 'Code-Block')])], max_length=20, verbose_name='Block-Typ'),
        ),
        migrations.CreateModel(
            name='WikiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=wiki.models.wiki_attachment_upload_path, verbose_name='Datei')),
                ('original_name', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Typ')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Größe (Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wiki.wikipage', verbose_name='Wiki-Seite')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Wiki-Anhang',
                'verbose_name_plural': 'Wiki-Anhänge',
                'ordering': ['-created_at'],
            },
        ),
    ]
