# Generated by Django 5.0.14 on 2025-10-03 12:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('check_number', models.CharField(help_text='Automatisch generiert, z.B. INV-2025-0001', max_length=50, unique=True, verbose_name='Inventur-Nummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('check_type', models.CharField(choices=[('full', 'Vollinventur'), ('partial', 'Teilinventur'), ('spot_check', 'Stichprobe'), ('cycle_count', 'Zykluszählung'), ('annual', 'Jahresinventur')], default='partial', max_length=20, verbose_name='Inventurart')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('counting_complete', 'Zählung abgeschlossen'), ('review', 'In Prüfung'), ('adjustments_pending', 'Korrekturen ausstehend'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='planned', max_length=30, verbose_name='Status')),
                ('scheduled_start_date', models.DateField(verbose_name='Geplanter Starttermin')),
                ('scheduled_end_date', models.DateField(verbose_name='Geplanter Endtermin')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächlicher Start')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('module_filter', models.CharField(blank=True, help_text='z.B. "medical", "magazine" - Leer = Alle Module', max_length=50, verbose_name='Modul-Filter')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Gesamt-Anzahl Artikel')),
                ('counted_items', models.PositiveIntegerField(default=0, verbose_name='Gezählte Artikel')),
                ('items_with_discrepancies', models.PositiveIntegerField(default=0, verbose_name='Artikel mit Abweichungen')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_checks_approved', to='personnel.person', verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, help_text='Leer = Alle Lagerorte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_checks', to='locations.location', verbose_name='Lagerort')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_checks_responsible', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('team_members', models.ManyToManyField(blank=True, related_name='inventory_checks_team', to='personnel.person', verbose_name='Team-Mitglieder')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Inventur',
                'verbose_name_plural': 'Inventuren',
                'db_table': 'inventory_check',
                'ordering': ['-scheduled_start_date', '-check_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('inventory_object_id', models.PositiveIntegerField(verbose_name='Lager-Artikel-ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Artikelbezeichnung')),
                ('item_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer')),
                ('expected_quantity', models.DecimalField(decimal_places=2, help_text='Bestand laut System', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sollbestand')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Tatsächlich gezählter Bestand', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Istbestand')),
                ('is_counted', models.BooleanField(default=False, verbose_name='Gezählt')),
                ('counted_date', models.DateTimeField(blank=True, null=True, verbose_name='Zähldatum')),
                ('has_discrepancy', models.BooleanField(default=False, verbose_name='Abweichung vorhanden')),
                ('variance_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Positiv = Überschuss, Negativ = Fehlbestand', max_digits=10, verbose_name='Abweichungsmenge')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('requires_recount', models.BooleanField(default=False, verbose_name='Nachzählung erforderlich')),
                ('recount_done', models.BooleanField(default=False, verbose_name='Nachzählung durchgeführt')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_counted', to='personnel.person', verbose_name='Gezählt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory_check.inventorycheck', verbose_name='Inventur')),
                ('inventory_content_type', models.ForeignKey(help_text='z.B. MagazineItem, MedicalItem, etc.', on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='Lager-Artikeltyp')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_items', to='locations.location', verbose_name='Lagerort')),
                ('recounted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items_recounted', to='personnel.person', verbose_name='Nachgezählt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Inventur-Position',
                'verbose_name_plural': 'Inventur-Positionen',
                'db_table': 'inventory_check_item',
                'ordering': ['location', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('discrepancy_type', models.CharField(choices=[('surplus', 'Überschuss'), ('shortage', 'Fehlbestand'), ('damaged', 'Beschädigt'), ('expired', 'Abgelaufen'), ('mislabeled', 'Falsch gekennzeichnet'), ('mislocated', 'Falsch eingelagert')], max_length=20, verbose_name='Abweichungsart')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Abweichungsmenge')),
                ('cause', models.TextField(help_text='Beschreibung der vermuteten oder festgestellten Ursache', verbose_name='Ursache')),
                ('found_date', models.DateTimeField(auto_now_add=True, verbose_name='Feststellungsdatum')),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wert pro Einheit (€)')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gesamtwert der Abweichung (€)')),
                ('corrective_action', models.TextField(blank=True, help_text='Geplante oder durchgeführte Maßnahme', verbose_name='Korrekturmaßnahme')),
                ('correction_applied', models.BooleanField(default=False, verbose_name='Korrektur durchgeführt')),
                ('correction_date', models.DateTimeField(blank=True, null=True, verbose_name='Korrekturdatum')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste von Foto-URLs', verbose_name='Fotos')),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='inventory_check.inventorycheckitem', verbose_name='Inventur-Position')),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies_corrected', to='personnel.person', verbose_name='Korrigiert von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('found_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies_found', to='personnel.person', verbose_name='Festgestellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Inventur-Abweichung',
                'verbose_name_plural': 'Inventur-Abweichungen',
                'db_table': 'inventory_discrepancy',
                'ordering': ['-found_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('adjustment_number', models.CharField(help_text='Automatisch generiert, z.B. ADJ-2025-0001', max_length=50, unique=True, verbose_name='Korrekturnummer')),
                ('adjustment_date', models.DateTimeField(verbose_name='Buchungsdatum')),
                ('old_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alter Bestand')),
                ('new_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Neuer Bestand')),
                ('adjustment_quantity', models.DecimalField(decimal_places=2, help_text='Positiv = Zugang, Negativ = Abgang', max_digits=10, verbose_name='Korrekturbetrag')),
                ('reason', models.TextField(verbose_name='Begründung')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigungsdatum')),
                ('applied', models.BooleanField(default=False, help_text='Wurde die Korrektur im Lagersystem gebucht?', verbose_name='Angewendet')),
                ('applied_date', models.DateTimeField(blank=True, null=True, verbose_name='Anwendungsdatum')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_approved', to='personnel.person', verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory_check.inventorycheck', verbose_name='Inventur')),
                ('check_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory_check.inventorycheckitem', verbose_name='Inventur-Position')),
                ('discrepancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory_check.inventorydiscrepancy', verbose_name='Zugehörige Abweichung')),
            ],
            options={
                'verbose_name': 'Korrekturbuchung',
                'verbose_name_plural': 'Korrekturbuchungen',
                'db_table': 'inventory_adjustment',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['check_number'], name='inventory_c_check_n_f68b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['status'], name='inventory_c_status_8b7912_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['-scheduled_start_date'], name='inventory_c_schedul_04bd3f_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['responsible_person', '-scheduled_start_date'], name='inventory_c_respons_97b77a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheck',
            index=models.Index(fields=['location'], name='inventory_c_locatio_a58da0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheckitem',
            index=models.Index(fields=['inventory_check', 'is_counted'], name='inventory_c_invento_0c1605_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheckitem',
            index=models.Index(fields=['inventory_check', 'has_discrepancy'], name='inventory_c_invento_49d9e2_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheckitem',
            index=models.Index(fields=['location'], name='inventory_c_locatio_bc97d8_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycheckitem',
            index=models.Index(fields=['counted_by'], name='inventory_c_counted_5be934_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorydiscrepancy',
            index=models.Index(fields=['check_item'], name='inventory_d_check_i_95d4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorydiscrepancy',
            index=models.Index(fields=['discrepancy_type'], name='inventory_d_discrep_99f727_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorydiscrepancy',
            index=models.Index(fields=['correction_applied'], name='inventory_d_correct_5d8b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorydiscrepancy',
            index=models.Index(fields=['found_by', '-found_date'], name='inventory_d_found_b_ebed58_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['adjustment_number'], name='inventory_a_adjustm_3b1d14_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['inventory_check', '-adjustment_date'], name='inventory_a_invento_e5ad30_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['applied'], name='inventory_a_applied_5dbae0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryadjustment',
            index=models.Index(fields=['approved_by'], name='inventory_a_approve_28c60c_idx'),
        ),
    ]
