# Generated by Django 5.0.14 on 2025-10-03 11:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisinfectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_number', models.CharField(help_text='Eindeutige Artikelnummer', max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Hersteller-Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestand')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Warnung bei Unterschreitung', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximalbestand')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode/EAN')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR-Code')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/images/', verbose_name='Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('disinfection_type', models.CharField(choices=[('surface_spray', 'Flächendesinfektionsspray'), ('surface_wipes', 'Desinfektionstücher'), ('surface_concentrate', 'Flächendesinfektions-Konzentrat'), ('surface_ready_to_use', 'Flächendesinfektion gebrauchsfertig'), ('hand_disinfection', 'Händedesinfektionsmittel'), ('hand_sanitizer_gel', 'Händedesinfektionsgel'), ('hand_sanitizer_foam', 'Händedesinfektionsschaum'), ('instrument_disinfection', 'Instrumentendesinfektion'), ('instrument_concentrate', 'Instrumentendesinfektions-Konzentrat'), ('laundry_disinfection', 'Wäschedesinfektionsmittel'), ('vehicle_disinfection', 'Fahrzeugdesinfektion'), ('room_disinfection', 'Raumdesinfektion'), ('nebulizer_solution', 'Verneblerlösung'), ('uv_disinfection', 'UV-Desinfektion (Gerät)'), ('ozone_generator', 'Ozongenerator (Gerät)'), ('protective_gloves', 'Schutzhandschuhe'), ('protective_suit', 'Schutzanzug'), ('face_shield', 'Gesichtsschutz'), ('respirator', 'Atemschutzmaske'), ('spray_bottle', 'Sprühflasche'), ('dispenser', 'Spender'), ('dosing_pump', 'Dosierpumpe'), ('measuring_cup', 'Messbecher'), ('other', 'Sonstiges')], max_length=50, verbose_name='Desinfektionsmittel-Typ')),
                ('disinfection_status', models.CharField(choices=[('in_stock', 'Auf Lager'), ('low_stock', 'Niedriger Bestand'), ('out_of_stock', 'Nicht vorrätig'), ('on_order', 'Bestellt'), ('expired', 'Abgelaufen'), ('quarantine', 'Quarantäne')], default='in_stock', max_length=20, verbose_name='Status')),
                ('spectrum', models.JSONField(blank=True, default=list, help_text='Liste der Wirkungsspektren (z.B. ["bactericidal", "virucidal"])', verbose_name='Wirkungsspektrum')),
                ('application_method', models.CharField(blank=True, choices=[('spray', 'Sprühen'), ('wipe', 'Wischen'), ('immersion', 'Tauchen/Einlegen'), ('nebulization', 'Vernebeln'), ('uv_light', 'UV-Licht'), ('ozone', 'Ozon'), ('manual', 'Manuelle Anwendung')], max_length=20, verbose_name='Anwendungsmethode')),
                ('contact_time_minutes', models.PositiveIntegerField(blank=True, help_text='Erforderliche Kontaktzeit für volle Wirkung', null=True, verbose_name='Einwirkzeit (Minuten)')),
                ('dilution_ratio', models.CharField(blank=True, help_text='z.B. 1:100, 2%', max_length=50, verbose_name='Verdünnungsverhältnis')),
                ('registration_number', models.CharField(blank=True, help_text='z.B. BAuA-Nummer, VAH-Listung', max_length=100, verbose_name='Zulassungsnummer')),
                ('vah_listed', models.BooleanField(default=False, help_text='Verbund für Angewandte Hygiene', verbose_name='VAH-gelistet')),
                ('dghm_listed', models.BooleanField(default=False, help_text='Deutsche Gesellschaft für Hygiene und Mikrobiologie', verbose_name='DGHM-gelistet')),
                ('rki_listed', models.BooleanField(default=False, help_text='Robert Koch-Institut', verbose_name='RKI-gelistet')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Gefahrstoff')),
                ('hazard_symbols', models.CharField(blank=True, help_text='GHS-Symbole: GHS02, GHS05, GHS07, etc.', max_length=200, verbose_name='Gefahrensymbole')),
                ('safety_data_sheet', models.FileField(blank=True, null=True, upload_to='disinfection/sds/', verbose_name='Sicherheitsdatenblatt')),
                ('storage_temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Min. Lagertemperatur (°C)')),
                ('storage_temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max. Lagertemperatur (°C)')),
                ('protect_from_light', models.BooleanField(default=False, verbose_name='Vor Licht schützen')),
                ('shelf_life_months', models.PositiveIntegerField(blank=True, help_text='Haltbarkeit ab Herstellungsdatum', null=True, verbose_name='Haltbarkeit (Monate)')),
                ('shelf_life_opened_months', models.PositiveIntegerField(blank=True, help_text='Haltbarkeit nach Anbruch', null=True, verbose_name='Haltbarkeit geöffnet (Monate)')),
                ('active_ingredient', models.CharField(blank=True, help_text='z.B. Ethanol, Isopropanol, Natriumhypochlorit', max_length=200, verbose_name='Wirkstoff')),
                ('concentration', models.CharField(blank=True, help_text='z.B. 70%, 0.5%', max_length=50, verbose_name='Konzentration')),
                ('application_areas', models.JSONField(blank=True, default=list, help_text='z.B. ["Fahrzeuge", "Tragen", "Instrumente", "Hände"]', verbose_name='Anwendungsbereiche')),
                ('assigned_vehicles', models.ManyToManyField(blank=True, help_text='Fahrzeuge, in denen dieses Mittel vorhanden ist', related_name='disinfection_items', to='vehicles.vehicle', verbose_name='Zugeordnete Fahrzeuge')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Desinfektionsmittel',
                'verbose_name_plural': 'Desinfektionsmittel',
                'ordering': ['disinfection_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DisinfectionStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('movement_type', models.CharField(choices=[('incoming', 'Wareneingang'), ('outgoing', 'Warenausgang'), ('transfer', 'Umlagerung'), ('inventory', 'Inventur-Korrektur'), ('damage', 'Beschädigung/Schwund'), ('return', 'Rückgabe'), ('disposal', 'Entsorgung')], max_length=20, verbose_name='Bewegungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('reference_number', models.CharField(blank=True, help_text='z.B. Lieferschein-Nr., Bestellnummer', max_length=100, verbose_name='Referenznummer')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Bewegungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Chargen-/Batch-Nummer')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Produktionsdatum')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Verfallsdatum')),
                ('opened_date', models.DateField(blank=True, help_text='Datum, an dem die Flasche/Packung geöffnet wurde', null=True, verbose_name='Anbruchdatum')),
                ('used_for', models.CharField(blank=True, help_text='z.B. "Fahrzeug XY nach Einsatz", "Trage", "Instrumente"', max_length=200, verbose_name='Verwendet für')),
                ('disinfection_protocol', models.TextField(blank=True, help_text='Beschreibung der durchgeführten Desinfektion', verbose_name='Desinfektionsprotokoll')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückkosten (EUR)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtkosten (EUR)')),
                ('delivery_note', models.CharField(blank=True, max_length=100, verbose_name='Lieferschein-Nr.')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_outgoing', to='locations.location', verbose_name='Von Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='disinfection.disinfectionitem', verbose_name='Desinfektionsmittel')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_disinfections', to='personnel.person', verbose_name='Durchgeführt von')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_incoming', to='locations.location', verbose_name='Nach Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Fahrzeug, dem das Mittel zugeordnet wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disinfection_movements', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': 'Desinfektionsmittel-Lagerbewegung',
                'verbose_name_plural': 'Desinfektionsmittel-Lagerbewegungen',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisinfectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(help_text='z.B. Fahrzeug, Trage, Raum, Instrumente', max_length=50, verbose_name='Objekt-Typ')),
                ('object_description', models.CharField(help_text='Genauere Beschreibung des desinfizierten Objekts', max_length=200, verbose_name='Objekt-Beschreibung')),
                ('disinfection_date', models.DateTimeField(verbose_name='Desinfektionsdatum')),
                ('dilution_used', models.CharField(blank=True, max_length=50, verbose_name='Verwendete Verdünnung')),
                ('contact_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Einwirkzeit (Minuten)')),
                ('method', models.CharField(choices=[('spray', 'Sprühen'), ('wipe', 'Wischen'), ('immersion', 'Tauchen/Einlegen'), ('nebulization', 'Vernebeln'), ('uv_light', 'UV-Licht'), ('ozone', 'Ozon'), ('manual', 'Manuelle Anwendung')], max_length=20, verbose_name='Methode')),
                ('protocol', models.TextField(help_text='Detaillierte Beschreibung der Durchführung', verbose_name='Protokoll')),
                ('reason', models.CharField(blank=True, help_text='z.B. "Nach Infektionstransport", "Routinedesinfektion"', max_length=200, verbose_name='Grund/Anlass')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste von Foto-URLs als Nachweis', verbose_name='Fotos')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_disinfection_logs', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('disinfection_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disinfection_logs', to='disinfection.disinfectionitem', verbose_name='Verwendetes Desinfektionsmittel')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disinfection_logs', to='personnel.person', verbose_name='Durchgeführt von')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disinfection_logs', to='vehicles.vehicle', verbose_name='Fahrzeug')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_disinfections', to='personnel.person', verbose_name='Kontrolliert von')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disinfection_logs', to='disinfection.disinfectionstockmovement', verbose_name='Zugehörige Lagerbewegung')),
            ],
            options={
                'verbose_name': 'Desinfektions-Protokoll',
                'verbose_name_plural': 'Desinfektions-Protokolle',
                'ordering': ['-disinfection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='disinfectionitem',
            index=models.Index(fields=['disinfection_type'], name='disinfectio_disinfe_3ed22d_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionitem',
            index=models.Index(fields=['disinfection_status'], name='disinfectio_disinfe_c91eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionitem',
            index=models.Index(fields=['vah_listed'], name='disinfectio_vah_lis_0cefa4_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionitem',
            index=models.Index(fields=['is_hazardous'], name='disinfectio_is_haza_24b698_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionitem',
            index=models.Index(fields=['registration_number'], name='disinfectio_registr_04a473_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionstockmovement',
            index=models.Index(fields=['item', 'movement_date'], name='disinfectio_item_id_5e055d_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionstockmovement',
            index=models.Index(fields=['vehicle', 'movement_date'], name='disinfectio_vehicle_7ee7e4_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionstockmovement',
            index=models.Index(fields=['batch_number'], name='disinfectio_batch_n_c2bc13_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionstockmovement',
            index=models.Index(fields=['expiry_date'], name='disinfectio_expiry__1221d5_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionstockmovement',
            index=models.Index(fields=['movement_type', 'movement_date'], name='disinfectio_movemen_27165f_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionlog',
            index=models.Index(fields=['vehicle', 'disinfection_date'], name='disinfectio_vehicle_472cc0_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionlog',
            index=models.Index(fields=['object_type', 'disinfection_date'], name='disinfectio_object__703049_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionlog',
            index=models.Index(fields=['performed_by', 'disinfection_date'], name='disinfectio_perform_a1529f_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionlog',
            index=models.Index(fields=['disinfection_item', 'disinfection_date'], name='disinfectio_disinfe_2e4227_idx'),
        ),
    ]
