# Generated by Django 5.0.14 on 2025-10-18 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disinfection', '0003_alter_disinfectionitem_category'),
        ('organization', '0007_function_related_module_and_more'),
        ('personnel', '0015_person_show_private_contact_data_and_more'),
        ('vehicles', '0005_vehicle_actual_retirement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisinfectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategorie-Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(blank=True, help_text='Emoji oder Icon-Symbol', max_length=10, verbose_name='Icon')),
                ('color', models.CharField(blank=True, help_text='Tailwind Color-Class (z.B. blue-500)', max_length=20, verbose_name='Farbe')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierreihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desinfektions-Kategorie',
                'verbose_name_plural': 'Desinfektions-Kategorien',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='disinfectionitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='disinfection.disinfectioncategory', verbose_name='Kategorie'),
        ),
        migrations.CreateModel(
            name='DisinfectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. "RTW 1 - Wöchentliche Desinfektion"', max_length=200, verbose_name='Plan-Name')),
                ('object_type', models.CharField(blank=True, help_text='Falls nicht Fahrzeug: z.B. Raum, Trage, etc.', max_length=50, verbose_name='Objekt-Typ')),
                ('object_description', models.CharField(blank=True, max_length=200, verbose_name='Objekt-Beschreibung')),
                ('frequency', models.CharField(choices=[('daily', 'Täglich'), ('after_each_use', 'Nach jeder Benutzung'), ('weekly', 'Wöchentlich'), ('biweekly', 'Alle 2 Wochen'), ('monthly', 'Monatlich'), ('quarterly', 'Vierteljährlich'), ('biannually', 'Halbjährlich'), ('annually', 'Jährlich'), ('custom', 'Individuell')], default='weekly', max_length=20, verbose_name='Häufigkeit')),
                ('custom_interval_days', models.PositiveIntegerField(blank=True, help_text='Nur bei Häufigkeit "Individuell"', null=True, verbose_name='Benutzerdefiniertes Intervall (Tage)')),
                ('start_date', models.DateField(help_text='Ab wann gilt dieser Plan', verbose_name='Start-Datum')),
                ('end_date', models.DateField(blank=True, help_text='Optional: Bis wann gilt dieser Plan', null=True, verbose_name='End-Datum')),
                ('next_due_date', models.DateField(blank=True, help_text='Automatisch berechnet basierend auf letzter Durchführung', null=True, verbose_name='Nächste fällige Desinfektion')),
                ('description', models.TextField(blank=True, help_text='Spezielle Hinweise oder Anweisungen für die Desinfektion', verbose_name='Beschreibung / Anweisungen')),
                ('contact_time_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Einwirkzeit (Minuten)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('reminder_days_before', models.PositiveIntegerField(default=3, help_text='Wie viele Tage vorher soll erinnert werden', verbose_name='Erinnerung (Tage vorher)')),
                ('send_email_reminder', models.BooleanField(default=True, verbose_name='E-Mail-Erinnerung senden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disinfection_plans', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('required_items', models.ManyToManyField(blank=True, related_name='required_for_plans', to='disinfection.disinfectionitem', verbose_name='Benötigte Desinfektionsmittel')),
                ('responsible_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disinfection_plans', to='organization.department', verbose_name='Verantwortliche Abteilung')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_for_disinfection_plans', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_disinfection_plans', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disinfection_plans', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': 'Desinfektionsplan',
                'verbose_name_plural': 'Desinfektionspläne',
                'ordering': ['next_due_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='disinfectionlog',
            name='disinfection_plan',
            field=models.ForeignKey(blank=True, help_text='Falls diese Desinfektion Teil eines Plans ist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disinfection_logs', to='disinfection.disinfectionplan', verbose_name='Zugehöriger Desinfektionsplan'),
        ),
        migrations.AddIndex(
            model_name='disinfectionplan',
            index=models.Index(fields=['vehicle', 'is_active'], name='disinfectio_vehicle_da1cdd_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionplan',
            index=models.Index(fields=['next_due_date', 'is_active'], name='disinfectio_next_du_7d1d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='disinfectionplan',
            index=models.Index(fields=['frequency'], name='disinfectio_frequen_624e00_idx'),
        ),
    ]
