# Generated by Django 5.0.14 on 2025-10-17 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0003_location_technical_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Einsatzabteilung, Technik, Verwaltung', max_length=200, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, help_text='z.B. EA, TEC, VW', max_length=20, verbose_name='Abkürzung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.IntegerField(default=0, help_text='Niedrigere Werte werden zuerst angezeigt', verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Abteilung',
                'verbose_name_plural': 'Abteilungen',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='organizatio_is_acti_3fe174_idx')],
            },
        ),
        migrations.CreateModel(
            name='VolunteerUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Löschzug 1, Löschgruppe Musterort', max_length=200, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, help_text='z.B. LZ 1, LG Muster', max_length=20, verbose_name='Abkürzung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.IntegerField(default=0, help_text='Niedrigere Werte werden zuerst angezeigt', verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('location', models.ForeignKey(blank=True, help_text='Feuerwehrhaus/Gerätehaus', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='volunteer_units', to='locations.location', verbose_name='Standort')),
            ],
            options={
                'verbose_name': 'FF-Einheit',
                'verbose_name_plural': 'FF-Einheiten',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='organizatio_is_acti_9a77c1_idx'), models.Index(fields=['location'], name='organizatio_locatio_2a145b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WatchCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. A-Schicht Wache 1', max_length=200, verbose_name='Name')),
                ('shift', models.CharField(choices=[('A', 'A-Schicht'), ('B', 'B-Schicht'), ('C', 'C-Schicht'), ('D', 'D-Schicht'), ('E', 'E-Schicht'), ('F', 'F-Schicht')], max_length=1, verbose_name='Schicht')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.IntegerField(default=0, help_text='Niedrigere Werte werden zuerst angezeigt', verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('station', models.ForeignKey(help_text='Feuerwache/Standort', on_delete=django.db.models.deletion.PROTECT, related_name='watch_crews', to='locations.location', verbose_name='Wachenstandort')),
            ],
            options={
                'verbose_name': 'Wachmannschaft',
                'verbose_name_plural': 'Wachmannschaften',
                'ordering': ['station', 'shift', 'sort_order'],
                'indexes': [models.Index(fields=['is_active', 'station', 'shift'], name='organizatio_is_acti_f59cca_idx'), models.Index(fields=['station'], name='organizatio_station_ab782a_idx')],
                'unique_together': {('shift', 'station')},
            },
        ),
    ]
