# Generated by Django 5.0.14 on 2025-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_technical_equipment'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchcrew',
            options={'ordering': ['station', 'sort_order', 'name'], 'verbose_name': 'Wachmannschaft', 'verbose_name_plural': 'Wachmannschaften'},
        ),
        migrations.RemoveIndex(
            model_name='watchcrew',
            name='organizatio_is_acti_f59cca_idx',
        ),
        migrations.AlterUniqueTogether(
            name='watchcrew',
            unique_together={('name', 'station')},
        ),
        migrations.AlterField(
            model_name='watchcrew',
            name='name',
            field=models.CharField(help_text='z.B. 1. Wachmannschaft, 2. Wachmannschaft', max_length=200, verbose_name='Name'),
        ),
        migrations.AddIndex(
            model_name='watchcrew',
            index=models.Index(fields=['is_active', 'station'], name='organizatio_is_acti_c64c58_idx'),
        ),
        migrations.RemoveField(
            model_name='watchcrew',
            name='shift',
        ),
    ]
