# Generated by Django 5.0.14 on 2025-10-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_watchcrew_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchcrew',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='z.B. WA1, WA2, WA3', max_length=20, verbose_name='Kürzel'),
        ),
    ]
