# Generated by Django 5.0.14 on 2025-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_watchcrew_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Gruppenführer, Taucher, Höhenretter', max_length=200, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, help_text='z.B. GF, MA, AGT', max_length=20, verbose_name='Abkürzung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('requires_qualification', models.BooleanField(default=False, help_text='Ist eine spezielle Qualifikation/Ausbildung erforderlich?', verbose_name='Qualifikation erforderlich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.IntegerField(default=0, help_text='Niedrigere Werte werden zuerst angezeigt', verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Funktion',
                'verbose_name_plural': 'Funktionen',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='organizatio_is_acti_6c3b3c_idx')],
            },
        ),
    ]
