# Generated by Django 5.0.14 on 2025-10-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='required_duty_hour_categories',
            field=models.JSONField(blank=True, default=list, help_text='Wählen Sie die Pflichtstunden-Kategorien aus, die für diese Funktion erforderlich sind', verbose_name='Erforderliche Pflichtstunden-Kategorien'),
        ),
    ]
