# Generated by Django 5.0.14 on 2025-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_function_required_duty_hour_categories'),
        ('personnel', '0011_dutyhourscategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='required_duty_hour_categories',
        ),
        migrations.AddField(
            model_name='function',
            name='required_duty_hour_categories',
            field=models.ManyToManyField(blank=True, help_text='Wählen Sie die Pflichtstunden-Kategorien aus, die für diese Funktion erforderlich sind', related_name='required_for_functions', to='personnel.dutyhourscategory', verbose_name='Erforderliche Pflichtstunden-Kategorien'),
        ),
    ]
