# Generated by Django 5.0.14 on 2025-10-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_function_required_duty_hour_categories_and_more'),
        ('personnel', '0014_dutyhourscategory_related_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='related_module',
            field=models.CharField(blank=True, choices=[('equipment', 'Ausrüstung'), ('diving', 'Taucher'), ('height_rescue', 'Höhenrettung')], help_text='Modul, zu dem diese Funktion gehört (z.B. Taucher, Höhenrettung, Ausrüstung)', max_length=50, null=True, verbose_name='Zugeordnetes Modul'),
        ),
        migrations.AddField(
            model_name='function',
            name='required_qualifications',
            field=models.ManyToManyField(blank=True, help_text='Wählen Sie die Qualifikationen aus, die für diese Funktion erforderlich sind', related_name='required_for_functions', to='personnel.qualificationtemplate', verbose_name='Erforderliche Qualifikationen'),
        ),
    ]
