# Generated by Django 5.0.14 on 2026-02-19 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_function_related_module_and_more'),
        ('personnel', '0020_add_watch_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='budget_code',
            field=models.CharField(blank=True, help_text='Standard-Budgetcode für diesen Fachbereich', max_length=50, verbose_name='Budgetcode'),
        ),
        migrations.AddField(
            model_name='department',
            name='deputy_head',
            field=models.ForeignKey(blank=True, help_text='Stellvertretende/r Leiter/in dieser Abteilung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_headed_departments', to='personnel.person', verbose_name='Stellv. Fachbereichsleiter'),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Leiter/in dieser Abteilung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='personnel.person', verbose_name='Fachbereichsleiter'),
        ),
    ]
