# Generated by Django 5.0.14 on 2026-04-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_add_department_head_deputy_budget'),
        ('personnel', '0020_add_watch_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerunit',
            name='deputy_leader',
            field=models.ForeignKey(blank=True, help_text='Stellvertretende/r Leiter/in dieser FF-Einheit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deputy_led_volunteer_units', to='personnel.person', verbose_name='Stellv. Einheitsführer'),
        ),
        migrations.AddField(
            model_name='volunteerunit',
            name='leader',
            field=models.ForeignKey(blank=True, help_text='Leiter/in dieser FF-Einheit', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_volunteer_units', to='personnel.person', verbose_name='Einheitsführer'),
        ),
    ]
