# Generated by Django 5.0.14 on 2025-10-03 12:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITHardwareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_number', models.CharField(help_text='Eindeutige Artikelnummer', max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Hersteller-Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestand')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Warnung bei Unterschreitung', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximalbestand')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode/EAN')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR-Code')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/images/', verbose_name='Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('hardware_type', models.CharField(choices=[('desktop_pc', 'Desktop-PC'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('thin_client', 'Thin Client'), ('all_in_one', 'All-in-One PC'), ('server', 'Server'), ('nas', 'NAS (Network Storage)'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('modem', 'Modem'), ('monitor', 'Monitor'), ('keyboard', 'Tastatur'), ('mouse', 'Maus'), ('printer', 'Drucker'), ('scanner', 'Scanner'), ('multifunction', 'Multifunktionsgerät'), ('webcam', 'Webcam'), ('headset', 'Headset'), ('speaker', 'Lautsprecher'), ('smartphone', 'Smartphone'), ('mobile_phone', 'Mobiltelefon'), ('mobile_radio', 'Funkgerät'), ('gps_device', 'GPS-Gerät'), ('external_hdd', 'Externe Festplatte'), ('usb_stick', 'USB-Stick'), ('ssd', 'SSD'), ('hdd', 'Interne Festplatte'), ('ram', 'RAM-Modul'), ('cpu', 'Prozessor'), ('gpu', 'Grafikkarte'), ('psu', 'Netzteil'), ('mainboard', 'Mainboard'), ('cable', 'Kabel'), ('adapter', 'Adapter'), ('docking_station', 'Dockingstation'), ('ups', 'USV (Unterbrechungsfreie Stromversorgung)'), ('kvm_switch', 'KVM-Switch'), ('rack', 'Server-Rack'), ('license', 'Softwarelizenz')], max_length=50, verbose_name='Hardware-Typ')),
                ('it_status', models.CharField(choices=[('in_use', 'In Betrieb'), ('in_stock', 'Auf Lager'), ('reserved', 'Reserviert'), ('defect', 'Defekt'), ('in_repair', 'In Reparatur'), ('retired', 'Ausgemustert'), ('ordered', 'Bestellt')], default='in_stock', max_length=20, verbose_name='IT-Status')),
                ('asset_tag', models.CharField(help_text='Eindeutige Inventarnummer', max_length=100, unique=True, verbose_name='Asset-Tag')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Seriennummer')),
                ('mac_address', models.CharField(blank=True, help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17, verbose_name='MAC-Adresse')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='Hostname')),
                ('operating_system', models.CharField(blank=True, choices=[('windows_11', 'Windows 11'), ('windows_10', 'Windows 10'), ('windows_server', 'Windows Server'), ('linux_ubuntu', 'Linux Ubuntu'), ('linux_debian', 'Linux Debian'), ('linux_centos', 'Linux CentOS'), ('mac_os', 'macOS'), ('android', 'Android'), ('ios', 'iOS'), ('other', 'Sonstiges')], max_length=50, verbose_name='Betriebssystem')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='BS-Version')),
                ('cpu_model', models.CharField(blank=True, max_length=200, verbose_name='CPU/Prozessor')),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Speicher (GB)')),
                ('gpu_model', models.CharField(blank=True, max_length=200, verbose_name='GPU/Grafikkarte')),
                ('screen_size_inch', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Bildschirmgröße (Zoll)')),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Zuweisungsdatum')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kaufpreis (€)')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Garantieende')),
                ('support_contract', models.CharField(blank=True, help_text='z.B. Vertragsnummer', max_length=200, verbose_name='Support-Vertrag')),
                ('support_end_date', models.DateField(blank=True, null=True, verbose_name='Support-Ende')),
                ('depreciation_years', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Abschreibungsdauer (Jahre)')),
                ('expected_replacement_date', models.DateField(blank=True, null=True, verbose_name='Geplanter Austausch')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('last_os_update', models.DateField(blank=True, null=True, verbose_name='Letztes OS-Update')),
                ('antivirus_software', models.CharField(blank=True, max_length=200, verbose_name='Antivirus-Software')),
                ('antivirus_last_update', models.DateField(blank=True, null=True, verbose_name='Letzte AV-Update')),
                ('license_key', models.CharField(blank=True, max_length=500, verbose_name='Lizenzschlüssel')),
                ('license_seats', models.PositiveIntegerField(blank=True, null=True, verbose_name='Anzahl Lizenzen')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='Lizenz-Ablauf')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Zustandsnotizen')),
                ('known_issues', models.TextField(blank=True, verbose_name='Bekannte Probleme')),
                ('invoice_file', models.FileField(blank=True, upload_to='it_hardware/invoices/', verbose_name='Rechnung')),
                ('manual_file', models.FileField(blank=True, upload_to='it_hardware/manuals/', verbose_name='Handbuch')),
                ('warranty_document', models.FileField(blank=True, upload_to='it_hardware/warranties/', verbose_name='Garantiedokument')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Fotos')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_it_hardware', to='personnel.person', verbose_name='Zugewiesen an')),
                ('assigned_vehicles', models.ManyToManyField(blank=True, related_name='it_hardware', to='vehicles.vehicle', verbose_name='Zugeordnete Fahrzeuge')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'IT-Hardware',
                'verbose_name_plural': 'IT-Hardware',
                'ordering': ['hardware_type', 'asset_tag'],
            },
        ),
        migrations.CreateModel(
            name='ITHardwareStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('movement_type', models.CharField(choices=[('incoming', 'Wareneingang'), ('outgoing', 'Warenausgang'), ('transfer', 'Umlagerung'), ('inventory', 'Inventur-Korrektur'), ('damage', 'Beschädigung/Schwund'), ('return', 'Rückgabe'), ('disposal', 'Entsorgung')], max_length=20, verbose_name='Bewegungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('reference_number', models.CharField(blank=True, help_text='z.B. Lieferschein-Nr., Bestellnummer', max_length=100, verbose_name='Referenznummer')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Bewegungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('assignment_reason', models.CharField(blank=True, help_text='z.B. Neueinstellung, Ersatz, Upgrade', max_length=200, verbose_name='Zuweisungsgrund')),
                ('maintenance_performed', models.BooleanField(default=False, verbose_name='Wartung durchgeführt')),
                ('maintenance_type', models.CharField(blank=True, help_text='z.B. Reinigung, Hardware-Upgrade, Software-Update', max_length=200, verbose_name='Wartungsart')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='Wartungsnotizen')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='Ersetzte Komponenten')),
                ('maintenance_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wartungskosten (€)')),
                ('os_updated', models.BooleanField(default=False, verbose_name='OS aktualisiert')),
                ('new_os_version', models.CharField(blank=True, max_length=100, verbose_name='Neue OS-Version')),
                ('software_installed', models.TextField(blank=True, help_text='Liste der installierten Programme', verbose_name='Installierte Software')),
                ('condition_before', models.TextField(blank=True, verbose_name='Zustand vorher')),
                ('condition_after', models.TextField(blank=True, verbose_name='Zustand nachher')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Fotos')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_hardware_assignments', to='personnel.person', verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_outgoing', to='locations.location', verbose_name='Von Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='it_hardware.ithardwareitem', verbose_name='Hardware')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_incoming', to='locations.location', verbose_name='Nach Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Lagerbewegung IT-Hardware',
                'verbose_name_plural': 'Lagerbewegungen IT-Hardware',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ithardwareitem',
            index=models.Index(fields=['hardware_type'], name='it_hardware_hardwar_96fb28_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwareitem',
            index=models.Index(fields=['it_status'], name='it_hardware_it_stat_426c81_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwareitem',
            index=models.Index(fields=['asset_tag'], name='it_hardware_asset_t_399e44_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwareitem',
            index=models.Index(fields=['serial_number'], name='it_hardware_serial__2217f3_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwareitem',
            index=models.Index(fields=['assigned_to'], name='it_hardware_assigne_4f897e_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwareitem',
            index=models.Index(fields=['warranty_end_date'], name='it_hardware_warrant_0e4c11_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwareitem',
            index=models.Index(fields=['support_end_date'], name='it_hardware_support_76c0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwarestockmovement',
            index=models.Index(fields=['item', 'movement_date'], name='it_hardware_item_id_1c0ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwarestockmovement',
            index=models.Index(fields=['assigned_to'], name='it_hardware_assigne_3d3df9_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwarestockmovement',
            index=models.Index(fields=['maintenance_performed'], name='it_hardware_mainten_c4baf2_idx'),
        ),
    ]
