# Generated by Django 5.2.7 on 2025-10-17 13:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_hardware', '0003_alter_ithardwareitem_category'),
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0007_add_organization_membership_and_anniversaries'),
        ('vehicles', '0005_vehicle_actual_retirement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITHardwareItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_number', models.CharField(help_text='Eindeutige Stammdaten-Nummer (z.B. IT-001)', max_length=50, unique=True, verbose_name='Stammdaten-Nummer')),
                ('name', models.CharField(help_text='z.B. ThinkPad T14 Gen 3, Dell Latitude 5420', max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('hardware_type', models.CharField(choices=[('desktop_pc', 'Desktop-PC'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('thin_client', 'Thin Client'), ('all_in_one', 'All-in-One PC'), ('server', 'Server'), ('nas', 'NAS (Network Storage)'), ('router', 'Router'), ('switch', 'Switch'), ('firewall', 'Firewall'), ('access_point', 'Access Point'), ('modem', 'Modem'), ('monitor', 'Monitor'), ('keyboard', 'Tastatur'), ('mouse', 'Maus'), ('printer', 'Drucker'), ('scanner', 'Scanner'), ('multifunction', 'Multifunktionsgerät'), ('webcam', 'Webcam'), ('headset', 'Headset'), ('speaker', 'Lautsprecher'), ('smartphone', 'Smartphone'), ('mobile_phone', 'Mobiltelefon'), ('mobile_radio', 'Funkgerät'), ('gps_device', 'GPS-Gerät'), ('external_hdd', 'Externe Festplatte'), ('usb_stick', 'USB-Stick'), ('ssd', 'SSD'), ('hdd', 'Interne Festplatte'), ('ram', 'RAM-Modul'), ('cpu', 'Prozessor'), ('gpu', 'Grafikkarte'), ('psu', 'Netzteil'), ('mainboard', 'Mainboard'), ('cable', 'Kabel'), ('adapter', 'Adapter'), ('docking_station', 'Dockingstation'), ('ups', 'USV (Unterbrechungsfreie Stromversorgung)'), ('kvm_switch', 'KVM-Switch'), ('rack', 'Server-Rack'), ('license', 'Softwarelizenz')], max_length=50, verbose_name='Hardware-Typ')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Modell')),
                ('operating_system', models.CharField(blank=True, choices=[('windows_11', 'Windows 11'), ('windows_10', 'Windows 10'), ('windows_server', 'Windows Server'), ('linux_ubuntu', 'Linux Ubuntu'), ('linux_debian', 'Linux Debian'), ('linux_centos', 'Linux CentOS'), ('mac_os', 'macOS'), ('android', 'Android'), ('ios', 'iOS'), ('other', 'Sonstiges')], max_length=50, verbose_name='Standard-Betriebssystem')),
                ('cpu_model', models.CharField(blank=True, max_length=200, verbose_name='CPU/Prozessor')),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='Speicher (GB)')),
                ('gpu_model', models.CharField(blank=True, max_length=200, verbose_name='GPU/Grafikkarte')),
                ('screen_size_inch', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Bildschirmgröße (Zoll)')),
                ('depreciation_years', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Abschreibungsdauer (Jahre)')),
                ('maintenance_interval_months', models.PositiveIntegerField(blank=True, help_text='0 = keine regelmäßige Wartung', null=True, verbose_name='Wartungsintervall (Monate)')),
                ('manual_document', models.FileField(blank=True, upload_to='it_hardware/manuals/', verbose_name='Handbuch/Datenblatt')),
                ('image', models.ImageField(blank=True, upload_to='it_hardware/images/', verbose_name='Produktbild')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Standard-Kaufpreis (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Stammdaten erscheinen nicht in Auswahllisten', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_it_masters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'IT-Hardware Stammdaten',
                'verbose_name_plural': 'IT-Hardware Stammdaten',
                'ordering': ['hardware_type', 'manufacturer', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ITHardwareDeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(help_text='Eindeutige Inventarnummer (z.B. IT-2025-042)', max_length=100, unique=True, verbose_name='Asset-Tag')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Seriennummer')),
                ('mac_address', models.CharField(blank=True, help_text='Format: XX:XX:XX:XX:XX:XX', max_length=17, verbose_name='MAC-Adresse')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('hostname', models.CharField(blank=True, max_length=200, verbose_name='Hostname')),
                ('operating_system', models.CharField(blank=True, choices=[('windows_11', 'Windows 11'), ('windows_10', 'Windows 10'), ('windows_server', 'Windows Server'), ('linux_ubuntu', 'Linux Ubuntu'), ('linux_debian', 'Linux Debian'), ('linux_centos', 'Linux CentOS'), ('mac_os', 'macOS'), ('android', 'Android'), ('ios', 'iOS'), ('other', 'Sonstiges')], max_length=50, verbose_name='Betriebssystem')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='BS-Version')),
                ('last_os_update', models.DateField(blank=True, null=True, verbose_name='Letztes OS-Update')),
                ('it_status', models.CharField(choices=[('in_use', 'In Betrieb'), ('in_stock', 'Auf Lager'), ('reserved', 'Reserviert'), ('defect', 'Defekt'), ('in_repair', 'In Reparatur'), ('retired', 'Ausgemustert'), ('ordered', 'Bestellt')], default='in_stock', max_length=20, verbose_name='IT-Status')),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Zuweisungsdatum')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kaufpreis (€)')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Garantieende')),
                ('support_contract', models.CharField(blank=True, max_length=200, verbose_name='Support-Vertrag')),
                ('support_end_date', models.DateField(blank=True, null=True, verbose_name='Support-Ende')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='Wartungsnotizen')),
                ('expected_replacement_date', models.DateField(blank=True, null=True, verbose_name='Geplanter Austausch')),
                ('license_key', models.CharField(blank=True, max_length=500, verbose_name='Lizenzschlüssel')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='Lizenz-Ablauf')),
                ('antivirus_software', models.CharField(blank=True, max_length=200, verbose_name='Antivirus-Software')),
                ('antivirus_last_update', models.DateField(blank=True, null=True, verbose_name='Letzte AV-Update')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Zustandsnotizen')),
                ('known_issues', models.TextField(blank=True, verbose_name='Bekannte Probleme')),
                ('has_qr_code', models.BooleanField(default=False, verbose_name='QR-Code vorhanden')),
                ('qr_code_data', models.CharField(blank=True, max_length=500, verbose_name='QR-Code Daten')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_it_devices', to='personnel.person', verbose_name='Zugewiesen an')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_hardware_devices', to='vehicles.vehicle', verbose_name='Zugeordnetes Fahrzeug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_it_devices', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='it_hardware_devices', to='locations.location', verbose_name='Lagerort')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_instances', to='it_hardware.ithardwareitemmaster', verbose_name='IT-Hardware Stammdaten')),
            ],
            options={
                'verbose_name': 'IT-Hardware Gerät',
                'verbose_name_plural': 'IT-Hardware Geräte',
                'ordering': ['asset_tag'],
            },
        ),
        migrations.AddIndex(
            model_name='ithardwareitemmaster',
            index=models.Index(fields=['master_number'], name='it_hardware_master__c25a99_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwareitemmaster',
            index=models.Index(fields=['hardware_type', 'manufacturer'], name='it_hardware_hardwar_f46331_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwareitemmaster',
            index=models.Index(fields=['is_active'], name='it_hardware_is_acti_6101b8_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['asset_tag'], name='it_hardware_asset_t_667405_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['serial_number'], name='it_hardware_serial__dbf448_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['master', 'is_active'], name='it_hardware_master__f1bb33_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['it_status'], name='it_hardware_it_stat_194c79_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['assigned_to'], name='it_hardware_assigne_b06ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['assigned_vehicle'], name='it_hardware_assigne_406adf_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['warranty_end_date'], name='it_hardware_warrant_d7ca25_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['support_end_date'], name='it_hardware_support_f0fb68_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['next_maintenance_date'], name='it_hardware_next_ma_3ba401_idx'),
        ),
        migrations.AddIndex(
            model_name='ithardwaredeviceinstance',
            index=models.Index(fields=['license_expiry_date'], name='it_hardware_license_4f9a6f_idx'),
        ),
    ]
