# Generated by Django 5.0.14 on 2025-10-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_hardware', '0004_ithardwareitemmaster_ithardwaredeviceinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ithardwaredeviceinstance',
            name='condition',
            field=models.CharField(choices=[('new', 'Neu'), ('excellent', 'Sehr gut'), ('good', 'Gut'), ('fair', 'Befriedigend'), ('poor', 'Schlecht'), ('defective', 'Defekt')], default='good', max_length=20, verbose_name='Zustand'),
        ),
    ]
