# Generated by Django 5.0.14 on 2025-10-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_hardware', '0005_ithardwaredeviceinstance_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ithardwaredeviceinstance',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='Interne Inventarnummer', max_length=100, verbose_name='Inventarnummer'),
        ),
        migrations.AlterField(
            model_name='ithardwaredeviceinstance',
            name='asset_tag',
            field=models.CharField(help_text='Eindeutige Asset-Tag-Nummer (z.B. IT-2025-042)', max_length=100, unique=True, verbose_name='Asset-Tag'),
        ),
    ]
