# Generated by Django 5.0.14 on 2025-10-22 09:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_hardware', '0007_alter_ithardwareitem_location'),
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0015_person_show_private_contact_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ITHardwareInventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('check_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Inventur-Nummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('check_type', models.CharField(choices=[('full', 'Vollinventur'), ('partial', 'Teilinventur'), ('spot_check', 'Stichprobe'), ('cycle_count', 'Zykluszählung'), ('annual', 'Jahresinventur')], default='partial', max_length=20, verbose_name='Inventurart')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('counting_complete', 'Zählung abgeschlossen'), ('review', 'In Prüfung'), ('adjustments_pending', 'Korrekturen ausstehend'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='planned', max_length=30, verbose_name='Status')),
                ('scheduled_start_date', models.DateField(verbose_name='Geplanter Start')),
                ('scheduled_end_date', models.DateField(verbose_name='Geplantes Ende')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächlicher Start')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Gesamt-Anzahl Artikel')),
                ('counted_items', models.PositiveIntegerField(default=0, verbose_name='Gezählte Artikel')),
                ('items_with_discrepancies', models.PositiveIntegerField(default=0, verbose_name='Artikel mit Abweichungen')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('check_warranty', models.BooleanField(default=True, help_text='Geräte mit abgelaufener Garantie identifizieren', verbose_name='Garantie prüfen')),
                ('check_support', models.BooleanField(default=True, help_text='Support-Verträge auf Ablauf prüfen', verbose_name='Support-Verträge prüfen')),
                ('check_os_updates', models.BooleanField(default=True, help_text='Betriebssystem-Update-Status prüfen', verbose_name='OS-Updates prüfen')),
                ('check_licenses', models.BooleanField(default=False, help_text='Software-Lizenzen auf Gültigkeit prüfen', verbose_name='Lizenzen prüfen')),
                ('warranty_expired_found', models.PositiveIntegerField(default=0, help_text='Anzahl Geräte mit abgelaufener Garantie', verbose_name='Garantie abgelaufen')),
                ('support_expired_found', models.PositiveIntegerField(default=0, help_text='Anzahl Geräte mit abgelaufenem Support', verbose_name='Support abgelaufen')),
                ('os_outdated_found', models.PositiveIntegerField(default=0, help_text='Anzahl Geräte mit veraltetem OS', verbose_name='OS veraltet')),
                ('defective_devices_found', models.PositiveIntegerField(default=0, help_text='Anzahl defekter Geräte gefunden', verbose_name='Defekte Geräte')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_approved', to='personnel.person', verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, help_text='Leer = Alle Lagerorte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_checks', to='locations.location', verbose_name='Lagerort')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_responsible', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('team_members', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_team', to='personnel.person', verbose_name='Team-Mitglieder')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'IT-Hardware Inventur',
                'verbose_name_plural': 'IT-Hardware Inventuren',
                'ordering': ['-created_at'],
                'permissions': [('approve_ithardwareinventorycheck', 'Kann IT-Hardware-Inventur genehmigen')],
            },
        ),
        migrations.CreateModel(
            name='ITHardwareInventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('item_name', models.CharField(max_length=200, verbose_name='Artikelbezeichnung')),
                ('item_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sollbestand')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Istbestand')),
                ('is_counted', models.BooleanField(default=False, verbose_name='Gezählt')),
                ('counted_date', models.DateTimeField(blank=True, null=True, verbose_name='Zähldatum')),
                ('has_discrepancy', models.BooleanField(default=False, verbose_name='Abweichung')),
                ('variance_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Differenz')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('requires_recount', models.BooleanField(default=False, verbose_name='Nachzählung erforderlich')),
                ('asset_tag', models.CharField(blank=True, max_length=100, verbose_name='Asset-Tag')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Seriennummer')),
                ('hardware_type', models.CharField(blank=True, max_length=50, verbose_name='Hardware-Typ')),
                ('it_status', models.CharField(blank=True, max_length=20, verbose_name='IT-Status')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Garantieende')),
                ('warranty_expired', models.BooleanField(default=False, verbose_name='Garantie abgelaufen')),
                ('support_end_date', models.DateField(blank=True, null=True, verbose_name='Support-Ende')),
                ('support_expired', models.BooleanField(default=False, verbose_name='Support abgelaufen')),
                ('operating_system', models.CharField(blank=True, max_length=100, verbose_name='Betriebssystem')),
                ('os_version', models.CharField(blank=True, max_length=100, verbose_name='OS-Version')),
                ('last_os_update', models.DateField(blank=True, null=True, verbose_name='Letztes OS-Update')),
                ('os_outdated', models.BooleanField(default=False, help_text='Letztes Update > 6 Monate', verbose_name='OS veraltet')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('mac_address', models.CharField(blank=True, max_length=17, verbose_name='MAC-Adresse')),
                ('is_defective', models.BooleanField(default=False, verbose_name='Defekt')),
                ('assigned_to_name', models.CharField(blank=True, max_length=200, verbose_name='Zugewiesen an')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_counted', to='personnel.person', verbose_name='Gezählt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='it_hardware.ithardwareinventorycheck', verbose_name='Inventur')),
                ('it_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='it_hardware.ithardwaredeviceinstance', verbose_name='IT-Gerät')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'IT-Hardware Inventur-Position',
                'verbose_name_plural': 'IT-Hardware Inventur-Positionen',
                'ordering': ['item_name', 'asset_tag'],
            },
        ),
    ]
