# Generated by Django 5.0.14 on 2025-10-03 08:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('personnel_number', models.CharField(blank=True, help_text='Eindeutige Personalnummer', max_length=20, null=True, unique=True, verbose_name='Personalnummer')),
                ('phone', models.CharField(blank=True, help_text='Telefonnummer', max_length=50, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, help_text='Mobilnummer', max_length=50, verbose_name='Mobil')),
                ('department', models.CharField(blank=True, help_text='Abteilung/Einheit', max_length=100, verbose_name='Abteilung')),
                ('position', models.CharField(blank=True, help_text='Position oder Funktion in der Feuerwehr', max_length=100, verbose_name='Position/Funktion')),
                ('force_2fa', models.BooleanField(default=False, help_text='Benutzer muss 2FA aktiviert haben', verbose_name='2FA Pflicht')),
                ('access_start_time', models.TimeField(blank=True, help_text='Zugriff nur ab dieser Uhrzeit erlaubt', null=True, verbose_name='Zugriff ab')),
                ('access_end_time', models.TimeField(blank=True, help_text='Zugriff nur bis zu dieser Uhrzeit erlaubt', null=True, verbose_name='Zugriff bis')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profilbild')),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen zum Benutzer', verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('manage_users', 'Kann Benutzer verwalten'), ('assign_roles', 'Kann Rollen zuweisen'), ('view_audit_log', 'Kann Audit-Log einsehen'), ('system_configuration', 'Kann Systemkonfiguration aendern')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
