# Generated by Django 5.0.14 on 2025-10-04 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=5, verbose_name='Sprache')),
                ('timezone', models.CharField(default='Europe/Berlin', max_length=50, verbose_name='Zeitzone')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-Mail-Benachrichtigungen')),
                ('email_critical_alerts', models.BooleanField(default=True, verbose_name='Kritische Alerts per E-Mail')),
                ('email_weekly_summary', models.BooleanField(default=False, verbose_name='Wöchentliche Zusammenfassung')),
                ('push_enabled', models.BooleanField(default=False, verbose_name='Push-Benachrichtigungen')),
                ('notify_critical_stock', models.BooleanField(default=True, verbose_name='Kritische Bestände')),
                ('notify_expiring_items', models.BooleanField(default=True, verbose_name='Ablaufende Artikel')),
                ('notify_upcoming_inspections', models.BooleanField(default=True, verbose_name='Anstehende Prüfungen')),
                ('notify_orders', models.BooleanField(default=False, verbose_name='Bestellungen')),
                ('notify_vehicle_handover', models.BooleanField(default=False, verbose_name='Fahrzeugübernahme')),
                ('theme', models.CharField(choices=[('light', 'Hell'), ('dark', 'Dunkel'), ('auto', 'Automatisch')], default='light', max_length=10, verbose_name='Theme')),
                ('sidebar_behavior', models.CharField(choices=[('expanded', 'Standard ausgeklappt'), ('collapsed', 'Standard eingeklappt'), ('auto', 'Automatisch')], default='expanded', max_length=10, verbose_name='Sidebar-Verhalten')),
                ('items_per_page', models.IntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=25, verbose_name='Einträge pro Seite')),
                ('table_density', models.CharField(choices=[('compact', 'Kompakt'), ('normal', 'Normal'), ('comfortable', 'Komfortabel')], default='normal', max_length=12, verbose_name='Tabellen-Dichte')),
                ('show_hints', models.BooleanField(default=True, verbose_name='Hilfe-Tooltips anzeigen')),
                ('show_breadcrumbs', models.BooleanField(default=True, verbose_name='Breadcrumb-Navigation anzeigen')),
                ('compact_mode', models.BooleanField(default=False, verbose_name='Kompakt-Modus')),
                ('analytics_enabled', models.BooleanField(default=True, verbose_name='Nutzungsstatistiken')),
                ('error_reporting', models.BooleanField(default=True, verbose_name='Anonyme Fehlerberichte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Benutzer-Einstellungen',
                'verbose_name_plural': 'Benutzer-Einstellungen',
            },
        ),
    ]
