# Generated by Django 5.0.14 on 2025-10-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_must_change',
            field=models.BooleanField(default=False, help_text='Benutzer muss bei nächster Anmeldung das Passwort ändern', verbose_name='Passwort muss geändert werden'),
        ),
    ]
