# Generated by Django 5.0.14 on 2025-10-23 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_password_must_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_enabled', models.BooleanField(default=False, help_text='Interne Wissensdatenbank aktivieren', verbose_name='Wiki-Modul')),
                ('procurement_enabled', models.BooleanField(default=True, help_text='Beschaffungs- und Bestellverwaltung', verbose_name='Bestellwesen')),
                ('inventory_check_enabled', models.BooleanField(default=True, help_text='Inventur-Modul', verbose_name='Inventur')),
                ('info_monitors_enabled', models.BooleanField(default=False, help_text='Dashboard-Builder für öffentliche Monitore', verbose_name='Info-Monitore')),
                ('barcode_scanning_enabled', models.BooleanField(default=True, help_text='Barcode/QR-Code Scanning aktivieren', verbose_name='Barcode-Scanner')),
                ('mobile_app_enabled', models.BooleanField(default=False, help_text='Mobile App Zugriff aktivieren', verbose_name='Mobile App')),
                ('api_enabled', models.BooleanField(default=False, help_text='REST API für externe Integrationen', verbose_name='REST API')),
                ('organization_name', models.CharField(default='Feuerwehr', max_length=200, verbose_name='Organisationsname')),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='system/logos/', verbose_name='Organisations-Logo')),
                ('system_email', models.EmailField(blank=True, help_text='E-Mail-Adresse für System-Benachrichtigungen', max_length=254, verbose_name='System-E-Mail')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'System-Einstellungen',
                'verbose_name_plural': 'System-Einstellungen',
            },
        ),
    ]
