# Generated by Django 5.0.14 on 2025-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='it_hardware_enabled',
            field=models.BooleanField(default=True, help_text='IT-Hardware Verwaltung', verbose_name='IT-Hardware'),
        ),
    ]
