# Generated by Django 5.0.14 on 2025-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_it_hardware_enabled_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='tickets_enabled',
            field=models.BooleanField(default=True, help_text='Internes Ticketsystem für Anfragen und Meldungen', verbose_name='Ticketsystem'),
        ),
    ]
