# Generated by Django 5.0.14 on 2025-12-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_tickets_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ff_dashboard_enabled',
            field=models.BooleanField(default=True, help_text='Feuerwehr-Verwaltung (Dienstgrade, Jubiläen, Beförderungen)', verbose_name='FF-Dashboard'),
        ),
    ]
