# Generated by Django 5.0.14 on 2026-01-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_ff_dashboard_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='vehicle_handover_enabled',
            field=models.BooleanField(default=True, help_text='Fahrzeugübernahme-Protokolle bei Schichtwechsel', verbose_name='Fahrzeugübernahme'),
        ),
    ]
