# Generated by Django 5.0.14 on 2026-02-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_vehicle_handover_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='two_factor_auth_enabled',
            field=models.BooleanField(default=False, help_text='2FA systemweit aktivieren (erfordert zusätzliche Konfiguration)', verbose_name='Zwei-Faktor-Authentifizierung'),
        ),
    ]
