# Generated by Django 5.0.14 on 2026-02-05 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_two_factor_auth_enabled'),
        ('locations', '0004_add_room_number_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_wbf',
            field=models.BooleanField(default=False, help_text='Ist dieser Benutzer ein Wachbereitschaftsführer?', verbose_name='Wachbereitschaftsführer (WBF)'),
        ),
        migrations.AddField(
            model_name='user',
            name='wbf_location',
            field=models.ForeignKey(blank=True, help_text='Für welche Feuerwache ist dieser WBF zuständig?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbf_users', to='locations.location', verbose_name='WBF Feuerwache'),
        ),
        migrations.AddField(
            model_name='user',
            name='wbf_watch_division',
            field=models.CharField(blank=True, choices=[('WA1', 'WA1'), ('WA2', 'WA2'), ('WA3', 'WA3')], help_text='Für welche Wachabteilung ist dieser WBF zuständig?', max_length=10, verbose_name='WBF Wachabteilung'),
        ),
    ]
