# Generated by Django 5.0.14 on 2026-02-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_wbf_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='driving_license_enabled',
            field=models.BooleanField(default=True, help_text='Führerscheinüberprüfung und -verwaltung', verbose_name='Führerscheinüberprüfung'),
        ),
    ]
