# Generated by Django 5.0.14 on 2026-02-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_driving_license_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='diving_enabled',
            field=models.BooleanField(default=True, help_text='Tauchausrüstung Verwaltung', verbose_name='Taucher'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='height_rescue_enabled',
            field=models.BooleanField(default=True, help_text='Höhenrettungsausrüstung (PSA) Verwaltung', verbose_name='Höhenrettung'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='workshop_enabled',
            field=models.BooleanField(default=True, help_text='KFZ-Werkstatt und Werkzeugverwaltung', verbose_name='KFZ-Werkstatt'),
        ),
    ]
