# Generated by Django 5.0.14 on 2026-02-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_height_rescue_diving_workshop_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_code',
            field=models.CharField(blank=True, default='', help_text='4-stelliger PIN-Code (gehashed gespeichert)', max_length=128, verbose_name='PIN-Code (Hash)'),
        ),
        migrations.AddField(
            model_name='user',
            name='pin_must_change',
            field=models.BooleanField(default=True, help_text='Benutzer muss bei nächster Anmeldung einen PIN einrichten', verbose_name='PIN muss eingerichtet werden'),
        ),
    ]
