# Generated by Django 5.0.14 on 2026-02-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_pin_code_user_pin_must_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='person_section_driving_license_visible',
            field=models.BooleanField(default=True, help_text='Führerscheinklassen im Personalformular anzeigen', verbose_name='Führerscheindaten'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='person_section_emergency_contact_visible',
            field=models.BooleanField(default=True, help_text='Notfallkontakt-Bereich im Personalformular anzeigen', verbose_name='Notfallkontakt'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='person_section_notes_visible',
            field=models.BooleanField(default=True, help_text='Interne Anmerkungen im Personalformular anzeigen', verbose_name='Notizen'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='person_section_organization_visible',
            field=models.BooleanField(default=True, help_text='JF, FF, BF-Zugehörigkeit im Personalformular anzeigen', verbose_name='Organisationszugehörigkeit'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='person_section_private_contact_visible',
            field=models.BooleanField(default=True, help_text='E-Mail, Telefon, Adresse im Personalformular anzeigen', verbose_name='Private Kontaktdaten'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='person_section_user_photo_visible',
            field=models.BooleanField(default=True, help_text='Benutzer-Account und Profilfoto im Personalformular anzeigen', verbose_name='Benutzer & Foto'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='phonebook_enabled',
            field=models.BooleanField(default=True, help_text='Internes Telefonbuch mit Kontaktdaten', verbose_name='Telefonbuch'),
        ),
    ]
