# Generated by Django 5.0.14 on 2026-02-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_phonebook_and_dsgvo_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='person_section_work_contact_visible',
            field=models.BooleanField(default=True, help_text='Standort, Raum, dienstliche Telefonnummern im Personalformular anzeigen', verbose_name='Dienstliche Kontaktdaten'),
        ),
    ]
