# Generated by Django 5.0.14 on 2026-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_work_contact_dsgvo_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='privacy_tab_visible',
            field=models.BooleanField(default=False, help_text='Datenschutz-Tab in den Benutzer-Einstellungen anzeigen', verbose_name='Datenschutz-Tab'),
        ),
    ]
