# Generated by Django 5.0.14 on 2026-02-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_privacy_tab_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='defect_management_enabled',
            field=models.BooleanField(default=True, help_text='Mängelerfassung und -verwaltung für Räume, Fahrzeuge und Ausrüstung', verbose_name='Mängelwesen'),
        ),
    ]
