# Generated by Django 5.0.14 on 2026-02-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_systemsettings_defect_management_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_position',
            field=models.CharField(blank=True, choices=[('mitarbeiter', 'Mitarbeiter'), ('stellv_fbl', 'Stellv. Fachbereichsleiter'), ('fbl', 'Fachbereichsleiter')], help_text='Organisatorische Dienststellung (steuert Freigabe-Gruppen)', max_length=20, verbose_name='Dienststellung'),
        ),
    ]
