# Generated by Django 5.0.14 on 2026-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_user_staff_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='civil_protection_enabled',
            field=models.BooleanField(default=False, help_text='Katastrophenschutz-Modul (Zivilschutz & Bevölkerungsschutz)', verbose_name='Katastrophenschutz'),
        ),
    ]
