# Generated by Django 5.0.14 on 2026-02-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_civil_protection_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='civil_protection_enabled',
            field=models.BooleanField(default=False, help_text='Bevölkerungsschutz-Modul (Bund, Land & Kommune)', verbose_name='Bevölkerungsschutz'),
        ),
    ]
