# Generated by Django 5.0.14 on 2026-02-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_civil_protection_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='person_tab_clothing_visible',
            field=models.BooleanField(default=True, help_text='Kleidung & PSA-Tab auf der Personaldetailseite anzeigen', verbose_name='Kleidung & PSA-Tab'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='person_tab_duty_hours_visible',
            field=models.BooleanField(default=True, help_text='Pflichtstunden-Tab auf der Personaldetailseite anzeigen', verbose_name='Pflichtstunden-Tab'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='person_tab_inspections_visible',
            field=models.BooleanField(default=True, help_text='Prüfungen-Tab auf der Personaldetailseite anzeigen', verbose_name='Prüfungen-Tab'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='person_tab_qualifications_visible',
            field=models.BooleanField(default=True, help_text='Qualifikationen-Tab auf der Personaldetailseite anzeigen', verbose_name='Qualifikationen-Tab'),
        ),
    ]
