# Generated by Django 5.0.14 on 2026-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_systemsettings_person_tab_clothing_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='person_section_fire_department_visible',
            field=models.BooleanField(default=True, help_text='Feuerwehr-Daten (Abteilung, Dienstgrad, Funktion) im Personalformular anzeigen', verbose_name='Feuerwehr-Daten'),
        ),
    ]
