# Generated by Django 5.2.15 on 2026-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_systemsettings_person_section_fire_department_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='objektverwaltung_enabled',
            field=models.BooleanField(default=True, help_text='Verwaltung öffentlicher Gebäude (Etagen, Fluchtwege, Laufkarten)', verbose_name='Objektverwaltung'),
        ),
    ]
