# Generated by Django 5.2.15 on 2026-07-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_systemsettings_objektverwaltung_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='accident_report_enabled',
            field=models.BooleanField(default=True, help_text='Erfassung und Verwaltung von Unfall-/Verletzungsmeldungen im Dienst', verbose_name='Unfallberichte'),
        ),
    ]
