# Generated by Django 5.2.15 on 2026-07-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_systemsettings_accident_report_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='site_title',
            field=models.CharField(default='Feuerwehr Lagerverwaltungssystem', help_text="Wird auf der öffentlichen Startseite als Überschrift angezeigt (z.B. 'Feuerwehr Oberhausen Lagerverwaltung').", max_length=200, verbose_name='Titel auf der Startseite'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='organization_logo',
            field=models.ImageField(blank=True, help_text='Wird auf der Startseite angezeigt (empfohlen: PNG mit transparentem Hintergrund).', null=True, upload_to='system/logos/', verbose_name='Organisations-Logo'),
        ),
    ]
