# Generated by Django 5.2.15 on 2026-08-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_systemsettings_site_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='surveys_enabled',
            field=models.BooleanField(default=False, help_text='Formularbasierte Umfragen, wahlweise anonym oder personalisiert', verbose_name='Umfragen'),
        ),
    ]
