# Generated by Django 5.2.15 on 2026-08-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_systemsettings_surveys_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='iuk_enabled',
            field=models.BooleanField(default=False, help_text='Drohnenstaffel: Drohnen, Drohnenführerscheine und Gutscheincodes', verbose_name='IUK'),
        ),
    ]
