# Generated by Django 5.2.15 on 2026-09-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_systemsettings_iuk_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='dienstplan_enabled',
            field=models.BooleanField(default=False, help_text='Dienstplan-Export importieren; Führungsdienst als Widget auf Info-Monitoren', verbose_name='Dienstplan'),
        ),
    ]
