# Generated by Django 5.2.15 on 2026-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_dienstplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='termine_enabled',
            field=models.BooleanField(default=False, help_text='Zentraler Kalender mit Kategorien; Widget „Kalender“ auf Info-Monitoren', verbose_name='Termine'),
        ),
    ]
