# Generated by Django 5.2.15 on 2026-09-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_termine'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='table_preferences',
            field=models.JSONField(blank=True, default=dict, help_text='Spaltenreihenfolge und Sichtbarkeit je Liste, vom Benutzer gespeichert', verbose_name='Tabellen-Einstellungen'),
        ),
    ]
