# Generated by Django 5.2.15 on 2026-09-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_usersettings_table_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='einsatzvorbereitung_enabled',
            field=models.BooleanField(default=False, help_text='Baustellen, Sperrungen und Gefahrenstellen mit Offline-Karte; Widget „Gefahrenstellen“ für die Leitstelle', verbose_name='Einsatzvorbereitung'),
        ),
    ]
