# Generated by Django 5.0.14 on 2025-10-03 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('personnel_number', models.CharField(help_text='Eindeutige Personalnummer', max_length=20, unique=True, verbose_name='Personalnummer')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobil')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('department', models.CharField(blank=True, help_text='z.B. Einsatzabteilung, Jugendfeuerwehr', max_length=100, verbose_name='Abteilung')),
                ('rank', models.CharField(blank=True, help_text='z.B. Feuerwehrmann, Hauptfeuerwehrmann, Oberlöschmeister', max_length=100, verbose_name='Dienstgrad')),
                ('function', models.CharField(blank=True, help_text='z.B. Gruppenführer, Maschinист, Atemschutzgeräteträger', max_length=100, verbose_name='Funktion')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Eintrittsdatum')),
                ('exit_date', models.DateField(blank=True, null=True, verbose_name='Austrittsdatum')),
                ('is_active', models.BooleanField(default=True, help_text='Ist die Person aktiv im Dienst?', verbose_name='Aktiv')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='personnel/photos/', verbose_name='Foto')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('user', models.OneToOneField(blank=True, help_text='Verknüpfter Benutzer-Account (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer-Account')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personal',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('qualification_type', models.CharField(choices=[('course', 'Lehrgang'), ('cert', 'Zertifikat'), ('license', 'Führerschein/Lizenz'), ('medical', 'Medizinische Untersuchung'), ('safety', 'Sicherheitsunterweisung'), ('other', 'Sonstiges')], default='course', max_length=20, verbose_name='Typ')),
                ('name', models.CharField(help_text='z.B. Atemschutzgeräteträger, Truppmannausbildung Teil 1', max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('issuing_authority', models.CharField(blank=True, help_text='z.B. Feuerwehrschule, TÜV', max_length=200, verbose_name='Ausstellende Stelle')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Zertifikatsnummer')),
                ('issue_date', models.DateField(verbose_name='Ausstellungsdatum')),
                ('expiry_date', models.DateField(blank=True, help_text='Leer lassen wenn unbefristet', null=True, verbose_name='Ablaufdatum')),
                ('certificate_file', models.FileField(blank=True, help_text='PDF, JPG oder PNG', null=True, upload_to='personnel/certificates/', verbose_name='Zertifikat-Datei')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='personnel.person', verbose_name='Person')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Qualifikation',
                'verbose_name_plural': 'Qualifikationen',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['personnel_number'], name='personnel_p_personn_93cfba_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['last_name', 'first_name'], name='personnel_p_last_na_29bf53_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['is_active'], name='personnel_p_is_acti_602943_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['person', 'is_active'], name='personnel_q_person__3d7f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['expiry_date'], name='personnel_q_expiry__775d8e_idx'),
        ),
    ]
