# Generated by Django 5.0.14 on 2025-10-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_card_photo',
            field=models.ImageField(blank=True, help_text='Automatisch generiert: 35x45mm, 300 DPI', null=True, upload_to='personnel/id_cards/', verbose_name='Dienstausweis-Foto'),
        ),
    ]
