# Generated by Django 5.2.7 on 2025-10-16 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_person_id_card_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(help_text='z.B. Atemschutzgeräteträgerlehrgang, G26.3-Untersuchung', max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('training_type', models.CharField(choices=[('course', 'Lehrgang'), ('cert', 'Zertifikat'), ('license', 'Führerschein/Lizenz'), ('medical', 'Medizinische Untersuchung'), ('safety', 'Sicherheitsunterweisung'), ('other', 'Sonstiges')], default='course', max_length=20, verbose_name='Schulungstyp')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('confirmed', 'Bestätigt'), ('in_progress', 'Läuft'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgesagt')], default='planned', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('end_date', models.DateField(blank=True, help_text='Bei mehrtägigen Schulungen', null=True, verbose_name='Enddatum')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('location', models.CharField(blank=True, help_text='z.B. Feuerwehrschule, Feuerwehrhaus', max_length=200, verbose_name='Veranstaltungsort')),
                ('organizer', models.CharField(blank=True, help_text='z.B. Kreisfeuerwehrverband', max_length=200, verbose_name='Veranstalter')),
                ('instructor', models.CharField(blank=True, max_length=200, verbose_name='Ausbilder/Dozent')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximale Teilnehmerzahl', null=True, verbose_name='Max. Teilnehmer')),
                ('cost_per_participant', models.DecimalField(blank=True, decimal_places=2, help_text='In Euro', max_digits=10, null=True, verbose_name='Kosten pro Teilnehmer')),
                ('training_materials', models.FileField(blank=True, null=True, upload_to='personnel/training_materials/', verbose_name='Schulungsunterlagen')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Schulung',
                'verbose_name_plural': 'Schulungen',
                'ordering': ['-start_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('registered', 'Angemeldet'), ('confirmed', 'Bestätigt'), ('attended', 'Teilgenommen'), ('absent', 'Abwesend'), ('cancelled', 'Abgemeldet')], default='registered', max_length=20, verbose_name='Status')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Anmeldedatum')),
                ('passed', models.BooleanField(blank=True, help_text='Hat die Person die Schulung erfolgreich abgeschlossen?', null=True, verbose_name='Bestanden')),
                ('certificate_issued', models.BooleanField(default=False, verbose_name='Zertifikat ausgestellt')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.person', verbose_name='Person')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.training', verbose_name='Schulung')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Schulungsteilnahme',
                'verbose_name_plural': 'Schulungsteilnahmen',
                'ordering': ['person__last_name', 'person__first_name'],
                'unique_together': {('training', 'person')},
            },
        ),
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(related_name='trainings', through='personnel.TrainingParticipant', to='personnel.person', verbose_name='Teilnehmer'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['start_date'], name='personnel_t_start_d_d6bcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='training',
            index=models.Index(fields=['status'], name='personnel_t_status_187e66_idx'),
        ),
    ]
