# Generated by Django 5.2.7 on 2025-10-16 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_training_trainingparticipant_training_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Atemschutzgeräteträger, Truppmannausbildung Teil 1', max_length=200, unique=True, verbose_name='Bezeichnung')),
                ('qualification_type', models.CharField(choices=[('course', 'Lehrgang'), ('cert', 'Zertifikat'), ('license', 'Führerschein/Lizenz'), ('medical', 'Medizinische Untersuchung'), ('safety', 'Sicherheitsunterweisung'), ('other', 'Sonstiges')], default='course', max_length=20, verbose_name='Typ')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('default_validity_days', models.PositiveIntegerField(blank=True, help_text='Standard-Gültigkeitsdauer in Tagen (z.B. 1095 für 3 Jahre). Leer lassen wenn unbefristet.', null=True, verbose_name='Standard-Gültigkeit (Tage)')),
                ('default_issuing_authority', models.CharField(blank=True, help_text='z.B. Feuerwehrschule, TÜV', max_length=200, verbose_name='Standard-Ausstellende Stelle')),
                ('is_active', models.BooleanField(default=True, help_text='Ist diese Vorlage aktiv und kann ausgewählt werden?', verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qualifikations-Vorlage',
                'verbose_name_plural': 'Qualifikations-Vorlagen',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='personnel_q_name_d0852a_idx'), models.Index(fields=['is_active'], name='personnel_q_is_acti_a25836_idx')],
            },
        ),
        migrations.AddField(
            model_name='qualification',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Optional: Vorlage auswählen um Felder automatisch auszufüllen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualifications', to='personnel.qualificationtemplate', verbose_name='Vorlage'),
        ),
    ]
