# Generated by Django 5.2.7 on 2025-10-16 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_qualificationtemplate_qualification_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyHoursRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('diving', 'Tauchen'), ('height_rescue', 'Höhenrettung'), ('medical', 'Medizinische Fortbildung'), ('breathing', 'Atemschutz'), ('vehicle', 'Fahrzeugführung'), ('technical', 'Technische Rettung'), ('other', 'Sonstiges')], max_length=20, verbose_name='Kategorie')),
                ('year', models.PositiveIntegerField(verbose_name='Jahr')),
                ('required_hours', models.DecimalField(decimal_places=2, help_text='Anzahl der erforderlichen Stunden pro Jahr', max_digits=5, verbose_name='Erforderliche Stunden')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Informationen zur Anforderung', verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Pflichtstunden-Anforderung',
                'verbose_name_plural': 'Pflichtstunden-Anforderungen',
                'ordering': ['-year', 'category'],
                'indexes': [models.Index(fields=['year', 'is_active'], name='personnel_d_year_1de8d6_idx')],
                'unique_together': {('category', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DutyHoursEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('category', models.CharField(choices=[('diving', 'Tauchen'), ('height_rescue', 'Höhenrettung'), ('medical', 'Medizinische Fortbildung'), ('breathing', 'Atemschutz'), ('vehicle', 'Fahrzeugführung'), ('technical', 'Technische Rettung'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Kategorie')),
                ('title', models.CharField(help_text='z.B. Tauchgang, Übung am Turm, EKG-Kurs', max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('date', models.DateField(verbose_name='Datum')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Anzahl der geleisteten Stunden (z.B. 2.5)', max_digits=5, verbose_name='Stunden')),
                ('year', models.PositiveIntegerField(help_text='Wird automatisch aus Datum gesetzt', verbose_name='Jahr')),
                ('supervisor', models.CharField(blank=True, help_text='Wer hat die Stunden bestätigt?', max_length=200, verbose_name='Trainer/Vorgesetzter')),
                ('confirmed', models.BooleanField(default=False, help_text='Wurden die Stunden offiziell bestätigt?', verbose_name='Bestätigt')),
                ('confirmed_date', models.DateField(blank=True, null=True, verbose_name='Bestätigt am')),
                ('certificate_file', models.FileField(blank=True, help_text='Teilnahmebescheinigung, Logbuch-Eintrag, etc.', null=True, upload_to='personnel/duty_hours/', verbose_name='Nachweis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_hours', to='personnel.person', verbose_name='Person')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Pflichtstunden-Eintrag',
                'verbose_name_plural': 'Pflichtstunden-Einträge',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['person', 'category', 'year'], name='personnel_d_person__8f2de6_idx'), models.Index(fields=['date'], name='personnel_d_date_992e10_idx'), models.Index(fields=['confirmed'], name='personnel_d_confirm_f944b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('inspection_type', models.CharField(choices=[('medical', 'Medizinische Untersuchung'), ('fitness', 'Belastungsübung'), ('equipment', 'Gerätewartung'), ('skill', 'Leistungsnachweis'), ('safety', 'Sicherheitsunterweisung'), ('other', 'Sonstiges')], default='medical', max_length=20, verbose_name='Prüfungstyp')),
                ('title', models.CharField(help_text='z.B. G26.3, Atemschutz-Belastungsübung, Leistungsnachweis', max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('scheduled_date', models.DateField(help_text='Wann soll die Prüfung stattfinden?', verbose_name='Geplantes Datum')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Durchgeführt am')),
                ('next_inspection_date', models.DateField(blank=True, help_text='Wann ist die nächste Prüfung fällig?', null=True, verbose_name='Nächste Prüfung')),
                ('interval_months', models.PositiveIntegerField(blank=True, help_text='z.B. 12 für jährliche Prüfung', null=True, verbose_name='Intervall (Monate)')),
                ('status', models.CharField(choices=[('pending', 'Anstehend'), ('due_soon', 'Bald fällig'), ('overdue', 'Überfällig'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgesagt')], default='pending', max_length=20, verbose_name='Status')),
                ('passed', models.BooleanField(blank=True, help_text='Hat die Person die Prüfung bestanden?', null=True, verbose_name='Bestanden')),
                ('result_notes', models.TextField(blank=True, verbose_name='Ergebnisnotizen')),
                ('examiner', models.CharField(blank=True, help_text='Wer hat die Prüfung durchgeführt?', max_length=200, verbose_name='Prüfer/Arzt')),
                ('certificate_file', models.FileField(blank=True, help_text='PDF, JPG oder PNG', null=True, upload_to='personnel/inspections/', verbose_name='Prüfungsdokument')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='personnel.person', verbose_name='Person')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Prüfung',
                'verbose_name_plural': 'Prüfungen',
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['person', 'status'], name='personnel_i_person__6a0361_idx'), models.Index(fields=['scheduled_date'], name='personnel_i_schedul_ed8c9b_idx'), models.Index(fields=['next_inspection_date'], name='personnel_i_next_in_fce829_idx')],
            },
        ),
    ]
