# Generated by Django 5.2.7 on 2025-10-16 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_dutyhoursrequirement_dutyhoursentry_inspection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['department'], name='personnel_p_departm_14d677_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['entry_date'], name='personnel_p_entry_d_486576_idx'),
        ),
    ]
