# Generated by Django 5.2.7 on 2025-10-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_professional_fire_brigade',
            field=models.BooleanField(default=False, help_text='Ist die Person bei der Berufsfeuerwehr?', verbose_name='Berufsfeuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_volunteer_fire_brigade',
            field=models.BooleanField(default=False, help_text='Ist/war die Person in der Freiwilligen Feuerwehr?', verbose_name='Freiwillige Feuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_youth_fire_brigade',
            field=models.BooleanField(default=False, help_text='Ist/war die Person in der Jugendfeuerwehr?', verbose_name='Jugendfeuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='previous_fire_department',
            field=models.CharField(blank=True, help_text='Von welcher Feuerwehr kam die Person? (z.B. BF München)', max_length=200, verbose_name='Vorherige Feuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='previous_fire_department_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Eintritt vorherige Feuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='previous_fire_department_exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Austritt vorherige Feuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='professional_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Eintritt Berufsfeuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='volunteer_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Eintritt Freiwillige Feuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='volunteer_unit',
            field=models.CharField(blank=True, help_text='z.B. Löschzug 1, Löschgruppe Musterort', max_length=100, verbose_name='Einheit FF'),
        ),
        migrations.AddField(
            model_name='person',
            name='youth_entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Eintritt Jugendfeuerwehr'),
        ),
        migrations.AddField(
            model_name='person',
            name='youth_exit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Austritt Jugendfeuerwehr'),
        ),
    ]
