# Generated by Django 5.0.14 on 2025-10-17 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('personnel', '0007_add_organization_membership_and_anniversaries'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='person',
            new_name='personnel_p_departm_cedca3_idx',
            old_name='personnel_p_departm_14d677_idx',
        ),
        migrations.AddField(
            model_name='person',
            name='watch_crew',
            field=models.ForeignKey(blank=True, help_text='z.B. A-Schicht Wache 1', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_members', to='organization.watchcrew', verbose_name='Wachmannschaft'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, help_text='z.B. Einsatzabteilung, Jugendfeuerwehr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='organization.department', verbose_name='Abteilung'),
        ),
        migrations.AlterField(
            model_name='person',
            name='volunteer_unit',
            field=models.ForeignKey(blank=True, help_text='z.B. Löschzug 1, Löschgruppe Musterort', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteers', to='organization.volunteerunit', verbose_name='Einheit FF'),
        ),
    ]
