# Generated by Django 5.0.14 on 2025-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_function'),
        ('personnel', '0008_rename_personnel_p_departm_14d677_idx_personnel_p_departm_cedca3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='functions',
            field=models.ManyToManyField(blank=True, help_text='z.B. Gruppenführer, Taucher, Atemschutzgeräteträger', related_name='personnel', to='organization.function', verbose_name='Funktionen'),
        ),
        migrations.AlterField(
            model_name='person',
            name='function',
            field=models.CharField(blank=True, help_text='Veraltet - bitte "Funktionen" verwenden', max_length=100, verbose_name='Funktion (deprecated)'),
        ),
    ]
