# Generated by Django 5.0.14 on 2025-10-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0010_qualificationtemplate_required_duty_hour_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyHoursCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Tauchen, Höhenrettung, Medizinische Fortbildung', max_length=200, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(blank=True, help_text='z.B. TAU, HR, MED', max_length=20, verbose_name='Abkürzung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('color', models.CharField(default='#6B7280', help_text='Hex-Farbcode für Darstellung (z.B. #3B82F6)', max_length=7, verbose_name='Farbe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.IntegerField(default=0, help_text='Niedrigere Werte werden zuerst angezeigt', verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Pflichtstunden-Kategorie',
                'verbose_name_plural': 'Pflichtstunden-Kategorien',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='dutyhoursentry',
            new_name='personnel_d_person__58f061_idx',
            old_name='personnel_d_person__8f2de6_idx',
        ),
        migrations.RemoveField(
            model_name='qualificationtemplate',
            name='required_duty_hour_categories',
        ),
        migrations.AddIndex(
            model_name='dutyhourscategory',
            index=models.Index(fields=['is_active', 'sort_order'], name='personnel_d_is_acti_db2c5e_idx'),
        ),
        migrations.AlterField(
            model_name='dutyhoursentry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='personnel.dutyhourscategory', verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='dutyhoursrequirement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='personnel.dutyhourscategory', verbose_name='Kategorie'),
        ),
        migrations.AddField(
            model_name='qualificationtemplate',
            name='required_duty_hour_categories',
            field=models.ManyToManyField(blank=True, help_text='Wählen Sie die Pflichtstunden-Kategorien aus, die für diese Qualifikation erforderlich sind', related_name='required_for_qualifications', to='personnel.dutyhourscategory', verbose_name='Erforderliche Pflichtstunden-Kategorien'),
        ),
    ]
