# Generated by Django 5.0.14 on 2025-10-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_qualificationtype_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='qualification_templates',
            field=models.ManyToManyField(blank=True, help_text='Welche Qualifikationen sollte diese Person haben?', related_name='personnel', to='personnel.qualificationtemplate', verbose_name='Qualifikations-Vorlagen'),
        ),
    ]
