# Generated by Django 5.0.14 on 2025-10-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0013_person_qualification_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyhourscategory',
            name='related_module',
            field=models.CharField(blank=True, choices=[('equipment', 'Ausrüstung'), ('diving', 'Taucher'), ('height_rescue', 'Höhenrettung')], help_text='Modul, zu dem diese Pflichtstunden-Kategorie gehört (z.B. Taucher, Höhenrettung, Ausrüstung)', max_length=50, null=True, verbose_name='Zugeordnetes Modul'),
        ),
        migrations.AddField(
            model_name='qualificationtemplate',
            name='related_module',
            field=models.CharField(blank=True, choices=[('equipment', 'Ausrüstung'), ('diving', 'Taucher'), ('height_rescue', 'Höhenrettung')], help_text='Modul, zu dem diese Qualifikation gehört (z.B. Taucher, Höhenrettung, Ausrüstung)', max_length=50, null=True, verbose_name='Zugeordnetes Modul'),
        ),
    ]
