# Generated by Django 5.0.14 on 2025-10-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0014_dutyhourscategory_related_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='show_private_contact_data',
            field=models.BooleanField(default=False, help_text='Sollen private Kontaktdaten (Telefon, Mobil, Adresse) im Telefonbuch angezeigt werden?', verbose_name='Private Kontaktdaten öffentlich'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_location',
            field=models.ForeignKey(blank=True, help_text='Standort/Wache der Person', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationed_personnel', to='locations.location', verbose_name='Dienstlicher Standort'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_mobile',
            field=models.CharField(blank=True, help_text='Dienstliches Mobiltelefon', max_length=50, verbose_name='Dienstliche Handynummer'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_phone',
            field=models.CharField(blank=True, help_text='Dienstliche Festnetznummer', max_length=50, verbose_name='Dienstliche Telefonnummer'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_room',
            field=models.CharField(blank=True, help_text='z.B. Raum 203, Büro Wachleitung', max_length=100, verbose_name='Raum/Büro'),
        ),
    ]
