# Generated by Django 5.0.14 on 2025-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0015_person_show_private_contact_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emergency_contact_address',
            field=models.TextField(blank=True, help_text='Vollständige Adresse des Notfallkontakts', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, help_text='Mobilnummer des Notfallkontakts', max_length=50, verbose_name='Mobil'),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Vollständiger Name des Notfallkontakts', max_length=200, verbose_name='Notfallkontakt Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Telefonnummer des Notfallkontakts', max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='z.B. Ehepartner, Elternteil, Geschwister', max_length=100, verbose_name='Beziehung'),
        ),
    ]
