# Generated by Django 5.0.14 on 2025-11-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0016_person_emergency_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='activity',
            field=models.CharField(blank=True, choices=[('fire_protection', 'Brandschutz'), ('day_service', 'Tagesdienst'), ('command_service', 'Führungsdienst'), ('intern', 'Praktikant')], help_text='Art der Tätigkeit bei der Feuerwehr', max_length=50, verbose_name='Tätigkeit'),
        ),
    ]
