# Generated by Django 5.0.14 on 2025-12-18 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0017_person_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Feuerwehrmann, Oberfeuerwehrmann, Brandmeister', max_length=100, verbose_name='Bezeichnung')),
                ('abbreviation', models.CharField(help_text='z.B. FM, OFM, BM', max_length=10, verbose_name='Abkürzung')),
                ('organization_type', models.CharField(choices=[('youth', 'Jugendfeuerwehr'), ('volunteer', 'Freiwillige Feuerwehr')], help_text='Jugendfeuerwehr oder Freiwillige Feuerwehr', max_length=20, verbose_name='Organisationstyp')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Reihenfolge der Dienstgrade (niedrigere Werte = niedrigerer Dienstgrad)', verbose_name='Sortierung')),
                ('min_years_in_previous', models.DecimalField(blank=True, decimal_places=1, help_text='Mindestzeit im vorherigen Dienstgrad für Beförderung', max_digits=4, null=True, verbose_name='Min. Jahre im vorherigen Dienstgrad')),
                ('min_total_years', models.DecimalField(blank=True, decimal_places=1, help_text='Mindest-Gesamtdienstzeit für diesen Dienstgrad', max_digits=4, null=True, verbose_name='Min. Gesamtdienstzeit')),
                ('requires_course', models.CharField(blank=True, help_text='z.B. Truppführer-Lehrgang, Gruppenführer-Lehrgang', max_length=200, verbose_name='Erforderlicher Lehrgang')),
                ('is_functional_rank', models.BooleanField(default=False, help_text='Ist dies ein Funktionsdienstgrad (z.B. Jugendgruppenführer)?', verbose_name='Funktionsdienstgrad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Informationen zum Dienstgrad', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dienstgrad',
                'verbose_name_plural': 'Dienstgrade',
                'ordering': ['organization_type', 'sort_order'],
                'indexes': [models.Index(fields=['organization_type', 'is_active', 'sort_order'], name='personnel_r_organiz_93b2a0_idx')],
                'unique_together': {('name', 'organization_type')},
            },
        ),
        migrations.CreateModel(
            name='PersonRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('since_date', models.DateField(help_text='Datum der Beförderung', verbose_name='Seit')),
                ('is_current', models.BooleanField(default=True, help_text='Ist dies der aktuelle Dienstgrad?', verbose_name='Aktueller Dienstgrad')),
                ('promoted_by', models.CharField(blank=True, help_text='Wer hat die Beförderung ausgesprochen?', max_length=200, verbose_name='Befördert durch')),
                ('certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Urkunden-Nr.')),
                ('certificate_file', models.FileField(blank=True, help_text='PDF oder Bild der Urkunde', null=True, upload_to='personnel/rank_certificates/', verbose_name='Beförderungsurkunde')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='personnel.person', verbose_name='Person')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_ranks', to='personnel.rank', verbose_name='Dienstgrad')),
            ],
            options={
                'verbose_name': 'Dienstgrad (Person)',
                'verbose_name_plural': 'Dienstgrade (Personen)',
                'ordering': ['-since_date'],
                'indexes': [models.Index(fields=['person', 'is_current'], name='personnel_p_person__8112de_idx'), models.Index(fields=['rank', 'since_date'], name='personnel_p_rank_id_b768b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceInterruption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('organization_type', models.CharField(choices=[('youth', 'Jugendfeuerwehr'), ('volunteer', 'Freiwillige Feuerwehr')], help_text='Für welche Organisation gilt die Unterbrechung?', max_length=20, verbose_name='Organisation')),
                ('interruption_type', models.CharField(choices=[('pause', 'Pause/Ruhend'), ('other_department', 'Andere Feuerwehr'), ('illness', 'Krankheit'), ('military', 'Wehrdienst/Bundeswehr'), ('other', 'Sonstiges')], default='pause', max_length=20, verbose_name='Art der Unterbrechung')),
                ('start_date', models.DateField(help_text='Beginn der Unterbrechung', verbose_name='Beginn')),
                ('end_date', models.DateField(blank=True, help_text='Ende der Unterbrechung (leer wenn noch aktiv)', null=True, verbose_name='Ende')),
                ('other_department_name', models.CharField(blank=True, help_text='Falls bei anderer Feuerwehr: Name der Feuerwehr', max_length=200, verbose_name='Name der anderen Feuerwehr')),
                ('reason', models.CharField(blank=True, help_text='Grund für die Unterbrechung', max_length=500, verbose_name='Grund')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_interruptions', to='personnel.person', verbose_name='Person')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Dienstunterbrechung',
                'verbose_name_plural': 'Dienstunterbrechungen',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['person', 'organization_type'], name='personnel_s_person__d65c62_idx'), models.Index(fields=['start_date', 'end_date'], name='personnel_s_start_d_ccf55b_idx')],
            },
        ),
    ]
