# Generated by Django 5.0.14 on 2026-02-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0019_add_default_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='watch_division',
            field=models.CharField(blank=True, choices=[('', '---------'), ('WA1', 'WA1'), ('WA2', 'WA2'), ('WA3', 'WA3')], help_text='Wachabteilung der Person (WA1, WA2 oder WA3)', max_length=10, verbose_name='Wachabteilung'),
        ),
    ]
