# Generated by Django 5.2.15 on 2026-09-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_add_watch_division'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('manage_ff_person', 'Kann FF-Personal verwalten (FF-Verwaltung)')], 'verbose_name': 'Person', 'verbose_name_plural': 'Personal'},
        ),
    ]
