# Generated by Django 5.0.14 on 2025-10-17 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0007_add_organization_membership_and_anniversaries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicenseCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(help_text='Wann wurde der Führerschein kontrolliert?', verbose_name='Datum der Überprüfung')),
                ('license_presented', models.BooleanField(default=False, help_text='Wurde der physische Führerschein vorgelegt?', verbose_name='Führerschein vorgezeigt')),
                ('has_class_B', models.BooleanField(default=False, verbose_name='Klasse B (PKW)')),
                ('has_class_BE', models.BooleanField(default=False, verbose_name='Klasse BE (PKW mit Anhänger)')),
                ('has_class_C', models.BooleanField(default=False, verbose_name='Klasse C (LKW)')),
                ('has_class_CE', models.BooleanField(default=False, verbose_name='Klasse CE (LKW mit Anhänger)')),
                ('has_class_C1', models.BooleanField(default=False, verbose_name='Klasse C1 (LKW bis 7,5t)')),
                ('has_class_C1E', models.BooleanField(default=False, verbose_name='Klasse C1E (LKW bis 7,5t mit Anhänger)')),
                ('has_class_D', models.BooleanField(default=False, verbose_name='Klasse D (Bus)')),
                ('has_class_A', models.BooleanField(default=False, verbose_name='Klasse A (Motorrad)')),
                ('license_expiry_date', models.DateField(blank=True, help_text='Ablaufdatum des Führerscheindokuments (nur für neue Führerscheine)', null=True, verbose_name='Führerschein gültig bis')),
                ('class_c_expiry_date', models.DateField(blank=True, help_text='Befristung der Fahrerlaubnis für C/C1 (alle 5 Jahre)', null=True, verbose_name='Klasse C/C1 gültig bis')),
                ('class_c_medical_check_date', models.DateField(blank=True, help_text='Datum der letzten ärztlichen Untersuchung für C/C1', null=True, verbose_name='Ärztliche Untersuchung C/C1 vom')),
                ('class_c_medical_expiry_date', models.DateField(blank=True, help_text='Gültigkeit des ärztlichen Gutachtens für C/C1', null=True, verbose_name='Ärztliche Untersuchung C/C1 gültig bis')),
                ('class_ce_expiry_date', models.DateField(blank=True, help_text='Befristung der Fahrerlaubnis für CE/C1E (alle 5 Jahre)', null=True, verbose_name='Klasse CE/C1E gültig bis')),
                ('class_ce_medical_check_date', models.DateField(blank=True, help_text='Datum der letzten ärztlichen Untersuchung für CE/C1E', null=True, verbose_name='Ärztliche Untersuchung CE/C1E vom')),
                ('class_ce_medical_expiry_date', models.DateField(blank=True, help_text='Gültigkeit des ärztlichen Gutachtens für CE/C1E', null=True, verbose_name='Ärztliche Untersuchung CE/C1E gültig bis')),
                ('class_d_expiry_date', models.DateField(blank=True, help_text='Befristung der Fahrerlaubnis für D/D1', null=True, verbose_name='Klasse D/D1 gültig bis')),
                ('class_d_medical_check_date', models.DateField(blank=True, help_text='Datum der letzten ärztlichen Untersuchung für D/D1', null=True, verbose_name='Ärztliche Untersuchung D/D1 vom')),
                ('class_d_medical_expiry_date', models.DateField(blank=True, help_text='Gültigkeit des ärztlichen Gutachtens für D/D1', null=True, verbose_name='Ärztliche Untersuchung D/D1 gültig bis')),
                ('notes', models.TextField(blank=True, help_text='Besonderheiten, Einschränkungen, etc.', verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_license_checks', to=settings.AUTH_USER_MODEL, verbose_name='Überprüft von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_license_checks', to='personnel.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Führerscheinüberprüfung',
                'verbose_name_plural': 'Führerscheinüberprüfungen',
                'ordering': ['-check_date', 'person__last_name', 'person__first_name'],
                'indexes': [models.Index(fields=['person', '-check_date'], name='driving_lic_person__a097a5_idx'), models.Index(fields=['check_date'], name='driving_lic_check_d_15b827_idx'), models.Index(fields=['license_presented'], name='driving_lic_license_8c57d9_idx')],
            },
        ),
    ]
