# Generated by Django 5.0.14 on 2025-10-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_license', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglicensecheck',
            name='license_expiry_date',
            field=models.DateField(blank=True, help_text='Ablaufdatum des Führerscheindokuments', null=True, verbose_name='Führerschein gültig bis'),
        ),
    ]
