# Generated by Django 5.0.14 on 2025-10-03 11:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_number', models.CharField(help_text='Eindeutige Artikelnummer', max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Hersteller-Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestand')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Warnung bei Unterschreitung', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximalbestand')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode/EAN')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR-Code')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/images/', verbose_name='Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('equipment_type', models.CharField(choices=[('helmet', 'Helm'), ('mask', 'Atemschutzmaske'), ('gloves', 'Handschuhe'), ('boots', 'Stiefel'), ('breathing_apparatus', 'Atemschutzgerät'), ('oxygen_tank', 'Sauerstoffflasche'), ('filter', 'Filter'), ('hose', 'Schlauch'), ('coupling', 'Kupplung'), ('nozzle', 'Strahlrohr'), ('valve', 'Ventil'), ('ladder', 'Leiter'), ('rope', 'Seil'), ('carabiner', 'Karabiner'), ('harness', 'Gurt'), ('pump', 'Pumpe'), ('generator', 'Stromerzeuger'), ('compressor', 'Kompressor'), ('tool_hydraulic', 'Hydraulisches Werkzeug'), ('tool_hand', 'Handwerkzeug'), ('tool_power', 'Elektrowerkzeug'), ('chainsaw', 'Motorsäge'), ('detector_gas', 'Gaswarngerät'), ('detector_co', 'CO-Warngerät'), ('detector_radiation', 'Strahlenmessgerät'), ('thermal_camera', 'Wärmebildkamera'), ('spotlight', 'Scheinwerfer'), ('flashlight', 'Taschenlampe'), ('headlamp', 'Stirnlampe'), ('radio', 'Funkgerät'), ('container', 'Behälter/Container'), ('other', 'Sonstiges')], max_length=30, verbose_name='Gerätetyp')),
                ('equipment_status', models.CharField(choices=[('operational', 'Einsatzbereit'), ('maintenance', 'In Wartung'), ('defective', 'Defekt'), ('testing', 'In Prüfung'), ('decommissioned', 'Ausgemustert')], default='operational', max_length=20, verbose_name='Betriebszustand')),
                ('model_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baujahr')),
                ('serial_number', models.CharField(blank=True, help_text='Eindeutige Herstellernummer', max_length=100, verbose_name='Seriennummer')),
                ('power_source', models.CharField(choices=[('none', 'Keine'), ('manual', 'Manuell'), ('electric_battery', 'Elektrisch (Akku)'), ('electric_mains', 'Elektrisch (Netz)'), ('gasoline', 'Benzin'), ('diesel', 'Diesel'), ('hydraulic', 'Hydraulisch'), ('pneumatic', 'Pneumatisch'), ('gas', 'Gas')], default='none', max_length=20, verbose_name='Stromversorgung/Antrieb')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gewicht (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='z.B. "100x50x30 cm"', max_length=100, verbose_name='Abmessungen')),
                ('requires_certification', models.BooleanField(default=False, help_text='Erfordert regelmäßige Zertifizierung', verbose_name='Zertifizierungspflichtig')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Zertifizierungsnummer')),
                ('certification_expires', models.DateField(blank=True, null=True, verbose_name='Zertifizierung läuft ab')),
                ('certification_status', models.CharField(choices=[('valid', 'Gültig'), ('expiring_soon', 'Läuft bald ab'), ('expired', 'Abgelaufen'), ('not_required', 'Nicht erforderlich')], default='not_required', max_length=20, verbose_name='Zertifizierungsstatus')),
                ('requires_maintenance', models.BooleanField(default=True, verbose_name='Wartungspflichtig')),
                ('maintenance_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wartungsintervall (Monate)')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='Wartungsnotizen')),
                ('requires_inspection', models.BooleanField(default=False, help_text='z.B. UVV-Prüfung, TÜV', verbose_name='Prüfpflicht')),
                ('inspection_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prüfintervall (Monate)')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('inspection_notes', models.TextField(blank=True, verbose_name='Prüfnotizen')),
                ('max_operating_hours', models.PositiveIntegerField(blank=True, help_text='Maximale Betriebsstunden laut Hersteller', null=True, verbose_name='Max. Betriebsstunden')),
                ('current_operating_hours', models.PositiveIntegerField(default=0, verbose_name='Aktuelle Betriebsstunden')),
                ('max_usage_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max. Nutzungsdauer (Jahre)')),
                ('replacement_due_date', models.DateField(blank=True, null=True, verbose_name='Austausch fällig am')),
                ('has_qr_code', models.BooleanField(default=False, verbose_name='QR-Code vorhanden')),
                ('qr_code_data', models.CharField(blank=True, max_length=200, verbose_name='QR-Code Daten')),
                ('technical_specs', models.JSONField(blank=True, default=dict, help_text='Zusätzliche technische Daten als JSON', verbose_name='Technische Spezifikationen')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='vehicles.vehicle', verbose_name='Zugeordnet zu Fahrzeug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Ausrüstung/Gerät',
                'verbose_name_plural': 'Ausrüstung/Geräte',
                'ordering': ['equipment_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('movement_type', models.CharField(choices=[('incoming', 'Wareneingang'), ('outgoing', 'Warenausgang'), ('transfer', 'Umlagerung'), ('inventory', 'Inventur-Korrektur'), ('damage', 'Beschädigung/Schwund'), ('return', 'Rückgabe'), ('disposal', 'Entsorgung')], max_length=20, verbose_name='Bewegungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('reference_number', models.CharField(blank=True, help_text='z.B. Lieferschein-Nr., Bestellnummer', max_length=100, verbose_name='Referenznummer')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Bewegungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('condition_before', models.TextField(blank=True, help_text='Zustand bei Entnahme', verbose_name='Zustand vorher')),
                ('condition_after', models.TextField(blank=True, help_text='Zustand bei Rückgabe', verbose_name='Zustand nachher')),
                ('is_defective', models.BooleanField(default=False, verbose_name='Defekt gemeldet')),
                ('defect_description', models.TextField(blank=True, verbose_name='Defektbeschreibung')),
                ('operating_hours_delta', models.PositiveIntegerField(default=0, help_text='Zusätzliche Betriebsstunden seit letzter Bewegung', verbose_name='Betriebsstunden (Delta)')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückkosten (EUR)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtkosten (EUR)')),
                ('delivery_note', models.CharField(blank=True, max_length=100, verbose_name='Lieferschein-Nr.')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_outgoing', to='locations.location', verbose_name='Von Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='equipment.equipmentitem', verbose_name='Ausrüstung/Gerät')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_movements', to='personnel.person', verbose_name='Person')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_incoming', to='locations.location', verbose_name='Nach Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Fahrzeug bei Aus-/Einlagerung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_movements', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': 'Lagerbewegung',
                'verbose_name_plural': 'Lagerbewegungen',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['equipment_type'], name='equipment_e_equipme_58a820_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['equipment_status'], name='equipment_e_equipme_92eb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['serial_number'], name='equipment_e_serial__ed582e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['next_maintenance_date'], name='equipment_e_next_ma_f35d07_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['next_inspection_date'], name='equipment_e_next_in_079b41_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitem',
            index=models.Index(fields=['assigned_vehicle'], name='equipment_e_assigne_155e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentstockmovement',
            index=models.Index(fields=['item', '-movement_date'], name='equipment_e_item_id_d3dcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentstockmovement',
            index=models.Index(fields=['vehicle', '-movement_date'], name='equipment_e_vehicle_1003b8_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentstockmovement',
            index=models.Index(fields=['person', '-movement_date'], name='equipment_e_person__fa4c07_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentstockmovement',
            index=models.Index(fields=['movement_type', '-movement_date'], name='equipment_e_movemen_a3135b_idx'),
        ),
    ]
