# Generated by Django 5.0.14 on 2025-10-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_equipmentitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='manual_document',
            field=models.FileField(blank=True, help_text='PDF oder Bild (wird per OCR durchsuchbar gemacht)', null=True, upload_to='equipment/manuals/%Y/%m/', verbose_name='Handbuch/Dokument'),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='manual_ocr_text',
            field=models.TextField(blank=True, help_text='Automatisch extrahierter Text für Suchfunktion', verbose_name='OCR-Text aus Handbuch'),
        ),
    ]
