# Generated by Django 5.0.14 on 2025-10-05 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentitem_manual_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInspectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_interval_months', models.PositiveIntegerField(blank=True, help_text='Überschreibt Standard-Intervall der Prüfungsart', null=True, verbose_name='Individuelles Intervall (Monate)')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('is_active', models.BooleanField(default=True, help_text='Prüfung wird noch durchgeführt', verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspection_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_assignments', to='equipment.equipmentitem', verbose_name='Gerät')),
            ],
            options={
                'verbose_name': 'Prüfungszuweisung',
                'verbose_name_plural': 'Prüfungszuweisungen',
                'ordering': ['item', 'inspection_type'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Prüfungsdatum')),
                ('result', models.CharField(choices=[('passed', 'Bestanden'), ('passed_with_remarks', 'Bestanden mit Anmerkungen'), ('failed', 'Nicht bestanden'), ('incomplete', 'Unvollständig')], max_length=30, verbose_name='Prüfergebnis')),
                ('checklist_results', models.JSONField(blank=True, default=dict, help_text='Detaillierte Ergebnisse der einzelnen Prüfpunkte', verbose_name='Checklisten-Ergebnisse')),
                ('findings', models.TextField(blank=True, verbose_name='Feststellungen/Mängel')),
                ('recommendations', models.TextField(blank=True, verbose_name='Empfehlungen/Maßnahmen')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung fällig am')),
                ('inspection_sticker_number', models.CharField(blank=True, max_length=100, verbose_name='Prüfplaketten-Nummer')),
                ('inspection_certificate', models.FileField(blank=True, null=True, upload_to='equipment/inspection_certificates/', verbose_name='Prüfprotokoll (PDF)')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste der Foto-URLs', verbose_name='Fotos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='equipment.equipmentinspectionassignment', verbose_name='Prüfungszuweisung')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Prüfer')),
            ],
            options={
                'verbose_name': 'Prüfungsprotokoll',
                'verbose_name_plural': 'Prüfungsprotokolle',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Sichtprüfung, Belastungsprüfung', max_length=200, verbose_name='Prüfungsbezeichnung')),
                ('description', models.TextField(blank=True, help_text='Was wird bei dieser Prüfung geprüft?', verbose_name='Beschreibung')),
                ('inspection_standard', models.CharField(blank=True, help_text='z.B. DIN 14811, DGUV 3, BetrSichV', max_length=100, verbose_name='Prüfnorm')),
                ('interval_months', models.PositiveIntegerField(blank=True, help_text='Wie oft muss diese Prüfung durchgeführt werden?', null=True, verbose_name='Intervall (Monate)')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Liste der zu prüfenden Punkte', verbose_name='Prüfpunkte')),
                ('applicable_equipment_types', models.JSONField(blank=True, default=list, help_text='Für welche Gerätetypen ist diese Prüfung relevant?', verbose_name='Anwendbar auf Gerätetypen')),
                ('requires_certification', models.BooleanField(default=False, help_text='Darf nur von zertifizierten Personen durchgeführt werden', verbose_name='Befähigungsnachweis erforderlich')),
                ('requires_external_service', models.BooleanField(default=False, help_text='Muss durch externen Dienstleister durchgeführt werden', verbose_name='Externe Prüfung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inspection_types', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Prüfungsart',
                'verbose_name_plural': 'Prüfungsarten',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipmentinspectionassignment',
            name='inspection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='equipment.inspectiontype', verbose_name='Prüfungsart'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentinspectionassignment',
            unique_together={('item', 'inspection_type')},
        ),
    ]
