# Generated by Django 5.2.7 on 2025-10-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipmentinspectionassignment_inspectionrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrecord',
            name='custom_field_values',
            field=models.JSONField(blank=True, default=dict, help_text='Werte der benutzerdefinierten Messfelder', verbose_name='Messwerte'),
        ),
        migrations.AddField(
            model_name='inspectiontype',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, help_text='Individuelle Felder für Messwerte (z.B. Durchbiegung, Abstand, etc.)', verbose_name='Benutzerdefinierte Messfelder'),
        ),
    ]
