# Generated by Django 5.2.7 on 2025-10-05 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_inspectionrecord_custom_field_values_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentMaintenanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_interval_months', models.PositiveIntegerField(blank=True, help_text='Überschreibt Standard-Intervall der Wartungsart', null=True, verbose_name='Individuelles Intervall (Monate)')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('is_active', models.BooleanField(default=True, help_text='Wartung wird noch durchgeführt', verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assignments', to='equipment.equipmentitem', verbose_name='Gerät')),
            ],
            options={
                'verbose_name': 'Wartungszuweisung',
                'verbose_name_plural': 'Wartungszuweisungen',
                'ordering': ['item', 'maintenance_type'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Wartungsdatum')),
                ('status', models.CharField(choices=[('completed', 'Abgeschlossen'), ('completed_with_remarks', 'Abgeschlossen mit Anmerkungen'), ('incomplete', 'Unvollständig'), ('parts_required', 'Ersatzteile erforderlich')], max_length=30, verbose_name='Status')),
                ('checklist_results', models.JSONField(blank=True, default=dict, help_text='Detaillierte Ergebnisse der einzelnen Wartungspunkte', verbose_name='Checklisten-Ergebnisse')),
                ('custom_field_values', models.JSONField(blank=True, default=dict, help_text='Werte der benutzerdefinierten Messfelder', verbose_name='Messwerte')),
                ('findings', models.TextField(blank=True, verbose_name='Feststellungen/Befunde')),
                ('work_performed', models.TextField(blank=True, verbose_name='Durchgeführte Arbeiten')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung fällig am')),
                ('parts_used', models.TextField(blank=True, verbose_name='Verwendete Ersatzteile')),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Arbeitsstunden')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gesamtkosten')),
                ('maintenance_report', models.FileField(blank=True, null=True, upload_to='equipment/maintenance_reports/', verbose_name='Wartungsbericht (PDF)')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste der Foto-URLs', verbose_name='Fotos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='equipment.equipmentmaintenanceassignment', verbose_name='Wartungszuweisung')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='Techniker')),
            ],
            options={
                'verbose_name': 'Wartungsprotokoll',
                'verbose_name_plural': 'Wartungsprotokolle',
                'ordering': ['-maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Ölwechsel, Filterwechsel, Jahreswartung', max_length=200, verbose_name='Wartungsbezeichnung')),
                ('description', models.TextField(blank=True, help_text='Was wird bei dieser Wartung durchgeführt?', verbose_name='Beschreibung')),
                ('maintenance_standard', models.CharField(blank=True, help_text='z.B. Herstellervorgabe, DIN-Norm', max_length=100, verbose_name='Wartungsstandard')),
                ('interval_months', models.PositiveIntegerField(blank=True, help_text='Wie oft muss diese Wartung durchgeführt werden?', null=True, verbose_name='Intervall (Monate)')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Liste der durchzuführenden Wartungsarbeiten', verbose_name='Wartungspunkte')),
                ('applicable_equipment_types', models.JSONField(blank=True, default=list, help_text='Für welche Gerätetypen ist diese Wartung relevant?', verbose_name='Anwendbar auf Gerätetypen')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Individuelle Felder für Messwerte (z.B. Ölstand, Betriebsstunden, etc.)', verbose_name='Benutzerdefinierte Messfelder')),
                ('requires_certification', models.BooleanField(default=False, help_text='Darf nur von zertifizierten Personen durchgeführt werden', verbose_name='Befähigungsnachweis erforderlich')),
                ('requires_external_service', models.BooleanField(default=False, help_text='Muss durch externen Dienstleister durchgeführt werden', verbose_name='Externe Wartung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_types', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Wartungsart',
                'verbose_name_plural': 'Wartungsarten',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipmentmaintenanceassignment',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_assignments', to='equipment.maintenancetype', verbose_name='Wartungsart'),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentmaintenanceassignment',
            unique_together={('item', 'maintenance_type')},
        ),
    ]
