# Generated by Django 5.2.7 on 2025-10-17 13:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_equipmentmaintenanceassignment_maintenancerecord_and_more'),
        ('inventory_base', '0001_initial'),
        ('locations', '0003_location_technical_equipment'),
        ('vehicles', '0005_vehicle_actual_retirement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_number', models.CharField(help_text='Eindeutige Stammdatennummer (z.B. EQ-2025-001)', max_length=50, unique=True, verbose_name='Stammdaten-Nummer')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('equipment_type', models.CharField(choices=[('helmet', 'Helm'), ('mask', 'Atemschutzmaske'), ('gloves', 'Handschuhe'), ('boots', 'Stiefel'), ('breathing_apparatus', 'Atemschutzgerät'), ('oxygen_tank', 'Sauerstoffflasche'), ('filter', 'Filter'), ('hose', 'Schlauch'), ('coupling', 'Kupplung'), ('nozzle', 'Strahlrohr'), ('valve', 'Ventil'), ('ladder', 'Leiter'), ('rope', 'Seil'), ('carabiner', 'Karabiner'), ('harness', 'Gurt'), ('pump', 'Pumpe'), ('generator', 'Stromerzeuger'), ('compressor', 'Kompressor'), ('tool_hydraulic', 'Hydraulisches Werkzeug'), ('tool_hand', 'Handwerkzeug'), ('tool_power', 'Elektrowerkzeug'), ('chainsaw', 'Motorsäge'), ('detector_gas', 'Gaswarngerät'), ('detector_co', 'CO-Warngerät'), ('detector_radiation', 'Strahlenmessgerät'), ('thermal_camera', 'Wärmebildkamera'), ('spotlight', 'Scheinwerfer'), ('flashlight', 'Taschenlampe'), ('headlamp', 'Stirnlampe'), ('radio', 'Funkgerät'), ('container', 'Behälter/Container'), ('other', 'Sonstiges')], max_length=30, verbose_name='Gerätetyp')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Modell/Typ')),
                ('model_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baujahr')),
                ('supplier_item_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Artikelnummer')),
                ('power_source', models.CharField(choices=[('none', 'Keine'), ('manual', 'Manuell'), ('electric_battery', 'Elektrisch (Akku)'), ('electric_mains', 'Elektrisch (Netz)'), ('gasoline', 'Benzin'), ('diesel', 'Diesel'), ('hydraulic', 'Hydraulisch'), ('pneumatic', 'Pneumatisch'), ('gas', 'Gas')], default='none', max_length=20, verbose_name='Stromversorgung/Antrieb')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gewicht (kg)')),
                ('dimensions', models.CharField(blank=True, help_text='z.B. "100x50x30 cm"', max_length=100, verbose_name='Abmessungen')),
                ('technical_specs', models.JSONField(blank=True, default=dict, help_text='Zusätzliche technische Daten als JSON', verbose_name='Technische Spezifikationen')),
                ('requires_certification', models.BooleanField(default=False, help_text='Erfordert regelmäßige Zertifizierung', verbose_name='Zertifizierungspflichtig')),
                ('requires_maintenance', models.BooleanField(default=True, verbose_name='Wartungspflichtig')),
                ('maintenance_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wartungsintervall (Monate)')),
                ('requires_inspection', models.BooleanField(default=False, help_text='z.B. UVV-Prüfung, TÜV', verbose_name='Prüfpflicht')),
                ('inspection_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prüfintervall (Monate)')),
                ('max_operating_hours', models.PositiveIntegerField(blank=True, help_text='Maximale Betriebsstunden laut Hersteller', null=True, verbose_name='Max. Betriebsstunden')),
                ('max_usage_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max. Nutzungsdauer (Jahre)')),
                ('manual_document', models.FileField(blank=True, help_text='PDF oder Bild (wird per OCR durchsuchbar gemacht)', null=True, upload_to='equipment/manuals/%Y/%m/', verbose_name='Handbuch/Dokument')),
                ('manual_ocr_text', models.TextField(blank=True, help_text='Automatisch extrahierter Text für Suchfunktion', verbose_name='OCR-Text aus Handbuch')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/images/%Y/%m/', verbose_name='Bild')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Durchschnittlicher Anschaffungspreis', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Anschaffungspreis (EUR)')),
                ('unit', models.CharField(default='Stück', help_text='Stück, Meter, Liter, etc.', max_length=20, verbose_name='Einheit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_masters', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_masters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_masters', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_equipment_masters', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Ausrüstungs-Stammdaten',
                'verbose_name_plural': 'Ausrüstungs-Stammdaten',
                'ordering': ['master_number'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentDeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Eindeutige Inventarnummer (z.B. P-2025-042)', max_length=100, unique=True, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(blank=True, help_text='Eindeutige Herstellernummer', max_length=100, verbose_name='Seriennummer')),
                ('is_operational', models.BooleanField(default=True, verbose_name='Einsatzbereit')),
                ('equipment_status', models.CharField(choices=[('operational', 'Einsatzbereit'), ('maintenance', 'In Wartung'), ('defective', 'Defekt'), ('testing', 'In Prüfung'), ('decommissioned', 'Ausgemustert')], default='operational', max_length=20, verbose_name='Betriebszustand')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Zertifizierungsnummer')),
                ('certification_expires', models.DateField(blank=True, null=True, verbose_name='Zertifizierung läuft ab')),
                ('certification_status', models.CharField(choices=[('valid', 'Gültig'), ('expiring_soon', 'Läuft bald ab'), ('expired', 'Abgelaufen'), ('not_required', 'Nicht erforderlich')], default='not_required', max_length=20, verbose_name='Zertifizierungsstatus')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('maintenance_notes', models.TextField(blank=True, verbose_name='Wartungsnotizen')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('inspection_notes', models.TextField(blank=True, verbose_name='Prüfnotizen')),
                ('current_operating_hours', models.PositiveIntegerField(default=0, verbose_name='Aktuelle Betriebsstunden')),
                ('replacement_due_date', models.DateField(blank=True, null=True, verbose_name='Austausch fällig am')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Anschaffungsdatum')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Anschaffungspreis (EUR)')),
                ('has_qr_code', models.BooleanField(default=False, verbose_name='QR-Code vorhanden')),
                ('qr_code_data', models.CharField(blank=True, max_length=200, verbose_name='QR-Code Daten')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment_devices', to='vehicles.vehicle', verbose_name='Zugeordnet zu Fahrzeug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_devices', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_devices', to='locations.location', verbose_name='Lagerort')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_equipment_devices', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_instances', to='equipment.equipmentitemmaster', verbose_name='Stammdaten')),
            ],
            options={
                'verbose_name': 'Ausrüstungs-Gerät (Instanz)',
                'verbose_name_plural': 'Ausrüstungs-Geräte (Instanzen)',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.AddIndex(
            model_name='equipmentitemmaster',
            index=models.Index(fields=['master_number'], name='equipment_e_master__203724_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitemmaster',
            index=models.Index(fields=['equipment_type', 'category'], name='equipment_e_equipme_7b77ae_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitemmaster',
            index=models.Index(fields=['manufacturer', 'model'], name='equipment_e_manufac_3ddcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentitemmaster',
            index=models.Index(fields=['is_active'], name='equipment_e_is_acti_442586_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdeviceinstance',
            index=models.Index(fields=['inventory_number'], name='equipment_e_invento_510c03_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdeviceinstance',
            index=models.Index(fields=['master', 'is_active'], name='equipment_e_master__b04012_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdeviceinstance',
            index=models.Index(fields=['next_maintenance_date'], name='equipment_e_next_ma_cba10a_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdeviceinstance',
            index=models.Index(fields=['next_inspection_date'], name='equipment_e_next_in_06ffb7_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdeviceinstance',
            index=models.Index(fields=['is_operational'], name='equipment_e_is_oper_cf6967_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmentdeviceinstance',
            index=models.Index(fields=['assigned_vehicle'], name='equipment_e_assigne_4189fa_idx'),
        ),
    ]
