# Generated by Django 5.0.14 on 2025-10-20 03:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipmentitemmaster_equipmentdeviceinstance_and_more'),
        ('locations', '0003_location_technical_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Chargen-Nummer')),
                ('received_date', models.DateField(verbose_name='Eingangsdatum')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Verfallsdatum')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Eingangsmenge')),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Restmenge')),
                ('supplier_batch_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Chargen-Nr.')),
                ('quality_check_passed', models.BooleanField(default=True, verbose_name='Qualitätskontrolle bestanden')),
                ('quality_check_date', models.DateField(blank=True, null=True, verbose_name='Qualitätskontrolle am')),
                ('quality_check_notes', models.TextField(blank=True, verbose_name='QK-Notizen')),
                ('is_recalled', models.BooleanField(default=False, help_text='Wurde diese Charge zurückgerufen?', verbose_name='Rückruf')),
                ('recall_date', models.DateField(blank=True, null=True, verbose_name='Rückruf-Datum')),
                ('recall_reason', models.TextField(blank=True, verbose_name='Rückruf-Grund')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_batches_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_batches', to='locations.location', verbose_name='Lagerort')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='equipment.equipmentitemmaster', verbose_name='Stammdaten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_batches_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Charge/Batch',
                'verbose_name_plural': 'Chargen/Batches',
                'ordering': ['expiry_date', 'received_date'],
                'indexes': [models.Index(fields=['master', 'expiry_date'], name='equipment_e_master__22668f_idx'), models.Index(fields=['batch_number'], name='equipment_e_batch_n_62a1af_idx'), models.Index(fields=['is_recalled'], name='equipment_e_is_reca_3a4386_idx'), models.Index(fields=['expiry_date'], name='equipment_e_expiry__360402_idx')],
                'unique_together': {('master', 'batch_number')},
            },
        ),
    ]
