# Generated by Django 5.0.14 on 2025-11-17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_equipmentinventorycheck_equipmentinventorycheckitem'),
    ]

    operations = [
        # EquipmentInspectionAssignment: item → device
        # First remove unique_together constraint that references 'item'
        migrations.AlterUniqueTogether(
            name='equipmentinspectionassignment',
            unique_together=set(),
        ),
        # Add new device field
        migrations.AddField(
            model_name='equipmentinspectionassignment',
            name='device',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='inspection_assignments',
                to='equipment.equipmentdeviceinstance',
                verbose_name='Gerät',
                null=True,  # Temporarily nullable
            ),
        ),
        # Remove old item field
        migrations.RemoveField(
            model_name='equipmentinspectionassignment',
            name='item',
        ),
        # Add new unique_together constraint
        migrations.AlterUniqueTogether(
            name='equipmentinspectionassignment',
            unique_together={('device', 'inspection_type')},
        ),

        # EquipmentMaintenanceAssignment: item → device
        # First remove unique_together constraint that references 'item'
        migrations.AlterUniqueTogether(
            name='equipmentmaintenanceassignment',
            unique_together=set(),
        ),
        # Add new device field
        migrations.AddField(
            model_name='equipmentmaintenanceassignment',
            name='device',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='maintenance_assignments',
                to='equipment.equipmentdeviceinstance',
                verbose_name='Gerät',
                null=True,  # Temporarily nullable
            ),
        ),
        # Remove old item field
        migrations.RemoveField(
            model_name='equipmentmaintenanceassignment',
            name='item',
        ),
        # Add new unique_together constraint
        migrations.AlterUniqueTogether(
            name='equipmentmaintenanceassignment',
            unique_together={('device', 'maintenance_type')},
        ),
    ]
