# Generated by Django 5.0.14 on 2025-11-28 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_remove_inspection_assignment_add_direct_refs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinspectionassignment',
            options={'ordering': ['device', 'inspection_type'], 'verbose_name': 'Prüfungszuweisung', 'verbose_name_plural': 'Prüfungszuweisungen'},
        ),
        migrations.AlterModelOptions(
            name='equipmentmaintenanceassignment',
            options={'ordering': ['device', 'maintenance_type'], 'verbose_name': 'Wartungszuweisung', 'verbose_name_plural': 'Wartungszuweisungen'},
        ),
        migrations.AlterField(
            model_name='equipmentinspectionassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_assignments', to='equipment.equipmentdeviceinstance', verbose_name='Gerät'),
        ),
        migrations.AlterField(
            model_name='equipmentmaintenanceassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assignments', to='equipment.equipmentdeviceinstance', verbose_name='Gerät'),
        ),
        migrations.CreateModel(
            name='MasterMaintenanceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_interval_months', models.PositiveIntegerField(blank=True, help_text='Überschreibt Standard-Intervall der Wartungsart', null=True, verbose_name='Individuelles Intervall (Monate)')),
                ('is_active', models.BooleanField(default=True, help_text='Wartung wird noch durchgeführt', verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_master_maintenance_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_assignments', to='equipment.maintenancetype', verbose_name='Wartungsart')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_assignments', to='equipment.equipmentitemmaster', verbose_name='Artikelstammdaten')),
            ],
            options={
                'verbose_name': 'Stammdaten-Wartungszuweisung',
                'verbose_name_plural': 'Stammdaten-Wartungszuweisungen',
                'ordering': ['master', 'maintenance_type'],
                'unique_together': {('master', 'maintenance_type')},
            },
        ),
    ]
