# Generated by Django 5.0.14 on 2026-01-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0014_add_master_maintenance_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdeviceinstance',
            name='additional_inventory_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Inventarnummern für Module/Komponenten dieses Geräts', verbose_name='Zusätzliche Inventarnummern'),
        ),
    ]
