# Generated by Django 5.0.14 on 2026-01-09 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_add_additional_inventory_numbers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetype',
            name='applicable_equipment_types',
            field=models.JSONField(blank=True, default=list, help_text='Für welche Gerätetypen ist diese Wartung relevant?', verbose_name='Anwendbar auf Gerätetypen (Legacy)'),
        ),
        migrations.CreateModel(
            name='DeviceTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Pumpen, Generatoren, Atemschutzgeräte', max_length=100, unique=True, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, help_text='Optionale Beschreibung des Gerätetyps', verbose_name='Beschreibung')),
                ('icon', models.CharField(default='🔧', help_text='Emoji oder Symbol zur Darstellung', max_length=10, verbose_name='Icon')),
                ('color', models.CharField(default='#6B7280', help_text='Hex-Farbcode (z.B. #FF5733)', max_length=7, verbose_name='Farbe')),
                ('default_maintenance_interval_months', models.PositiveIntegerField(blank=True, help_text='Empfohlenes Wartungsintervall für diesen Gerätetyp', null=True, verbose_name='Standard-Wartungsintervall (Monate)')),
                ('default_inspection_interval_months', models.PositiveIntegerField(blank=True, help_text='Empfohlenes Prüfintervall für diesen Gerätetyp', null=True, verbose_name='Standard-Prüfintervall (Monate)')),
                ('applicable_standards', models.TextField(blank=True, help_text='z.B. DIN 14811, DGUV Vorschrift 3, UVV', verbose_name='Anwendbare Normen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_device_type_categories', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Gerätetyp',
                'verbose_name_plural': 'Gerätetypen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='applicable_device_types',
            field=models.ManyToManyField(blank=True, help_text='Für welche Gerätetypen ist diese Wartung relevant?', related_name='maintenance_types', to='equipment.devicetypecategory', verbose_name='Anwendbar auf Gerätetypen'),
        ),
    ]
