# Generated by Claude - Data migration to populate DeviceTypeCategory

from django.db import migrations


def populate_device_type_categories(apps, schema_editor):
    """Migrate hardcoded EquipmentType choices to DeviceTypeCategory model."""
    DeviceTypeCategory = apps.get_model('equipment', 'DeviceTypeCategory')
    User = apps.get_model('core', 'User')

    # Get or create a system user for created_by
    system_user = User.objects.filter(is_superuser=True).first()
    if not system_user:
        system_user = User.objects.first()

    if not system_user:
        # Skip if no users exist yet
        return

    # Define all equipment types with their metadata
    equipment_types = [
        # Persönliche Schutzausrüstung (PSA)
        {
            'name': 'Helm',
            'description': 'Feuerwehrhelme und Schutzhelme',
            'icon': '⛑️',
            'color': '#EF4444',  # Red
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 443, DIN 14940',
        },
        {
            'name': 'Atemschutzmaske',
            'description': 'Vollmasken und Halbmasken für Atemschutz',
            'icon': '😷',
            'color': '#3B82F6',  # Blue
            'default_maintenance_interval_months': 6,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 136, DIN EN 140',
        },
        {
            'name': 'Handschuhe',
            'description': 'Schutzhandschuhe für verschiedene Einsatzbereiche',
            'icon': '🧤',
            'color': '#F59E0B',  # Amber
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 659',
        },
        {
            'name': 'Stiefel',
            'description': 'Feuerwehrstiefel und Sicherheitsschuhe',
            'icon': '🥾',
            'color': '#78350F',  # Brown
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 15090',
        },

        # Atemschutz
        {
            'name': 'Atemschutzgerät',
            'description': 'Pressluftatmer und umluftunabhängige Atemschutzgeräte',
            'icon': '🫁',
            'color': '#06B6D4',  # Cyan
            'default_maintenance_interval_months': 6,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 137, DIN 58600',
        },
        {
            'name': 'Sauerstoffflasche',
            'description': 'Atemluft- und Sauerstoffflaschen',
            'icon': '🔵',
            'color': '#0EA5E9',  # Sky
            'default_inspection_interval_months': 60,  # TÜV alle 5 Jahre
            'applicable_standards': 'TRG 280, BetrSichV',
        },
        {
            'name': 'Filter',
            'description': 'Atemschutzfilter für verschiedene Schadstoffe',
            'icon': '🔘',
            'color': '#6B7280',  # Gray
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 14387',
        },

        # Schläuche & Armaturen
        {
            'name': 'Schlauch',
            'description': 'Druckschläuche, Saugschläuche',
            'icon': '🔄',
            'color': '#DC2626',  # Red
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN 14811, DIN EN 1947',
        },
        {
            'name': 'Kupplung',
            'description': 'Storz-Kupplungen und andere Anschlüsse',
            'icon': '🔗',
            'color': '#A3A3A3',  # Gray
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN 14307',
        },
        {
            'name': 'Strahlrohr',
            'description': 'Hohlstrahlrohre, Mehrzweckstrahlrohre',
            'icon': '💨',
            'color': '#2563EB',  # Blue
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 15182',
        },
        {
            'name': 'Ventil',
            'description': 'Absperrventile, Verteiler',
            'icon': '🔧',
            'color': '#71717A',  # Gray
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN 14361',
        },

        # Leiter & Höhengeräte
        {
            'name': 'Leiter',
            'description': 'Steck-, Schiebe- und Mehrzweckleitern',
            'icon': '🪜',
            'color': '#CA8A04',  # Yellow
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 1147, DIN 14711',
        },
        {
            'name': 'Seil',
            'description': 'Rettungsseile, Arbeitsseile',
            'icon': '🪢',
            'color': '#65A30D',  # Green
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 1891, DIN 14920',
        },
        {
            'name': 'Karabiner',
            'description': 'Karabinerhaken für Absturzsicherung',
            'icon': '🔐',
            'color': '#A3A3A3',  # Gray
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 362',
        },
        {
            'name': 'Gurt',
            'description': 'Auffang- und Haltegurte, Rettungsgurte',
            'icon': '🎗️',
            'color': '#F97316',  # Orange
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 361, DIN EN 358',
        },

        # Pumpen & Aggregate
        {
            'name': 'Pumpe',
            'description': 'Tragkraftspritzen, Tauchpumpen',
            'icon': '⛽',
            'color': '#EF4444',  # Red
            'default_maintenance_interval_months': 12,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 14466',
        },
        {
            'name': 'Stromerzeuger',
            'description': 'Mobile Stromgeneratoren',
            'icon': '⚡',
            'color': '#FBBF24',  # Yellow
            'default_maintenance_interval_months': 12,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN 14685',
        },
        {
            'name': 'Kompressor',
            'description': 'Atemluftkompressoren, Druckluftkompressoren',
            'icon': '💨',
            'color': '#3B82F6',  # Blue
            'default_maintenance_interval_months': 12,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 12021',
        },

        # Werkzeuge
        {
            'name': 'Hydraulisches Werkzeug',
            'description': 'Spreizer, Rettungsschere, Rettungszylinder',
            'icon': '🔴',
            'color': '#DC2626',  # Red
            'default_maintenance_interval_months': 12,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 13204',
        },
        {
            'name': 'Handwerkzeug',
            'description': 'Äxte, Brechstangen, Werkzeuge',
            'icon': '🪓',
            'color': '#78350F',  # Brown
            'default_inspection_interval_months': 12,
        },
        {
            'name': 'Elektrowerkzeug',
            'description': 'Akkubetriebene und elektrische Werkzeuge',
            'icon': '🔌',
            'color': '#16A34A',  # Green
            'default_maintenance_interval_months': 12,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DGUV Vorschrift 3',
        },
        {
            'name': 'Motorsäge',
            'description': 'Motorsägen und Trennschleifer',
            'icon': '🪚',
            'color': '#F97316',  # Orange
            'default_maintenance_interval_months': 6,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DGUV Regel 114-018',
        },

        # Messgeräte
        {
            'name': 'Gaswarngerät',
            'description': 'Multi-Gaswarngeräte für Ex und Tox',
            'icon': '📟',
            'color': '#FBBF24',  # Yellow
            'default_maintenance_interval_months': 6,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 60079-29-1',
        },
        {
            'name': 'CO-Warngerät',
            'description': 'Kohlenmonoxid-Warngeräte',
            'icon': '⚠️',
            'color': '#EF4444',  # Red
            'default_maintenance_interval_months': 6,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'DIN EN 50291',
        },
        {
            'name': 'Strahlenmessgerät',
            'description': 'Dosimeter, Dosisleistungsmessgeräte',
            'icon': '☢️',
            'color': '#A855F7',  # Purple
            'default_maintenance_interval_months': 12,
            'default_inspection_interval_months': 12,
            'applicable_standards': 'StrlSchV',
        },
        {
            'name': 'Wärmebildkamera',
            'description': 'Wärmebildkameras für Brandbekämpfung',
            'icon': '📸',
            'color': '#EF4444',  # Red
            'default_maintenance_interval_months': 12,
            'default_inspection_interval_months': 12,
        },
    ]

    for et in equipment_types:
        DeviceTypeCategory.objects.get_or_create(
            name=et['name'],
            defaults={
                'description': et.get('description', ''),
                'icon': et.get('icon', '🔧'),
                'color': et.get('color', '#6B7280'),
                'default_maintenance_interval_months': et.get('default_maintenance_interval_months'),
                'default_inspection_interval_months': et.get('default_inspection_interval_months'),
                'applicable_standards': et.get('applicable_standards', ''),
                'is_active': True,
                'created_by': system_user,
            }
        )


def reverse_populate(apps, schema_editor):
    """Remove the auto-created DeviceTypeCategory entries."""
    DeviceTypeCategory = apps.get_model('equipment', 'DeviceTypeCategory')
    # Only delete entries we created (by name)
    names = [
        'Helm', 'Atemschutzmaske', 'Handschuhe', 'Stiefel',
        'Atemschutzgerät', 'Sauerstoffflasche', 'Filter',
        'Schlauch', 'Kupplung', 'Strahlrohr', 'Ventil',
        'Leiter', 'Seil', 'Karabiner', 'Gurt',
        'Pumpe', 'Stromerzeuger', 'Kompressor',
        'Hydraulisches Werkzeug', 'Handwerkzeug', 'Elektrowerkzeug', 'Motorsäge',
        'Gaswarngerät', 'CO-Warngerät', 'Strahlenmessgerät', 'Wärmebildkamera',
    ]
    DeviceTypeCategory.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_add_device_type_category'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_device_type_categories, reverse_populate),
    ]
