# Generated by Django 5.2.15 on 2026-06-24 12:11

import django.db.models.deletion
import objektverwaltung.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Zeitpunkt der Loeschung (soft delete)', null=True, verbose_name='Geloescht am')),
                ('object_number', models.CharField(help_text='Eindeutige Kennung des Objekts', max_length=50, unique=True, verbose_name='Objektnummer')),
                ('name', models.CharField(help_text="Name des Objekts (z.B. 'Grundschule Musterstadt')", max_length=200, verbose_name='Bezeichnung')),
                ('usage_type', models.CharField(choices=[('school', 'Schule'), ('kindergarten', 'Kindergarten / Kita'), ('hospital', 'Krankenhaus / Pflege'), ('assembly', 'Versammlungsstätte'), ('office', 'Verwaltung / Büro'), ('industry', 'Industrie / Gewerbe'), ('residential', 'Wohngebäude'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Nutzungsart')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geografische Breite (optional)', max_digits=9, null=True, verbose_name='Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geografische Länge (optional)', max_digits=9, null=True, verbose_name='Längengrad')),
                ('floor_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Anzahl Obergeschosse')),
                ('basement_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Anzahl Untergeschosse')),
                ('has_fire_alarm_system', models.BooleanField(default=False, verbose_name='Brandmeldeanlage vorhanden')),
                ('notes', models.TextField(blank=True, verbose_name='Allgemeine Hinweise')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Benutzer, der die Loeschung vorgenommen hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Geloescht von')),
                ('followers', models.ManyToManyField(blank=True, help_text='Nutzer, die bei Änderungen an diesem Objekt benachrichtigt werden', related_name='followed_objects', to=settings.AUTH_USER_MODEL, verbose_name='Abonnenten')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuildingContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('role', models.CharField(blank=True, help_text='z.B. Hausmeister, Betreiber, Sicherheitsbeauftragter', max_length=120, verbose_name='Funktion')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('mobile', models.CharField(blank=True, max_length=50, verbose_name='Mobil')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('notes', models.TextField(blank=True, verbose_name='Hinweise')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Hauptansprechpartner')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Ansprechpartner',
                'verbose_name_plural': 'Ansprechpartner',
                'ordering': ['building', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FireAlarmPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('designation', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('location_description', models.CharField(blank=True, help_text="Wo befindet sich die BMZ? (z.B. 'Haupteingang links')", max_length=255, verbose_name='Standort')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, max_length=120, verbose_name='Typ/Modell')),
                ('notes', models.TextField(blank=True, verbose_name='Hinweise')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_alarm_panels', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Brandmeldezentrale',
                'verbose_name_plural': 'Brandmeldezentralen',
                'ordering': ['building', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('level', models.IntegerField(help_text='z.B. -1 = Keller, 0 = Erdgeschoss, 1 = 1. OG', verbose_name='Geschoss-Ebene')),
                ('name', models.CharField(blank=True, help_text="z.B. 'Erdgeschoss', 'Dachgeschoss'", max_length=100, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Etage',
                'verbose_name_plural': 'Etagen',
                'ordering': ['building', 'level'],
                'unique_together': {('building', 'level')},
            },
        ),
        migrations.CreateModel(
            name='EscapeRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escape_routes', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escape_routes', to='objektverwaltung.floor', verbose_name='Etage')),
            ],
            options={
                'verbose_name': 'Fluchtweg',
                'verbose_name_plural': 'Fluchtwege',
                'ordering': ['building', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BuildingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('plan_type', models.CharField(choices=[('laufkarte', 'Laufkarte'), ('feuerwehrplan', 'Feuerwehrplan'), ('fluchtplan', 'Flucht- und Rettungsplan'), ('grundriss', 'Grundriss / Gebäudeplan'), ('other', 'Sonstiges')], default='laufkarte', max_length=20, verbose_name='Art')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('file', models.FileField(upload_to=objektverwaltung.models.building_plan_upload_path, verbose_name='Datei')),
                ('notes', models.TextField(blank=True, verbose_name='Hinweise')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='objektverwaltung.floor', verbose_name='Etage')),
            ],
            options={
                'verbose_name': 'Plan / Laufkarte',
                'verbose_name_plural': 'Pläne / Laufkarten',
                'ordering': ['building', 'plan_type', '-created_at'],
            },
        ),
    ]
