# Generated by Django 5.2.15 on 2026-06-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objektverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireSuppressionSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('system_type', models.CharField(choices=[('sprinkler', 'Sprinkleranlage'), ('gas', 'Gaslöschanlage'), ('foam', 'Schaumlöschanlage'), ('water_mist', 'Wassernebel-Löschanlage'), ('dry_riser', 'Steigleitung trocken'), ('wet_riser', 'Steigleitung nass'), ('other', 'Sonstige')], default='sprinkler', max_length=20, verbose_name='Art')),
                ('designation', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('location_description', models.CharField(blank=True, max_length=255, verbose_name='Standort / abgedeckter Bereich')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Hersteller')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('is_operational', models.BooleanField(default=True, verbose_name='Funktionsfähig / in Betrieb')),
                ('notes', models.TextField(blank=True, verbose_name='Hinweise')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppression_systems', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Löschanlage',
                'verbose_name_plural': 'Löschanlagen',
                'ordering': ['building', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='CompensationMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('reason', models.TextField(blank=True, help_text='Welcher Mangel wird kompensiert? (z.B. Fluchtweg gesperrt)', verbose_name='Grund / Mangel')),
                ('description', models.TextField(blank=True, help_text='Welche Kompensationsmaßnahme wurde getroffen? (z.B. Brandsicherheitswache)', verbose_name='Maßnahme')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('active', 'Aktiv'), ('done', 'Erledigt')], default='active', max_length=10, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Beginn')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Frist / Ende')),
                ('responsible', models.CharField(blank=True, max_length=150, verbose_name='Verantwortlich')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_measures', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
                ('escape_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_measures', to='objektverwaltung.escaperoute', verbose_name='Betroffener Fluchtweg')),
                ('suppression_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compensation_measures', to='objektverwaltung.firesuppressionsystem', verbose_name='Betroffene Löschanlage')),
            ],
            options={
                'verbose_name': 'Kompensationsmaßnahme',
                'verbose_name_plural': 'Kompensationsmaßnahmen',
                'ordering': ['building', 'status', '-start_date'],
            },
        ),
    ]
