# Generated by Django 5.2.15 on 2026-09-02 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objektverwaltung', '0002_firesuppressionsystem_compensationmeasure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FireKeyDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('depot_type', models.CharField(choices=[('fsd1', 'FSD 1'), ('fsd2', 'FSD 2'), ('fsd3', 'FSD 3')], default='fsd3', max_length=10, verbose_name='Typ')),
                ('designation', models.CharField(help_text="z.B. 'FSD Haupteingang'", max_length=200, verbose_name='Bezeichnung')),
                ('location_description', models.CharField(blank=True, help_text="Wo befindet sich das Depot? (z.B. 'Rechts neben Haupteingang')", max_length=255, verbose_name='Standort')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='Hersteller')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Serien-/Depot-Nr.')),
                ('installed_at', models.DateField(blank=True, null=True, verbose_name='Einbaudatum')),
                ('inspection_interval_months', models.PositiveSmallIntegerField(default=12, verbose_name='Prüfintervall (Monate)')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection', models.DateField(blank=True, help_text='Wird aus letzter Prüfung (bzw. Einbaudatum) und Intervall berechnet', null=True, verbose_name='Nächste Prüfung')),
                ('contents', models.TextField(blank=True, help_text='Hinterlegte Schlüssel; wird als Vorbelegung in neue Prüfberichte übernommen', verbose_name='Depot-Inhalt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Hinweise')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_depots', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Feuerwehrschlüsseldepot',
                'verbose_name_plural': 'Feuerwehrschlüsseldepots',
                'ordering': ['building', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='FSDInspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('inspection_date', models.DateField(verbose_name='Überprüfungsdatum')),
                ('participant_operator', models.CharField(blank=True, max_length=200, verbose_name='Teilnehmer Betrieb')),
                ('participant_fire_dept', models.CharField(blank=True, max_length=200, verbose_name='Teilnehmer Feuerwehr')),
                ('participant_other', models.CharField(blank=True, max_length=200, verbose_name='Teilnehmer Sonstige')),
                ('depot_contents', models.TextField(blank=True, verbose_name='Depot-Inhalt')),
                ('condition_report', models.TextField(blank=True, verbose_name='Zustandsbericht')),
                ('result', models.CharField(choices=[('ok', 'Ohne Mängel'), ('defects', 'Mit Mängeln')], default='ok', max_length=10, verbose_name='Ergebnis')),
                ('keys_match', models.BooleanField(default=True, help_text='Bescheinigung: Die deponierten Schlüssel entsprechen der General- bzw. Torschließanlage und öffnen alle Toranlagen und Türen gewaltfrei.', verbose_name='Schlüssel entsprechen der Schließanlage')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_reports', to='objektverwaltung.firekeydepot', verbose_name='Schlüsseldepot')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'FSD-Prüfbericht',
                'verbose_name_plural': 'FSD-Prüfberichte',
                'ordering': ['-inspection_date', '-created_at'],
            },
        ),
    ]
