# Generated by Django 5.2.15 on 2026-09-10 12:25

import django.db.models.deletion
import objektverwaltung.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objektverwaltung', '0006_usagecategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSVInspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Bezeichnung')),
                ('interval_months', models.PositiveSmallIntegerField(default=36, help_text='Vorschlag für „gültig bis“ beim Eintragen einer neuen Prüfung', verbose_name='Prüfintervall (Monate)')),
                ('warning_days', models.PositiveSmallIntegerField(default=90, help_text='So viele Tage vor Ablauf wird die Frist gelb markiert', verbose_name='Vorwarnzeit (Tage)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Prüfarten stehen für neue Prüfpflichten nicht mehr zur Auswahl', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'PSV-Prüfart',
                'verbose_name_plural': 'PSV-Prüfarten',
                'ordering': ['sort_order', 'name'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BVSPhraseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Nummer')),
                ('title', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('parent', models.ForeignKey(blank=True, help_text='Leer lassen für ein Kapitel; bei einem Abschnitt das übergeordnete Kapitel', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='objektverwaltung.bvsphrasecategory', verbose_name='Kapitel')),
            ],
            options={
                'verbose_name': 'Mustersatz-Kapitel',
                'verbose_name_plural': 'Mustersatz-Kapitel',
                'ordering': ['sort_order', 'number'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BVSPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Nr.')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('text', models.TextField(blank=True, help_text='„…“ markiert Stellen, die vor Ort ergänzt werden', verbose_name='Text')),
                ('review_note', models.TextField(blank=True, help_text='Hinweise aus dem Import (z.B. Randkommentare der Vorlage) – nach Durchsicht leeren', verbose_name='Prüfhinweis')),
                ('is_active', models.BooleanField(default=True, help_text='Nur aktive Mustersätze stehen bei der Brandverhütungsschau zur Auswahl', verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phrases', to='objektverwaltung.bvsphrasecategory', verbose_name='Kapitel / Abschnitt')),
            ],
            options={
                'verbose_name': 'Mustersatz',
                'verbose_name_plural': 'Mustersätze',
                'ordering': ['sort_order', 'code'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FireSafetyInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('status', models.CharField(choices=[('draft', 'In Bearbeitung'), ('completed', 'Abgeschlossen')], default='draft', max_length=10, verbose_name='Status')),
                ('inspection_date', models.DateField(verbose_name='Datum der Brandverhütungsschau')),
                ('report_number', models.CharField(blank=True, max_length=50, verbose_name='Berichtnummer')),
                ('object_key', models.CharField(blank=True, max_length=50, verbose_name='Objekt-Kennziffer laut Satzung')),
                ('cost_bearer', models.CharField(blank=True, max_length=200, verbose_name='Kostenträger (Firma)')),
                ('participant_operator', models.CharField(blank=True, max_length=300, verbose_name='Teilnehmer Betrieb')),
                ('participant_fire_dept', models.CharField(blank=True, max_length=300, verbose_name='Teilnehmer Feuerwehr')),
                ('participant_other', models.CharField(blank=True, max_length=300, verbose_name='Teilnehmer Sonstige')),
                ('departure_station', models.TimeField(blank=True, null=True, verbose_name='Abfahrt Feuerwache')),
                ('arrival_object', models.TimeField(blank=True, null=True, verbose_name='Ankunft Objekt')),
                ('departure_object', models.TimeField(blank=True, null=True, verbose_name='Abfahrt Objekt')),
                ('arrival_station', models.TimeField(blank=True, null=True, verbose_name='Ankunft Feuerwache')),
                ('prep_minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Vor- und Nachbearbeitung (Minuten)')),
                ('defect_deadline', models.DateField(blank=True, help_text='Danach erfolgt eine Nachschau', null=True, verbose_name='Frist zur Mängelbeseitigung')),
                ('next_inspection', models.DateField(blank=True, help_text='Es zählt nur Monat und Jahr', null=True, verbose_name='Nächste Brandverhütungsschau (voraussichtlich)')),
                ('is_fee_required', models.BooleanField(default=True, help_text='Niederschrift mit Hinweis auf den Gebührenbescheid', verbose_name='Gebührenpflichtig')),
                ('recipient_address', models.TextField(blank=True, help_text='Erscheint im Adressfeld der Niederschrift', verbose_name='Anschrift Empfänger')),
                ('clerk_name', models.CharField(blank=True, max_length=150, verbose_name='Bearbeiter/in')),
                ('clerk_phone', models.CharField(blank=True, max_length=30, verbose_name='Durchwahl')),
                ('clerk_room', models.CharField(blank=True, max_length=30, verbose_name='Zimmer-Nr.')),
                ('clerk_email', models.CharField(blank=True, max_length=150, verbose_name='E-Mail')),
                ('our_reference', models.CharField(blank=True, max_length=50, verbose_name='Mein Zeichen')),
                ('notes', models.TextField(blank=True, help_text='Erscheint nicht in der Niederschrift', verbose_name='Interne Notizen')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_safety_inspections', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Abgeschlossen von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Brandverhütungsschau',
                'verbose_name_plural': 'Brandverhütungsschauen',
                'ordering': ['-inspection_date', '-created_at'],
                'permissions': [('bvs_view', 'Brandverhütungsschau: Niederschriften und PSV-Fristen ansehen'), ('bvs_edit', 'Brandverhütungsschau: durchführen, Niederschriften und PSV-Fristen bearbeiten'), ('bvs_manage', 'Brandverhütungsschau: Mustersätze und PSV-Prüfarten verwalten')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FireSafetyDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Punkt')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ort / Bereich')),
                ('text', models.TextField(blank=True, verbose_name='Art des Mangels und notwendige Maßnahme')),
                ('resolved_on', models.DateField(blank=True, null=True, verbose_name='Behoben am')),
                ('phrase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defects', to='objektverwaltung.bvsphrase', verbose_name='Mustersatz')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='objektverwaltung.firesafetyinspection', verbose_name='Brandverhütungsschau')),
            ],
            options={
                'verbose_name': 'Mangel',
                'verbose_name_plural': 'Mängel',
                'ordering': ['position', 'pk'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PSVRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('designation', models.CharField(blank=True, help_text='z.B. „RWA Treppenraum A“ – leer lassen, wenn es nur eine Anlage dieser Art gibt', max_length=200, verbose_name='Anlage / Bereich')),
                ('notes', models.TextField(blank=True, verbose_name='Hinweise')),
                ('is_active', models.BooleanField(default=True, help_text='Nicht mehr erforderliche Prüfpflichten bleiben mit ihrer Historie erhalten', verbose_name='Erforderlich')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psv_requirements', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='objektverwaltung.psvinspectiontype', verbose_name='Prüfart')),
            ],
            options={
                'verbose_name': 'PSV-Prüfpflicht',
                'verbose_name_plural': 'PSV-Prüfpflichten',
                'ordering': ['building', 'inspection_type__sort_order', 'inspection_type__name', 'designation'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PSVCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('inspection_date', models.DateField(verbose_name='Prüfdatum')),
                ('valid_until', models.DateField(verbose_name='Gültig bis')),
                ('expert_name', models.CharField(blank=True, max_length=150, verbose_name='Prüfsachverständige/r')),
                ('expert_company', models.CharField(blank=True, max_length=150, verbose_name='Firma / Büro')),
                ('result', models.CharField(choices=[('ok', 'Ohne Mängel'), ('minor', 'Geringfügige Mängel'), ('major', 'Wesentliche Mängel')], default='ok', max_length=10, verbose_name='Ergebnis')),
                ('document', models.FileField(blank=True, upload_to=objektverwaltung.models.psv_certificate_upload_path, verbose_name='Bescheinigung (Datei)')),
                ('notes', models.TextField(blank=True, verbose_name='Hinweise')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='objektverwaltung.psvrequirement', verbose_name='Prüfpflicht')),
            ],
            options={
                'verbose_name': 'PSV-Prüfbescheinigung',
                'verbose_name_plural': 'PSV-Prüfbescheinigungen',
                'ordering': ['-inspection_date', '-pk'],
                'default_permissions': (),
            },
        ),
    ]
