# Generated by Django 5.2.15 on 2026-09-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objektverwaltung', '0008_psv_pruefarten'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionreport',
            name='signature_fire_dept',
            field=models.TextField(blank=True, verbose_name='Unterschrift Feuerwehr'),
        ),
        migrations.AddField(
            model_name='inspectionreport',
            name='signature_operator',
            field=models.TextField(blank=True, verbose_name='Unterschrift Firma / Objekt'),
        ),
    ]
