# Generated by Django 5.2.15 on 2026-09-30 11:06

import django.db.models.deletion
import objektverwaltung.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objektverwaltung', '0009_inspectionreport_signatures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FireSafetyStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('statement_type', models.CharField(choices=[('bauantrag', 'Bauantrag / Baugenehmigung'), ('bauvoranfrage', 'Bauvoranfrage'), ('nutzungsaenderung', 'Nutzungsänderung'), ('brandschutzkonzept', 'Brandschutzkonzept / -nachweis'), ('veranstaltung', 'Veranstaltung / Nutzung auf Zeit'), ('abweichung', 'Abweichung / Befreiung'), ('sonstiges', 'Sonstiges')], default='bauantrag', max_length=30, verbose_name='Art')),
                ('subject', models.CharField(help_text='z.B. Umbau und Erweiterung der Sporthalle', max_length=250, verbose_name='Betreff / Vorhaben')),
                ('reference_number', models.CharField(blank=True, max_length=80, verbose_name='Aktenzeichen (anfragende Stelle)')),
                ('our_reference', models.CharField(blank=True, max_length=80, verbose_name='Eigenes Zeichen')),
                ('requesting_authority', models.CharField(blank=True, help_text='z.B. Untere Bauaufsichtsbehörde', max_length=200, verbose_name='Anfragende Stelle')),
                ('applicant', models.CharField(blank=True, max_length=200, verbose_name='Antragsteller / Bauherr')),
                ('received_on', models.DateField(verbose_name='Eingang am')),
                ('due_on', models.DateField(blank=True, null=True, verbose_name='Frist')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='Abgegeben am')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('issued', 'Abgegeben'), ('closed', 'Abgeschlossen')], default='open', max_length=20, verbose_name='Status')),
                ('result', models.CharField(blank=True, choices=[('', '– noch offen –'), ('no_objection', 'Keine Bedenken'), ('conditions', 'Keine Bedenken unter Auflagen'), ('objection', 'Bedenken / Ablehnung')], default='', max_length=20, verbose_name='Ergebnis')),
                ('text', models.TextField(blank=True, help_text='Inhalt der Stellungnahme; erscheint im PDF', verbose_name='Stellungnahme')),
                ('requirements', models.TextField(blank=True, help_text='Je Zeile eine Auflage; erscheint nummeriert im PDF', verbose_name='Auflagen / Forderungen')),
                ('clerk', models.CharField(blank=True, max_length=150, verbose_name='Bearbeiter/in')),
                ('request_file', models.FileField(blank=True, null=True, upload_to=objektverwaltung.models.statement_upload_path, verbose_name='Antragsunterlagen (Datei)')),
                ('file', models.FileField(blank=True, help_text='z.B. das unterschriebene Schreiben als PDF', null=True, upload_to=objektverwaltung.models.statement_upload_path, verbose_name='Stellungnahme (Datei)')),
                ('notes', models.TextField(blank=True, help_text='Erscheint nicht im PDF', verbose_name='Interne Notizen')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Stellungnahme',
                'verbose_name_plural': 'Stellungnahmen',
                'ordering': ['-received_on', '-created_at'],
            },
        ),
    ]
