# Generated by Django 5.2.15 on 2026-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objektverwaltung', '0010_firesafetystatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingobject',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Nur für die eigene Sachbearbeitung – erscheint nicht in Objekt-PDF, Akte-Auszug oder Export', verbose_name='Interne Vermerke'),
        ),
    ]
