# Generated by Django 5.0.14 on 2025-10-03 10:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_number', models.CharField(help_text='Eindeutige Artikelnummer', max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Hersteller-Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestand')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Warnung bei Unterschreitung', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximalbestand')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode/EAN')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR-Code')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/images/', verbose_name='Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('item_type', models.CharField(choices=[('medication', 'Medikament'), ('btm', 'Betäubungsmittel (BTM)'), ('infusion', 'Infusion'), ('injection', 'Injektion'), ('bandage', 'Verbandmaterial'), ('diagnostic', 'Diagnostik'), ('device', 'Medizintechnik'), ('disinfectant', 'Desinfektionsmittel'), ('oxygen', 'Sauerstoff'), ('disposable', 'Einwegartikel'), ('other', 'Sonstiges')], default='medication', max_length=20, verbose_name='Artikeltyp')),
                ('is_btm', models.BooleanField(default=False, help_text='Unterliegt dem Betäubungsmittelgesetz', verbose_name='Betäubungsmittel (BTM)')),
                ('active_ingredient', models.CharField(blank=True, help_text='z.B. "Paracetamol", "Morphin"', max_length=200, verbose_name='Wirkstoff')),
                ('dosage', models.CharField(blank=True, help_text='z.B. "500mg", "10ml"', max_length=100, verbose_name='Dosierung')),
                ('pharmaceutical_form', models.CharField(blank=True, help_text='z.B. "Tabletten", "Ampullen", "Salbe"', max_length=100, verbose_name='Darreichungsform')),
                ('administration_route', models.CharField(blank=True, choices=[('oral', 'Oral'), ('iv', 'Intravenös (i.v.)'), ('im', 'Intramuskulär (i.m.)'), ('sc', 'Subkutan (s.c.)'), ('inhalation', 'Inhalation'), ('topical', 'Topisch (Haut)'), ('rectal', 'Rektal'), ('sublingual', 'Sublingual'), ('other', 'Sonstiges')], max_length=20, verbose_name='Verabreichungsweg')),
                ('pzn', models.CharField(blank=True, help_text='Deutsche Pharmazentralnummer', max_length=20, verbose_name='PZN (Pharmazentralnummer)')),
                ('atc_code', models.CharField(blank=True, help_text='Anatomisch-Therapeutisch-Chemisches Klassifikationssystem', max_length=20, verbose_name='ATC-Code')),
                ('approval_number', models.CharField(blank=True, max_length=50, verbose_name='Zulassungsnummer')),
                ('expiry_warning_days', models.PositiveIntegerField(default=90, help_text='Warnung X Tage vor Ablauf', verbose_name='Ablauf-Warnung (Tage)')),
                ('storage_condition', models.CharField(choices=[('room_temp', 'Raumtemperatur (15-25°C)'), ('refrigerated', 'Gekühlt (2-8°C)'), ('frozen', 'Gefroren (<-15°C)'), ('dark', 'Dunkel'), ('dry', 'Trocken'), ('special', 'Spezielle Bedingungen')], default='room_temp', max_length=20, verbose_name='Lagerungsbedingungen')),
                ('requires_cold_chain', models.BooleanField(default=False, help_text='Lückenlose Kühlung notwendig', verbose_name='Kühlkette erforderlich')),
                ('is_prescription_required', models.BooleanField(default=False, verbose_name='Verschreibungspflichtig')),
                ('package_insert', models.FileField(blank=True, help_text='PDF-Datei des Beipackzettels', null=True, upload_to='medical/package_inserts/', verbose_name='Beipackzettel')),
                ('spc_document', models.FileField(blank=True, help_text='Summary of Product Characteristics', null=True, upload_to='medical/spc/', verbose_name='Fachinformation (SPC)')),
                ('is_medical_device', models.BooleanField(default=False, help_text='Unterliegt Medizinproduktegesetz (MPG)', verbose_name='Medizinprodukt')),
                ('medical_device_class', models.CharField(blank=True, help_text='z.B. "I", "IIa", "IIb", "III"', max_length=10, verbose_name='Medizinprodukte-Klasse')),
                ('udi', models.CharField(blank=True, max_length=100, verbose_name='UDI (Unique Device Identifier)')),
                ('requires_maintenance', models.BooleanField(default=False, verbose_name='Wartung erforderlich')),
                ('maintenance_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wartungsintervall (Monate)')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('indications', models.TextField(blank=True, help_text='Anwendungsgebiete', verbose_name='Indikationen')),
                ('contraindications', models.TextField(blank=True, help_text='Gegenanzeigen', verbose_name='Kontraindikationen')),
                ('side_effects', models.TextField(blank=True, verbose_name='Nebenwirkungen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Medizinischer Artikel',
                'verbose_name_plural': 'Medizinische Artikel',
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='MedicalBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Chargen-Nummer')),
                ('received_date', models.DateField(verbose_name='Eingangsdatum')),
                ('expiry_date', models.DateField(verbose_name='Verfallsdatum')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Eingangsmenge')),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Restmenge')),
                ('supplier_batch_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Chargen-Nr.')),
                ('temperature_log', models.JSONField(blank=True, default=dict, help_text='JSON-Array mit Temperatur-Messungen', verbose_name='Temperatur-Log')),
                ('cold_chain_break', models.BooleanField(default=False, help_text='Wurde die Kühlkette unterbrochen?', verbose_name='Kühlketten-Unterbrechung')),
                ('quality_check_passed', models.BooleanField(default=True, verbose_name='Qualitätskontrolle bestanden')),
                ('quality_check_date', models.DateField(blank=True, null=True, verbose_name='Qualitätskontrolle am')),
                ('quality_check_notes', models.TextField(blank=True, verbose_name='QK-Notizen')),
                ('is_recalled', models.BooleanField(default=False, help_text='Wurde diese Charge zurückgerufen?', verbose_name='Rückruf')),
                ('recall_date', models.DateField(blank=True, null=True, verbose_name='Rückruf-Datum')),
                ('recall_reason', models.TextField(blank=True, verbose_name='Rückruf-Grund')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_batches', to='locations.location', verbose_name='Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medical.medicalitem', verbose_name='Artikel')),
            ],
            options={
                'verbose_name': 'Charge/Batch',
                'verbose_name_plural': 'Chargen/Batches',
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('movement_type', models.CharField(choices=[('incoming', 'Wareneingang'), ('outgoing', 'Warenausgang'), ('transfer', 'Umlagerung'), ('inventory', 'Inventur-Korrektur'), ('damage', 'Beschädigung/Schwund'), ('return', 'Rückgabe'), ('disposal', 'Entsorgung')], max_length=20, verbose_name='Bewegungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('reference_number', models.CharField(blank=True, help_text='z.B. Lieferschein-Nr., Bestellnummer', max_length=100, verbose_name='Referenznummer')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Bewegungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Chargen-/Batch-Nummer')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Verfallsdatum')),
                ('patient_id', models.CharField(blank=True, help_text='Anonymisierte Patienten-ID (nur bei Verabreichung)', max_length=50, verbose_name='Patienten-ID')),
                ('diagnosis', models.CharField(blank=True, max_length=200, verbose_name='Diagnose/Indikation')),
                ('requires_approval', models.BooleanField(default=False, help_text='BTM-Bewegungen erfordern Freigabe', verbose_name='Freigabe erforderlich')),
                ('approval_status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Freigabe-Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Freigegeben am')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('prescription_number', models.CharField(blank=True, max_length=100, verbose_name='Rezeptnummer')),
                ('delivery_note', models.CharField(blank=True, max_length=100, verbose_name='Lieferschein-Nr.')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückkosten (EUR)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtkosten (EUR)')),
                ('administered_by', models.ForeignKey(blank=True, help_text='Person die das Medikament verabreicht hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_administrations', to=settings.AUTH_USER_MODEL, verbose_name='Verabreicht durch')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btm_approvals', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben durch')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_outgoing', to='locations.location', verbose_name='Von Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='medical.medicalitem', verbose_name='Artikel')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_incoming', to='locations.location', verbose_name='Nach Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Lagerbewegung',
                'verbose_name_plural': 'Lagerbewegungen',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalitem',
            index=models.Index(fields=['item_type', 'category'], name='medical_med_item_ty_8a76b5_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitem',
            index=models.Index(fields=['is_btm'], name='medical_med_is_btm_60cb08_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitem',
            index=models.Index(fields=['pzn'], name='medical_med_pzn_6bdbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitem',
            index=models.Index(fields=['atc_code'], name='medical_med_atc_cod_78db14_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitem',
            index=models.Index(fields=['next_maintenance_date'], name='medical_med_next_ma_b62863_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalbatch',
            index=models.Index(fields=['item', 'expiry_date'], name='medical_med_item_id_219863_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalbatch',
            index=models.Index(fields=['batch_number'], name='medical_med_batch_n_3f4034_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalbatch',
            index=models.Index(fields=['is_recalled'], name='medical_med_is_reca_ca7973_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalbatch',
            index=models.Index(fields=['expiry_date'], name='medical_med_expiry__9a047e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='medicalbatch',
            unique_together={('item', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='medicalstockmovement',
            index=models.Index(fields=['item', '-movement_date'], name='medical_med_item_id_272704_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalstockmovement',
            index=models.Index(fields=['movement_type', '-movement_date'], name='medical_med_movemen_3ae178_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalstockmovement',
            index=models.Index(fields=['batch_number'], name='medical_med_batch_n_fb4931_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalstockmovement',
            index=models.Index(fields=['expiry_date'], name='medical_med_expiry__ce7285_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalstockmovement',
            index=models.Index(fields=['approval_status'], name='medical_med_approva_f58436_idx'),
        ),
    ]
