# Generated by Django 5.2.7 on 2025-10-04 11:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Messzeitpunkt')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Temperatur (°C)')),
                ('device_id', models.CharField(blank=True, help_text='ID des Temperatur-Sensors', max_length=100, verbose_name='Messgerät-ID')),
                ('is_within_range', models.BooleanField(default=True, help_text='Temperatur im erlaubten Bereich?', verbose_name='Im Sollbereich')),
                ('notes', models.TextField(blank=True, help_text='z.B. Maßnahmen bei Überschreitung', verbose_name='Notizen')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='medical.medicalbatch', verbose_name='Charge')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temperature_logs', to='locations.location', verbose_name='Lagerort')),
                ('measured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_measurements', to=settings.AUTH_USER_MODEL, verbose_name='Gemessen durch')),
            ],
            options={
                'verbose_name': 'Temperatur-Messung',
                'verbose_name_plural': 'Temperatur-Messungen',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['batch', '-measured_at'], name='medical_tem_batch_i_52be90_idx'), models.Index(fields=['is_within_range'], name='medical_tem_is_with_c5c9ec_idx'), models.Index(fields=['-measured_at'], name='medical_tem_measure_061b53_idx')],
            },
        ),
    ]
