# Generated by Django 5.0.14 on 2025-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_temperaturelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalitem',
            name='external_order_number',
            field=models.CharField(blank=True, help_text='Externe Bestellnummer / Herstellernummer', max_length=100, verbose_name='Externe Bestellnummer'),
        ),
        migrations.AddField(
            model_name='medicalitem',
            name='internal_order_number',
            field=models.CharField(blank=True, help_text='Interne Artikelnummer des Lieferanten', max_length=100, verbose_name='Interne Bestellnummer'),
        ),
    ]
