# Generated by Django 5.0.14 on 2025-10-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_medicalitem_external_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalitem',
            name='generic_alternative',
            field=models.CharField(blank=True, help_text='Alternative Produkte / Generika', max_length=255, verbose_name='Generikum'),
        ),
    ]
