# Generated by Django 5.0.14 on 2025-10-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_alter_medicalitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalitem',
            name='manual_document',
            field=models.FileField(blank=True, help_text='PDF oder Bild-Datei (wird automatisch per OCR durchsuchbar gemacht)', null=True, upload_to='medical/manuals/', verbose_name='Handbuch / Bedienungsanleitung'),
        ),
    ]
