# Generated by Django 5.2.7 on 2025-10-17 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0003_location_technical_equipment'),
        ('medical', '0007_medicalitem_manual_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalbatch',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medical.medicalitem', verbose_name='Artikel (Legacy)'),
        ),
        migrations.CreateModel(
            name='MedicalItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_number', models.CharField(help_text='Eindeutige Stammdatennummer (z.B. MASTER-MED-001)', max_length=50, unique=True, verbose_name='Stammdatennummer')),
                ('name', models.CharField(max_length=255, verbose_name='Artikelname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_type', models.CharField(choices=[('medication', 'Medikament'), ('btm', 'Betäubungsmittel (BTM)'), ('infusion', 'Infusion'), ('injection', 'Injektion'), ('bandage', 'Verbandmaterial'), ('diagnostic', 'Diagnostik'), ('device', 'Medizintechnik'), ('disinfectant', 'Desinfektionsmittel'), ('oxygen', 'Sauerstoff'), ('disposable', 'Einwegartikel'), ('other', 'Sonstiges')], default='medication', max_length=20, verbose_name='Artikeltyp')),
                ('is_btm', models.BooleanField(default=False, help_text='Unterliegt dem Betäubungsmittelgesetz', verbose_name='Betäubungsmittel (BTM)')),
                ('active_ingredient', models.CharField(blank=True, help_text='z.B. "Paracetamol", "Morphin"', max_length=200, verbose_name='Wirkstoff')),
                ('dosage', models.CharField(blank=True, help_text='z.B. "500mg", "10ml"', max_length=100, verbose_name='Dosierung')),
                ('pharmaceutical_form', models.CharField(blank=True, help_text='z.B. "Tabletten", "Ampullen", "Salbe"', max_length=100, verbose_name='Darreichungsform')),
                ('administration_route', models.CharField(blank=True, choices=[('oral', 'Oral'), ('iv', 'Intravenös (i.v.)'), ('im', 'Intramuskulär (i.m.)'), ('sc', 'Subkutan (s.c.)'), ('inhalation', 'Inhalation'), ('topical', 'Topisch (Haut)'), ('rectal', 'Rektal'), ('sublingual', 'Sublingual'), ('other', 'Sonstiges')], max_length=20, verbose_name='Verabreichungsweg')),
                ('pzn', models.CharField(blank=True, help_text='Deutsche Pharmazentralnummer', max_length=20, null=True, unique=True, verbose_name='PZN (Pharmazentralnummer)')),
                ('atc_code', models.CharField(blank=True, help_text='Anatomisch-Therapeutisch-Chemisches Klassifikationssystem', max_length=20, verbose_name='ATC-Code')),
                ('approval_number', models.CharField(blank=True, max_length=50, verbose_name='Zulassungsnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='Hersteller')),
                ('internal_order_number', models.CharField(blank=True, help_text='Interne Artikelnummer des Lieferanten', max_length=100, verbose_name='Interne Bestellnummer')),
                ('external_order_number', models.CharField(blank=True, help_text='Externe Bestellnummer / Herstellernummer', max_length=100, verbose_name='Externe Bestellnummer')),
                ('generic_alternative', models.CharField(blank=True, help_text='Alternative Produkte / Generika', max_length=255, verbose_name='Generikum')),
                ('unit', models.CharField(choices=[('Stück', 'Stück'), ('Packung', 'Packung'), ('Karton', 'Karton'), ('Paar', 'Paar'), ('Set', 'Set'), ('ml', 'Milliliter (ml)'), ('l', 'Liter (l)'), ('mg', 'Milligramm (mg)'), ('g', 'Gramm (g)'), ('kg', 'Kilogramm (kg)'), ('Ampulle', 'Ampulle'), ('Durchstechflasche', 'Durchstechflasche'), ('Tablette', 'Tablette'), ('Kapsel', 'Kapsel'), ('Blister', 'Blister'), ('Tube', 'Tube'), ('Flasche', 'Flasche'), ('Beutel', 'Beutel'), ('Rolle', 'Rolle'), ('Liter (Gas)', 'Liter (Gas)'), ('m³', 'Kubikmeter (m³)')], default='Stück', max_length=50, verbose_name='Einheit')),
                ('expiry_warning_days', models.PositiveIntegerField(default=90, help_text='Warnung X Tage vor Ablauf', verbose_name='Ablauf-Warnung (Tage)')),
                ('storage_condition', models.CharField(choices=[('room_temp', 'Raumtemperatur (15-25°C)'), ('refrigerated', 'Gekühlt (2-8°C)'), ('frozen', 'Gefroren (<-15°C)'), ('dark', 'Dunkel'), ('dry', 'Trocken'), ('special', 'Spezielle Bedingungen')], default='room_temp', max_length=20, verbose_name='Lagerungsbedingungen')),
                ('requires_cold_chain', models.BooleanField(default=False, help_text='Lückenlose Kühlung notwendig', verbose_name='Kühlkette erforderlich')),
                ('is_prescription_required', models.BooleanField(default=False, verbose_name='Verschreibungspflichtig')),
                ('package_insert', models.FileField(blank=True, help_text='PDF-Datei des Beipackzettels', null=True, upload_to='medical/package_inserts/', verbose_name='Beipackzettel')),
                ('spc_document', models.FileField(blank=True, help_text='Summary of Product Characteristics', null=True, upload_to='medical/spc/', verbose_name='Fachinformation (SPC)')),
                ('manual_document', models.FileField(blank=True, help_text='PDF oder Bild-Datei (wird automatisch per OCR durchsuchbar gemacht)', null=True, upload_to='medical/manuals/', verbose_name='Handbuch / Bedienungsanleitung')),
                ('is_medical_device', models.BooleanField(default=False, help_text='Unterliegt Medizinproduktegesetz (MPG)', verbose_name='Medizinprodukt')),
                ('medical_device_class', models.CharField(blank=True, help_text='z.B. "I", "IIa", "IIb", "III"', max_length=10, verbose_name='Medizinprodukte-Klasse')),
                ('udi', models.CharField(blank=True, max_length=100, verbose_name='UDI (Unique Device Identifier)')),
                ('requires_maintenance', models.BooleanField(default=False, verbose_name='Wartung erforderlich')),
                ('maintenance_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wartungsintervall (Monate)')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximalbestand')),
                ('indications', models.TextField(blank=True, help_text='Anwendungsgebiete', verbose_name='Indikationen')),
                ('contraindications', models.TextField(blank=True, help_text='Gegenanzeigen', verbose_name='Kontraindikationen')),
                ('side_effects', models.TextField(blank=True, verbose_name='Nebenwirkungen')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('image', models.ImageField(blank=True, null=True, upload_to='medical/items/', verbose_name='Artikelbild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_master_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_medical_masters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_master_items', to='inventory_base.supplier', verbose_name='Hauptlieferant')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_medical_masters', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Medizinische Stammdaten',
                'verbose_name_plural': 'Medizinische Stammdaten',
                'ordering': ['master_number'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Eindeutige Inventarnummer (z.B. DEV-CORPULS-001)', max_length=50, unique=True, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(blank=True, help_text='Hersteller-Seriennummer', max_length=100, verbose_name='Seriennummer')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Anschaffungsdatum')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Inbetriebnahme')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Anschaffungspreis (EUR)')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('fair', 'Befriedigend'), ('poor', 'Mangelhaft'), ('defect', 'Defekt')], default='good', max_length=20, verbose_name='Zustand')),
                ('is_operational', models.BooleanField(default=True, help_text='Gerät ist funktionsfähig und einsatzbereit', verbose_name='Einsatzbereit')),
                ('is_active', models.BooleanField(default=True, help_text='Gerät ist im Bestand (nicht ausgemustert)', verbose_name='Aktiv')),
                ('decommissioned_date', models.DateField(blank=True, null=True, verbose_name='Ausgemustert am')),
                ('decommissioned_reason', models.TextField(blank=True, verbose_name='Ausmusterungsgrund')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_device_instances', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medical_device_instances', to='locations.location', verbose_name='Lagerort')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_device_instances', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_instances', to='medical.medicalitemmaster', verbose_name='Stammdaten')),
            ],
            options={
                'verbose_name': 'Medizintechnik-Instanz',
                'verbose_name_plural': 'Medizintechnik-Instanzen',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.AddField(
            model_name='medicalbatch',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='medical.medicalitemmaster', verbose_name='Stammdaten'),
        ),
        migrations.AddIndex(
            model_name='medicalitemmaster',
            index=models.Index(fields=['master_number'], name='medical_med_master__aeae8e_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitemmaster',
            index=models.Index(fields=['item_type', 'category'], name='medical_med_item_ty_a67d75_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitemmaster',
            index=models.Index(fields=['is_btm'], name='medical_med_is_btm_346fca_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitemmaster',
            index=models.Index(fields=['pzn'], name='medical_med_pzn_a7718a_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitemmaster',
            index=models.Index(fields=['atc_code'], name='medical_med_atc_cod_be3acd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalitemmaster',
            index=models.Index(fields=['is_active'], name='medical_med_is_acti_a035c2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldeviceinstance',
            index=models.Index(fields=['inventory_number'], name='medical_med_invento_205d34_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldeviceinstance',
            index=models.Index(fields=['master', 'is_active'], name='medical_med_master__d882f2_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldeviceinstance',
            index=models.Index(fields=['next_maintenance_date'], name='medical_med_next_ma_a23440_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldeviceinstance',
            index=models.Index(fields=['next_inspection_date'], name='medical_med_next_in_5798a0_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldeviceinstance',
            index=models.Index(fields=['is_operational'], name='medical_med_is_oper_e1c28e_idx'),
        ),
    ]
