# Generated by Django 5.0.14 on 2025-10-20 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_technical_equipment'),
        ('medical', '0008_alter_medicalbatch_item_medicalitemmaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort'),
        ),
    ]
