# Generated by Django 5.0.14 on 2025-10-22 07:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_technical_equipment'),
        ('medical', '0009_alter_medicalitem_location'),
        ('personnel', '0015_person_show_private_contact_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('check_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Inventur-Nummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('check_type', models.CharField(choices=[('full', 'Vollinventur'), ('partial', 'Teilinventur'), ('spot_check', 'Stichprobe'), ('cycle_count', 'Zykluszählung'), ('annual', 'Jahresinventur')], default='partial', max_length=20, verbose_name='Inventurart')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('counting_complete', 'Zählung abgeschlossen'), ('review', 'In Prüfung'), ('adjustments_pending', 'Korrekturen ausstehend'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='planned', max_length=30, verbose_name='Status')),
                ('scheduled_start_date', models.DateField(verbose_name='Geplanter Start')),
                ('scheduled_end_date', models.DateField(verbose_name='Geplantes Ende')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächlicher Start')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Gesamt-Anzahl Artikel')),
                ('counted_items', models.PositiveIntegerField(default=0, verbose_name='Gezählte Artikel')),
                ('items_with_discrepancies', models.PositiveIntegerField(default=0, verbose_name='Artikel mit Abweichungen')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('include_btm', models.BooleanField(default=False, help_text='Betäubungsmittel in Inventur einbeziehen', verbose_name='BTM einbeziehen')),
                ('btm_verification_date', models.DateTimeField(blank=True, null=True, verbose_name='BTM Verifizierungsdatum')),
                ('check_expiry_dates', models.BooleanField(default=True, verbose_name='Ablaufdaten prüfen')),
                ('expired_items_found', models.PositiveIntegerField(default=0, verbose_name='Abgelaufene Medikamente gefunden')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_approved', to='personnel.person', verbose_name='Genehmigt von')),
                ('btm_verified_by', models.ForeignKey(blank=True, help_text='Zweite Person für Vier-Augen-Prinzip bei BTM', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medical_btm_inventories_verified', to='personnel.person', verbose_name='BTM verifiziert von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, help_text='Leer = Alle Lagerorte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_checks', to='locations.location', verbose_name='Lagerort')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_responsible', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('team_members', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_team', to='personnel.person', verbose_name='Team-Mitglieder')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Medical Inventur',
                'verbose_name_plural': 'Medical Inventuren',
                'db_table': 'medical_inventory_check',
                'ordering': ['-scheduled_start_date'],
                'permissions': [('view_btm_inventory', 'Kann BTM-Inventuren sehen'), ('verify_btm_inventory', 'Kann BTM-Inventuren verifizieren')],
            },
        ),
        migrations.CreateModel(
            name='MedicalInventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('item_name', models.CharField(max_length=200, verbose_name='Artikelbezeichnung')),
                ('item_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sollbestand')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Istbestand')),
                ('is_counted', models.BooleanField(default=False, verbose_name='Gezählt')),
                ('counted_date', models.DateTimeField(blank=True, null=True, verbose_name='Zähldatum')),
                ('has_discrepancy', models.BooleanField(default=False, verbose_name='Abweichung')),
                ('variance_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Differenz')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('requires_recount', models.BooleanField(default=False, verbose_name='Nachzählung erforderlich')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Chargennummer')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ablaufdatum')),
                ('is_btm', models.BooleanField(default=False, verbose_name='Ist BTM')),
                ('btm_verified', models.BooleanField(default=False, verbose_name='BTM verifiziert')),
                ('physical_condition', models.CharField(blank=True, choices=[('good', 'Gut'), ('acceptable', 'Akzeptabel'), ('damaged', 'Beschädigt'), ('unusable', 'Unbrauchbar')], default='good', max_length=20, verbose_name='Physischer Zustand')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_counted', to='personnel.person', verbose_name='Gezählt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medical.medicalinventorycheck', verbose_name='Inventur')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('medical_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical.medicaldeviceinstance', verbose_name='Medizintechnik-Gerät')),
                ('medical_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='medical.medicalitemmaster', verbose_name='Medizinischer Artikel')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Medical Inventur-Position',
                'verbose_name_plural': 'Medical Inventur-Positionen',
                'db_table': 'medical_inventory_check_item',
                'ordering': ['location', 'item_name'],
            },
        ),
    ]
