# Generated by Django 5.0.14 on 2026-01-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_medicalinventorycheck_medicalinventorycheckitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldeviceinstance',
            name='additional_inventory_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Inventarnummern für Module/Komponenten dieses Geräts', verbose_name='Zusätzliche Inventarnummern'),
        ),
    ]
