# Generated by Django 5.0.14 on 2026-01-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_add_additional_inventory_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalbatch',
            name='external_order_number',
            field=models.CharField(blank=True, help_text='Bestellnummer des Lieferanten/Herstellers', max_length=100, verbose_name='Externe Bestellnummer'),
        ),
        migrations.AddField(
            model_name='medicalbatch',
            name='internal_order_number',
            field=models.CharField(blank=True, help_text='Interne Bestellnummer aus dem eigenen System', max_length=100, verbose_name='Interne Bestellnummer'),
        ),
    ]
