# Generated by Django 5.0.14 on 2026-02-10 12:46

import django.db.models.deletion
from django.db import migrations, models


def nullify_legacy_item_refs(apps, schema_editor):
    """Alte item_id-Werte nullen, da sie auf MedicalItem statt MedicalItemMaster zeigen."""
    MedicalStockMovement = apps.get_model('medical', 'MedicalStockMovement')
    MedicalStockMovement.objects.all().update(item=None)


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_add_order_numbers_to_batch'),
    ]

    operations = [
        # 1. Erst FK nullable machen (behält alte Tabellen-Referenz)
        migrations.AlterField(
            model_name='medicalstockmovement',
            name='item',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='stock_movements',
                to='medical.medicalitem',
                verbose_name='Artikel',
            ),
        ),
        # 2. Alte Referenzen nullen (IDs stammen aus anderer Tabelle)
        migrations.RunPython(nullify_legacy_item_refs, migrations.RunPython.noop),
        # 3. FK-Ziel auf MedicalItemMaster umstellen
        migrations.AlterField(
            model_name='medicalstockmovement',
            name='item',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='stock_movements',
                to='medical.medicalitemmaster',
                verbose_name='Artikel',
            ),
        ),
    ]
