# Generated by Django 5.0.14 on 2026-02-13 11:17

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_retarget_stockmovement_item_to_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalbatch',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Einkaufspreis pro Einheit (EUR)'),
        ),
    ]
