# Generated by Django 5.0.14 on 2025-10-22 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('valid_from', models.DateTimeField(help_text='Start der Vertretung', verbose_name='Gültig ab')),
                ('valid_to', models.DateTimeField(help_text='Ende der Vertretung', verbose_name='Gültig bis')),
                ('delegated_permissions', models.JSONField(blank=True, default=list, help_text='Liste der delegierten Permission-Codes. Leer wenn alle.', verbose_name='Delegierte Berechtigungen')),
                ('delegate_all_permissions', models.BooleanField(default=False, help_text='Wenn aktiv: Vertreter erhält alle Rechte des Vertretenen', verbose_name='Alle Berechtigungen delegieren')),
                ('is_active', models.BooleanField(default=True, help_text='Vertretung ist aktiv', verbose_name='Aktiv')),
                ('reason', models.TextField(blank=True, help_text='Grund der Vertretung (z.B. Urlaub, Krankheit)', verbose_name='Grund')),
                ('notes', models.TextField(blank=True, help_text='Zusätzliche Hinweise zur Vertretung', verbose_name='Notizen')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigt am')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Vorgesetzter der die Vertretung genehmigt hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_approved', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('delegate', models.ForeignKey(help_text='Person die vertritt', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='Vertreter')),
                ('delegator', models.ForeignKey(help_text='Person die vertreten wird', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='Vertretener')),
            ],
            options={
                'verbose_name': 'Vertretung',
                'verbose_name_plural': 'Vertretungen',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['delegator', 'is_active'], name='permissions_delegat_e4ee24_idx'), models.Index(fields=['delegate', 'is_active'], name='permissions_delegat_a7d72b_idx'), models.Index(fields=['valid_from', 'valid_to'], name='permissions_valid_f_9d398f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('permission', models.CharField(help_text='Permission-Code', max_length=255, verbose_name='Permission')),
                ('object_type', models.CharField(help_text="z.B. 'location', 'order', etc.", max_length=100, verbose_name='Objekttyp')),
                ('object_id', models.PositiveIntegerField(verbose_name='Objekt-ID')),
                ('reason', models.TextField(blank=True, verbose_name='Grund')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional: Zeitpunkt wann Permission abläuft', null=True, verbose_name='Läuft ab am')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_permissions_granted', to=settings.AUTH_USER_MODEL, verbose_name='Erteilt von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Objekt-Berechtigung',
                'verbose_name_plural': 'Objekt-Berechtigungen',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'permission', 'is_active'], name='permissions_user_id_621069_idx'), models.Index(fields=['object_type', 'object_id'], name='permissions_object__affc1a_idx')],
                'unique_together': {('user', 'permission', 'object_type', 'object_id')},
            },
        ),
        migrations.CreateModel(
            name='TimeBasedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('permission', models.CharField(help_text="Permission-Code (z.B. 'medical.view_medication')", max_length=255, verbose_name='Permission')),
                ('valid_from_time', models.TimeField(blank=True, help_text='z.B. 08:00 für Start der Dienstzeit', null=True, verbose_name='Gültig ab (Uhrzeit)')),
                ('valid_to_time', models.TimeField(blank=True, help_text='z.B. 20:00 für Ende der Dienstzeit', null=True, verbose_name='Gültig bis (Uhrzeit)')),
                ('valid_weekdays', models.JSONField(blank=True, default=list, help_text='Liste von Wochentagen (1=Montag, 7=Sonntag). Leer = alle Tage', verbose_name='Gültige Wochentage')),
                ('valid_from_date', models.DateField(blank=True, help_text='Permission erst ab diesem Datum gültig', null=True, verbose_name='Gültig ab (Datum)')),
                ('valid_to_date', models.DateField(blank=True, help_text='Permission nur bis zu diesem Datum gültig', null=True, verbose_name='Gültig bis (Datum)')),
                ('is_active', models.BooleanField(default=True, help_text='Kann deaktiviert werden ohne zu löschen', verbose_name='Aktiv')),
                ('reason', models.TextField(blank=True, help_text='Grund für die zeitliche Beschränkung', verbose_name='Grund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Zeitbasierte Berechtigung',
                'verbose_name_plural': 'Zeitbasierte Berechtigungen',
                'ordering': ['user', 'permission'],
                'indexes': [models.Index(fields=['user', 'permission', 'is_active'], name='permissions_user_id_cd19d8_idx'), models.Index(fields=['valid_from_date', 'valid_to_date'], name='permissions_valid_f_92937f_idx')],
            },
        ),
    ]
