# Generated by Django 5.2.15 on 2026-09-16 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0008_migrate_nip_leuchtturm_to_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('color', models.CharField(choices=[('gray', 'Grau'), ('blue', 'Blau'), ('green', 'Grün'), ('yellow', 'Gelb'), ('orange', 'Orange'), ('red', 'Rot'), ('purple', 'Lila')], default='gray', max_length=10, verbose_name='Farbe')),
                ('icon', models.CharField(blank=True, help_text='Emoji, z.B. 🚒', max_length=8, verbose_name='Symbol')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Terminkategorie',
                'verbose_name_plural': 'Terminkategorien',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('start_date', models.DateField(db_index=True, verbose_name='Beginn (Datum)')),
                ('end_date', models.DateField(blank=True, help_text='Leer = eintägig', null=True, verbose_name='Ende (Datum)')),
                ('all_day', models.BooleanField(default=True, verbose_name='Ganztägig')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Beginn (Uhrzeit)')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Ende (Uhrzeit)')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ort')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('recurrence', models.CharField(choices=[('none', 'Einmalig'), ('weekly', 'Wöchentlich'), ('biweekly', 'Alle zwei Wochen'), ('monthly', 'Monatlich (gleicher Tag)'), ('yearly', 'Jährlich')], default='none', max_length=10, verbose_name='Wiederholung')),
                ('recurrence_until', models.DateField(blank=True, help_text='Leer = bis zu zwei Jahre ab Beginn', null=True, verbose_name='Wiederholen bis')),
                ('show_on_monitor', models.BooleanField(default=True, verbose_name='Auf Info-Monitoren anzeigen')),
                ('is_public', models.BooleanField(default=False, help_text='Öffentliche Info-Monitore sind ohne Anmeldung abrufbar', verbose_name='Auch auf öffentlichen Monitoren')),
                ('uid', models.CharField(blank=True, db_index=True, help_text='Kennung aus einem ICS-Import (für erneuten Import)', max_length=255, verbose_name='ICS-UID')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('sites', models.ManyToManyField(blank=True, help_text='Optional: nur für bestimmte Wachen relevant (Filter für Listen und Monitore)', limit_choices_to={'location_type': 'site'}, related_name='termine', to='locations.location', verbose_name='Wachen')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='termine.eventcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['start_date', 'start_time', 'title'],
                'permissions': [('termine_view', 'Termine: Kalender ansehen'), ('termine_edit', 'Termine: anlegen und bearbeiten'), ('termine_manage', 'Termine: löschen, Kategorien und Import verwalten')],
            },
        ),
    ]
