# Generated by Django 5.0.14 on 2025-10-03 12:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('report_type', models.CharField(choices=[('inventory', 'Bestandsübersicht'), ('expiring', 'Ablaufende Items'), ('low_stock', 'Niedrige Bestände'), ('procurement', 'Bestellübersicht'), ('vehicle', 'Fahrzeugübersicht'), ('inspection', 'Prüfungen & Wartungen'), ('personnel', 'Personalübersicht'), ('document', 'Dokumentenübersicht'), ('audit', 'Audit-Trail'), ('custom', 'Benutzerdefiniert')], max_length=20, verbose_name='Report-Typ')),
                ('query', models.TextField(help_text='SQL-Query oder Python-Code für Datenabfrage', verbose_name='Query / Code')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='JSON-Objekt mit Template-Parametern', verbose_name='Parameter')),
                ('template_file', models.CharField(blank=True, help_text='Django-Template für HTML/PDF-Rendering', max_length=255, verbose_name='Template-Datei')),
                ('available_formats', models.JSONField(default=list, help_text='Liste der unterstützten Export-Formate', verbose_name='Verfügbare Formate')),
                ('is_public', models.BooleanField(default=False, help_text='Für alle Benutzer sichtbar', verbose_name='Öffentlich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Verwendungen')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='Berechtigte Benutzer')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Report-Template',
                'verbose_name_plural': 'Report-Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('frequency', models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich'), ('quarterly', 'Vierteljährlich'), ('yearly', 'Jährlich'), ('custom', 'Benutzerdefiniert')], default='monthly', max_length=20, verbose_name='Frequenz')),
                ('cron_expression', models.CharField(blank=True, help_text='Nur für benutzerdefinierte Frequenz', max_length=100, verbose_name='Cron-Ausdruck')),
                ('run_at_time', models.TimeField(blank=True, help_text='Uhrzeit für tägliche/wöchentliche Reports', null=True, verbose_name='Ausführungszeit')),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='Für wöchentliche Reports', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Wochentag')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='Für monatliche Reports', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Tag des Monats')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameter')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Export-Format')),
                ('send_email', models.BooleanField(default=True, verbose_name='Per E-Mail senden')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Reports werden nach X Tagen gelöscht', verbose_name='Aufbewahrung (Tage)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt ausgeführt')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Nächste Ausführung')),
                ('run_count', models.PositiveIntegerField(default=0, verbose_name='Ausführungen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('recipients', models.ManyToManyField(help_text='Benutzer, die Report per E-Mail erhalten', related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reporting.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Report-Zeitplan',
                'verbose_name_plural': 'Report-Zeitpläne',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('report_type', models.CharField(choices=[('inventory', 'Bestandsübersicht'), ('expiring', 'Ablaufende Items'), ('low_stock', 'Niedrige Bestände'), ('procurement', 'Bestellübersicht'), ('vehicle', 'Fahrzeugübersicht'), ('inspection', 'Prüfungen & Wartungen'), ('personnel', 'Personalübersicht'), ('document', 'Dokumentenübersicht'), ('audit', 'Audit-Trail'), ('custom', 'Benutzerdefiniert')], max_length=20, verbose_name='Report-Typ')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('generating', 'Wird erstellt'), ('completed', 'Abgeschlossen'), ('failed', 'Fehlgeschlagen'), ('expired', 'Abgelaufen')], default='pending', max_length=20, verbose_name='Status')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Von')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Bis')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameter')),
                ('file', models.FileField(blank=True, upload_to='reports/%Y/%m/', verbose_name='Datei')),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Format')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)')),
                ('generation_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Generierung gestartet')),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Generierung abgeschlossen')),
                ('generation_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='Generierungsdauer (Sekunden)')),
                ('error_message', models.TextField(blank=True, verbose_name='Fehlermeldung')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Reports werden nach Ablauf automatisch gelöscht', null=True, verbose_name='Läuft ab am')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Downloads')),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt heruntergeladen')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Verknüpftes Objekt ID')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Verknüpfter Typ')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='reporting.reporttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('category', models.CharField(choices=[('inventory', 'Lagerbestand'), ('financial', 'Finanzen'), ('operational', 'Betrieb'), ('quality', 'Qualität'), ('compliance', 'Compliance')], max_length=20, verbose_name='Kategorie')),
                ('kpi_type', models.CharField(choices=[('count', 'Anzahl'), ('sum', 'Summe'), ('average', 'Durchschnitt'), ('percentage', 'Prozentsatz'), ('ratio', 'Verhältnis'), ('trend', 'Trend')], max_length=20, verbose_name='KPI-Typ')),
                ('query', models.TextField(help_text='SQL-Query oder Python-Code für KPI-Berechnung', verbose_name='Query / Code')),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Zielwert')),
                ('threshold_good', models.DecimalField(blank=True, decimal_places=2, help_text='Grüne Ampel ab diesem Wert', max_digits=12, null=True, verbose_name='Schwellwert Gut')),
                ('threshold_warning', models.DecimalField(blank=True, decimal_places=2, help_text='Gelbe Ampel ab diesem Wert', max_digits=12, null=True, verbose_name='Schwellwert Warnung')),
                ('unit', models.CharField(blank=True, help_text='z.B. €, %, Stück', max_length=20, verbose_name='Einheit')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Farbe')),
                ('refresh_interval', models.PositiveIntegerField(default=60, help_text='Wie oft KPI neu berechnet wird', verbose_name='Aktualisierungsintervall (Minuten)')),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt berechnet')),
                ('last_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Letzter Wert')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['category', 'display_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='reporting_k_categor_da4aa5_idx'), models.Index(fields=['kpi_type'], name='reporting_k_kpi_typ_afeeae_idx'), models.Index(fields=['is_active', 'display_order'], name='reporting_k_is_acti_89c7f5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['report_type', 'is_active'], name='reporting_r_report__a12015_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_public'], name='reporting_r_is_publ_c6be3f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['template', 'is_active'], name='reporting_r_templat_8f4f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='reporting_r_is_acti_c913b7_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['frequency'], name='reporting_r_frequen_f0505d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['template', '-created_at'], name='reporting_r_templat_020189_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type', 'status'], name='reporting_r_report__cc1d17_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='reporting_r_status_8d3840_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_by', '-created_at'], name='reporting_r_created_889b69_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['expires_at'], name='reporting_r_expires_3c9d9e_idx'),
        ),
    ]
