# Generated by Django 5.0.14 on 2025-10-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['name'], 'permissions': [('view_reporting_dashboard', 'Kann Reports & KPIs Dashboard sehen'), ('generate_reports', 'Kann Reports generieren'), ('schedule_reports', 'Kann Reports planen'), ('export_reports', 'Kann Reports exportieren')], 'verbose_name': 'Report-Template', 'verbose_name_plural': 'Report-Templates'},
        ),
    ]
