# Generated by Django 5.0.14 on 2026-02-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_alter_reporttemplate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['name'], 'permissions': [('view_reporting_dashboard', 'Kann Reports & KPIs Dashboard sehen'), ('view_module_reports', 'Kann Modul-Reports sehen'), ('generate_reports', 'Kann Reports generieren'), ('schedule_reports', 'Kann Reports planen'), ('export_reports', 'Kann Reports exportieren')], 'verbose_name': 'Report-Template', 'verbose_name_plural': 'Report-Templates'},
        ),
    ]
