# Generated by Django 5.2.15 on 2026-09-16 07:09

import dienstplan.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('kind', models.CharField(choices=[('duty', 'Dienst'), ('office', 'Büro / Tagdienst'), ('training', 'Lehrgang / Fortbildung'), ('absence', 'Abwesenheit'), ('free', 'Frei'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Art')),
                ('function', models.CharField(blank=True, choices=[('a1', 'A1-Dienst'), ('a2', 'A2-Dienst'), ('b', 'B-Dienst'), ('c', 'C-Dienst'), ('lagedienst', 'Lagedienst'), ('lna', 'LNA')], default='', help_text='Mit dieser Zuordnung wird der Code im Dienstplan-Widget der Info-Monitore als Führungsdienst des Tages angezeigt', max_length=20, verbose_name='Führungsdienst-Funktion')),
                ('color', models.CharField(choices=[('gray', 'Grau'), ('blue', 'Blau'), ('green', 'Grün'), ('yellow', 'Gelb'), ('orange', 'Orange'), ('red', 'Rot'), ('purple', 'Lila')], default='gray', max_length=10, verbose_name='Farbe')),
                ('show_on_monitor', models.BooleanField(default=False, help_text='Im Dienstplan-Widget werden nur Codes mit diesem Haken aufgeführt', verbose_name='Auf Info-Monitor anzeigen')),
                ('verified', models.BooleanField(default=False, help_text='Vorbelegte Codes sind Vermutungen aus dem ersten Import; nach Prüfung Haken setzen', verbose_name='Bedeutung geprüft')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Dienstcode',
                'verbose_name_plural': 'Dienstcodes',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RosterUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=dienstplan.models._upload_path, verbose_name='CSV-Datei')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=dienstplan.models._upload_path, verbose_name='PDF-Datei (optional)')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='Dateiname')),
                ('period_start', models.DateField(verbose_name='Zeitraum von')),
                ('period_end', models.DateField(verbose_name='Zeitraum bis')),
                ('month_label', models.CharField(blank=True, max_length=50, verbose_name='Monat')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Fachabteilung')),
                ('plan_status', models.CharField(blank=True, help_text='z.B. vorläufig oder genehmigt', max_length=50, verbose_name='Zustand laut Export')),
                ('status', models.CharField(choices=[('pending', 'Vorschau (noch nicht übernommen)'), ('imported', 'Aktueller Stand'), ('replaced', 'Durch neueren Upload ersetzt')], default='pending', max_length=10, verbose_name='Status')),
                ('person_count', models.PositiveIntegerField(default=0, verbose_name='Personen')),
                ('warnings', models.TextField(blank=True, verbose_name='Hinweise aus dem Import')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='Übernommen am')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dienstplan_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Dienstplan-Upload',
                'verbose_name_plural': 'Dienstplan-Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Datum')),
                ('person_name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='Code')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dienstplan.rosterupload')),
            ],
            options={
                'verbose_name': 'Dienstplan-Eintrag',
                'verbose_name_plural': 'Dienstplan-Einträge',
                'ordering': ['date', 'person_name'],
            },
        ),
        migrations.AddIndex(
            model_name='rosterupload',
            index=models.Index(fields=['status', 'period_start', 'period_end'], name='dienstplan__status_753004_idx'),
        ),
        migrations.AddConstraint(
            model_name='rosterentry',
            constraint=models.UniqueConstraint(fields=('upload', 'date', 'person_name'), name='dienstplan_entry_unique'),
        ),
    ]
