# Generated by Django 5.2.15 on 2026-09-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dienstplan', '0002_default_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dutycode',
            name='function',
            field=models.CharField(blank=True, choices=[('a1', 'A1-Dienst'), ('a2', 'A2-Dienst'), ('a2e', 'Ersatz A-Dienst'), ('b', 'B-Dienst'), ('c', 'C-Dienst'), ('lagedienst', 'Lagedienst'), ('lna', 'LNA')], default='', help_text='Mit dieser Zuordnung wird der Code im Dienstplan-Widget der Info-Monitore als Führungsdienst des Tages angezeigt', max_length=20, verbose_name='Führungsdienst-Funktion'),
        ),
    ]
