# Generated by Django 5.2.15 on 2026-09-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dienstplan', '0004_confirmed_codes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rosterupload',
            options={'ordering': ['-uploaded_at'], 'permissions': [('dienstplan_view', 'Dienstplan: ansehen (Übersicht, Monatsansicht, Uploads)'), ('dienstplan_edit', 'Dienstplan: bearbeiten (hochladen, übernehmen, Dienstcodes pflegen)'), ('dienstplan_stats', 'Dienstplan: statistische Auswertung')], 'verbose_name': 'Dienstplan-Upload', 'verbose_name_plural': 'Dienstplan-Uploads'},
        ),
    ]
