# Generated by Django 5.2.15 on 2026-09-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dienstplan', '0005_custom_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterupload',
            name='pdf_file',
        ),
    ]
