# Generated by Django 5.0.14 on 2025-10-03 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Mangel-Titel')),
                ('description', models.TextField(help_text='Detaillierte Beschreibung des Mangels', verbose_name='Beschreibung')),
                ('severity', models.CharField(choices=[('info', 'Information (kein Mangel)'), ('minor', 'Geringer Mangel (einsatzbereit)'), ('moderate', 'Mittlerer Mangel (eingeschränkt einsatzbereit)'), ('major', 'Erheblicher Mangel (nicht einsatzbereit)'), ('critical', 'Kritischer Mangel (Verkehrssicherheit gefährdet)')], default='minor', max_length=20, verbose_name='Schweregrad')),
                ('category', models.CharField(choices=[('bodywork', 'Karosserie'), ('glass', 'Verglasung'), ('lights', 'Beleuchtung'), ('tires', 'Reifen/Räder'), ('interior', 'Innenraum'), ('equipment', 'Ausrüstung'), ('engine', 'Motor/Antrieb'), ('brakes', 'Bremsen'), ('electronics', 'Elektronik'), ('cleaning', 'Reinigung'), ('other', 'Sonstiges')], default='other', max_length=100, verbose_name='Kategorie')),
                ('requires_immediate_action', models.BooleanField(default=False, verbose_name='Sofortige Maßnahme erforderlich')),
                ('affects_operational_readiness', models.BooleanField(default=False, verbose_name='Beeinträchtigt Einsatzbereitschaft')),
                ('repaired', models.BooleanField(default=False, verbose_name='Behoben')),
                ('repair_date', models.DateTimeField(blank=True, null=True, verbose_name='Behebungsdatum')),
                ('repair_notes', models.TextField(blank=True, verbose_name='Reparatur-Notizen')),
                ('estimated_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Geschätzte Reparaturkosten (€)')),
                ('actual_repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tatsächliche Reparaturkosten (€)')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('repaired_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_defects_repaired', to='personnel.person', verbose_name='Behoben durch')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Fahrzeug-Mangel',
                'verbose_name_plural': 'Fahrzeug-Mängel',
                'db_table': 'vehicle_handover_defect',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('handover_type', models.CharField(choices=[('shift_change', 'Wachablösung'), ('deployment_start', 'Einsatzbeginn'), ('deployment_end', 'Einsatzende'), ('maintenance_in', 'Werkstatteingang'), ('maintenance_out', 'Werkstattausgang'), ('rental', 'Ausleihe'), ('return', 'Rückgabe'), ('inspection', 'Kontrolle/Inspektion')], default='shift_change', max_length=30, verbose_name='Art der Übergabe')),
                ('handover_date', models.DateTimeField(verbose_name='Übergabezeitpunkt')),
                ('status', models.CharField(choices=[('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('defects_noted', 'Mit Mängeln abgeschlossen'), ('cancelled', 'Abgebrochen')], default='in_progress', max_length=20, verbose_name='Status')),
                ('odometer_reading', models.PositiveIntegerField(help_text='Kilometerstand bei Übergabe', validators=[django.core.validators.MinValueValidator(0)], verbose_name='KM-Stand')),
                ('fuel_level', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tankfüllung (%)')),
                ('cleanliness_interior', models.PositiveSmallIntegerField(default=5, help_text='1 = sehr schmutzig, 5 = sehr sauber', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Sauberkeit Innenraum (1-5)')),
                ('cleanliness_exterior', models.PositiveSmallIntegerField(default=5, help_text='1 = sehr schmutzig, 5 = sehr sauber', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Sauberkeit Außen (1-5)')),
                ('completeness_check_done', models.BooleanField(default=False, verbose_name='Vollständigkeitsprüfung durchgeführt')),
                ('all_items_present', models.BooleanField(default=True, verbose_name='Alle Gegenstände vollständig')),
                ('has_defects', models.BooleanField(default=False, verbose_name='Mängel festgestellt')),
                ('defects_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl Mängel')),
                ('notes', models.TextField(blank=True, help_text='Allgemeine Bemerkungen zur Übergabe', verbose_name='Bemerkungen')),
                ('confirmed_by_giver', models.BooleanField(default=False, verbose_name='Bestätigt durch Übergeber')),
                ('confirmed_by_receiver', models.BooleanField(default=False, verbose_name='Bestätigt durch Empfänger')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('handover_from', models.ForeignKey(blank=True, help_text='Person, die das Fahrzeug übergibt (bei erster Übernahme leer)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_handovers_given', to='personnel.person', verbose_name='Übergeben von')),
                ('handover_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_handovers_received', to='personnel.person', verbose_name='Übergeben an')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_handovers', to='locations.location', verbose_name='Standort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeugübergabe',
                'verbose_name_plural': 'Fahrzeugübergaben',
                'db_table': 'vehicle_handover',
                'ordering': ['-handover_date'],
            },
        ),
        migrations.CreateModel(
            name='HandoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('image', models.ImageField(upload_to='vehicle_handovers/%Y/%m/%d/', verbose_name='Foto')),
                ('photo_type', models.CharField(choices=[('360_front', '360° - Vorne'), ('360_front_right', '360° - Vorne Rechts'), ('360_right', '360° - Rechts'), ('360_rear_right', '360° - Hinten Rechts'), ('360_rear', '360° - Hinten'), ('360_rear_left', '360° - Hinten Links'), ('360_left', '360° - Links'), ('360_front_left', '360° - Vorne Links'), ('interior_front', 'Innenraum - Vorne'), ('interior_rear', 'Innenraum - Hinten'), ('cargo_area', 'Laderaum/Mannschaftsraum'), ('dashboard', 'Armaturenbrett'), ('defect', 'Schaden/Mangel'), ('equipment', 'Ausrüstung/Beladung'), ('other', 'Sonstiges')], default='other', max_length=50, verbose_name='Foto-Typ')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='GPS Breitengrad')),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='GPS Längengrad')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('related_defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='vehicle_handover.handoverdefect', verbose_name='Zugehöriger Mangel')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='vehicle_handover.vehiclehandover', verbose_name='Übergabe')),
            ],
            options={
                'verbose_name': 'Übergabe-Foto',
                'verbose_name_plural': 'Übergabe-Fotos',
                'db_table': 'vehicle_handover_photo',
                'ordering': ['order', 'photo_type', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='handoverdefect',
            name='handover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='vehicle_handover.vehiclehandover', verbose_name='Übergabe'),
        ),
        migrations.CreateModel(
            name='HandoverChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('item_name', models.CharField(max_length=200, verbose_name='Gegenstand/Prüfpunkt')),
                ('category', models.CharField(blank=True, help_text='z.B. "Fahrzeugpapiere", "Beladung", "Sicherheitsausrüstung"', max_length=100, verbose_name='Kategorie')),
                ('checked', models.BooleanField(default=False, verbose_name='Geprüft')),
                ('present', models.BooleanField(default=True, help_text='Ist der Gegenstand vorhanden?', verbose_name='Vorhanden')),
                ('functional', models.BooleanField(default=True, help_text='Ist der Gegenstand funktionsfähig?', verbose_name='Funktionsfähig')),
                ('serial_number', models.CharField(blank=True, help_text='Falls zutreffend', max_length=100, verbose_name='Seriennummer/ID')),
                ('notes', models.TextField(blank=True, verbose_name='Bemerkungen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='vehicle_handover.vehiclehandover', verbose_name='Übergabe')),
            ],
            options={
                'verbose_name': 'Checklisten-Eintrag',
                'verbose_name_plural': 'Checklisten-Einträge',
                'db_table': 'vehicle_handover_checklist',
                'ordering': ['order', 'category', 'item_name'],
            },
        ),
        migrations.AddIndex(
            model_name='vehiclehandover',
            index=models.Index(fields=['-handover_date'], name='vehicle_han_handove_6d5982_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclehandover',
            index=models.Index(fields=['vehicle', '-handover_date'], name='vehicle_han_vehicle_86254f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclehandover',
            index=models.Index(fields=['handover_to', '-handover_date'], name='vehicle_han_handove_1480a9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclehandover',
            index=models.Index(fields=['status'], name='vehicle_han_status_c5d0fb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclehandover',
            index=models.Index(fields=['handover_type'], name='vehicle_han_handove_18dfb9_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverphoto',
            index=models.Index(fields=['handover', 'order'], name='vehicle_han_handove_204962_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverphoto',
            index=models.Index(fields=['photo_type'], name='vehicle_han_photo_t_d2154d_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverdefect',
            index=models.Index(fields=['handover'], name='vehicle_han_handove_031d80_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverdefect',
            index=models.Index(fields=['severity'], name='vehicle_han_severit_07be08_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverdefect',
            index=models.Index(fields=['repaired'], name='vehicle_han_repaire_489695_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverdefect',
            index=models.Index(fields=['affects_operational_readiness'], name='vehicle_han_affects_24e54f_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverchecklist',
            index=models.Index(fields=['handover', 'order'], name='vehicle_han_handove_1541aa_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverchecklist',
            index=models.Index(fields=['category'], name='vehicle_han_categor_c7301c_idx'),
        ),
    ]
