# Generated by Django 5.0.14 on 2025-10-21 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='z.B. "LF 10/6 Standard" oder "HLF 20 Vollausstattung"', max_length=200, verbose_name='Template-Name')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Informationen zu diesem Template', verbose_name='Beschreibung')),
                ('vehicle_types', models.JSONField(default=list, help_text='Liste von vehicle_type codes, z.B. ["lf", "dlk", "hlf"]', verbose_name='Fahrzeugtypen')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Templates werden nicht zur Auswahl angezeigt', verbose_name='Aktiv')),
                ('is_default', models.BooleanField(default=False, help_text='Wird automatisch vorausgewählt für zugeordnete Fahrzeugtypen', verbose_name='Standard-Template')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Anzahl der Übergaben mit diesem Template', verbose_name='Verwendungen')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt verwendet')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Checklisten-Vorlage',
                'verbose_name_plural': 'Checklisten-Vorlagen',
                'db_table': 'vehicle_handover_checklist_template',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='checklist_template',
            field=models.ForeignKey(blank=True, help_text='Verwendete Checklisten-Vorlage für diese Übergabe', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='vehicle_handover.checklisttemplate', verbose_name='Checklisten-Vorlage'),
        ),
        migrations.CreateModel(
            name='ChecklistTemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. "Fahrzeugpapiere", "Beladung", "Sicherheitsausrüstung"', max_length=200, verbose_name='Kategorie-Name')),
                ('order', models.PositiveIntegerField(default=0, help_text='Sortierung der Kategorien (niedrigere Zahlen zuerst)', verbose_name='Reihenfolge')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='vehicle_handover.checklisttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template-Kategorie',
                'verbose_name_plural': 'Template-Kategorien',
                'db_table': 'vehicle_handover_template_category',
                'ordering': ['template', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. "Fahrzeugschein", "Atemschutzgerät"', max_length=200, verbose_name='Item-Name')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('requires_serial', models.BooleanField(default=False, help_text='Bei der Übergabe muss eine Seriennummer erfasst werden', verbose_name='Seriennummer erforderlich')),
                ('expected_quantity', models.PositiveIntegerField(default=1, help_text='Wie viele Stück sollten vorhanden sein?', verbose_name='Erwartete Anzahl')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Informationen zu diesem Item', verbose_name='Beschreibung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vehicle_handover.checklisttemplatecategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Template-Item',
                'verbose_name_plural': 'Template-Items',
                'db_table': 'vehicle_handover_template_item',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['is_active'], name='vehicle_han_is_acti_2550b6_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['is_default'], name='vehicle_han_is_defa_13517e_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['-usage_count'], name='vehicle_han_usage_c_01d673_idx'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplatecategory',
            index=models.Index(fields=['template', 'order'], name='vehicle_han_templat_99dc92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='checklisttemplatecategory',
            unique_together={('template', 'name')},
        ),
        migrations.AddIndex(
            model_name='checklisttemplateitem',
            index=models.Index(fields=['category', 'order'], name='vehicle_han_categor_198da5_idx'),
        ),
    ]
