# Generated by Django 5.0.14 on 2025-10-21 18:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0002_checklisttemplate_vehiclehandover_checklist_template_and_more'),
        ('vehicles', '0005_vehicle_actual_retirement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle360Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('photo_type', models.CharField(choices=[('front', 'Vorne (Fahrerkabine)'), ('rear', 'Hinten (Laderaum/Mannschaftsraum)')], max_length=20, verbose_name='Foto-Typ')),
                ('image', models.ImageField(help_text='Equirectangular/Spherical Foto (z.B. von Insta360)', upload_to='vehicles/360/%Y/%m/', verbose_name='360° Foto')),
                ('title', models.CharField(help_text='z.B. "HLF 20 - Mannschaftsraum"', max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, help_text='Wird dieses Foto aktuell verwendet?', verbose_name='Aktiv')),
                ('captured_date', models.DateTimeField(blank=True, help_text='Wann wurde das Foto aufgenommen?', null=True, verbose_name='Aufnahmedatum')),
                ('resolution_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Auflösung Breite (px)')),
                ('resolution_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Auflösung Höhe (px)')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_360', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': '360° Fahrzeug-Foto',
                'verbose_name_plural': '360° Fahrzeug-Fotos',
                'db_table': 'vehicle_360_photo',
                'ordering': ['vehicle', 'photo_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle360Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(help_text='z.B. "Schublade 1 - Sanitätsmaterial"', max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, help_text='Was befindet sich in diesem Bereich?', verbose_name='Beschreibung')),
                ('pitch', models.FloatField(help_text='Vertikale Position: -90° (unten) bis +90° (oben)', validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Pitch (Neigung)')),
                ('yaw', models.FloatField(help_text='Horizontale Position: -180° (links) bis +180° (rechts)', validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Yaw (Drehung)')),
                ('hotspot_type', models.CharField(choices=[('checklist', 'Checkliste'), ('images', 'Bildergalerie'), ('info', 'Information'), ('mixed', 'Gemischt (Bilder + Checkliste)')], default='checklist', max_length=20, verbose_name='Hotspot-Typ')),
                ('icon', models.CharField(choices=[('drawer', '🗄️ Schublade'), ('cabinet', '🚪 Schrank'), ('box', '📦 Box/Kiste'), ('bag', '🎒 Tasche'), ('toolbox', '🧰 Werkzeugkasten'), ('medical', '🏥 Sanitätsmaterial'), ('fire', '🧯 Brandschutz'), ('equipment', '⚙️ Ausrüstung'), ('marker', '📍 Markierung')], default='marker', max_length=20, verbose_name='Icon')),
                ('color', models.CharField(choices=[('blue', 'Blau'), ('green', 'Grün'), ('red', 'Rot'), ('yellow', 'Gelb'), ('orange', 'Orange'), ('purple', 'Lila'), ('white', 'Weiß')], default='blue', max_length=20, verbose_name='Farbe')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('checklist_template', models.ForeignKey(blank=True, help_text='Verknüpfte Checkliste für diesen Bereich', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspots_360', to='vehicle_handover.checklisttemplate', verbose_name='Checklisten-Vorlage')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('photo_360', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='vehicle_handover.vehicle360photo', verbose_name='360° Foto')),
            ],
            options={
                'verbose_name': '360° Hotspot',
                'verbose_name_plural': '360° Hotspots',
                'db_table': 'vehicle_360_hotspot',
                'ordering': ['photo_360', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HotspotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('image', models.ImageField(upload_to='vehicles/hotspots/%Y/%m/', verbose_name='Bild')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Bildunterschrift')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicle_handover.vehicle360hotspot', verbose_name='Hotspot')),
            ],
            options={
                'verbose_name': 'Hotspot-Bild',
                'verbose_name_plural': 'Hotspot-Bilder',
                'db_table': 'vehicle_360_hotspot_image',
                'ordering': ['hotspot', 'order', 'created_at'],
                'indexes': [models.Index(fields=['hotspot', 'order'], name='vehicle_360_hotspot_ca4279_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle360photo',
            index=models.Index(fields=['vehicle', 'is_active'], name='vehicle_360_vehicle_5f3176_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle360photo',
            index=models.Index(fields=['photo_type'], name='vehicle_360_photo_t_1c7f7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle360photo',
            unique_together={('vehicle', 'photo_type')},
        ),
        migrations.AddIndex(
            model_name='vehicle360hotspot',
            index=models.Index(fields=['photo_360', 'is_active'], name='vehicle_360_photo_3_9f1756_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle360hotspot',
            index=models.Index(fields=['hotspot_type'], name='vehicle_360_hotspot_05f5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle360hotspot',
            index=models.Index(fields=['checklist_template'], name='vehicle_360_checkli_26306d_idx'),
        ),
    ]
