# Generated by Django 5.0.14 on 2025-10-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0003_vehicle360photo_vehicle360hotspot_hotspotimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handoverphoto',
            name='photo_type',
            field=models.CharField(choices=[('defect', 'Schaden'), ('dirt', 'Verunreinigung'), ('exterior', 'Außenansicht'), ('interior', 'Innenraum'), ('cargo_area', 'Laderaum/Mannschaftsraum'), ('dashboard', 'Armaturenbrett'), ('equipment', 'Ausrüstung/Beladung'), ('other', 'Sonstiges')], default='other', max_length=50, verbose_name='Kategorie'),
        ),
    ]
