# Generated by Django 5.0.14 on 2025-11-03 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0004_update_photo_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclehandover',
            name='cleanliness_exterior',
        ),
        migrations.RemoveField(
            model_name='vehiclehandover',
            name='cleanliness_interior',
        ),
        migrations.AlterField(
            model_name='vehiclehandover',
            name='fuel_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tankfüllung in Prozent (optional)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tankfüllung (%)'),
        ),
    ]
