# Generated by Django 5.0.14 on 2026-01-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0005_remove_cleanliness_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle360hotspot',
            name='custom_checklist',
            field=models.JSONField(blank=True, default=list, help_text='Liste von Checklistenpunkten: [{"name": "Artikel", "required": true}, ...]', verbose_name='Benutzerdefinierte Checkliste'),
        ),
    ]
