# Generated by Django 5.0.14 on 2026-02-13 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0007_checklist_template_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclehandover',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Melder (E-Mail)'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Melder (Name)'),
        ),
        migrations.AlterField(
            model_name='vehiclehandover',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_handover_vehiclehandover_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AlterField(
            model_name='vehiclehandover',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_handover_vehiclehandover_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von'),
        ),
    ]
