# Generated by Django 5.0.14 on 2026-02-20 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0008_vehiclehandover_reporter_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclehandover',
            name='reporter_email',
        ),
        migrations.RemoveField(
            model_name='vehiclehandover',
            name='reporter_name',
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='reporter_first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Melder (Vorname)'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='reporter_last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Melder (Nachname)'),
        ),
    ]
