# Generated by Django 5.0.14 on 2026-03-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_add_watch_division'),
        ('vehicle_handover', '0009_reporter_first_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclehandover',
            name='handover_to',
            field=models.ForeignKey(blank=True, help_text='Bei öffentlichen Übergaben leer (Melder-Daten werden stattdessen verwendet)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_handovers_received', to='personnel.person', verbose_name='Übergeben an'),
        ),
    ]
