# Generated by Django 5.2.15 on 2026-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0010_allow_null_handover_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='allows_photo',
            field=models.BooleanField(default=False, help_text='Bei der Übergabe kann optional ein Foto zu diesem Item hochgeladen werden', verbose_name='Foto möglich'),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='allows_photo',
            field=models.BooleanField(default=False, help_text='Zu diesem Item kann ein Foto hochgeladen werden', verbose_name='Foto möglich'),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='photo',
            field=models.ImageField(blank=True, help_text='Optionales Foto zu diesem Prüfpunkt', null=True, upload_to='vehicle_handovers/checklist/%Y/%m/%d/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='vehiclehandover',
            name='pdf_archive',
            field=models.FileField(blank=True, help_text='Bei Abschluss automatisch erzeugtes Übergabeprotokoll', null=True, upload_to='vehicle_handovers/protocols/%Y/%m/', verbose_name='Archiviertes Protokoll (PDF)'),
        ),
    ]
