# Generated by Django 5.2.15 on 2026-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_handover', '0011_checklisttemplateitem_allows_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplatecategory',
            name='inspection_interval',
            field=models.CharField(choices=[('none', 'Keine'), ('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich')], default='none', help_text='Gilt für alle Items dieser Kategorie (Items können abweichen)', max_length=10, verbose_name='Prüfintervall'),
        ),
        migrations.AddField(
            model_name='checklisttemplateitem',
            name='inspection_interval',
            field=models.CharField(choices=[('inherit', 'Von Kategorie übernehmen'), ('none', 'Keine'), ('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich')], default='inherit', help_text='Standard: von der Kategorie übernehmen', max_length=10, verbose_name='Prüfintervall'),
        ),
        migrations.AddField(
            model_name='handoverchecklist',
            name='inspection_interval',
            field=models.CharField(choices=[('none', 'Keine'), ('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich')], default='none', max_length=10, verbose_name='Prüfintervall'),
        ),
    ]
