# Generated by Django 5.2.15 on 2026-07-09 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_populate_device_type_categories'),
        ('vehicle_handover', '0012_checklisttemplatecategory_inspection_interval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverEquipmentInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('equipment_label', models.CharField(help_text='Kopie der Gerätebezeichnung zum Zeitpunkt der Prüfung', max_length=250, verbose_name='Bezeichnung')),
                ('inspected_at', models.DateTimeField(verbose_name='Geprüft am')),
                ('inspector_name', models.CharField(help_text='Name des Prüfers (Melder der Übergabe bzw. angemeldeter Benutzer)', max_length=200, verbose_name='Prüfer')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung fällig am')),
                ('device_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handover_inspections', to='equipment.equipmentdeviceinstance', verbose_name='Gerät (Instanz)')),
                ('equipment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='handover_inspections', to='equipment.equipmentitem', verbose_name='Ausrüstungsstück')),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_inspections', to='vehicle_handover.vehiclehandover', verbose_name='Übergabe')),
            ],
            options={
                'verbose_name': 'Ausrüstungsprüfung (Übergabe)',
                'verbose_name_plural': 'Ausrüstungsprüfungen (Übergabe)',
                'db_table': 'vehicle_handover_equipment_inspection',
                'ordering': ['-inspected_at'],
                'indexes': [models.Index(fields=['handover'], name='vehicle_han_handove_5f9434_idx'), models.Index(fields=['device_instance'], name='vehicle_han_device__0b8028_idx'), models.Index(fields=['equipment_item'], name='vehicle_han_equipme_1f675a_idx')],
            },
        ),
    ]
