# Generated by Django 5.2.15 on 2026-07-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect_management', '0007_defectcategorymodel_responsible_users'),
        ('vehicle_handover', '0013_handoverequipmentinspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverdefect',
            name='exported_defect',
            field=models.ForeignKey(blank=True, help_text='Automatisch erzeugter Eintrag im Mängelwesen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='defect_management.defect', verbose_name='Mängelwesen-Eintrag'),
        ),
    ]
