# Generated by Django 5.0.14 on 2025-10-03 13:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Farbe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_default', models.BooleanField(default=False, help_text='Wird automatisch geladen wenn kein Profil ausgewählt', verbose_name='Standard-Profil')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Monitor-Profil',
                'verbose_name_plural': 'Monitor-Profile',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('theme', models.CharField(choices=[('light', 'Hell'), ('dark', 'Dunkel'), ('auto', 'Automatisch')], default='light', max_length=10, verbose_name='Theme')),
                ('columns', models.PositiveSmallIntegerField(default=12, help_text='Grid-Spalten (Bootstrap 12-Spalten-System)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Spalten')),
                ('auto_refresh', models.BooleanField(default=True, verbose_name='Auto-Refresh')),
                ('refresh_interval', models.PositiveIntegerField(default=30, help_text='Mindestens 5 Sekunden', validators=[django.core.validators.MinValueValidator(5)], verbose_name='Refresh-Intervall (Sekunden)')),
                ('fullscreen_default', models.BooleanField(default=False, verbose_name='Vollbild als Standard')),
                ('hide_header', models.BooleanField(default=False, verbose_name='Header ausblenden')),
                ('hide_sidebar', models.BooleanField(default=False, verbose_name='Sidebar ausblenden')),
                ('is_public', models.BooleanField(default=False, verbose_name='Öffentlich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Aufrufe')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt angesehen')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Berechtigte Benutzer')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='info_monitors.monitorprofile', verbose_name='Profil')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['profile', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI-Anzeige'), ('chart', 'Diagramm'), ('table', 'Tabelle'), ('list', 'Liste'), ('map', 'Karte'), ('gauge', 'Tachometer'), ('progress', 'Fortschrittsbalken'), ('counter', 'Zähler'), ('alert', 'Warnungen'), ('clock', 'Uhr'), ('weather', 'Wetter'), ('custom', 'Benutzerdefiniert')], max_length=20, verbose_name='Widget-Typ')),
                ('row', models.PositiveIntegerField(default=0, help_text='Zeile im Grid (0 = erste Zeile)', verbose_name='Zeile')),
                ('column', models.PositiveIntegerField(default=0, help_text='Spalte im Grid (0-11)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Spalte')),
                ('width', models.CharField(choices=[('1', 'Klein (1/12)'), ('2', 'Mittel (2/12)'), ('3', 'Groß (3/12)'), ('4', 'Extra Groß (4/12)'), ('12', 'Vollbreite (12/12)')], default='3', help_text='Anzahl Spalten (12-Spalten-Grid)', max_length=2, verbose_name='Breite')),
                ('height', models.PositiveIntegerField(default=300, help_text='Höhe in Pixel', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Höhe (px)')),
                ('data_source', models.TextField(blank=True, help_text='SQL-Query oder API-Endpoint für Daten', verbose_name='Datenquelle')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Widget-spezifische Konfiguration (JSON)', verbose_name='Konfiguration')),
                ('chart_type', models.CharField(blank=True, choices=[('line', 'Liniendiagramm'), ('bar', 'Balkendiagramm'), ('pie', 'Kreisdiagramm'), ('doughnut', 'Ring-Diagramm'), ('area', 'Flächendiagramm'), ('radar', 'Radar-Diagramm'), ('scatter', 'Streudiagramm')], help_text='Nur für Chart-Widgets', max_length=20, verbose_name='Diagramm-Typ')),
                ('background_color', models.CharField(blank=True, max_length=20, verbose_name='Hintergrundfarbe')),
                ('text_color', models.CharField(blank=True, max_length=20, verbose_name='Textfarbe')),
                ('border_color', models.CharField(blank=True, max_length=20, verbose_name='Rahmenfarbe')),
                ('auto_refresh', models.BooleanField(default=True, verbose_name='Auto-Refresh')),
                ('refresh_interval', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Refresh-Intervall (Sekunden)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Anzeigereihenfolge')),
                ('cached_data', models.JSONField(blank=True, default=dict, verbose_name='Gecachte Daten')),
                ('last_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt aktualisiert')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='info_monitors.dashboard', verbose_name='Dashboard')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reporting.kpi', verbose_name='KPI')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
                'ordering': ['dashboard', 'row', 'column', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='WidgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('condition', models.CharField(choices=[('greater', 'Größer als'), ('less', 'Kleiner als'), ('equal', 'Gleich'), ('not_equal', 'Ungleich'), ('between', 'Zwischen')], max_length=20, verbose_name='Bedingung')),
                ('threshold_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Schwellwert')),
                ('threshold_value_max', models.DecimalField(blank=True, decimal_places=2, help_text='Für "Zwischen"-Bedingung', max_digits=12, null=True, verbose_name='Max. Schwellwert')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warnung'), ('error', 'Fehler'), ('critical', 'Kritisch')], default='warning', max_length=20, verbose_name='Schweregrad')),
                ('message', models.TextField(help_text='Alert-Nachricht die angezeigt wird', verbose_name='Nachricht')),
                ('send_notification', models.BooleanField(default=False, verbose_name='Benachrichtigung senden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt ausgelöst')),
                ('trigger_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl Auslösungen')),
                ('notification_users', models.ManyToManyField(blank=True, related_name='widget_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='info_monitors.widget', verbose_name='Widget')),
            ],
            options={
                'verbose_name': 'Widget-Alert',
                'verbose_name_plural': 'Widget-Alerts',
                'ordering': ['widget', '-severity'],
            },
        ),
        migrations.AddIndex(
            model_name='monitorprofile',
            index=models.Index(fields=['is_active', 'display_order'], name='info_monito_is_acti_1c4070_idx'),
        ),
        migrations.AddIndex(
            model_name='monitorprofile',
            index=models.Index(fields=['is_default'], name='info_monito_is_defa_4d9bee_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['profile', 'is_active'], name='info_monito_profile_f7a124_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['is_public'], name='info_monito_is_publ_248cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['display_order'], name='info_monito_display_fe5831_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['dashboard', 'is_active'], name='info_monito_dashboa_ff5760_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['widget_type'], name='info_monito_widget__06c7a1_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['kpi'], name='info_monito_kpi_id_ee8849_idx'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['row', 'column'], name='info_monito_row_7a425e_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetalert',
            index=models.Index(fields=['widget', 'is_active'], name='info_monito_widget__a06ff7_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetalert',
            index=models.Index(fields=['severity'], name='info_monito_severit_efbae1_idx'),
        ),
    ]
