# Generated by Django 5.0.14 on 2025-10-23 17:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='canvas_height',
            field=models.PositiveIntegerField(default=1080, help_text='Höhe des Canvas in Pixel (nur für Canvas-Modus)', validators=[django.core.validators.MinValueValidator(600)], verbose_name='Canvas-Höhe (px)'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='canvas_width',
            field=models.PositiveIntegerField(default=1920, help_text='Breite des Canvas in Pixel (nur für Canvas-Modus)', validators=[django.core.validators.MinValueValidator(800)], verbose_name='Canvas-Breite (px)'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='use_canvas_layout',
            field=models.BooleanField(default=True, help_text='Canvas = freie Positionierung, Grid = 12-Spalten-System', verbose_name='Canvas-Layout verwenden'),
        ),
        migrations.AddField(
            model_name='widget',
            name='canvas_width',
            field=models.PositiveIntegerField(blank=True, default=400, help_text='Breite in Pixel - nur für Canvas-Modus', null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Canvas-Breite (px)'),
        ),
        migrations.AddField(
            model_name='widget',
            name='x_position',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='X-Koordinate in Pixel - nur für Canvas-Modus', null=True, verbose_name='X-Position (px)'),
        ),
        migrations.AddField(
            model_name='widget',
            name='y_position',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Y-Koordinate in Pixel - nur für Canvas-Modus', null=True, verbose_name='Y-Position (px)'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='columns',
            field=models.PositiveSmallIntegerField(default=12, help_text='Grid-Spalten (nur für Grid-Modus)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Spalten'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='column',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Spalte im Grid (0-11) - nur für Grid-Modus', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)], verbose_name='Spalte'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='height',
            field=models.PositiveIntegerField(default=300, help_text='Höhe in Pixel (für beide Modi)', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Höhe (px)'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='row',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Zeile im Grid (0 = erste Zeile) - nur für Grid-Modus', null=True, verbose_name='Zeile'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('kpi', 'KPI-Anzeige'), ('chart', 'Diagramm'), ('table', 'Tabelle'), ('list', 'Liste'), ('map', 'Karte'), ('gauge', 'Tachometer'), ('progress', 'Fortschrittsbalken'), ('counter', 'Zähler'), ('alert', 'Warnungen'), ('clock', 'Uhr'), ('weather', 'Wetter'), ('text', 'Text/Information'), ('pdf', 'PDF-Dokument'), ('announcements', 'Bekanntmachungen'), ('events', 'Termine/Kalender'), ('custom', 'Benutzerdefiniert')], max_length=20, verbose_name='Widget-Typ'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='width',
            field=models.CharField(blank=True, choices=[('1', 'Klein (1/12)'), ('2', 'Mittel (2/12)'), ('3', 'Groß (3/12)'), ('4', 'Extra Groß (4/12)'), ('12', 'Vollbreite (12/12)')], default='3', help_text='Anzahl Spalten (12-Spalten-Grid) - nur für Grid-Modus', max_length=2, verbose_name='Breite'),
        ),
        migrations.CreateModel(
            name='MonitorPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('auto_rotate', models.BooleanField(default=True, verbose_name='Auto-Rotation')),
                ('default_duration', models.PositiveIntegerField(default=60, help_text='Standard-Dauer pro Dashboard', validators=[django.core.validators.MinValueValidator(5)], verbose_name='Standard-Anzeigedauer (Sekunden)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('play_count', models.PositiveIntegerField(default=0, verbose_name='Abspielungen')),
                ('last_played_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt abgespielt')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Monitor-Playlist',
                'verbose_name_plural': 'Monitor-Playlists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Überschreibt Standard-Dauer der Playlist (optional)', null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Anzeigedauer (Sekunden)')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='info_monitors.dashboard', verbose_name='Dashboard')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='info_monitors.monitorplaylist', verbose_name='Playlist')),
            ],
            options={
                'verbose_name': 'Playlist-Eintrag',
                'verbose_name_plural': 'Playlist-Einträge',
                'ordering': ['playlist', 'order'],
            },
        ),
        migrations.AddField(
            model_name='monitorplaylist',
            name='dashboards',
            field=models.ManyToManyField(related_name='playlists', through='info_monitors.PlaylistItem', to='info_monitors.dashboard', verbose_name='Dashboards'),
        ),
        migrations.CreateModel(
            name='MonitorAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='Beschreibender Name (z.B. "Monitor Leitstelle")', max_length=200, verbose_name='Name')),
                ('token', models.CharField(db_index=True, help_text='Eindeutiger Zugriffs-Token', max_length=64, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional: Ablaufdatum des Tokens', null=True, verbose_name='Gültig bis')),
                ('ip_whitelist', models.TextField(blank=True, help_text='Komma-getrennte Liste erlaubter IP-Adressen (leer = alle)', verbose_name='IP-Whitelist')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Optional: Maximale Anzahl Zugriffe', null=True, verbose_name='Max. Verwendungen')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='Verwendungen')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Zuletzt verwendet')),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Letzte IP')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_monitor_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='info_monitors.dashboard', verbose_name='Dashboard')),
            ],
            options={
                'verbose_name': 'Monitor-Zugriffs-Token',
                'verbose_name_plural': 'Monitor-Zugriffs-Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token', 'is_active'], name='info_monito_token_d6d43a_idx'), models.Index(fields=['dashboard', 'is_active'], name='info_monito_dashboa_5c01d3_idx'), models.Index(fields=['expires_at'], name='info_monito_expires_419462_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='playlistitem',
            index=models.Index(fields=['playlist', 'order'], name='info_monito_playlis_3f2bc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistitem',
            unique_together={('playlist', 'dashboard')},
        ),
    ]
