# Generated by Django 5.0.14 on 2025-10-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitors', '0002_dashboard_canvas_height_dashboard_canvas_width_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['profile', 'display_order', 'name'], 'permissions': [('publish_dashboard', 'Kann Dashboards veröffentlichen'), ('view_all_dashboards', 'Kann alle Dashboards sehen'), ('edit_all_dashboards', 'Kann alle Dashboards bearbeiten')], 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.AlterModelOptions(
            name='monitoraccesstoken',
            options={'ordering': ['-created_at'], 'permissions': [('manage_access_tokens', 'Kann Zugriffs-Tokens verwalten'), ('create_access_token', 'Kann Zugriffs-Tokens erstellen'), ('delete_access_token', 'Kann Zugriffs-Tokens löschen')], 'verbose_name': 'Monitor-Zugriffs-Token', 'verbose_name_plural': 'Monitor-Zugriffs-Tokens'},
        ),
        migrations.AlterModelOptions(
            name='monitorplaylist',
            options={'ordering': ['name'], 'permissions': [('manage_playlists', 'Kann Playlists verwalten')], 'verbose_name': 'Monitor-Playlist', 'verbose_name_plural': 'Monitor-Playlists'},
        ),
    ]
