# Generated by Django 5.0.14 on 2025-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitors', '0003_alter_dashboard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF-Datei für PDF-Widgets', null=True, upload_to='info_monitors/pdfs/%Y/%m/', verbose_name='PDF-Datei'),
        ),
    ]
