# Generated by Django 5.2.15 on 2026-09-16 05:31

from django.db import migrations, models
from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    Dashboard = apps.get_model('info_monitors', 'Dashboard')
    used = set()
    for dashboard in Dashboard.objects.order_by('pk'):
        base = slugify(dashboard.name)[:100] or 'monitor'
        slug, n = base, 1
        while slug in used:
            n += 1
            slug = f'{base}-{n}'
        used.add(slug)
        dashboard.slug = slug
        dashboard.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitors', '0004_widget_pdf_file'),
    ]

    operations = [
        # Erst ohne Index/Unique-Constraint anlegen, befüllen, dann eindeutig machen.
        # (Mit db_index=True kollidiert auf PostgreSQL der "_like"-Index beim AlterField.)
        migrations.AddField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(blank=True, db_index=False, help_text='Endung des Vollbild-Links (/monitors/kiosk/<link-name>/); wird aus dem Namen erzeugt', max_length=120, verbose_name='Link-Name'),
        ),
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(blank=True, help_text='Endung des Vollbild-Links (/monitors/kiosk/<link-name>/); wird aus dem Namen erzeugt', max_length=120, unique=True, verbose_name='Link-Name'),
        ),
    ]
