# Generated by Django 5.2.15 on 2026-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_monitors', '0006_dienstplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget_type',
            field=models.CharField(choices=[('kpi', 'KPI-Anzeige'), ('chart', 'Diagramm'), ('table', 'Tabelle'), ('list', 'Liste'), ('map', 'Karte'), ('gauge', 'Tachometer'), ('progress', 'Fortschrittsbalken'), ('counter', 'Zähler'), ('alert', 'Warnungen'), ('clock', 'Uhr'), ('weather', 'Wetter'), ('text', 'Text/Information'), ('pdf', 'PDF-Dokument'), ('announcements', 'Bekanntmachungen'), ('events', 'Termine/Kalender'), ('dienstplan', 'Dienstplan / Führungsdienst'), ('kalender', 'Kalender (Termine-Modul)'), ('custom', 'Benutzerdefiniert')], max_length=20, verbose_name='Widget-Typ'),
        ),
    ]
