# Generated by Django 5.0.14 on 2025-10-03 12:46

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, verbose_name='Kategorie')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(blank=True, help_text='Tailwind/Heroicons Icon-Name', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(blank=True, help_text='Tailwind Color-Class (z.B. blue-500)', max_length=20, verbose_name='Farbe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentcategory', verbose_name='Übergeordnete Kategorie')),
            ],
            options={
                'verbose_name': 'Dokumenten-Kategorie',
                'verbose_name_plural': 'Dokumenten-Kategorien',
                'ordering': ['tree_id', 'lft'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('document_number', models.CharField(blank=True, help_text='Eindeutige Dokumentennummer (z.B. DOC-2025-0001)', max_length=50, unique=True, verbose_name='Dokumentennummer')),
                ('document_type', models.CharField(choices=[('manual', 'Handbuch / Anleitung'), ('certificate', 'Zertifikat / Nachweis'), ('invoice', 'Rechnung'), ('contract', 'Vertrag'), ('protocol', 'Protokoll'), ('report', 'Bericht'), ('form', 'Formular'), ('photo', 'Foto'), ('drawing', 'Zeichnung / Plan'), ('specification', 'Spezifikation'), ('policy', 'Richtlinie / Vorschrift'), ('other', 'Sonstiges')], default='other', max_length=20, verbose_name='Dokumententyp')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('review', 'In Prüfung'), ('approved', 'Freigegeben'), ('active', 'Aktiv'), ('superseded', 'Ersetzt'), ('expired', 'Abgelaufen'), ('archived', 'Archiviert')], default='draft', max_length=20, verbose_name='Status')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'csv', 'zip'])], verbose_name='Datei')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-Type')),
                ('version_number', models.CharField(default='1.0', help_text='z.B. 1.0, 1.2, 2.0', max_length=20, verbose_name='Version')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('tags', models.CharField(blank=True, help_text='Komma-getrennte Schlagwörter für Suche', max_length=500, verbose_name='Schlagwörter')),
                ('author', models.CharField(blank=True, help_text='Externer Autor (z.B. Hersteller)', max_length=200, verbose_name='Autor / Ersteller')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Gültig ab')),
                ('valid_until', models.DateField(blank=True, help_text='Bei Ablauf wird Status auf "Abgelaufen" gesetzt', null=True, verbose_name='Gültig bis')),
                ('review_date', models.DateField(blank=True, help_text='Datum für regelmäßige Überprüfung', null=True, verbose_name='Nächste Prüfung')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archiviert am')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Verknüpftes Objekt ID')),
                ('access_level', models.CharField(choices=[('public', 'Öffentlich'), ('internal', 'Intern'), ('confidential', 'Vertraulich'), ('restricted', 'Eingeschränkt'), ('secret', 'Geheim')], default='internal', max_length=20, verbose_name='Zugriffslevel')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Download-Anzahl')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Aufrufe')),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Zugriff')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Bei eingeschränktem Zugriff', related_name='accessible_documents', to=settings.AUTH_USER_MODEL, verbose_name='Berechtigte Benutzer')),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_documents', to=settings.AUTH_USER_MODEL, verbose_name='Archiviert von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Verknüpfter Typ')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='documents.document', verbose_name='Ersetzt durch')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('review_status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt'), ('revision', 'Überarbeitung erforderlich')], default='pending', max_length=20, verbose_name='Prüfstatus')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='Prüfdatum')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Frist')),
                ('comments', models.TextField(blank=True, verbose_name='Kommentare')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='documents.document', verbose_name='Dokument')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Prüfer')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Dokumenten-Prüfung',
                'verbose_name_plural': 'Dokumenten-Prüfungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('version_number', models.CharField(max_length=20, verbose_name='Versionsnummer')),
                ('change_type', models.CharField(choices=[('major', 'Hauptversion (1.0 → 2.0)'), ('minor', 'Nebenversion (1.0 → 1.1)'), ('patch', 'Korrektur (1.0.0 → 1.0.1)'), ('revision', 'Revision (ohne Versionsnummer)')], default='minor', max_length=20, verbose_name='Änderungstyp')),
                ('file', models.FileField(upload_to='documents/versions/%Y/%m/', verbose_name='Datei')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dateigröße (Bytes)')),
                ('change_summary', models.TextField(help_text='Was wurde in dieser Version geändert?', verbose_name='Änderungszusammenfassung')),
                ('change_details', models.TextField(blank=True, help_text='Detaillierte Beschreibung der Änderungen', verbose_name='Änderungsdetails')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Dokument')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Dokumenten-Version',
                'verbose_name_plural': 'Dokumenten-Versionen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('access_type', models.CharField(choices=[('view', 'Angesehen'), ('download', 'Heruntergeladen'), ('edit', 'Bearbeitet'), ('delete', 'Gelöscht'), ('share', 'Geteilt')], max_length=20, verbose_name='Zugriffstyp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document', verbose_name='Dokument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Dokumenten-Zugriff',
                'verbose_name_plural': 'Dokumenten-Zugriffe',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document', '-created_at'], name='documents_d_documen_022705_idx'), models.Index(fields=['user', '-created_at'], name='documents_d_user_id_1b1347_idx'), models.Index(fields=['access_type', '-created_at'], name='documents_d_access__62f073_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['parent', 'name'], name='documents_d_parent__0a803f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['is_active'], name='documents_d_is_acti_c8e63e_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['tree_id', 'lft'], name='documents_documentcategory8eec'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_number'], name='documents_d_documen_dbcf06_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', '-created_at'], name='documents_d_categor_66efd5_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status', '-created_at'], name='documents_d_status_dead80_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['valid_until'], name='documents_d_valid_u_25bf49_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['review_date'], name='documents_d_review__c879ab_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['related_content_type', 'related_object_id'], name='documents_d_related_f203de_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['access_level'], name='documents_d_access__2eb685_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreview',
            index=models.Index(fields=['document', 'review_status'], name='documents_d_documen_c99f76_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreview',
            index=models.Index(fields=['reviewer', 'review_status'], name='documents_d_reviewe_9ba24f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentreview',
            index=models.Index(fields=['deadline'], name='documents_d_deadlin_34f946_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', '-created_at'], name='documents_d_documen_f780b3_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['change_type'], name='documents_d_change__389544_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
