# Generated by Django 5.0.14 on 2025-10-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_processed',
            field=models.BooleanField(default=False, verbose_name='OCR verarbeitet'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OCR verarbeitet am'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Automatisch extrahierter Text aus PDF/Bildern via OCR', verbose_name='OCR-Text'),
        ),
    ]
