# Generated by Django 5.0.14 on 2025-10-03 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zeitstempel')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('action', models.CharField(choices=[('create', 'Erstellt'), ('update', 'Geändert'), ('delete', 'Gelöscht'), ('view', 'Angesehen'), ('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('export', 'Exportiert'), ('import', 'Importiert'), ('approve', 'Freigegeben'), ('reject', 'Abgelehnt'), ('custom', 'Benutzerdefiniert')], db_index=True, max_length=20, verbose_name='Aktion')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warnung'), ('error', 'Fehler'), ('critical', 'Kritisch'), ('security', 'Sicherheitsrelevant')], db_index=True, default='info', max_length=20, verbose_name='Schweregrad')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objekt-ID')),
                ('object_repr', models.CharField(blank=True, max_length=200, verbose_name='Objekt-Bezeichnung')),
                ('app_label', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='App')),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Model')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('changes', models.JSONField(blank=True, help_text='JSON mit alten und neuen Werten', null=True, verbose_name='Änderungen')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='Zusätzliche Daten')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='Request-Pfad')),
                ('http_method', models.CharField(blank=True, max_length=10, verbose_name='HTTP-Methode')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Objekttyp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Audit-Log',
                'verbose_name_plural': 'Audit-Logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_all_logs', 'Kann alle Audit-Logs sehen'), ('export_logs', 'Kann Audit-Logs exportieren')],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['severity', '-timestamp'], name='audit_audit_severit_34f2e8_idx'), models.Index(fields=['app_label', 'model_name', '-timestamp'], name='audit_audit_app_lab_f1ec38_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
    ]
