# Generated by Django 5.2.15 on 2026-08-04 10:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, help_text='Einleitungstext, der den Teilnehmenden vor der ersten Frage angezeigt wird', verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('closed', 'Geschlossen')], default='draft', max_length=20, verbose_name='Status')),
                ('is_anonymous', models.BooleanField(default=True, help_text='Ja: Die Antworten werden ohne Personenbezug gespeichert. Es wird lediglich getrennt vermerkt, WER teilgenommen hat – nicht WAS er geantwortet hat. Nein: Die Antworten sind der Person zugeordnet und in der Auswertung sichtbar.', verbose_name='Anonyme Umfrage')),
                ('min_responses_for_results', models.PositiveIntegerField(default=5, help_text='Schutz vor Rückschlüssen bei kleinen Gruppen. Solange weniger Antworten vorliegen, bleibt die Auswertung gesperrt. 0 = keine Sperre.', verbose_name='Auswertung erst ab X Antworten')),
                ('start_date', models.DateTimeField(blank=True, help_text='Leer = ab Freischaltung', null=True, verbose_name='Startzeitpunkt')),
                ('end_date', models.DateTimeField(blank=True, help_text='Leer = kein automatisches Ende', null=True, verbose_name='Endzeitpunkt')),
                ('allow_multiple_responses', models.BooleanField(default=False, help_text='Erlaubt es, die Umfrage mehrfach auszufüllen (z.B. für wiederkehrende Meldungen)', verbose_name='Mehrfachteilnahme erlauben')),
                ('show_results_to_participants', models.BooleanField(default=False, help_text='Teilnehmende sehen nach dem Absenden die (aggregierte) Auswertung', verbose_name='Ergebnisse für Teilnehmende sichtbar')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('target_groups', models.ManyToManyField(blank=True, help_text='Nur Mitglieder dieser Rollen dürfen teilnehmen. Leer = alle Benutzer.', related_name='surveys', to='auth.group', verbose_name='Zielgruppe')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Umfrage',
                'verbose_name_plural': 'Umfragen',
                'ordering': ['-created_at'],
                'permissions': [('conduct_survey', 'Kann Umfragen erstellen und auswerten'), ('participate_survey', 'Kann an Umfragen teilnehmen')],
            },
        ),
        migrations.CreateModel(
            name='SurveyParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participated_on', models.DateField(default=django.utils.timezone.localdate, help_text='Bewusst nur das Datum, nicht die Uhrzeit', verbose_name='Teilgenommen am')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='surveys.survey', verbose_name='Umfrage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_participations', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Teilnahme',
                'verbose_name_plural': 'Teilnahmen',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('question_type', models.CharField(choices=[('text', 'Kurztext'), ('textarea', 'Langtext'), ('radio', 'Einzelauswahl'), ('checkbox', 'Mehrfachauswahl'), ('select', 'Dropdown'), ('scale', 'Skala'), ('yesno', 'Ja/Nein'), ('number', 'Zahl'), ('date', 'Datum')], default='text', max_length=20, verbose_name='Fragetyp')),
                ('text', models.CharField(max_length=500, verbose_name='Frage')),
                ('help_text', models.CharField(blank=True, help_text='Optionale Erläuterung unterhalb der Frage', max_length=300, verbose_name='Hilfetext')),
                ('is_required', models.BooleanField(default=True, verbose_name='Pflichtfrage')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Typspezifische Einstellungen (Optionen, Skalenbereich, ...)', verbose_name='Konfiguration')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Umfrage')),
            ],
            options={
                'verbose_name': 'Frage',
                'verbose_name_plural': 'Fragen',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(help_text='Bei anonymen Umfragen bewusst nur tagesgenau gespeichert, damit sich Antworten nicht über den Zeitpunkt einer Person zuordnen lassen.', verbose_name='Abgesendet am')),
                ('is_complete', models.BooleanField(default=True, verbose_name='Vollständig')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.survey', verbose_name='Umfrage')),
                ('user', models.ForeignKey(blank=True, help_text='Bleibt bei anonymen Umfragen leer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='Teilnehmer')),
            ],
            options={
                'verbose_name': 'Antwort',
                'verbose_name_plural': 'Antworten',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, verbose_name='Textantwort')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Zahlenantwort')),
                ('value_date', models.DateField(blank=True, null=True, verbose_name='Datumsantwort')),
                ('value_json', models.JSONField(blank=True, default=list, verbose_name='Mehrfachauswahl')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyquestion', verbose_name='Frage')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.surveyresponse', verbose_name='Fragebogen')),
            ],
            options={
                'verbose_name': 'Einzelantwort',
                'verbose_name_plural': 'Einzelantworten',
                'ordering': ['question__order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['status'], name='surveys_sur_status_88f57b_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyparticipation',
            constraint=models.UniqueConstraint(fields=('survey', 'user'), name='unique_participation_per_survey'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', 'is_complete'], name='surveys_sur_survey__ff1807_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_question'),
        ),
    ]
