# Generated by Django 5.2.15 on 2026-08-04 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='access_mode',
            field=models.CharField(choices=[('login', 'Über Login (Zielgruppe)'), ('token', 'Über Einmal-Links (QR-Zettel)')], default='login', help_text='Login: gemeinsamer Link, Teilnahme über das Benutzerkonto – zeigt an, wer noch fehlt. Einmal-Links: QR-Zettel zum Verteilen, funktioniert ohne Konto.', max_length=20, verbose_name='Zugang'),
        ),
        migrations.AddField(
            model_name='survey',
            name='pdf_intro_text',
            field=models.TextField(blank=True, help_text='Freier Text, der auf jedem ausgedruckten Zettel über dem QR-Code steht', verbose_name='Anschreiben für die QR-Zettel'),
        ),
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Zugangs-Token')),
                ('label', models.CharField(blank=True, help_text="Optionaler Text auf dem Zettel, z.B. 'Zug 1'. Bei anonymen Umfragen hier KEINE Namen eintragen – der Aufdruck wird mit dem Token gespeichert.", max_length=100, verbose_name='Aufdruck')),
                ('is_used', models.BooleanField(default=False, verbose_name='Bereits verwendet')),
                ('used_on', models.DateField(blank=True, help_text='Bewusst nur das Datum, nicht die Uhrzeit', null=True, verbose_name='Verwendet am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='surveys.survey', verbose_name='Umfrage')),
                ('user', models.ForeignKey(blank=True, help_text='Nur bei personalisierten Umfragen erlaubt – siehe Klassen-Docstring', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Zugeordnete Person')),
            ],
            options={
                'verbose_name': 'Zugangs-Link',
                'verbose_name_plural': 'Zugangs-Links',
                'ordering': ['pk'],
                'indexes': [models.Index(fields=['survey', 'is_used'], name='surveys_sur_survey__6cb8f4_idx')],
            },
        ),
    ]
