# Generated by Django 5.2.15 on 2026-08-04 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_survey_access_mode_survey_pdf_intro_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='condition_operator',
            field=models.CharField(blank=True, choices=[('any_of', 'eine der gewählten Antworten'), ('none_of', 'keine der gewählten Antworten')], default='any_of', max_length=10, verbose_name='Bedingung'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='condition_question',
            field=models.ForeignKey(blank=True, help_text='Diese Frage nur anzeigen, wenn die Bezugsfrage passend beantwortet wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='surveys.surveyquestion', verbose_name='Bezugsfrage'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='condition_values',
            field=models.JSONField(blank=True, default=list, help_text='Bei welchen Antworten der Bezugsfrage soll diese Frage erscheinen?', verbose_name='Auslösende Antworten'),
        ),
    ]
