# Generated by Django 5.2.15 on 2026-08-14 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0008_migrate_nip_leuchtturm_to_locations'),
        ('personnel', '0020_add_watch_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('designation', models.CharField(help_text='Interne Bezeichnung, z.B. "Drohne 1" oder "Florian Drohne 01"', max_length=100, verbose_name='Bezeichnung')),
                ('model', models.CharField(help_text='Hersteller und Typ, z.B. "DJI Matrice 30T"', max_length=100, verbose_name='Modell')),
                ('serial_number', models.CharField(help_text='Seriennummer des Herstellers', max_length=100, unique=True, verbose_name='Seriennummer')),
                ('lba_registration_number', models.CharField(blank=True, help_text='Registrierungsnummer beim Luftfahrt-Bundesamt (e-ID des Betreibers/Geräts)', max_length=100, verbose_name='LBA-Registrierungsnummer')),
                ('status', models.CharField(choices=[('einsatzbereit', 'Einsatzbereit'), ('wartung', 'In Wartung / Reparatur'), ('ausser_dienst', 'Außer Dienst')], db_index=True, default='einsatzbereit', max_length=20, verbose_name='Status')),
                ('commissioned_date', models.DateField(blank=True, null=True, verbose_name='In Dienst seit')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_drone_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_drones', to='locations.location', verbose_name='Standort')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_drone_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Drohne',
                'verbose_name_plural': 'Drohnen',
                'ordering': ['designation'],
            },
        ),
        migrations.CreateModel(
            name='DroneLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('pilot_name', models.CharField(blank=True, help_text='Nur ausfüllen, wenn keine Person aus der Personalverwaltung gewählt wurde', max_length=150, verbose_name='Name (extern)')),
                ('license_type', models.CharField(choices=[('a1_a3', 'EU-Kompetenznachweis A1/A3'), ('a2', 'EU-Fernpiloten-Zeugnis A2'), ('sts', 'Standardszenarien STS-01/STS-02')], db_index=True, default='a1_a3', max_length=20, verbose_name='Art des Nachweises')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='Nachweis-/Zeugnisnummer')),
                ('issuing_authority', models.CharField(default='Luftfahrt-Bundesamt (LBA)', max_length=150, verbose_name='Ausgestellt von')),
                ('issued_date', models.DateField(verbose_name='Ausgestellt am')),
                ('expiry_date', models.DateField(db_index=True, help_text='EU-Kompetenznachweise sind in der Regel 5 Jahre gültig', verbose_name='Gültig bis')),
                ('document', models.FileField(blank=True, help_text='Scan oder PDF des Nachweises', null=True, upload_to='iuk/drone_licenses/', verbose_name='Dokument')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('last_reminder_sent', models.DateField(blank=True, help_text='Wird vom automatischen Erinnerungslauf gesetzt', null=True, verbose_name='Letzte Erinnerung')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_dronelicense_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(blank=True, help_text='Person aus der Personalverwaltung – leer lassen für externe Piloten', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_licenses', to='personnel.person', verbose_name='Person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_dronelicense_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Drohnenführerschein',
                'verbose_name_plural': 'Drohnenführerscheine',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('code', models.CharField(help_text='Code, der beim LBA eingegeben wird', max_length=100, unique=True, verbose_name='Gutscheincode')),
                ('issuer', models.CharField(blank=True, help_text='Behörde/Stelle, von der der Gutschein stammt', max_length=150, verbose_name='Ausgegeben von')),
                ('received_date', models.DateField(verbose_name='Erhalten am')),
                ('valid_until', models.DateField(blank=True, help_text='Ablaufdatum des Gutscheins, falls vorhanden', null=True, verbose_name='Gültig bis')),
                ('intended_use', models.CharField(blank=True, choices=[('a1_a3', 'EU-Kompetenznachweis A1/A3'), ('a2', 'EU-Fernpiloten-Zeugnis A2'), ('sts', 'Standardszenarien STS-01/STS-02')], help_text='Für welchen Nachweis ist der Gutschein gedacht?', max_length=20, verbose_name='Verwendungszweck')),
                ('status', models.CharField(choices=[('offen', 'Verfügbar'), ('genutzt', 'Genutzt'), ('verfallen', 'Verfallen')], db_index=True, default='offen', max_length=20, verbose_name='Status')),
                ('used_by_name', models.CharField(blank=True, help_text='Nur ausfüllen, wenn keine Person aus der Personalverwaltung gewählt wurde', max_length=150, verbose_name='Genutzt von (extern)')),
                ('used_at', models.DateField(blank=True, null=True, verbose_name='Genutzt am')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_voucher_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('license', models.ForeignKey(blank=True, help_text='Optional: Nachweis, der mit diesem Gutschein erworben wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='iuk.dronelicense', verbose_name='Zugehöriger Führerschein')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_voucher_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_drone_vouchers', to='personnel.person', verbose_name='Genutzt von')),
            ],
            options={
                'verbose_name': 'Gutscheincode',
                'verbose_name_plural': 'Gutscheincodes',
                'ordering': ['status', '-received_date', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='dronelicense',
            index=models.Index(fields=['expiry_date', 'license_type'], name='iuk_droneli_expiry__cfe4bc_idx'),
        ),
    ]
