# Generated by Django 5.2.15 on 2026-08-19 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuk', '0001_initial'),
        ('personnel', '0020_add_watch_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='assigned_at',
            field=models.DateField(blank=True, null=True, verbose_name='Vergeben am'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Person, die den Gutscheincode erhalten hat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drone_vouchers', to='personnel.person', verbose_name='Vergeben an'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='assigned_to_name',
            field=models.CharField(blank=True, help_text='Nur ausfüllen, wenn keine Person aus der Personalverwaltung gewählt wurde', max_length=150, verbose_name='Vergeben an (extern)'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='intended_use',
            field=models.CharField(blank=True, choices=[('a1_a3', 'EU-Kompetenznachweis A1/A3'), ('a2', 'EU-Fernpiloten-Zeugnis A2'), ('sts', 'Standardszenarien STS-01/STS-02')], help_text='Nachweis, für den der Gutschein eingesetzt werden soll', max_length=20, verbose_name='Für welchen Nachweis'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('offen', 'Verfügbar'), ('vergeben', 'Vergeben'), ('genutzt', 'Genutzt'), ('verfallen', 'Verfallen')], db_index=True, default='offen', max_length=20, verbose_name='Status'),
        ),
    ]
