# Generated by Django 5.2.15 on 2026-08-19 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuk', '0002_voucher_assigned_at_voucher_assigned_to_and_more'),
        ('personnel', '0020_add_watch_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('angelegt', 'Angelegt'), ('importiert', 'Aus CSV importiert'), ('vergeben', 'An Person vergeben'), ('genutzt', 'Eingelöst'), ('geaendert', 'Bearbeitet')], db_index=True, max_length=20, verbose_name='Vorgang')),
                ('person_name', models.CharField(blank=True, max_length=150, verbose_name='Person (extern)')),
                ('license_type', models.CharField(blank=True, choices=[('a1_a3', 'EU-Kompetenznachweis A1/A3'), ('a2', 'EU-Fernpiloten-Zeugnis A2'), ('sts', 'Standardszenarien STS-01/STS-02')], max_length=20, verbose_name='Für welchen Nachweis')),
                ('occurred_on', models.DateField(blank=True, help_text='Fachliches Datum, z.B. Tag der Einlösung', null=True, verbose_name='Vorgangsdatum')),
                ('note', models.TextField(blank=True, verbose_name='Bemerkung')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erfasst am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_voucher_events', to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_voucher_events', to='personnel.person', verbose_name='Person')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='iuk.voucher', verbose_name='Gutschein')),
            ],
            options={
                'verbose_name': 'Gutschein-Vorgang',
                'verbose_name_plural': 'Gutschein-Vorgänge',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
