# Generated by Django 5.2.15 on 2026-08-19 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuk', '0003_voucherevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('category', models.CharField(choices=[('akku', 'Akku'), ('fernsteuerung', 'Fernsteuerung / Controller'), ('kamera', 'Kamera / Sensor'), ('ladegeraet', 'Ladegerät / Netzteil'), ('propeller', 'Propeller / Rotorblätter'), ('speicher', 'Speicherkarte'), ('transport', 'Transportkoffer / Tasche'), ('ersatzteil', 'Ersatzteil'), ('sonstiges', 'Sonstiges')], db_index=True, default='sonstiges', max_length=20, verbose_name='Art')),
                ('name', models.CharField(help_text='z.B. "Akku 1" oder "Smart Controller"', max_length=100, verbose_name='Bezeichnung')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modell / Typ')),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Seriennummer')),
                ('inventory_number', models.CharField(blank=True, max_length=50, verbose_name='Inventarnummer')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('status', models.CharField(choices=[('einsatzbereit', 'Einsatzbereit'), ('wartung', 'In Wartung / Reparatur'), ('ausser_dienst', 'Außer Dienst')], db_index=True, default='einsatzbereit', max_length=20, verbose_name='Status')),
                ('commissioned_date', models.DateField(blank=True, null=True, verbose_name='In Dienst seit')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_droneaccessory_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='iuk.drone', verbose_name='Drohne')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_droneaccessory_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Drohnen-Zubehör',
                'verbose_name_plural': 'Drohnen-Zubehör',
                'ordering': ['category', 'name'],
            },
        ),
    ]
