# Generated by Django 5.2.15 on 2026-08-19 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iuk', '0004_droneaccessory'),
        ('personnel', '0020_add_watch_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('year', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Jahr')),
                ('flight_number', models.PositiveIntegerField(editable=False, help_text='Wird beim Speichern fortlaufend je Jahr vergeben', verbose_name='Flug-Nr.')),
                ('operation_type', models.CharField(choices=[('einsatz', 'Einsatz'), ('uebung', 'Übung'), ('ausbildung', 'Ausbildung')], db_index=True, default='uebung', max_length=20, verbose_name='Einsatz / Übung / Ausbildung')),
                ('operation_number', models.CharField(blank=True, help_text='Pflicht bei Einsätzen', max_length=50, verbose_name='Einsatznummer')),
                ('location', models.CharField(help_text='Startort bzw. Einsatzstelle', max_length=200, verbose_name='Ort (Adresse)')),
                ('pilot_name', models.CharField(blank=True, help_text='Nur ausfüllen, wenn keine Person aus der Personalverwaltung gewählt wurde', max_length=150, verbose_name='Pilot (extern)')),
                ('camera_operator_name', models.CharField(blank=True, max_length=150, verbose_name='Kamerabeobachter (extern)')),
                ('airspace_observer_name', models.CharField(blank=True, max_length=150, verbose_name='Luftraumbeobachter (extern)')),
                ('drone_lead_name', models.CharField(blank=True, max_length=150, verbose_name='Führungskraft Drohne (extern)')),
                ('overall_commander', models.CharField(blank=True, max_length=150, verbose_name='Gesamteinsatzleiter')),
                ('flight_date', models.DateField(db_index=True, verbose_name='Datum')),
                ('takeoff_time', models.TimeField(verbose_name='Start (Uhrzeit)')),
                ('landing_time', models.TimeField(verbose_name='Landung (Uhrzeit)')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Wird aus Start und Landung berechnet, kann überschrieben werden', verbose_name='Flugdauer (Minuten)')),
                ('flight_mode', models.CharField(choices=[('vlos', 'VLOS – in Sichtweite'), ('evlos', 'EVLOS – erweiterte Sichtweite'), ('bvlos', 'BVLOS – außerhalb der Sichtweite')], default='vlos', max_length=10, verbose_name='Flugmodus')),
                ('payload', models.CharField(blank=True, help_text='z.B. Wärmebildkamera, Lautsprecher, Abwurfvorrichtung', max_length=200, verbose_name='Nutzlast')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung Einsatz')),
                ('preflight_check', models.BooleanField(default=False, verbose_name='Vorflugkontrolle durchgeführt')),
                ('postflight_check', models.BooleanField(default=False, verbose_name='Nachflugkontrolle durchgeführt')),
                ('has_incident', models.BooleanField(db_index=True, default=False, verbose_name='Vorkommnisse')),
                ('incident_description', models.TextField(blank=True, verbose_name='Welche Vorkommnisse')),
                ('lba_report', models.CharField(choices=[('nein', 'Nein – nicht meldepflichtig'), ('absturz', 'Ja – Absturz gemeldet'), ('kollision', 'Ja – Kollision gemeldet'), ('sonstiges', 'Ja – sonstiges Vorkommnis gemeldet')], default='nein', max_length=20, verbose_name='Vorkommnis beim LBA gemeldet')),
                ('airspace_observer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_flights_as_observer', to='personnel.person', verbose_name='Luftraumbeobachter')),
                ('camera_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_flights_as_camera', to='personnel.person', verbose_name='Kamerabeobachter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_flightlog_created', to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von')),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='iuk.drone', verbose_name='Drohne')),
                ('drone_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drone_flights_as_lead', to='personnel.person', verbose_name='Führungskraft Drohne')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='drone_flights', to='personnel.person', verbose_name='Pilot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_flightlog_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Flugbucheintrag',
                'verbose_name_plural': 'Flugbuch',
                'ordering': ['-flight_date', '-takeoff_time', '-flight_number'],
            },
        ),
        migrations.CreateModel(
            name='FlightLogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Korrektur / Nachtrag')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erfasst am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iuk_flight_comments', to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='iuk.flightlog', verbose_name='Flugbucheintrag')),
            ],
            options={
                'verbose_name': 'Flugbuch-Kommentar',
                'verbose_name_plural': 'Flugbuch-Kommentare',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='flightlog',
            constraint=models.UniqueConstraint(fields=('year', 'flight_number'), name='iuk_flightlog_unique_number_per_year'),
        ),
    ]
