# Generated by Django 5.0.14 on 2025-10-03 11:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('oil_change', 'Ölwechsel'), ('inspection', 'Inspektion'), ('main_inspection', 'Hauptuntersuchung (HU)'), ('emission_test', 'Abgasuntersuchung (AU)'), ('tire_change', 'Reifenwechsel'), ('brake_service', 'Bremsenwartung'), ('battery_replacement', 'Batteriewechsel'), ('filter_replacement', 'Filterwechsel'), ('belt_replacement', 'Riemenwechsel'), ('repair', 'Reparatur'), ('bodywork', 'Karosseriearbeiten'), ('paint_work', 'Lackierung'), ('washing', 'Fahrzeugwäsche'), ('cleaning', 'Innenreinigung'), ('other', 'Sonstiges')], max_length=30, verbose_name='Service-Typ')),
                ('service_status', models.CharField(choices=[('scheduled', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('waiting_parts', 'Wartet auf Teile'), ('waiting_approval', 'Wartet auf Freigabe'), ('completed', 'Abgeschlossen'), ('cancelled', 'Storniert')], default='scheduled', max_length=20, verbose_name='Status')),
                ('scheduled_date', models.DateField(verbose_name='Geplantes Datum')),
                ('started_date', models.DateField(blank=True, null=True, verbose_name='Beginn')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Abschluss')),
                ('mileage_at_service', models.PositiveIntegerField(help_text='Kilometerstand bei Service-Beginn', verbose_name='Kilometerstand')),
                ('operating_hours_at_service', models.PositiveIntegerField(blank=True, help_text='Betriebsstunden bei Service-Beginn', null=True, verbose_name='Betriebsstunden')),
                ('description', models.TextField(help_text='Detaillierte Beschreibung der durchgeführten Arbeiten', verbose_name='Beschreibung')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Arbeitsstunden')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Arbeitskosten')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wird automatisch aus verwendeten Artikeln berechnet', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Teilekosten')),
                ('external_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='z.B. Fremdwerkstatt, TÜV-Gebühren', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Externe Kosten')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtkosten')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Freigabedatum')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Rechnungsnummer')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='workshop/invoices/', verbose_name='Rechnung')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste von Foto-URLs der Arbeiten', verbose_name='Fotos')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_services', to=settings.AUTH_USER_MODEL, verbose_name='Freigegeben von')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_service_records', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_services', to='personnel.person', verbose_name='Mechaniker/Techniker')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_records', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeug-Serviceeintrag',
                'verbose_name_plural': 'Fahrzeug-Serviceeinträge',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_number', models.CharField(help_text='Eindeutige Artikelnummer', max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestand')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Warnung bei Unterschreitung', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximalbestand')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode/EAN')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR-Code')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/images/', verbose_name='Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('workshop_item_type', models.CharField(choices=[('engine_oil', 'Motoröl'), ('transmission_oil', 'Getriebeöl'), ('hydraulic_oil', 'Hydrauliköl'), ('brake_fluid', 'Bremsflüssigkeit'), ('coolant', 'Kühlflüssigkeit'), ('antifreeze', 'Frostschutzmittel'), ('windshield_washer', 'Scheibenwaschmittel'), ('grease', 'Schmierfett'), ('diesel_fuel', 'Diesel'), ('gasoline', 'Benzin'), ('adblue', 'AdBlue'), ('oil_filter', 'Ölfilter'), ('air_filter', 'Luftfilter'), ('fuel_filter', 'Kraftstofffilter'), ('cabin_filter', 'Innenraumfilter'), ('brake_pads', 'Bremsbeläge'), ('brake_discs', 'Bremsscheiben'), ('spark_plugs', 'Zündkerzen'), ('glow_plugs', 'Glühkerzen'), ('drive_belt', 'Keilriemen'), ('timing_belt', 'Zahnriemen'), ('wiper_blades', 'Scheibenwischerblätter'), ('tire_summer', 'Sommerreifen'), ('tire_winter', 'Winterreifen'), ('tire_allseason', 'Ganzjahresreifen'), ('wheel_rim', 'Felge'), ('wheel_nut', 'Radmutter'), ('valve_cap', 'Ventilkappe'), ('headlight_bulb', 'Scheinwerferbirne'), ('tail_light_bulb', 'Rücklichtbirne'), ('turn_signal_bulb', 'Blinkerbirne'), ('led_unit', 'LED-Einheit'), ('battery', 'Batterie'), ('alternator', 'Lichtmaschine'), ('starter_motor', 'Anlasser'), ('fuse', 'Sicherung'), ('relay', 'Relais'), ('cable', 'Kabel'), ('paint', 'Lack'), ('primer', 'Grundierung'), ('clear_coat', 'Klarlack'), ('body_filler', 'Spachtelmasse'), ('rust_protection', 'Rostschutz'), ('wrench', 'Schraubenschlüssel'), ('socket_set', 'Steckschlüsselsatz'), ('torque_wrench', 'Drehmomentschlüssel'), ('jack', 'Wagenheber'), ('jack_stand', 'Unterstellbock'), ('diagnostic_tool', 'Diagnosegerät'), ('multimeter', 'Multimeter'), ('compressor', 'Kompressor'), ('grinder', 'Schleifgerät'), ('drill', 'Bohrmaschine'), ('car_wash', 'Autowaschmittel'), ('car_wax', 'Autowachs'), ('polish', 'Politur'), ('degreaser', 'Entfetter'), ('brake_cleaner', 'Bremsenreiniger'), ('glass_cleaner', 'Glasreiniger'), ('interior_cleaner', 'Innenraumreiniger'), ('sealant', 'Dichtmittel'), ('adhesive', 'Klebstoff'), ('lubricant_spray', 'Schmierspray'), ('rust_remover', 'Rostlöser'), ('shop_towels', 'Werkstatttücher'), ('gloves', 'Handschuhe'), ('safety_glasses', 'Schutzbrille'), ('ear_protection', 'Gehörschutz'), ('other', 'Sonstiges')], max_length=50, verbose_name='Werkstatt-Artikel-Typ')),
                ('workshop_status', models.CharField(choices=[('in_stock', 'Auf Lager'), ('low_stock', 'Niedriger Bestand'), ('out_of_stock', 'Nicht vorrätig'), ('on_order', 'Bestellt'), ('reserved', 'Reserviert'), ('expired', 'Abgelaufen'), ('defective', 'Defekt')], default='in_stock', max_length=20, verbose_name='Werkstatt-Status')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Herstellerteilenummer')),
                ('oem_number', models.CharField(blank=True, help_text='Original Equipment Manufacturer Nummer', max_length=100, verbose_name='OEM-Nummer')),
                ('viscosity', models.CharField(blank=True, help_text='z.B. 5W-30 für Motoröl', max_length=20, verbose_name='Viskosität')),
                ('specification', models.CharField(blank=True, help_text='z.B. API SN/CF, ACEA C3', max_length=100, verbose_name='Spezifikation')),
                ('shelf_life_months', models.PositiveIntegerField(blank=True, help_text='Maximale Lagerdauer in Monaten', null=True, verbose_name='Haltbarkeit (Monate)')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Produktionsdatum')),
                ('storage_temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Min. Lagertemperatur (°C)')),
                ('storage_temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max. Lagertemperatur (°C)')),
                ('is_hazardous', models.BooleanField(default=False, help_text='Kennzeichnung als Gefahrstoff (z.B. brennbar, ätzend)', verbose_name='Gefahrstoff')),
                ('hazard_symbols', models.CharField(blank=True, help_text='z.B. GHS02 (Flamme), GHS07 (Ausrufezeichen)', max_length=200, verbose_name='Gefahrensymbole')),
                ('safety_data_sheet', models.FileField(blank=True, null=True, upload_to='workshop/sds/', verbose_name='Sicherheitsdatenblatt (SDB)')),
                ('recommended_change_interval_km', models.PositiveIntegerField(blank=True, help_text='Empfohlenes Wechselintervall in Kilometern', null=True, verbose_name='Wechselintervall (km)')),
                ('recommended_change_interval_months', models.PositiveIntegerField(blank=True, help_text='Empfohlenes Wechselintervall in Monaten', null=True, verbose_name='Wechselintervall (Monate)')),
                ('core_charge', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pfandbetrag für Altteilrückgabe', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Pfand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('compatible_vehicles', models.ManyToManyField(blank=True, help_text='Fahrzeuge, für die dieses Teil verwendet werden kann', related_name='compatible_workshop_items', to='vehicles.vehicle', verbose_name='Kompatible Fahrzeuge')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Werkstatt-Artikel',
                'verbose_name_plural': 'Werkstatt-Artikel',
                'ordering': ['workshop_item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('movement_type', models.CharField(choices=[('incoming', 'Wareneingang'), ('outgoing', 'Warenausgang'), ('transfer', 'Umlagerung'), ('inventory', 'Inventur-Korrektur'), ('damage', 'Beschädigung/Schwund'), ('return', 'Rückgabe'), ('disposal', 'Entsorgung')], max_length=20, verbose_name='Bewegungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('reference_number', models.CharField(blank=True, help_text='z.B. Lieferschein-Nr., Bestellnummer', max_length=100, verbose_name='Referenznummer')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Bewegungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('vehicle_mileage', models.PositiveIntegerField(blank=True, help_text='Kilometerstand des Fahrzeugs bei Verwendung', null=True, verbose_name='Kilometerstand')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Chargen-/Batch-Nummer')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Verfallsdatum')),
                ('core_returned', models.BooleanField(default=False, help_text='Altteil wurde zurückgegeben', verbose_name='Pfand zurückgegeben')),
                ('core_return_date', models.DateField(blank=True, null=True, verbose_name='Pfand-Rückgabedatum')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückkosten (EUR)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtkosten (EUR)')),
                ('delivery_note', models.CharField(blank=True, max_length=100, verbose_name='Lieferschein-Nr.')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_outgoing', to='locations.location', verbose_name='Von Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='workshop.workshopitem', verbose_name='Werkstatt-Artikel')),
                ('service_record', models.ForeignKey(blank=True, help_text='Zugehöriger Fahrzeug-Serviceeintrag', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_items', to='workshop.vehicleservicerecord', verbose_name='Serviceeintrag')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_incoming', to='locations.location', verbose_name='Nach Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('vehicle', models.ForeignKey(blank=True, help_text='Fahrzeug, für das der Artikel verwendet wurde', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_movements', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': 'Werkstatt-Lagerbewegung',
                'verbose_name_plural': 'Werkstatt-Lagerbewegungen',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleservicerecord',
            index=models.Index(fields=['vehicle', 'scheduled_date'], name='workshop_ve_vehicle_a18669_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleservicerecord',
            index=models.Index(fields=['service_type', 'service_status'], name='workshop_ve_service_696a04_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleservicerecord',
            index=models.Index(fields=['technician', 'scheduled_date'], name='workshop_ve_technic_33cefd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleservicerecord',
            index=models.Index(fields=['service_status', 'scheduled_date'], name='workshop_ve_service_62218e_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopitem',
            index=models.Index(fields=['workshop_item_type'], name='workshop_wo_worksho_1ecb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopitem',
            index=models.Index(fields=['workshop_status'], name='workshop_wo_worksho_d21ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopitem',
            index=models.Index(fields=['manufacturer_part_number'], name='workshop_wo_manufac_a27ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopitem',
            index=models.Index(fields=['oem_number'], name='workshop_wo_oem_num_978023_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopitem',
            index=models.Index(fields=['is_hazardous'], name='workshop_wo_is_haza_9f2368_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopstockmovement',
            index=models.Index(fields=['item', 'movement_date'], name='workshop_wo_item_id_70107c_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopstockmovement',
            index=models.Index(fields=['vehicle', 'movement_date'], name='workshop_wo_vehicle_e305c5_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopstockmovement',
            index=models.Index(fields=['service_record'], name='workshop_wo_service_507230_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopstockmovement',
            index=models.Index(fields=['movement_type', 'movement_date'], name='workshop_wo_movemen_7d6740_idx'),
        ),
    ]
