# Generated by Django 5.0.14 on 2025-10-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopitem',
            name='unit',
            field=models.CharField(choices=[('Stück', 'Stück'), ('Packung', 'Packung'), ('Karton', 'Karton'), ('Palette', 'Palette'), ('Meter', 'Meter'), ('Zentimeter', 'Zentimeter'), ('Millimeter', 'Millimeter'), ('Liter', 'Liter'), ('Milliliter', 'Milliliter'), ('Kilogramm', 'Kilogramm'), ('Gramm', 'Gramm'), ('Quadratmeter', 'Quadratmeter'), ('Paar', 'Paar'), ('Rolle', 'Rolle'), ('Set', 'Set')], default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit'),
        ),
    ]
