# Generated by Django 5.0.14 on 2025-10-17 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0007_add_organization_membership_and_anniversaries'),
        ('vehicles', '0005_vehicle_actual_retirement_date_and_more'),
        ('workshop', '0003_alter_workshopitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_number', models.CharField(help_text='Eindeutige Nummer für dieses Produkt, z.B. WRK-2025-001', max_length=50, unique=True, verbose_name='Stammdatennummer')),
                ('name', models.CharField(help_text='z.B. Diagnosegerät Bosch KTS 560', max_length=200, verbose_name='Produktname')),
                ('description', models.TextField(blank=True, help_text='Detaillierte Produktbeschreibung', verbose_name='Beschreibung')),
                ('item_type', models.CharField(choices=[], max_length=50, verbose_name='Werkzeug-/Artikeltyp')),
                ('manufacturer', models.CharField(blank=True, help_text='z.B. Bosch, Hazet, Stahlwille', max_length=200, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, help_text='z.B. KTS 560, Drehmomentschlüssel 6123-1', max_length=200, verbose_name='Modell')),
                ('tool_size', models.CharField(blank=True, help_text='z.B. 10-13mm, 1/2 Zoll, M6-M24', max_length=100, verbose_name='Werkzeuggröße')),
                ('torque_range_nm', models.CharField(blank=True, help_text='z.B. 10-210 Nm für Drehmomentschlüssel', max_length=100, verbose_name='Drehmomentbereich (Nm)')),
                ('max_load_kg', models.PositiveIntegerField(blank=True, help_text='Für Wagenheber, Unterstellböcke', null=True, verbose_name='Max. Tragkraft (kg)')),
                ('viscosity', models.CharField(blank=True, help_text='z.B. 5W-30, 10W-40 für Öle', max_length=50, verbose_name='Viskosität')),
                ('specification_standard', models.CharField(blank=True, help_text='z.B. API SN/CF, ACEA C3, DIN 51524', max_length=200, verbose_name='Spezifikation/Norm')),
                ('volume_content', models.CharField(blank=True, help_text='z.B. 5L, 20L, 200L für Betriebsstoffe', max_length=100, verbose_name='Inhalt/Volumen')),
                ('is_hazardous', models.BooleanField(default=False, help_text='Kennzeichnung als Gefahrstoff (z.B. brennbar, ätzend)', verbose_name='Gefahrstoff')),
                ('hazard_symbols', models.CharField(blank=True, help_text='z.B. GHS02 (Flamme), GHS07 (Ausrufezeichen)', max_length=200, verbose_name='Gefahrensymbole')),
                ('shelf_life_months', models.PositiveIntegerField(blank=True, help_text='Maximale Lagerdauer in Monaten', null=True, verbose_name='Haltbarkeit (Monate)')),
                ('storage_temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Min. Lagertemperatur (°C)')),
                ('storage_temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max. Lagertemperatur (°C)')),
                ('requires_calibration', models.BooleanField(default=False, help_text='z.B. für Drehmomentschlüssel, Diagnosegeräte', verbose_name='Kalibrierung erforderlich')),
                ('calibration_interval_months', models.PositiveIntegerField(blank=True, help_text='Drehmomentschlüssel: 12 Monate', null=True, verbose_name='Kalibrierungsintervall (Monate)')),
                ('service_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wartungsintervall (Monate)')),
                ('max_service_life_years', models.PositiveIntegerField(blank=True, help_text='Maximale Nutzungsdauer laut Hersteller', null=True, verbose_name='Max. Nutzungsdauer (Jahre)')),
                ('compatible_vehicle_types', models.JSONField(blank=True, default=list, help_text='Liste der Fahrzeugtypen, z.B. ["PKW", "LKW", "Anhänger"]', verbose_name='Kompatible Fahrzeugtypen')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Durchschnittlicher Einkaufspreis', max_digits=10, null=True, verbose_name='Standardpreis (netto)')),
                ('safety_data_sheet', models.FileField(blank=True, help_text='SDB für Gefahrstoffe', null=True, upload_to='workshop/masters/sds/', verbose_name='Sicherheitsdatenblatt')),
                ('manual_document', models.FileField(blank=True, null=True, upload_to='workshop/masters/manuals/', verbose_name='Bedienungsanleitung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshop/masters/images/', verbose_name='Produktbild')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, help_text='Wird dieses Produkt noch verwendet?', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workshop_masters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Werkstatt-Artikel-Stammdaten',
                'verbose_name_plural': 'Werkstatt-Artikel-Stammdaten',
                'ordering': ['master_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopToolInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Eindeutige Inventarnummer, z.B. WRK-DG-001', max_length=100, unique=True, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(blank=True, help_text='Herstellerseriennummer', max_length=200, verbose_name='Seriennummer')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Herstellungsdatum')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('first_use_date', models.DateField(blank=True, null=True, verbose_name='Erstinbetriebnahme')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='Letzte Kalibrierung')),
                ('next_calibration_date', models.DateField(blank=True, help_text='Drehmomentschlüssel: jährlich', null=True, verbose_name='Nächste Kalibrierung')),
                ('calibration_certificate_number', models.CharField(blank=True, max_length=100, verbose_name='Kalibrierschein-Nr.')),
                ('calibration_status', models.CharField(choices=[('not_required', 'Nicht erforderlich'), ('valid', 'Gültig'), ('due_soon', 'Demnächst fällig'), ('overdue', 'Überfällig')], default='not_required', max_length=20, verbose_name='Kalibrierstatus')),
                ('calibration_certificate', models.FileField(blank=True, upload_to='workshop/tools/calibration/', verbose_name='Kalibrierschein')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('service_log', models.FileField(blank=True, upload_to='workshop/tools/service_logs/', verbose_name='Wartungsprotokoll')),
                ('total_usage_hours', models.DecimalField(decimal_places=2, default=0, help_text='Für elektrische Geräte', max_digits=10, verbose_name='Betriebsstunden')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='Anzahl Einsätze')),
                ('last_use_date', models.DateField(blank=True, null=True, verbose_name='Letzter Einsatz')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('excellent', 'Sehr gut'), ('good', 'Gut'), ('fair', 'Befriedigend'), ('poor', 'Schlecht'), ('defective', 'Defekt')], default='good', max_length=20, verbose_name='Zustand')),
                ('is_operational', models.BooleanField(default=True, help_text='Kann das Werkzeug verwendet werden?', verbose_name='Einsatzbereit')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Zustandsnotizen')),
                ('defects', models.TextField(blank=True, verbose_name='Bekannte Mängel')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Aussonderungsdatum')),
                ('retirement_reason', models.TextField(blank=True, verbose_name='Aussonderungsgrund')),
                ('purchase_price_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Einkaufspreis dieser spezifischen Instanz', max_digits=10, null=True, verbose_name='Tatsächlicher Kaufpreis')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste der Foto-URLs', verbose_name='Fotos')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='workshop/tools/qr_codes/', verbose_name='QR-Code')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='workshop/tools/barcodes/', verbose_name='Barcode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workshop_tools', to='personnel.person', verbose_name='Zugeordnet an Person')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_tools', to='vehicles.vehicle', verbose_name='Zugeordnetes Fahrzeug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workshop_tools', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('last_service_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviced_workshop_tools', to='personnel.person', verbose_name='Letzter Servicetechniker')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_tools', to='locations.location', verbose_name='Lagerort')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_instances', to='workshop.workshopitemmaster', verbose_name='Stammdaten')),
            ],
            options={
                'verbose_name': 'Werkzeug-Instanz',
                'verbose_name_plural': 'Werkzeug-Instanzen',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.AddIndex(
            model_name='workshopitemmaster',
            index=models.Index(fields=['master_number'], name='workshop_wo_master__cc9b0d_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopitemmaster',
            index=models.Index(fields=['item_type'], name='workshop_wo_item_ty_790314_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopitemmaster',
            index=models.Index(fields=['manufacturer'], name='workshop_wo_manufac_adea9e_idx'),
        ),
        migrations.AddIndex(
            model_name='workshopitemmaster',
            index=models.Index(fields=['is_active'], name='workshop_wo_is_acti_7e1e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['inventory_number'], name='workshop_wo_invento_6f4823_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['serial_number'], name='workshop_wo_serial__3e2394_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['master'], name='workshop_wo_master__13cac4_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['location'], name='workshop_wo_locatio_b164fa_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['next_calibration_date'], name='workshop_wo_next_ca_b322ef_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['next_service_date'], name='workshop_wo_next_se_3b7cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['calibration_status'], name='workshop_wo_calibra_377b35_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['is_operational'], name='workshop_wo_is_oper_0c9dec_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['assigned_vehicle'], name='workshop_wo_assigne_ccb75c_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoptoolinstance',
            index=models.Index(fields=['assigned_to'], name='workshop_wo_assigne_3844ab_idx'),
        ),
    ]
