# Generated by Django 5.0.14 on 2025-10-20 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_alter_workshopitem_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Drehmomentschlüssel, Diagnosegerät, Motoröl', max_length=100, unique=True, verbose_name='Werkzeug-/Artikeltyp')),
                ('code', models.CharField(help_text='Eindeutiger Code, z.B. torque_wrench, diagnostic_tool', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('category', models.CharField(blank=True, help_text='z.B. Werkzeug, Betriebsstoffe, Verschleißteile', max_length=50, verbose_name='Kategorie')),
                ('icon', models.CharField(blank=True, help_text='Emoji oder Icon-Klasse', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workshop_tool_types', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Werkzeug-/Artikeltyp',
                'verbose_name_plural': 'Werkzeug-/Artikeltypen',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
    ]
