# Generated by Django 5.0.14 on 2025-10-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_workshoptooltype'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workshopitemmaster',
            new_name='workshop_wo_item_ty_3d05bd_idx',
            old_name='workshop_wo_item_ty_790314_idx',
        ),
        migrations.AlterField(
            model_name='workshopitemmaster',
            name='item_type',
            field=models.ForeignKey(help_text='Wählen Sie den Typ aus der Typenverwaltung', on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='workshop.workshoptooltype', verbose_name='Werkzeug-/Artikeltyp'),
        ),
    ]
