# Generated by Django 5.0.14 on 2025-10-22 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0015_person_show_private_contact_data_and_more'),
        ('workshop', '0007_rename_workshop_wo_item_ty_790314_idx_workshop_wo_item_ty_3d05bd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopInventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(help_text='Wird automatisch generiert, z.B. WS-INV-2025-001', max_length=50, unique=True, verbose_name='Inventur-Nummer')),
                ('title', models.CharField(help_text='z.B. Jahresinventur 2025, Quartalsprüfung Q1', max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('check_type', models.CharField(choices=[('full', 'Vollinventur'), ('partial', 'Teilinventur'), ('spot_check', 'Stichprobe'), ('cycle_count', 'Zykluszählung'), ('annual', 'Jahresinventur')], default='partial', max_length=20, verbose_name='Inventurart')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('counting_complete', 'Zählung abgeschlossen'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='planned', max_length=20, verbose_name='Status')),
                ('scheduled_start_date', models.DateField(verbose_name='Geplanter Start')),
                ('scheduled_end_date', models.DateField(verbose_name='Geplantes Ende')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächlicher Start')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Gesamtanzahl Artikel')),
                ('counted_items', models.PositiveIntegerField(default=0, verbose_name='Gezählte Artikel')),
                ('items_with_discrepancies', models.PositiveIntegerField(default=0, verbose_name='Artikel mit Abweichungen')),
                ('check_tool_condition', models.BooleanField(default=True, help_text='Verschleiß und Beschädigungen kontrollieren', verbose_name='Werkzeugzustand prüfen')),
                ('check_calibration', models.BooleanField(default=True, help_text='Messgeräte auf fällige Kalibrierungen prüfen', verbose_name='Kalibrierung prüfen')),
                ('check_safety_equipment', models.BooleanField(default=True, help_text='PSA und Sicherheitswerkzeuge kontrollieren', verbose_name='Sicherheitsausrüstung prüfen')),
                ('damaged_tools_found', models.PositiveIntegerField(default=0, help_text='Anzahl beschädigter oder verschlissener Werkzeuge', verbose_name='Beschädigte Werkzeuge')),
                ('calibration_due_found', models.PositiveIntegerField(default=0, help_text='Anzahl Messgeräte mit fälliger Kalibrierung', verbose_name='Kalibrierung fällig')),
                ('safety_issues_found', models.PositiveIntegerField(default=0, help_text='Anzahl sicherheitsrelevanter Mängel', verbose_name='Sicherheitsprobleme')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigt am')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workshop_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workshop_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, help_text='Leer = alle Lagerorte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_inventory_checks', to='locations.location', verbose_name='Eingeschränkt auf Lagerort')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_workshop_inventory_checks', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('team_members', models.ManyToManyField(blank=True, related_name='workshop_inventory_checks', to='personnel.person', verbose_name='Team-Mitglieder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_workshop_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Workshop Inventur',
                'verbose_name_plural': 'Workshop Inventuren',
                'ordering': ['-created_at'],
                'permissions': [('approve_workshopinventorycheck', 'Kann Workshop-Inventur genehmigen')],
            },
        ),
        migrations.CreateModel(
            name='WorkshopInventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Artikelbezeichnung')),
                ('item_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer')),
                ('inventory_number', models.CharField(blank=True, max_length=100, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Seriennummer')),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Soll-Menge')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ist-Menge')),
                ('variance_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Differenz')),
                ('is_counted', models.BooleanField(default=False, verbose_name='Gezählt')),
                ('has_discrepancy', models.BooleanField(default=False, verbose_name='Abweichung vorhanden')),
                ('counted_date', models.DateTimeField(blank=True, null=True, verbose_name='Gezählt am')),
                ('item_type', models.CharField(blank=True, max_length=50, verbose_name='Artikel-Typ')),
                ('condition', models.CharField(blank=True, max_length=20, verbose_name='Zustand')),
                ('is_damaged', models.BooleanField(default=False, verbose_name='Beschädigt')),
                ('damage_description', models.TextField(blank=True, verbose_name='Schadensbeschreibung')),
                ('last_calibration_date', models.DateField(blank=True, null=True, verbose_name='Letzte Kalibrierung')),
                ('next_calibration_date', models.DateField(blank=True, null=True, verbose_name='Nächste Kalibrierung')),
                ('calibration_due', models.BooleanField(default=False, verbose_name='Kalibrierung fällig')),
                ('is_safety_equipment', models.BooleanField(default=False, verbose_name='Sicherheitsausrüstung')),
                ('has_safety_issue', models.BooleanField(default=False, verbose_name='Sicherheitsproblem')),
                ('safety_issue_description', models.TextField(blank=True, verbose_name='Sicherheitsproblem Beschreibung')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_workshop_items', to='personnel.person', verbose_name='Gezählt von')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.workshopinventorycheck', verbose_name='Inventur')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_inventory_items', to='locations.location', verbose_name='Lagerort')),
                ('workshop_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='workshop.workshopitem', verbose_name='Material/Teil')),
                ('workshop_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='workshop.workshoptoolinstance', verbose_name='Werkzeug')),
            ],
            options={
                'verbose_name': 'Workshop Inventur-Position',
                'verbose_name_plural': 'Workshop Inventur-Positionen',
                'ordering': ['item_name', 'inventory_number'],
            },
        ),
    ]
