# Generated by Django 5.0.14 on 2025-10-03 10:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='z.B. LF 10/6, RTW 1', max_length=200, verbose_name='Fahrzeugname')),
                ('vehicle_type', models.CharField(choices=[('fire_truck', 'Löschfahrzeug'), ('command', 'Kommandowagen'), ('ambulance', 'Rettungswagen'), ('ladder', 'Drehleiter'), ('special', 'Sonderfahrzeug'), ('trailer', 'Anhänger'), ('boat', 'Boot'), ('utility', 'Mannschaftstransporter'), ('other', 'Sonstiges')], default='fire_truck', max_length=20, verbose_name='Fahrzeugtyp')),
                ('call_sign', models.CharField(help_text='z.B. Florian Musterstadt 10/1', max_length=50, unique=True, verbose_name='Funkrufname')),
                ('license_plate', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Ungültiges deutsches Kennzeichen-Format', regex='^[A-ZÄÖÜ]{1,3}-[A-Z]{1,2}\\s?\\d{1,4}[EH]?$')], verbose_name='Kennzeichen')),
                ('manufacturer', models.CharField(blank=True, help_text='z.B. MAN, Mercedes-Benz, Iveco', max_length=100, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modell')),
                ('year_of_manufacture', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baujahr')),
                ('vin', models.CharField(blank=True, help_text='17-stellige FIN', max_length=17, verbose_name='Fahrzeug-Identifikationsnummer (FIN/VIN)')),
                ('engine_number', models.CharField(blank=True, max_length=50, verbose_name='Motornummer')),
                ('fuel_type', models.CharField(blank=True, help_text='z.B. Diesel, Benzin, Elektro', max_length=50, verbose_name='Kraftstoffart')),
                ('current_mileage', models.PositiveIntegerField(default=0, verbose_name='Aktueller Kilometerstand')),
                ('status', models.CharField(choices=[('operational', 'Einsatzbereit'), ('in_use', 'Im Einsatz'), ('maintenance', 'In Wartung'), ('repair', 'In Reparatur'), ('out_of_service', 'Außer Dienst'), ('reserved', 'Reserviert')], default='operational', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, help_text='Ist das Fahrzeug im aktiven Bestand?', verbose_name='Aktiv')),
                ('is_mobile_storage', models.BooleanField(default=False, help_text='Fahrzeug kann Inventar-Items zugeordnet bekommen', verbose_name='Als Mobiles Lager nutzen')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Hauptuntersuchung (HU)')),
                ('next_safety_check_date', models.DateField(blank=True, null=True, verbose_name='Nächste Sicherheitsprüfung (UVV)')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, verbose_name='Versicherungspolice')),
                ('insurance_expires', models.DateField(blank=True, null=True, verbose_name='Versicherung gültig bis')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/', verbose_name='Fahrzeugfoto')),
                ('vehicle_documents', models.FileField(blank=True, help_text='Fahrzeugschein, Bedienungsanleitung, etc.', null=True, upload_to='vehicles/documents/', verbose_name='Fahrzeugdokumente')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('home_location', models.ForeignKey(blank=True, help_text='Feste Wache/Gerätehaus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stationed_vehicles', to='locations.location', verbose_name='Heimatstandort')),
                ('mobile_storage_location', models.OneToOneField(blank=True, help_text='Automatisch erstellte Location für Fahrzeug-Inventar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_vehicle', to='locations.location', verbose_name='Mobile Location')),
                ('responsible_person', models.ForeignKey(blank=True, help_text='Fahrzeugwart/Gerätewart', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_vehicles', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Fahrzeug',
                'verbose_name_plural': 'Fahrzeuge',
                'ordering': ['call_sign'],
            },
        ),
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('inspection_type', models.CharField(choices=[('hu', 'Hauptuntersuchung (HU)'), ('uvv', 'Unfallverhütungsvorschrift (UVV)'), ('maintenance', 'Wartung'), ('repair', 'Reparatur'), ('damage', 'Schadenserfassung'), ('other', 'Sonstiges')], max_length=20, verbose_name='Prüfungstyp')),
                ('inspection_date', models.DateField(verbose_name='Prüfungsdatum')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung fällig am')),
                ('status', models.CharField(choices=[('passed', 'Bestanden'), ('passed_defects', 'Bestanden mit Mängeln'), ('failed', 'Nicht bestanden'), ('in_progress', 'In Bearbeitung'), ('scheduled', 'Geplant')], default='in_progress', max_length=20, verbose_name='Status')),
                ('organization', models.CharField(blank=True, help_text='z.B. TÜV, DEKRA, Werkstatt', max_length=200, verbose_name='Prüforganisation')),
                ('mileage_at_inspection', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kilometerstand bei Prüfung')),
                ('findings', models.TextField(blank=True, verbose_name='Feststellungen/Mängel')),
                ('repairs_needed', models.TextField(blank=True, verbose_name='Erforderliche Reparaturen')),
                ('repairs_completed', models.BooleanField(default=False, verbose_name='Reparaturen durchgeführt')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kosten (EUR)')),
                ('inspection_report', models.FileField(blank=True, null=True, upload_to='vehicles/inspections/', verbose_name='Prüfbericht')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_inspections', to='personnel.person', verbose_name='Prüfer/Techniker')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vehicles.vehicle', verbose_name='Fahrzeug')),
            ],
            options={
                'verbose_name': 'Fahrzeugprüfung',
                'verbose_name_plural': 'Fahrzeugprüfungen',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['call_sign'], name='vehicles_ve_call_si_dee800_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_plate'], name='vehicles_ve_license_907c55_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status'], name='vehicles_ve_status_f71f77_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='vehicles_ve_is_acti_53dbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['next_inspection_date'], name='vehicles_ve_next_in_36b6da_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['vehicle', 'inspection_type'], name='vehicles_ve_vehicle_149610_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['inspection_date'], name='vehicles_ve_inspect_13f5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinspection',
            index=models.Index(fields=['next_inspection_date'], name='vehicles_ve_next_in_0037e8_idx'),
        ),
    ]
