# Generated by Django 5.2.7 on 2025-10-09 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Hersteller')),
                ('country', models.CharField(blank=True, help_text='z.B. Deutschland, USA', max_length=100, verbose_name='Land')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Fahrzeughersteller',
                'verbose_name_plural': 'Fahrzeughersteller',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Betriebsstunden'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.vehiclemanufacturer', verbose_name='Hersteller'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modellname')),
                ('vehicle_type', models.CharField(blank=True, choices=[('fire_truck', 'Löschfahrzeug'), ('command', 'Kommandowagen'), ('ambulance', 'Rettungswagen'), ('ladder', 'Drehleiter'), ('special', 'Sonderfahrzeug'), ('trailer', 'Anhänger'), ('boat', 'Boot'), ('utility', 'Mannschaftstransporter'), ('other', 'Sonstiges')], help_text='Standard-Fahrzeugtyp für dieses Modell', max_length=20, verbose_name='Standardtyp')),
                ('year_from', models.PositiveIntegerField(blank=True, help_text='Erster Produktionsjahr', null=True, verbose_name='Baujahr von')),
                ('year_to', models.PositiveIntegerField(blank=True, help_text='Letztes Produktionsjahr (leer = aktuell)', null=True, verbose_name='Baujahr bis')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclemanufacturer', verbose_name='Hersteller')),
            ],
            options={
                'verbose_name': 'Fahrzeugmodell',
                'verbose_name_plural': 'Fahrzeugmodelle',
                'ordering': ['manufacturer__name', 'name'],
                'unique_together': {('manufacturer', 'name')},
            },
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='vehicles.vehiclemodel', verbose_name='Modell'),
        ),
    ]
