# Generated by Django 5.0.14 on 2025-10-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclemanufacturer_vehicle_engine_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='address_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Straße und Hausnummer'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Kontakt-E-Mail-Adresse', max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='contact_mobile',
            field=models.CharField(blank=True, help_text='Mobilnummer des Ansprechpartners', max_length=50, verbose_name='Mobiltelefon'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Name des Ansprechpartners', max_length=200, verbose_name='Ansprechpartner'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Telefonnummer für Rückfragen', max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='parts_department_phone',
            field=models.CharField(blank=True, help_text='Telefon Ersatzteilbestellung', max_length=50, verbose_name='Ersatzteil-Abteilung'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='service_email',
            field=models.EmailField(blank=True, help_text='E-Mail für Serviceanfragen', max_length=254, verbose_name='Service-E-Mail'),
        ),
        migrations.AddField(
            model_name='vehiclemanufacturer',
            name='support_hotline',
            field=models.CharField(blank=True, help_text='Technischer Support / Notfall-Hotline', max_length=50, verbose_name='Support-Hotline'),
        ),
    ]
