# Generated by Django 5.0.14 on 2025-10-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehiclemanufacturer_address_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='call_sign',
            field=models.CharField(blank=True, help_text='z.B. Florian Musterstadt 10/1', max_length=50, unique=True, verbose_name='Funkrufname'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, help_text='z.B. LF 10/6, RTW 1', max_length=200, verbose_name='Fahrzeugname'),
        ),
    ]
