# Generated by Django 5.0.14 on 2025-10-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_call_sign_alter_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='actual_retirement_date',
            field=models.DateField(blank=True, help_text='Tatsächliches Datum der Außerdienststellung', null=True, verbose_name='Tatsächliche Außerdienststellung'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='commissioning_date',
            field=models.DateField(blank=True, help_text='Datum der Indienststellung', null=True, verbose_name='Indienststellung'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='planned_retirement_date',
            field=models.DateField(blank=True, help_text='Geplantes Datum der Außerdienststellung', null=True, verbose_name='Geplante Außerdienststellung'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='replacement_vehicle',
            field=models.ForeignKey(blank=True, help_text='Fahrzeug das dieses ersetzt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_vehicles', to='vehicles.vehicle', verbose_name='Nachfolgefahrzeug'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='retirement_reason',
            field=models.TextField(blank=True, help_text='z.B. Alter, Wirtschaftlichkeit, Beschädigung', verbose_name='Grund der Außerdienststellung'),
        ),
    ]
