# Generated by Django 5.0.14 on 2025-10-29 18:11

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def migrate_manufacturers_to_suppliers(apps, schema_editor):
    """
    Migriert alle VehicleManufacturer zu Supplier
    und aktualisiert die ForeignKeys in Vehicle und VehicleModel
    """
    VehicleManufacturer = apps.get_model('vehicles', 'VehicleManufacturer')
    Supplier = apps.get_model('inventory_base', 'Supplier')
    Vehicle = apps.get_model('vehicles', 'Vehicle')
    VehicleModel = apps.get_model('vehicles', 'VehicleModel')
    User = apps.get_model('core', 'User')

    # Hole den ersten Admin-User für created_by/updated_by
    admin_user = User.objects.filter(is_superuser=True).first()
    if not admin_user:
        admin_user = User.objects.first()

    if not admin_user:
        print("⚠ Warnung: Kein User gefunden, überspringe Migration")
        return

    # Mapping: VehicleManufacturer.id -> Supplier.id
    manufacturer_to_supplier = {}

    # 1. Alle VehicleManufacturer zu Supplier kopieren
    for vm in VehicleManufacturer.objects.all():
        # Generiere eine eindeutige Lieferantennummer
        base_number = f"VH-{slugify(vm.name)[:20]}"
        supplier_number = base_number
        counter = 1

        # Prüfe auf Duplikate
        while Supplier.objects.filter(supplier_number=supplier_number).exists():
            supplier_number = f"{base_number}-{counter}"
            counter += 1

        # Erstelle neuen Supplier aus VehicleManufacturer
        supplier = Supplier.objects.create(
            name=vm.name,
            supplier_number=supplier_number,
            country=vm.country or '',
            website=vm.website or '',
            contact_person=vm.contact_person or '',
            email=vm.contact_email or '',
            phone=vm.contact_phone or '',
            mobile=vm.contact_mobile or '',
            street=vm.address_street or '',
            postal_code=vm.address_postal_code or '',
            city=vm.address_city or '',
            support_hotline=vm.support_hotline or '',
            parts_department_phone=vm.parts_department_phone or '',
            service_email=vm.service_email or '',
            notes=vm.notes or '',
            is_active=vm.is_active,
            created_by=admin_user,
            updated_by=admin_user,
        )

        # Mapping speichern
        manufacturer_to_supplier[vm.id] = supplier.id

        print(f"✓ Migriert: {vm.name} → Supplier #{supplier.supplier_number}")

    # 2. Vehicle ForeignKeys aktualisieren
    for vehicle in Vehicle.objects.all():
        if vehicle.manufacturer_id and vehicle.manufacturer_id in manufacturer_to_supplier:
            vehicle.manufacturer_id = manufacturer_to_supplier[vehicle.manufacturer_id]
            vehicle.save(update_fields=['manufacturer_id'])

    # 3. VehicleModel ForeignKeys aktualisieren
    for model in VehicleModel.objects.all():
        if model.manufacturer_id and model.manufacturer_id in manufacturer_to_supplier:
            model.manufacturer_id = manufacturer_to_supplier[model.manufacturer_id]
            model.save(update_fields=['manufacturer_id'])

    print(f"\n✓ Migration abgeschlossen: {len(manufacturer_to_supplier)} Hersteller migriert")


def reverse_migration(apps, schema_editor):
    """
    Rückgängig machen ist schwierig, da wir Supplier nicht einfach löschen können
    (sie könnten auch von anderen Modulen verwendet werden)
    """
    print("Warnung: Reverse-Migration nicht vollständig implementiert")
    print("Supplier-Einträge werden NICHT gelöscht (könnten von anderen Modulen genutzt werden)")


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_base', '0002_add_vehicle_fields_to_supplier'),
        ('vehicles', '0005_vehicle_actual_retirement_date_and_more'),
    ]

    operations = [
        # Erst Datenmigration
        migrations.RunPython(
            migrate_manufacturers_to_suppliers,
            reverse_migration
        ),

        # Dann FK-Felder ändern
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={'is_active': True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='vehicles',
                to='inventory_base.supplier',
                verbose_name='Hersteller'
            ),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='manufacturer',
            field=models.ForeignKey(
                limit_choices_to={'is_active': True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='vehicle_models',
                to='inventory_base.supplier',
                verbose_name='Hersteller'
            ),
        ),
    ]
