# Generated by Django 5.0.14 on 2025-10-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_migrate_to_supplier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleManufacturer',
        ),
    ]
