# Generated by Django 5.0.14 on 2026-02-10 13:10

from django.db import migrations


def create_vehicle_locations(apps, schema_editor):
    """Erstellt Location-Einträge für alle aktiven Fahrzeuge ohne Lagerort."""
    from locations.models import Location, LocationType

    Vehicle = apps.get_model('vehicles', 'Vehicle')

    for vehicle in Vehicle.objects.filter(is_active=True):
        if Location.objects.filter(linked_vehicle_id=vehicle.pk).exists():
            continue

        code = f"FZG-{vehicle.license_plate}".replace(' ', '-')
        if Location.objects.filter(code=code).exists():
            code = f"FZG-{vehicle.pk}-{vehicle.license_plate}".replace(' ', '-')

        # Echtes MPTT-Model verwenden, damit lft/rgt/tree_id korrekt gesetzt werden
        Location.objects.create(
            name=vehicle.name,
            code=code,
            location_type=LocationType.VEHICLE,
            linked_vehicle_id=vehicle.pk,
            is_active=True,
            description=f"Mobiler Lagerort: {vehicle.call_sign} ({vehicle.license_plate})",
            created_by_id=vehicle.created_by_id,
            updated_by_id=vehicle.updated_by_id,
        )


def remove_vehicle_locations(apps, schema_editor):
    """Reverse: Entfernt auto-erstellte Fahrzeug-Lagerorte."""
    from locations.models import Location
    Location.objects.filter(
        location_type='vehicle',
        code__startswith='FZG-',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_cleanup_vehicle_type'),
        ('locations', '0006_location_linked_vehicle'),
    ]

    operations = [
        migrations.RunPython(create_vehicle_locations, remove_vehicle_locations),
    ]
