# Generated by Django 5.0.14 on 2026-02-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_auto_create_vehicle_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='rubrik',
            field=models.CharField(blank=True, choices=[('bs', 'Brandschutz (BS)'), ('rd', 'Rettungsdienst (RD)')], db_index=True, help_text='BS = Brandschutz, RD = Rettungsdienst', max_length=10, verbose_name='Rubrik'),
        ),
    ]
