# Generated by Django 5.0.14 on 2026-02-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_vehicle_rubrik_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='rubrik',
            field=models.CharField(choices=[('bs', 'Brandschutz (BS)'), ('rd', 'Rettungsdienst (RD)'), ('ks', 'Katastrophenschutz (KS)')], db_index=True, default='', help_text='BS = Brandschutz, RD = Rettungsdienst, KS = Katastrophenschutz', max_length=10, verbose_name='Rubrik'),
        ),
    ]
