# Generated by Django 5.0.14 on 2026-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_alter_vehicle_rubrik'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='bereich',
            field=models.CharField(blank=True, choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], default='', help_text='Nur bei Rubrik Katastrophenschutz: Bund, Land oder Kommune', max_length=30, verbose_name='Bereich (KatS)'),
        ),
    ]
