# Generated by Django 5.2.15 on 2026-07-13 12:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_base', '0003_category_module'),
        ('locations', '0008_migrate_nip_leuchtturm_to_locations'),
        ('personnel', '0020_add_watch_division'),
        ('vehicles', '0014_vehicle_bereich'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSignAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('call_sign', models.CharField(help_text='z.B. Florian Musterstadt 10/1', max_length=50, verbose_name='Funkrufname')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Gültig ab')),
                ('valid_to', models.DateField(blank=True, help_text='Leer = aktuell gültig', null=True, verbose_name='Gültig bis')),
                ('reason', models.CharField(blank=True, help_text='z.B. "Fahrzeug in der Werkstatt", "Ersatzbeschaffung"', max_length=200, verbose_name='Grund')),
            ],
            options={
                'verbose_name': 'Funkrufnamen-Zuordnung',
                'verbose_name_plural': 'Funkrufnamen-Zuordnungen',
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['license_plate'], 'verbose_name': 'Fahrzeug', 'verbose_name_plural': 'Fahrzeuge'},
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='call_sign',
            field=models.CharField(blank=True, default='', help_text='z.B. Florian Musterstadt 10/1', max_length=50, verbose_name='Funkrufname'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('call_sign', ''), _negated=True), fields=('call_sign',), name='unique_call_sign_when_set'),
        ),
        migrations.AddField(
            model_name='callsignassignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles_callsignassignment_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von'),
        ),
        migrations.AddField(
            model_name='callsignassignment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles_callsignassignment_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von'),
        ),
        migrations.AddField(
            model_name='callsignassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sign_assignments', to='vehicles.vehicle', verbose_name='Fahrzeug'),
        ),
        migrations.AddIndex(
            model_name='callsignassignment',
            index=models.Index(fields=['call_sign'], name='vehicles_ca_call_si_4ad757_idx'),
        ),
        migrations.AddIndex(
            model_name='callsignassignment',
            index=models.Index(fields=['vehicle'], name='vehicles_ca_vehicle_ae3377_idx'),
        ),
        migrations.AddIndex(
            model_name='callsignassignment',
            index=models.Index(fields=['valid_to'], name='vehicles_ca_valid_t_fc9f29_idx'),
        ),
        migrations.AddConstraint(
            model_name='callsignassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('call_sign',), name='unique_active_call_sign'),
        ),
        migrations.AddConstraint(
            model_name='callsignassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_to__isnull', True)), fields=('vehicle',), name='unique_active_call_sign_per_vehicle'),
        ),
    ]
