# Generated by Django 5.0.14 on 2025-10-03 10:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_number', models.CharField(help_text='Eindeutige Artikelnummer', max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Hersteller-Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestand')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Warnung bei Unterschreitung', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximalbestand')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode/EAN')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR-Code')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/images/', verbose_name='Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('clothing_type', models.CharField(choices=[('jacket', 'Jacke'), ('pants', 'Hose'), ('overall', 'Overall/Kombi'), ('shirt', 'Hemd/Shirt'), ('underwear', 'Unterwäsche'), ('shoes', 'Schuhe'), ('boots', 'Stiefel'), ('gloves', 'Handschuhe'), ('helmet', 'Helm'), ('vest', 'Weste'), ('coat', 'Mantel'), ('hat', 'Kopfbedeckung'), ('protective', 'Schutzausrüstung'), ('uniform', 'Uniform'), ('other', 'Sonstiges')], max_length=20, verbose_name='Kleidungstyp')),
                ('size', models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('xxxxl', 'XXXXL'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('s36', 'Schuh 36'), ('s37', 'Schuh 37'), ('s38', 'Schuh 38'), ('s39', 'Schuh 39'), ('s40', 'Schuh 40'), ('s41', 'Schuh 41'), ('s42', 'Schuh 42'), ('s43', 'Schuh 43'), ('s44', 'Schuh 44'), ('s45', 'Schuh 45'), ('s46', 'Schuh 46'), ('s47', 'Schuh 47'), ('s48', 'Schuh 48'), ('other', 'Andere')], max_length=10, verbose_name='Größe')),
                ('gender', models.CharField(choices=[('unisex', 'Unisex'), ('male', 'Herren'), ('female', 'Damen')], default='unisex', max_length=10, verbose_name='Schnitt')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Farbe')),
                ('material', models.CharField(blank=True, help_text='z.B. "Nomex", "Gore-Tex", "Baumwolle"', max_length=200, verbose_name='Material')),
                ('is_psa', models.BooleanField(default=False, help_text='Unterliegt PSA-Verordnung', verbose_name='Persönliche Schutzausrüstung (PSA)')),
                ('protection_level', models.CharField(choices=[('none', 'Keine PSA'), ('basic', 'Basisschutz'), ('enhanced', 'Erhöhter Schutz'), ('high', 'Hoher Schutz'), ('specialist', 'Spezialschutz')], default='none', max_length=20, verbose_name='Schutzlevel')),
                ('norm_standard', models.CharField(blank=True, help_text='z.B. "EN 469", "EN ISO 20471"', max_length=100, verbose_name='Norm/Standard')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Zertifizierungsnummer')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Zertifizierungsdatum')),
                ('certification_expires', models.DateField(blank=True, null=True, verbose_name='Zertifizierung läuft ab')),
                ('max_usage_years', models.PositiveIntegerField(blank=True, help_text='Maximale Nutzungsdauer laut Hersteller', null=True, verbose_name='Max. Nutzungsdauer (Jahre)')),
                ('requires_inspection', models.BooleanField(default=False, help_text='Regelmäßige Prüfung erforderlich', verbose_name='Prüfpflicht')),
                ('inspection_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prüfintervall (Monate)')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('washing_instructions', models.TextField(blank=True, verbose_name='Waschanleitung')),
                ('max_washing_cycles', models.PositiveIntegerField(blank=True, help_text='Maximale Anzahl Waschvorgänge laut Hersteller', null=True, verbose_name='Max. Waschzyklen')),
                ('current_washing_cycles', models.PositiveIntegerField(default=0, help_text='Anzahl bisheriger Waschvorgänge', verbose_name='Aktuelle Waschzyklen')),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Zugeordnet am')),
                ('is_personal_issue', models.BooleanField(default=False, help_text='Wurde persönlich ausgegeben und nicht Poolware', verbose_name='Persönliche Ausgabe')),
                ('has_name_tag', models.BooleanField(default=False, verbose_name='Namensschildversehen')),
                ('reflective_strips', models.BooleanField(default=False, verbose_name='Reflektierende Streifen')),
                ('special_features', models.TextField(blank=True, help_text='z.B. "Verstärkte Knie", "Futter herausnehmbar"', verbose_name='Besondere Merkmale')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Person der dieses Kleidungsstück zugeordnet ist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clothing', to='personnel.person', verbose_name='Zugeordnet an')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Kleidungsstück',
                'verbose_name_plural': 'Kleidungsstücke',
                'ordering': ['clothing_type', 'size'],
            },
        ),
        migrations.CreateModel(
            name='ClothingSizeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_type', models.CharField(choices=[('jacket', 'Jacke'), ('pants', 'Hose'), ('overall', 'Overall/Kombi'), ('shirt', 'Hemd/Shirt'), ('underwear', 'Unterwäsche'), ('shoes', 'Schuhe'), ('boots', 'Stiefel'), ('gloves', 'Handschuhe'), ('helmet', 'Helm'), ('vest', 'Weste'), ('coat', 'Mantel'), ('hat', 'Kopfbedeckung'), ('protective', 'Schutzausrüstung'), ('uniform', 'Uniform'), ('other', 'Sonstiges')], max_length=20, verbose_name='Kleidungstyp')),
                ('size', models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('xxxxl', 'XXXXL'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('s36', 'Schuh 36'), ('s37', 'Schuh 37'), ('s38', 'Schuh 38'), ('s39', 'Schuh 39'), ('s40', 'Schuh 40'), ('s41', 'Schuh 41'), ('s42', 'Schuh 42'), ('s43', 'Schuh 43'), ('s44', 'Schuh 44'), ('s45', 'Schuh 45'), ('s46', 'Schuh 46'), ('s47', 'Schuh 47'), ('s48', 'Schuh 48'), ('other', 'Andere')], max_length=10, verbose_name='Größe')),
                ('notes', models.TextField(blank=True, help_text='z.B. "Bevorzugt weite Passform"', verbose_name='Notizen')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_sizes', to='personnel.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Größenzuordnung',
                'verbose_name_plural': 'Größenzuordnungen',
                'ordering': ['person', 'clothing_type'],
            },
        ),
        migrations.CreateModel(
            name='ClothingStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('movement_type', models.CharField(choices=[('incoming', 'Wareneingang'), ('outgoing', 'Warenausgang'), ('transfer', 'Umlagerung'), ('inventory', 'Inventur-Korrektur'), ('damage', 'Beschädigung/Schwund'), ('return', 'Rückgabe'), ('disposal', 'Entsorgung')], max_length=20, verbose_name='Bewegungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('reference_number', models.CharField(blank=True, help_text='z.B. Lieferschein-Nr., Bestellnummer', max_length=100, verbose_name='Referenznummer')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Bewegungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('return_reason', models.CharField(blank=True, help_text='z.B. "Größe passt nicht", "Beschädigt", "Person ausgeschieden"', max_length=200, verbose_name='Rückgabegrund')),
                ('return_condition_notes', models.TextField(blank=True, verbose_name='Zustandsnotizen bei Rückgabe')),
                ('cleaned_before_return', models.BooleanField(default=False, verbose_name='Gereinigt vor Rückgabe')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückkosten (EUR)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtkosten (EUR)')),
                ('delivery_note', models.CharField(blank=True, max_length=100, verbose_name='Lieferschein-Nr.')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_outgoing', to='locations.location', verbose_name='Von Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='clothing.clothingitem', verbose_name='Kleidungsstück')),
                ('person', models.ForeignKey(blank=True, help_text='Person die das Kleidungsstück erhält/zurückgibt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_movements', to='personnel.person', verbose_name='Person')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_incoming', to='locations.location', verbose_name='Nach Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Lagerbewegung',
                'verbose_name_plural': 'Lagerbewegungen',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['clothing_type', 'size'], name='clothing_cl_clothin_51d657_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['is_psa'], name='clothing_cl_is_psa_9ef357_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['assigned_to'], name='clothing_cl_assigne_63f25b_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingitem',
            index=models.Index(fields=['next_inspection_date'], name='clothing_cl_next_in_43709d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clothingsizeassignment',
            unique_together={('person', 'clothing_type')},
        ),
        migrations.AddIndex(
            model_name='clothingstockmovement',
            index=models.Index(fields=['item', '-movement_date'], name='clothing_cl_item_id_62f252_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingstockmovement',
            index=models.Index(fields=['person', '-movement_date'], name='clothing_cl_person__0e3e07_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingstockmovement',
            index=models.Index(fields=['movement_type', '-movement_date'], name='clothing_cl_movemen_b3b04e_idx'),
        ),
    ]
