# Generated by Django 5.0.14 on 2025-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_alter_clothingitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='manual_document',
            field=models.FileField(blank=True, help_text='PDF oder Bild-Datei (wird automatisch per OCR durchsuchbar gemacht)', null=True, upload_to='clothing/manuals/', verbose_name='Handbuch / Pflegeanleitung'),
        ),
    ]
