# Generated by Django 5.0.14 on 2025-11-17 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_clothinginventorycheck_clothinginventorycheckitem'),
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0017_person_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='z.B. "Hupfjacke TEXPORT Fire Twin", "Poloshirt Feuerwehr"', max_length=255, verbose_name='Produktname')),
                ('clothing_type', models.CharField(choices=[('jacket', 'Jacke'), ('pants', 'Hose'), ('overall', 'Overall/Kombi'), ('shirt', 'Hemd/Shirt'), ('underwear', 'Unterwäsche'), ('shoes', 'Schuhe'), ('boots', 'Stiefel'), ('gloves', 'Handschuhe'), ('helmet', 'Helm'), ('vest', 'Weste'), ('coat', 'Mantel'), ('hat', 'Kopfbedeckung'), ('protective', 'Schutzausrüstung'), ('uniform', 'Uniform'), ('other', 'Sonstiges')], max_length=20, verbose_name='Kleidungstyp')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Modellnummer/Artikelnummer')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('material', models.CharField(blank=True, help_text='z.B. "Nomex", "Gore-Tex", "100% Baumwolle"', max_length=200, verbose_name='Material')),
                ('is_psa', models.BooleanField(default=False, verbose_name='Persönliche Schutzausrüstung (PSA)')),
                ('protection_level', models.CharField(choices=[('none', 'Keine PSA'), ('basic', 'Basisschutz'), ('enhanced', 'Erhöhter Schutz'), ('high', 'Hoher Schutz'), ('specialist', 'Spezialschutz')], default='none', max_length=20, verbose_name='Schutzlevel')),
                ('norm_standard', models.CharField(blank=True, help_text='z.B. "EN 469", "EN ISO 20471"', max_length=100, verbose_name='Norm/Standard')),
                ('max_usage_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max. Nutzungsdauer (Jahre)')),
                ('max_washing_cycles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max. Waschzyklen')),
                ('washing_instructions', models.TextField(blank=True, verbose_name='Waschanleitung/Pflegehinweise')),
                ('requires_inspection', models.BooleanField(default=False, verbose_name='Prüfpflicht')),
                ('inspection_interval_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Prüfintervall (Monate)')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stückpreis (EUR)')),
                ('manual_document', models.FileField(blank=True, null=True, upload_to='clothing/masters/manuals/', verbose_name='Handbuch/Datenblatt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clothing/masters/images/', verbose_name='Produktbild')),
                ('special_features', models.TextField(blank=True, help_text='z.B. "Verstärkte Knie", "Herausnehmbares Futter"', verbose_name='Besondere Merkmale')),
                ('available_sizes', models.JSONField(blank=True, default=list, help_text='Liste der verfügbaren Größen', verbose_name='Verfügbare Größen')),
                ('available_colors', models.JSONField(blank=True, default=list, help_text='Liste der verfügbaren Farben', verbose_name='Verfügbare Farben')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='clothing.clothingcategory', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Kleidungs-Stammdaten',
                'verbose_name_plural': 'Kleidungs-Stammdaten',
                'ordering': ['category', 'clothing_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingItemInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('inventory_number', models.CharField(help_text='Eindeutige Inventarnummer, z.B. "CLO-0001"', max_length=50, unique=True, verbose_name='Inventarnummer')),
                ('size', models.CharField(choices=[('xxs', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL'), ('xxxl', 'XXXL'), ('xxxxl', 'XXXXL'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('44', '44'), ('46', '46'), ('48', '48'), ('50', '50'), ('52', '52'), ('54', '54'), ('56', '56'), ('58', '58'), ('60', '60'), ('s36', 'Schuh 36'), ('s37', 'Schuh 37'), ('s38', 'Schuh 38'), ('s39', 'Schuh 39'), ('s40', 'Schuh 40'), ('s41', 'Schuh 41'), ('s42', 'Schuh 42'), ('s43', 'Schuh 43'), ('s44', 'Schuh 44'), ('s45', 'Schuh 45'), ('s46', 'Schuh 46'), ('s47', 'Schuh 47'), ('s48', 'Schuh 48'), ('other', 'Andere')], max_length=10, verbose_name='Größe')),
                ('gender', models.CharField(choices=[('unisex', 'Unisex'), ('male', 'Herren'), ('female', 'Damen')], default='unisex', max_length=10, verbose_name='Schnitt')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Farbe')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Zugeordnet am')),
                ('is_personal_issue', models.BooleanField(default=False, verbose_name='Persönliche Ausgabe')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Zertifizierungsnummer')),
                ('certification_date', models.DateField(blank=True, null=True, verbose_name='Zertifizierungsdatum')),
                ('certification_expires', models.DateField(blank=True, null=True, verbose_name='Zertifizierung läuft ab')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Kaufdatum')),
                ('first_use_date', models.DateField(blank=True, null=True, verbose_name='Erstverwendung')),
                ('current_washing_cycles', models.PositiveIntegerField(default=0, verbose_name='Aktuelle Waschzyklen')),
                ('last_washing_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wäsche')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('has_name_tag', models.BooleanField(default=False, verbose_name='Namensschildversehen')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seriennummer')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_instances', to='personnel.person', verbose_name='Zugeordnet an')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_instances', to='locations.location', verbose_name='Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='clothing.clothingitemmaster', verbose_name='Stammdaten')),
            ],
            options={
                'verbose_name': 'Kleidungsstück-Instanz',
                'verbose_name_plural': 'Kleidungsstück-Instanzen',
                'ordering': ['master__name', 'size', 'inventory_number'],
                'indexes': [models.Index(fields=['inventory_number'], name='clothing_cl_invento_4a95e8_idx'), models.Index(fields=['assigned_to'], name='clothing_cl_assigne_a09ed6_idx'), models.Index(fields=['master', 'size'], name='clothing_cl_master__794f0c_idx')],
            },
        ),
    ]
