# Generated by Django 5.0.14 on 2025-11-17 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0007_add_master_instance_architecture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitemmaster',
            name='clothing_type',
            field=models.CharField(blank=True, choices=[('jacket', 'Jacke'), ('pants', 'Hose'), ('overall', 'Overall/Kombi'), ('shirt', 'Hemd/Shirt'), ('underwear', 'Unterwäsche'), ('shoes', 'Schuhe'), ('boots', 'Stiefel'), ('gloves', 'Handschuhe'), ('helmet', 'Helm'), ('vest', 'Weste'), ('coat', 'Mantel'), ('hat', 'Kopfbedeckung'), ('protective', 'Schutzausrüstung'), ('uniform', 'Uniform'), ('other', 'Sonstiges')], default='', max_length=20, verbose_name='Kleidungstyp (Legacy)'),
        ),
        migrations.CreateModel(
            name='ClothingProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='z.B. "Jacke", "Hose", "Helm"', max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(help_text='Eindeutiger Code, z.B. "JACKET", "PANTS"', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(default='👕', help_text='Emoji oder Symbol für visuelle Darstellung', max_length=10, verbose_name='Icon')),
                ('is_psa_typical', models.BooleanField(default=False, help_text='Gibt an, ob dieser Produkttyp normalerweise PSA ist', verbose_name='Typischerweise PSA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Produkttyp',
                'verbose_name_plural': 'Produkttypen',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='clothingitemmaster',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='clothing.clothingproducttype', verbose_name='Produkttyp'),
        ),
    ]
