# Generated by Django 5.2.15 on 2026-08-26 04:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0009_clear_bulk_item_person_assignment'),
        ('personnel', '0020_add_watch_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingIssueList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(help_text='z.B. "Neueinstellung BF"', max_length=200, verbose_name='Titel')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('partial', 'Teilweise ausgegeben'), ('completed', 'Abgeschlossen')], default='open', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Ausgabedatum')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clothing_issue_lists', to='personnel.person', verbose_name='Person')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Ausgabeliste',
                'verbose_name_plural': 'Ausgabelisten',
                'ordering': ['-issue_date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ClothingIssueListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Anzahl')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Hinweis')),
                ('is_done', models.BooleanField(default=False, verbose_name='Ausgegeben')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Ausgegeben am')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ausgegeben von')),
                ('issue_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clothing.clothingissuelist', verbose_name='Ausgabeliste')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_list_items', to='clothing.clothingitem', verbose_name='Artikel')),
                ('movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_list_item', to='clothing.clothingstockmovement', verbose_name='Lagerbewegung')),
            ],
            options={
                'verbose_name': 'Ausgabeposition',
                'verbose_name_plural': 'Ausgabepositionen',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ClothingIssueTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='z.B. "Neueinstellung BF", "Grundausstattung Praktikant"', max_length=200, unique=True, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Ausgabevorlage',
                'verbose_name_plural': 'Ausgabevorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='clothingissuelist',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_lists', to='clothing.clothingissuetemplate', verbose_name='Vorlage'),
        ),
        migrations.CreateModel(
            name='ClothingIssueTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Anzahl')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('notes', models.CharField(blank=True, help_text='z.B. "nur bei Atemschutzträgern"', max_length=200, verbose_name='Hinweis')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_template_items', to='clothing.clothingitem', verbose_name='Artikel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clothing.clothingissuetemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Vorlagenposition',
                'verbose_name_plural': 'Vorlagenpositionen',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='clothingissuelist',
            index=models.Index(fields=['person', '-issue_date'], name='clothing_cl_person__e79c89_idx'),
        ),
        migrations.AddIndex(
            model_name='clothingissuelist',
            index=models.Index(fields=['status'], name='clothing_cl_status_12d9d1_idx'),
        ),
    ]
