# Generated by Django 5.0.14 on 2026-02-13 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('category', models.CharField(choices=[('vehicle', 'Fahrzeug'), ('location', 'Raum / Standort'), ('equipment', 'Ausrüstung & Geräte'), ('clothing', 'Bekleidung'), ('medical', 'Rettungsdienst / Medizin'), ('magazine', 'Verbrauchsmaterial'), ('workshop', 'Werkstatt'), ('height_rescue', 'Höhenrettung'), ('diving', 'Taucher'), ('it_hardware', 'IT-Hardware'), ('other', 'Sonstiges')], max_length=20, verbose_name='Kategorie')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objekt-ID')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('resolved', 'Behoben'), ('closed', 'Geschlossen')], default='open', max_length=20, verbose_name='Status')),
                ('reported_date', models.DateTimeField(auto_now_add=True, verbose_name='Gemeldet am')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Behoben am')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Behebungsnotiz')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Objekttyp')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_defects', to=settings.AUTH_USER_MODEL, verbose_name='Behoben von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Mangel',
                'verbose_name_plural': 'Mängel',
                'ordering': ['-reported_date'],
                'permissions': [('assign_defect', 'Kann Mängel zuweisen')],
            },
        ),
        migrations.CreateModel(
            name='DefectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('text', models.TextField(verbose_name='Kommentar')),
                ('is_status_change', models.BooleanField(default=False, help_text='Automatischer Eintrag bei Status-Änderung', verbose_name='Status-Änderung')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defect_management.defect', verbose_name='Mangel')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Mangel-Kommentar',
                'verbose_name_plural': 'Mangel-Kommentare',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('image', models.ImageField(upload_to='defect_management/%Y/%m/', verbose_name='Foto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Beschreibung')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='defect_management.defect', verbose_name='Mangel')),
            ],
            options={
                'verbose_name': 'Mangel-Foto',
                'verbose_name_plural': 'Mangel-Fotos',
            },
        ),
    ]
