# Generated by Django 5.2.15 on 2026-07-09 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defect_management', '0006_reporter_first_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defectcategorymodel',
            name='responsible_users',
            field=models.ManyToManyField(blank=True, help_text='Sachbearbeiter, die Mängel dieser Kategorie sehen/bearbeiten dürfen. Leer = für alle Bearbeiter sichtbar (keine Einschränkung).', related_name='responsible_defect_categories', to=settings.AUTH_USER_MODEL, verbose_name='Zuständige Bearbeiter'),
        ),
    ]
