# Generated by Django 5.2.7 on 2025-10-09 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0003_alter_divingitem_category'),
        ('personnel', '0002_person_id_card_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivingServiceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_interval_months', models.PositiveIntegerField(blank=True, help_text='Überschreibt Standard-Intervall der Wartungsart', null=True, verbose_name='Individuelles Intervall (Monate)')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('is_active', models.BooleanField(default=True, help_text='Wartung wird noch durchgeführt', verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diving_service_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='diving.divingitem', verbose_name='Ausrüstung')),
            ],
            options={
                'verbose_name': 'Wartungszuweisung Tauchen',
                'verbose_name_plural': 'Wartungszuweisungen Tauchen',
                'ordering': ['item', 'service_type'],
            },
        ),
        migrations.CreateModel(
            name='DivingServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Wartungsdatum')),
                ('result', models.CharField(choices=[('completed', 'Abgeschlossen'), ('completed_with_remarks', 'Abgeschlossen mit Anmerkungen'), ('incomplete', 'Unvollständig'), ('failed', 'Fehlgeschlagen')], max_length=30, verbose_name='Wartungsergebnis')),
                ('checklist_results', models.JSONField(blank=True, default=dict, help_text='Detaillierte Ergebnisse der einzelnen Wartungspunkte', verbose_name='Checklisten-Ergebnisse')),
                ('custom_field_values', models.JSONField(blank=True, default=dict, help_text='Werte der benutzerdefinierten Messfelder', verbose_name='Messwerte')),
                ('findings', models.TextField(blank=True, verbose_name='Feststellungen/Mängel')),
                ('work_performed', models.TextField(blank=True, verbose_name='Durchgeführte Arbeiten')),
                ('parts_replaced', models.TextField(blank=True, verbose_name='Ersetzte Teile')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung fällig am')),
                ('labor_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Arbeitsstunden')),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Materialkosten (€)')),
                ('service_certificate', models.FileField(blank=True, null=True, upload_to='diving/service_certificates/', verbose_name='Wartungsprotokoll (PDF)')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste der Foto-URLs', verbose_name='Fotos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='diving.divingserviceassignment', verbose_name='Wartungszuweisung')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_diving_services', to='personnel.person', verbose_name='Techniker')),
            ],
            options={
                'verbose_name': 'Wartungsprotokoll Tauchen',
                'verbose_name_plural': 'Wartungsprotokolle Tauchen',
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='DivingServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Jahresservice Atemregler, TÜV-Prüfung Flasche, Dichtungswechsel', max_length=200, verbose_name='Wartungsbezeichnung')),
                ('description', models.TextField(blank=True, help_text='Was wird bei dieser Wartung durchgeführt?', verbose_name='Beschreibung')),
                ('service_standard', models.CharField(blank=True, help_text='z.B. Herstellervorgabe, DIN EN 250', max_length=100, verbose_name='Wartungsstandard')),
                ('interval_months', models.PositiveIntegerField(blank=True, help_text='Wie oft muss diese Wartung durchgeführt werden?', null=True, verbose_name='Intervall (Monate)')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Liste der durchzuführenden Wartungsarbeiten', verbose_name='Wartungspunkte')),
                ('applicable_item_types', models.JSONField(blank=True, default=list, help_text='Für welche Ausrüstungstypen ist diese Wartung relevant?', verbose_name='Anwendbar auf Ausrüstungstypen')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Individuelle Felder für Messwerte (z.B. Ansprechdruck, Durchflussrate)', verbose_name='Benutzerdefinierte Messfelder')),
                ('requires_certification', models.BooleanField(default=False, help_text='Darf nur von zertifizierten Personen durchgeführt werden', verbose_name='Befähigungsnachweis erforderlich')),
                ('requires_external_service', models.BooleanField(default=False, help_text='Muss durch externen Dienstleister durchgeführt werden', verbose_name='Externe Wartung')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Gesetzlich oder herstellerseitig vorgeschriebene Wartung', verbose_name='Pflichtwartung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diving_service_types', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Wartungsart Tauchen',
                'verbose_name_plural': 'Wartungsarten Tauchen',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='divingserviceassignment',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='diving.divingservicetype', verbose_name='Wartungsart'),
        ),
        migrations.AlterUniqueTogether(
            name='divingserviceassignment',
            unique_together={('item', 'service_type')},
        ),
    ]
