# Generated by Django 5.0.14 on 2025-10-17 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0004_divingserviceassignment_divingservicerecord_and_more'),
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0007_add_organization_membership_and_anniversaries'),
        ('vehicles', '0005_vehicle_actual_retirement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivingItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_number', models.CharField(help_text='Eindeutige Nummer für dieses Produkt, z.B. DIV-2025-001', max_length=50, unique=True, verbose_name='Stammdatennummer')),
                ('name', models.CharField(help_text='z.B. Atemregler Scubapro MK25 EVO', max_length=200, verbose_name='Produktname')),
                ('description', models.TextField(blank=True, help_text='Detaillierte Produktbeschreibung', verbose_name='Beschreibung')),
                ('item_type', models.CharField(choices=[], max_length=50, verbose_name='Ausrüstungstyp')),
                ('manufacturer', models.CharField(blank=True, help_text='z.B. Scubapro, Mares, Aqualung', max_length=200, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, help_text='z.B. MK25 EVO, Puck Pro', max_length=200, verbose_name='Modell')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Liste der Zertifizierungen, z.B. ["EN 250", "CE"]', verbose_name='Zertifizierungen')),
                ('certification_number', models.CharField(blank=True, max_length=200, verbose_name='Zertifizierungsnummer')),
                ('tank_type', models.CharField(blank=True, choices=[], max_length=20, verbose_name='Flaschentyp')),
                ('volume_liters', models.DecimalField(blank=True, decimal_places=1, help_text='Flaschenvolumen, z.B. 10, 12, 15 Liter', max_digits=5, null=True, verbose_name='Volumen (Liter)')),
                ('working_pressure_bar', models.PositiveIntegerField(blank=True, help_text='Betriebsdruck der Flasche, z.B. 200, 232, 300 bar', null=True, verbose_name='Nenndruck (bar)')),
                ('test_pressure_bar', models.PositiveIntegerField(blank=True, help_text='Druck bei TÜV-Prüfung', null=True, verbose_name='Prüfdruck (bar)')),
                ('max_depth_m', models.PositiveIntegerField(blank=True, help_text='Maximale Einsatztiefe', null=True, verbose_name='Max. Tauchtiefe (m)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gewicht (kg)')),
                ('material', models.CharField(blank=True, help_text='z.B. Neopren 5mm, Trilaminat, Messing', max_length=200, verbose_name='Material')),
                ('max_service_life_years', models.PositiveIntegerField(blank=True, help_text='Maximale Nutzungsdauer laut Hersteller', null=True, verbose_name='Max. Nutzungsdauer (Jahre)')),
                ('service_interval_months', models.PositiveIntegerField(default=12, help_text='Standard-Wartungsintervall, z.B. 12 für jährlich', verbose_name='Wartungsintervall (Monate)')),
                ('tuv_interval_months', models.PositiveIntegerField(blank=True, help_text='Tauchflaschen: 30 Monate (2.5 Jahre)', null=True, verbose_name='TÜV-Intervall (Monate)')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Durchschnittlicher Einkaufspreis', max_digits=10, null=True, verbose_name='Standardpreis (netto)')),
                ('manual_document', models.FileField(blank=True, help_text='PDF-Dokument der Bedienungsanleitung', null=True, upload_to='diving/masters/manuals/', verbose_name='Bedienungsanleitung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='diving/masters/images/', verbose_name='Produktbild')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, help_text='Wird dieses Produkt noch verwendet?', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diving_masters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Tauchausrüstungs-Stammdaten',
                'verbose_name_plural': 'Tauchausrüstungs-Stammdaten',
                'ordering': ['master_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DivingDeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Eindeutige Inventarnummer, z.B. DIV-FL-001', max_length=100, unique=True, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(blank=True, help_text='Herstellerseriennummer', max_length=200, verbose_name='Seriennummer')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Herstellungsdatum')),
                ('first_use_date', models.DateField(blank=True, null=True, verbose_name='Erstinbetriebnahme')),
                ('last_tuv_inspection', models.DateField(blank=True, null=True, verbose_name='Letzte TÜV-Prüfung')),
                ('next_tuv_inspection', models.DateField(blank=True, help_text='Tauchflaschen: alle 2.5 Jahre', null=True, verbose_name='Nächste TÜV-Prüfung')),
                ('tuv_certificate_number', models.CharField(blank=True, max_length=100, verbose_name='TÜV-Zertifikatsnummer')),
                ('inspection_status', models.CharField(choices=[], default='not_due', max_length=20, verbose_name='Prüfstatus')),
                ('tuv_certificate', models.FileField(blank=True, upload_to='diving/devices/tuv_certificates/', verbose_name='TÜV-Zertifikat')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Letzte Wartung')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('service_log', models.FileField(blank=True, upload_to='diving/devices/service_logs/', verbose_name='Wartungsprotokoll')),
                ('total_dives', models.PositiveIntegerField(default=0, verbose_name='Anzahl Tauchgänge')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Gesamte Tauchstunden')),
                ('last_use_date', models.DateField(blank=True, null=True, verbose_name='Letzter Einsatz')),
                ('current_gas_type', models.CharField(blank=True, choices=[], max_length=20, verbose_name='Aktuelles Atemgas')),
                ('current_fill_pressure_bar', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aktueller Fülldruck (bar)')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('excellent', 'Sehr gut'), ('good', 'Gut'), ('fair', 'Befriedigend'), ('poor', 'Schlecht'), ('defective', 'Defekt')], default='good', max_length=20, verbose_name='Zustand')),
                ('is_operational', models.BooleanField(default=True, help_text='Kann die Ausrüstung verwendet werden?', verbose_name='Einsatzbereit')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Zustandsnotizen')),
                ('defects', models.TextField(blank=True, verbose_name='Bekannte Mängel')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Aussonderungsdatum')),
                ('retirement_reason', models.TextField(blank=True, verbose_name='Aussonderungsgrund')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste der Foto-URLs', verbose_name='Fotos')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='diving/devices/qr_codes/', verbose_name='QR-Code')),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='diving/devices/barcodes/', verbose_name='Barcode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diving_devices', to='personnel.person', verbose_name='Zugeordnet an Person')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diving_devices', to='vehicles.vehicle', verbose_name='Zugeordnetes Fahrzeug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diving_devices', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('last_service_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serviced_diving_devices', to='personnel.person', verbose_name='Letzter Servicetechniker')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diving_devices', to='locations.location', verbose_name='Lagerort')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_instances', to='diving.divingitemmaster', verbose_name='Stammdaten')),
            ],
            options={
                'verbose_name': 'Tauchgerät-Instanz',
                'verbose_name_plural': 'Tauchgeräte-Instanzen',
                'ordering': ['inventory_number'],
            },
        ),
        migrations.AddIndex(
            model_name='divingitemmaster',
            index=models.Index(fields=['master_number'], name='diving_divi_master__38b2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='divingitemmaster',
            index=models.Index(fields=['item_type'], name='diving_divi_item_ty_239fde_idx'),
        ),
        migrations.AddIndex(
            model_name='divingitemmaster',
            index=models.Index(fields=['manufacturer'], name='diving_divi_manufac_ca1d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='divingitemmaster',
            index=models.Index(fields=['is_active'], name='diving_divi_is_acti_b99be5_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['inventory_number'], name='diving_divi_invento_f97bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['serial_number'], name='diving_divi_serial__06a9ce_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['master'], name='diving_divi_master__b9f450_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['location'], name='diving_divi_locatio_67e0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['next_tuv_inspection'], name='diving_divi_next_tu_d5f677_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['next_service_date'], name='diving_divi_next_se_9d228b_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['inspection_status'], name='diving_divi_inspect_eca808_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['is_operational'], name='diving_divi_is_oper_8beb95_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['assigned_vehicle'], name='diving_divi_assigne_4d458f_idx'),
        ),
        migrations.AddIndex(
            model_name='divingdeviceinstance',
            index=models.Index(fields=['assigned_to'], name='diving_divi_assigne_22cc9c_idx'),
        ),
    ]
