# Generated by Django 5.0.14 on 2025-10-20 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0006_alter_divingitem_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Stahlflasche, Aluminiumflasche', max_length=100, unique=True, verbose_name='Flaschentyp')),
                ('code', models.CharField(help_text='Eindeutiger Code, z.B. steel, aluminum', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('material', models.CharField(blank=True, help_text='z.B. Stahl, Aluminium, Komposit', max_length=100, verbose_name='Material')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bottle_types', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Flaschentyp',
                'verbose_name_plural': 'Flaschentypen',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Tauchflasche, Atemregler, Tarierjacket', max_length=100, unique=True, verbose_name='Ausrüstungstyp')),
                ('code', models.CharField(help_text='Eindeutiger Code, z.B. scuba_tank, regulator', max_length=50, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('category', models.CharField(blank=True, help_text='z.B. Atemausrüstung, Schutzausrüstung, Instrumente', max_length=50, verbose_name='Kategorie')),
                ('icon', models.CharField(blank=True, help_text='Emoji oder Icon-Klasse', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_equipment_types', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Ausrüstungstyp',
                'verbose_name_plural': 'Ausrüstungstypen',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
