# Generated by Django 5.0.14 on 2025-10-20 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0007_bottletype_equipmenttype'),
        ('locations', '0003_location_technical_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Herstellerchargennummer', max_length=100, verbose_name='Chargennummer')),
                ('received_date', models.DateField(help_text='Wann wurde die Charge empfangen?', verbose_name='Eingangsdatum')),
                ('expiry_date', models.DateField(blank=True, help_text='Mindesthaltbarkeitsdatum', null=True, verbose_name='Ablaufdatum')),
                ('quantity_received', models.PositiveIntegerField(help_text='Wie viele Einheiten wurden empfangen?', verbose_name='Eingangsmenge')),
                ('quantity_remaining', models.PositiveIntegerField(help_text='Wie viele Einheiten sind noch vorhanden?', verbose_name='Restmenge')),
                ('supplier', models.CharField(blank=True, help_text='Von wem wurde die Charge bezogen?', max_length=200, verbose_name='Lieferant')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Preis für die gesamte Charge', max_digits=10, null=True, verbose_name='Einkaufspreis (€)')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, help_text='Ist die Charge noch im Bestand?', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diving_batches', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diving_batches', to='locations.location', verbose_name='Lagerort')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='diving.divingitemmaster', verbose_name='Stammdaten')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Chargen',
                'ordering': ['-received_date', 'expiry_date'],
                'indexes': [models.Index(fields=['master'], name='diving_divi_master__9538d9_idx'), models.Index(fields=['batch_number'], name='diving_divi_batch_n_2c841f_idx'), models.Index(fields=['expiry_date'], name='diving_divi_expiry__41d32c_idx'), models.Index(fields=['location'], name='diving_divi_locatio_3bc844_idx'), models.Index(fields=['is_active'], name='diving_divi_is_acti_633827_idx')],
            },
        ),
    ]
