# Generated by Django 5.0.14 on 2025-10-20 17:34

from django.db import migrations


def import_legacy_equipment_types(apps, schema_editor):
    """Import legacy DivingItemType choices as EquipmentType database entries"""
    EquipmentType = apps.get_model('diving', 'EquipmentType')
    User = apps.get_model('core', 'User')

    # Get first superuser for created_by field
    try:
        admin_user = User.objects.filter(is_superuser=True).first()
        if not admin_user:
            admin_user = User.objects.first()
    except:
        # If no users exist, skip migration
        return

    if not admin_user:
        return

    # Legacy types with categories and icons
    legacy_types = [
        # Atemausrüstung
        {'code': 'scuba_tank', 'name': 'Tauchflasche', 'category': 'Atemausrüstung', 'icon': '🧊', 'sort_order': 10},
        {'code': 'regulator', 'name': 'Atemregler', 'category': 'Atemausrüstung', 'icon': '🫁', 'sort_order': 20},
        {'code': 'octopus', 'name': 'Oktopus (Reserveatemregler)', 'category': 'Atemausrüstung', 'icon': '🫁', 'sort_order': 30},
        {'code': 'bcd', 'name': 'Tarierjacket (BCD)', 'category': 'Atemausrüstung', 'icon': '🦺', 'sort_order': 40},

        # Schutzausrüstung
        {'code': 'wetsuit', 'name': 'Nassanzug', 'category': 'Schutzausrüstung', 'icon': '🩱', 'sort_order': 110},
        {'code': 'drysuit', 'name': 'Trockenanzug', 'category': 'Schutzausrüstung', 'icon': '🩱', 'sort_order': 120},
        {'code': 'diving_mask', 'name': 'Tauchmaske', 'category': 'Schutzausrüstung', 'icon': '🥽', 'sort_order': 130},
        {'code': 'snorkel', 'name': 'Schnorchel', 'category': 'Schutzausrüstung', 'icon': '🤿', 'sort_order': 140},
        {'code': 'fins', 'name': 'Flossen', 'category': 'Schutzausrüstung', 'icon': '👟', 'sort_order': 150},
        {'code': 'diving_boots', 'name': 'Tauchschuhe', 'category': 'Schutzausrüstung', 'icon': '👟', 'sort_order': 160},
        {'code': 'diving_gloves', 'name': 'Tauchhandschuhe', 'category': 'Schutzausrüstung', 'icon': '🧤', 'sort_order': 170},
        {'code': 'hood', 'name': 'Kopfhaube', 'category': 'Schutzausrüstung', 'icon': '🧤', 'sort_order': 180},

        # Instrumente & Navigation
        {'code': 'dive_computer', 'name': 'Tauchcomputer', 'category': 'Instrumente & Navigation', 'icon': '⏱️', 'sort_order': 210},
        {'code': 'depth_gauge', 'name': 'Tiefenmesser', 'category': 'Instrumente & Navigation', 'icon': '📏', 'sort_order': 220},
        {'code': 'compass', 'name': 'Kompass', 'category': 'Instrumente & Navigation', 'icon': '🧭', 'sort_order': 230},
        {'code': 'pressure_gauge', 'name': 'Finimeter', 'category': 'Instrumente & Navigation', 'icon': '📏', 'sort_order': 240},

        # Sicherheit & Rettung
        {'code': 'knife', 'name': 'Tauchmesser', 'category': 'Sicherheit & Rettung', 'icon': '🔪', 'sort_order': 310},
        {'code': 'torch', 'name': 'Tauchlampe', 'category': 'Sicherheit & Rettung', 'icon': '💡', 'sort_order': 320},
        {'code': 'smb', 'name': 'Signalboje (SMB)', 'category': 'Sicherheit & Rettung', 'icon': '🎈', 'sort_order': 330},
        {'code': 'whistle', 'name': 'Signalpfeife', 'category': 'Sicherheit & Rettung', 'icon': '📢', 'sort_order': 340},
        {'code': 'safety_reel', 'name': 'Sicherheitsleine mit Rolle', 'category': 'Sicherheit & Rettung', 'icon': '🪢', 'sort_order': 350},

        # Gewichte & Zubehör
        {'code': 'weight_belt', 'name': 'Bleigurt', 'category': 'Gewichte & Zubehör', 'icon': '⚖️', 'sort_order': 410},
        {'code': 'weight', 'name': 'Bleigewicht', 'category': 'Gewichte & Zubehör', 'icon': '⚖️', 'sort_order': 420},
        {'code': 'mesh_bag', 'name': 'Netztasche', 'category': 'Gewichte & Zubehör', 'icon': '🎒', 'sort_order': 430},

        # Kompressor & Wartung
        {'code': 'compressor', 'name': 'Tauchkompressor', 'category': 'Kompressor & Wartung', 'icon': '⚙️', 'sort_order': 510},
        {'code': 'fill_station', 'name': 'Füllstation', 'category': 'Kompressor & Wartung', 'icon': '⚙️', 'sort_order': 520},
        {'code': 'maintenance_kit', 'name': 'Wartungskit', 'category': 'Kompressor & Wartung', 'icon': '🔧', 'sort_order': 530},
    ]

    # Create EquipmentType entries if they don't exist
    for type_data in legacy_types:
        EquipmentType.objects.get_or_create(
            code=type_data['code'],
            defaults={
                'name': type_data['name'],
                'category': type_data['category'],
                'icon': type_data['icon'],
                'sort_order': type_data['sort_order'],
                'is_active': True,
                'created_by': admin_user,
                'description': f'Importiert aus Legacy-Typen'
            }
        )


def reverse_import(apps, schema_editor):
    """Remove imported legacy types"""
    EquipmentType = apps.get_model('diving', 'EquipmentType')

    legacy_codes = [
        'scuba_tank', 'regulator', 'octopus', 'bcd',
        'wetsuit', 'drysuit', 'diving_mask', 'snorkel', 'fins', 'diving_boots', 'diving_gloves', 'hood',
        'dive_computer', 'depth_gauge', 'compass', 'pressure_gauge',
        'knife', 'torch', 'smb', 'whistle', 'safety_reel',
        'weight_belt', 'weight', 'mesh_bag',
        'compressor', 'fill_station', 'maintenance_kit'
    ]

    EquipmentType.objects.filter(code__in=legacy_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0008_divingbatch'),
        ('core', '0001_initial'),  # Need User model
    ]

    operations = [
        migrations.RunPython(import_legacy_equipment_types, reverse_import),
    ]
