# Generated by Django 5.0.14 on 2025-10-22 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0009_import_legacy_equipment_types'),
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0015_person_show_private_contact_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DivingInventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.CharField(help_text='Wird automatisch generiert, z.B. DIV-INV-2025-001', max_length=50, unique=True, verbose_name='Inventur-Nummer')),
                ('title', models.CharField(help_text='z.B. Jahresinventur 2025, Quartalsprüfung Q1', max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('check_type', models.CharField(choices=[('full', 'Vollinventur'), ('spot', 'Stichprobeninventur'), ('location', 'Standortinventur'), ('category', 'Kategorieninventur')], default='full', max_length=20, verbose_name='Inventurtyp')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('counting_complete', 'Zählung abgeschlossen'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='planned', max_length=20, verbose_name='Status')),
                ('scheduled_start_date', models.DateField(verbose_name='Geplanter Start')),
                ('scheduled_end_date', models.DateField(verbose_name='Geplantes Ende')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächlicher Start')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Gesamtanzahl Artikel')),
                ('counted_items', models.PositiveIntegerField(default=0, verbose_name='Gezählte Artikel')),
                ('items_with_discrepancies', models.PositiveIntegerField(default=0, verbose_name='Artikel mit Abweichungen')),
                ('check_tuv_inspection', models.BooleanField(default=True, help_text='Tauchflaschen auf ablaufende TÜV-Prüfungen prüfen', verbose_name='TÜV-Prüfung kontrollieren')),
                ('check_service_due', models.BooleanField(default=True, help_text='Atemregler und andere Ausrüstung auf fällige Wartungen prüfen', verbose_name='Wartungstermine kontrollieren')),
                ('check_condition', models.BooleanField(default=True, help_text='Visuellen Zustand der Ausrüstung bewerten', verbose_name='Zustand prüfen')),
                ('check_defects', models.BooleanField(default=True, help_text='Defekte und Beschädigungen dokumentieren', verbose_name='Mängel erfassen')),
                ('tuv_overdue_found', models.PositiveIntegerField(default=0, help_text='Anzahl Flaschen mit überfälliger TÜV-Prüfung', verbose_name='TÜV überfällig')),
                ('service_overdue_found', models.PositiveIntegerField(default=0, help_text='Anzahl Ausrüstung mit überfälliger Wartung', verbose_name='Wartung überfällig')),
                ('defective_items_found', models.PositiveIntegerField(default=0, help_text='Anzahl defekter oder beschädigter Ausrüstung', verbose_name='Defekte Ausrüstung')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigt am')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_diving_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diving_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, help_text='Leer = alle Lagerorte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diving_inventory_checks', to='locations.location', verbose_name='Eingeschränkt auf Lagerort')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_diving_inventory_checks', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('team_members', models.ManyToManyField(blank=True, related_name='diving_inventory_checks', to='personnel.person', verbose_name='Team-Mitglieder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_diving_inventory_checks', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Diving Inventur',
                'verbose_name_plural': 'Diving Inventuren',
                'ordering': ['-created_at'],
                'permissions': [('approve_divinginventorycheck', 'Kann Diving-Inventur genehmigen')],
            },
        ),
        migrations.CreateModel(
            name='DivingInventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, verbose_name='Artikelbezeichnung')),
                ('item_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer')),
                ('inventory_number', models.CharField(blank=True, max_length=100, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Seriennummer')),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Soll-Menge')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ist-Menge')),
                ('variance_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Differenz')),
                ('is_counted', models.BooleanField(default=False, verbose_name='Gezählt')),
                ('has_discrepancy', models.BooleanField(default=False, verbose_name='Abweichung vorhanden')),
                ('counted_date', models.DateTimeField(blank=True, null=True, verbose_name='Gezählt am')),
                ('item_type', models.CharField(blank=True, max_length=50, verbose_name='Ausrüstungstyp')),
                ('next_tuv_inspection', models.DateField(blank=True, null=True, verbose_name='Nächste TÜV-Prüfung')),
                ('tuv_overdue', models.BooleanField(default=False, verbose_name='TÜV überfällig')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Nächste Wartung')),
                ('service_overdue', models.BooleanField(default=False, verbose_name='Wartung überfällig')),
                ('condition', models.CharField(blank=True, max_length=20, verbose_name='Zustand')),
                ('is_operational', models.BooleanField(default=True, verbose_name='Einsatzbereit')),
                ('is_defective', models.BooleanField(default=False, verbose_name='Defekt')),
                ('defects_description', models.TextField(blank=True, verbose_name='Mängelbeschreibung')),
                ('assigned_to_name', models.CharField(blank=True, max_length=200, verbose_name='Zugeordnet an')),
                ('assigned_vehicle_name', models.CharField(blank=True, max_length=200, verbose_name='Zugeordnetes Fahrzeug')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counted_diving_items', to='personnel.person', verbose_name='Gezählt von')),
                ('diving_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='diving.divingdeviceinstance', verbose_name='Tauchgerät')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diving.divinginventorycheck', verbose_name='Inventur')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diving_inventory_items', to='locations.location', verbose_name='Lagerort')),
            ],
            options={
                'verbose_name': 'Diving Inventur-Position',
                'verbose_name_plural': 'Diving Inventur-Positionen',
                'ordering': ['item_name', 'inventory_number'],
            },
        ),
    ]
