# Generated by Django 5.0.14 on 2025-10-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0010_divinginventorycheck_divinginventorycheckitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divinginventorycheck',
            name='check_type',
            field=models.CharField(choices=[('full', 'Vollinventur'), ('partial', 'Teilinventur'), ('spot_check', 'Stichprobe'), ('cycle_count', 'Zykluszählung'), ('annual', 'Jahresinventur')], default='partial', max_length=20, verbose_name='Inventurart'),
        ),
    ]
