# Generated by Django 5.0.14 on 2025-11-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0012_change_service_assignment_to_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divingserviceassignment',
            options={'ordering': ['device', 'service_type'], 'verbose_name': 'Wartungszuweisung Tauchen', 'verbose_name_plural': 'Wartungszuweisungen Tauchen'},
        ),
    ]
