# Generated by Django 5.0.14 on 2025-11-17 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0014_change_service_log_to_device'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='divingservicelog',
            new_name='diving_divi_device__818209_idx',
            old_name='diving_divi_device__8a2c1f_idx',
        ),
    ]
