# Generated by Django 5.0.14 on 2025-11-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diving', '0015_rename_diving_divi_device__8a2c1f_idx_diving_divi_device__818209_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='divingservicelog',
            name='checklist_results',
            field=models.JSONField(blank=True, default=dict, help_text='Ergebnisse der Checklisten-Prüfpunkte', verbose_name='Checklisten-Ergebnisse'),
        ),
        migrations.AddField(
            model_name='divingservicelog',
            name='measurement_results',
            field=models.JSONField(blank=True, default=dict, help_text='Erfasste Messwerte aus dem Wartungstyp', verbose_name='Messwerte'),
        ),
        migrations.AddField(
            model_name='divingservicelog',
            name='service_type_obj',
            field=models.ForeignKey(blank=True, help_text='Optional: Wählen Sie einen vordefinierten Wartungstyp mit Checkliste', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_logs', to='diving.divingservicetype', verbose_name='Wartungstyp (mit Checkliste)'),
        ),
        migrations.AlterField(
            model_name='divingservicelog',
            name='service_type',
            field=models.CharField(choices=[('annual', 'Jahresservice'), ('tuv', 'TÜV-Prüfung'), ('repair', 'Reparatur'), ('visual', 'Sichtprüfung'), ('function_test', 'Funktionstest'), ('cleaning', 'Reinigung'), ('custom', 'Benutzerdefiniert')], default='annual', help_text='Wird verwendet wenn kein Wartungstyp mit Checkliste gewählt wurde', max_length=50, verbose_name='Einfache Serviceart'),
        ),
    ]
