# Generated by Django 5.0.14 on 2026-02-19 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civil_protection', '0001_initial'),
        ('personnel', '0020_add_watch_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KatSLending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('lending_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Ausleihe-Nr.')),
                ('bereich', models.CharField(choices=[('zivilschutz', 'Zivilschutz'), ('bevoelkerungsschutz', 'Bevölkerungsschutz')], max_length=30, verbose_name='Bereich')),
                ('borrower_name', models.CharField(blank=True, max_length=200, verbose_name='Name des Ausleihenden')),
                ('borrower_organization', models.CharField(blank=True, max_length=200, verbose_name='Organisation')),
                ('borrower_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('borrower_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('lending_date', models.DateField(verbose_name='Ausgabedatum')),
                ('expected_return_date', models.DateField(verbose_name='Geplantes Rückgabedatum')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Tatsächliches Rückgabedatum')),
                ('status', models.CharField(choices=[('offen', 'Offen'), ('ausgegeben', 'Ausgegeben'), ('zurueckgegeben', 'Zurückgegeben'), ('ueberfaellig', 'Überfällig')], default='offen', max_length=20, verbose_name='Status')),
                ('purpose', models.TextField(blank=True, verbose_name='Verwendungszweck')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kats_lendings', to='personnel.person', verbose_name='Ausleihende Person (intern)')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'KatS-Ausleihe',
                'verbose_name_plural': 'KatS-Ausleihen',
                'ordering': ['-lending_date'],
                'permissions': [('manage_lending', 'Kann Ausleihen verwalten')],
            },
        ),
        migrations.CreateModel(
            name='KatSLendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='z.B. Bierzeltgarnitur, Kaffeemaschine', max_length=200, verbose_name='Artikelbezeichnung')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('quantity_returned', models.PositiveIntegerField(default=0, verbose_name='Menge zurückgegeben')),
                ('condition_out', models.CharField(blank=True, max_length=100, verbose_name='Zustand bei Ausgabe')),
                ('condition_in', models.CharField(blank=True, max_length=100, verbose_name='Zustand bei Rückgabe')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('equipment_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lending_items', to='civil_protection.katsequipmentmaster', verbose_name='KatS-Ausrüstung')),
                ('lending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='civil_protection.katslending', verbose_name='Ausleihe')),
            ],
            options={
                'verbose_name': 'Ausleihe-Position',
                'verbose_name_plural': 'Ausleihe-Positionen',
            },
        ),
    ]
