# Generated by Django 5.0.14 on 2026-02-20 06:23

from django.db import migrations, models


def convert_bereich_values(apps, schema_editor):
    """Convert old bereich values (zivilschutz/bevoelkerungsschutz) to new ones (bund)."""
    models_to_update = [
        'KatSEquipmentMaster', 'KatSEquipmentInstance', 'KatSVehicle',
        'KatSMedicationMaster', 'KatSMedicationBatch', 'KatSStockMovement',
        'KatSInventoryCheck', 'Notfallinformationspunkt', 'Leuchtturmstandort',
        'KatSLending',
    ]
    for model_name in models_to_update:
        Model = apps.get_model('civil_protection', model_name)
        Model.objects.filter(bereich='zivilschutz').update(bereich='bund')
        Model.objects.filter(bereich='bevoelkerungsschutz').update(bereich='bund')


class Migration(migrations.Migration):

    dependencies = [
        ('civil_protection', '0002_katslending_katslendingitem'),
    ]

    operations = [
        migrations.RunPython(convert_bereich_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='katsequipmentinstance',
            name='bereich',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='katsequipmentmaster',
            name='bereich',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='katsinventorycheck',
            name='bereich',
            field=models.CharField(blank=True, choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], help_text='Leer = alle Bereiche', max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='katslending',
            name='bereich',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='katsmedicationbatch',
            name='bereich',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='katsmedicationmaster',
            name='bereich',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='katsstockmovement',
            name='bereich',
            field=models.CharField(blank=True, choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='katsvehicle',
            name='bereich',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='leuchtturmstandort',
            name='bereich',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], default='bund', max_length=30, verbose_name='Bereich'),
        ),
        migrations.AlterField(
            model_name='notfallinformationspunkt',
            name='bereich',
            field=models.CharField(choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], default='bund', max_length=30, verbose_name='Bereich'),
        ),
    ]
