# Generated by Django 5.0.14 on 2025-10-03 12:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeightRescueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_number', models.CharField(help_text='Eindeutige Artikelnummer', max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Hersteller-Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestand')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Warnung bei Unterschreitung', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximalbestand')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode/EAN')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR-Code')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/images/', verbose_name='Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('item_type', models.CharField(choices=[('rope', 'Seil'), ('harness', 'Auffanggurt'), ('helmet', 'Helm'), ('carabiner', 'Karabiner'), ('descender', 'Abseilgerät'), ('ascender', 'Steigklemme'), ('pulley', 'Seilrolle'), ('anchor', 'Anschlagpunkt'), ('fall_arrester', 'Falldämpfer'), ('retrieval_device', 'Rettungsgerät'), ('tripod', 'Dreibein'), ('rope_protector', 'Kantenschutz'), ('webbing', 'Bandschlinge'), ('chest_harness', 'Brustgurt'), ('sit_harness', 'Sitzgurt'), ('work_positioning', 'Positionierungsmittel'), ('rescue_stretcher', 'Rettungstrage'), ('edge_roller', 'Kantenrolle'), ('safety_line', 'Sicherheitsleine'), ('belay_device', 'Sicherungsgerät')], max_length=50, verbose_name='Ausrüstungstyp')),
                ('rope_type', models.CharField(blank=True, choices=[('type_a', 'Typ A - Statisches Seil (Rettung)'), ('type_b', 'Typ B - Halbstatisches Seil'), ('dynamic', 'Dynamisches Seil (Klettern)'), ('kernmantle', 'Kernmantelseil'), ('steel_cable', 'Stahlseil')], max_length=50, verbose_name='Seiltyp')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Liste der Zertifizierungsstandards (z.B. EN 361, EN 1891)', verbose_name='Zertifizierungen')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Zertifizierungsnummer')),
                ('max_load_kg', models.PositiveIntegerField(blank=True, help_text='Maximale zulässige Belastung in Kilogramm', null=True, verbose_name='Max. Belastung (kg)')),
                ('breaking_strength_kn', models.DecimalField(blank=True, decimal_places=2, help_text='Bruchfestigkeit in Kilonewton', max_digits=6, null=True, verbose_name='Bruchfestigkeit (kN)')),
                ('working_load_limit_kg', models.PositiveIntegerField(blank=True, help_text='Maximale Arbeitslast (WLL - Working Load Limit)', null=True, verbose_name='Arbeitslast (kg)')),
                ('rope_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Seillänge (m)')),
                ('rope_diameter_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Seildurchmesser (mm)')),
                ('manufacturing_date', models.DateField(blank=True, help_text='Wichtig für Alterungsberechnung', null=True, verbose_name='Herstellungsdatum')),
                ('max_service_life_years', models.PositiveIntegerField(blank=True, help_text='Maximale Nutzungsdauer laut Hersteller', null=True, verbose_name='Max. Nutzungsdauer (Jahre)')),
                ('retirement_date', models.DateField(blank=True, help_text='Datum der geplanten oder erfolgten Aussonderung', null=True, verbose_name='Aussonderungsdatum')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, help_text='Mindestens jährlich nach DGUV', null=True, verbose_name='Nächste Prüfung')),
                ('inspection_interval_months', models.PositiveIntegerField(default=12, help_text='Standard: 12 Monate', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Prüfintervall (Monate)')),
                ('inspection_status', models.CharField(choices=[('not_due', 'Nicht fällig'), ('due_soon', 'Demnächst fällig'), ('overdue', 'Überfällig'), ('failed', 'Nicht bestanden'), ('passed', 'Bestanden'), ('retired', 'Ausgemustert')], default='not_due', max_length=20, verbose_name='Prüfstatus')),
                ('total_falls_arrested', models.PositiveIntegerField(default=0, help_text='Wichtig: Nach Sturz meist Aussonderung!', verbose_name='Anzahl Stürze aufgefangen')),
                ('total_uses', models.PositiveIntegerField(default=0, verbose_name='Anzahl Einsätze')),
                ('last_use_date', models.DateField(blank=True, null=True, verbose_name='Letzter Einsatz')),
                ('inspection_report', models.FileField(blank=True, upload_to='height_rescue/inspection_reports/', verbose_name='Prüfprotokoll')),
                ('manual_file', models.FileField(blank=True, upload_to='height_rescue/manuals/', verbose_name='Bedienungsanleitung')),
                ('test_certificate', models.FileField(blank=True, upload_to='height_rescue/certificates/', verbose_name='Prüfzeugnis')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Pfade zu Fotos für Zustandsdokumentation', verbose_name='Fotos')),
                ('condition_notes', models.TextField(blank=True, help_text='Beschädigungen, Abnutzung, etc.', verbose_name='Zustandsnotizen')),
                ('retirement_reason', models.TextField(blank=True, help_text='Grund für Aussonderung (z.B. Sturz, Beschädigung, Alter)', verbose_name='Aussonderungsgrund')),
                ('assigned_vehicles', models.ManyToManyField(blank=True, related_name='height_rescue_equipment', to='vehicles.vehicle', verbose_name='Zugeordnete Fahrzeuge')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('last_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_height_rescue_items', to='personnel.person', verbose_name='Letzter Prüfer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Höhenrettungsausrüstung',
                'verbose_name_plural': 'Höhenrettungsausrüstung',
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeightRescueInspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Prüfdatum')),
                ('inspection_type', models.CharField(choices=[('annual', 'Jährliche Prüfung'), ('post_use', 'Prüfung nach Einsatz'), ('post_fall', 'Prüfung nach Sturz'), ('visual', 'Sichtprüfung'), ('detailed', 'Detailprüfung')], default='annual', max_length=50, verbose_name='Prüfart')),
                ('passed', models.BooleanField(verbose_name='Bestanden')),
                ('findings', models.TextField(blank=True, help_text='Mängel, Beschädigungen, Abnutzungserscheinungen', verbose_name='Feststellungen')),
                ('actions_taken', models.TextField(blank=True, help_text='Reparatur, Austausch, Aussonderung, etc.', verbose_name='Durchgeführte Maßnahmen')),
                ('visual_check', models.BooleanField(default=True, verbose_name='Sichtprüfung OK')),
                ('functionality_check', models.BooleanField(default=True, verbose_name='Funktionsprüfung OK')),
                ('marking_legible', models.BooleanField(default=True, verbose_name='Kennzeichnung lesbar')),
                ('no_damage', models.BooleanField(default=True, verbose_name='Keine Beschädigungen')),
                ('no_wear', models.BooleanField(default=True, verbose_name='Keine übermäßige Abnutzung')),
                ('no_corrosion', models.BooleanField(default=True, verbose_name='Keine Korrosion')),
                ('protocol_file', models.FileField(blank=True, upload_to='height_rescue/inspection_protocols/', verbose_name='Prüfprotokoll (PDF)')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Fotos')),
                ('next_inspection_due', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung fällig')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='height_rescue_inspection_logs', to='personnel.person', verbose_name='Prüfer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_logs', to='height_rescue.heightrescueitem', verbose_name='Ausrüstung')),
            ],
            options={
                'verbose_name': 'Prüfprotokoll Höhenrettung',
                'verbose_name_plural': 'Prüfprotokolle Höhenrettung',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='HeightRescueStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('movement_type', models.CharField(choices=[('incoming', 'Wareneingang'), ('outgoing', 'Warenausgang'), ('transfer', 'Umlagerung'), ('inventory', 'Inventur-Korrektur'), ('damage', 'Beschädigung/Schwund'), ('return', 'Rückgabe'), ('disposal', 'Entsorgung')], max_length=20, verbose_name='Bewegungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('reference_number', models.CharField(blank=True, help_text='z.B. Lieferschein-Nr., Bestellnummer', max_length=100, verbose_name='Referenznummer')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Bewegungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('mission_date', models.DateField(blank=True, null=True, verbose_name='Einsatzdatum')),
                ('mission_type', models.CharField(blank=True, help_text='z.B. Personenrettung, Höhenzugang, Training', max_length=200, verbose_name='Einsatzart')),
                ('fall_arrested', models.BooleanField(default=False, help_text='⚠️ Bei Ja: Ausrüstung MUSS ausgesondert werden!', verbose_name='Sturz aufgefangen')),
                ('fall_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Fallhöhe (m)')),
                ('fall_description', models.TextField(blank=True, verbose_name='Sturzbeschreibung')),
                ('inspection_performed', models.BooleanField(default=False, verbose_name='Prüfung durchgeführt')),
                ('inspection_passed', models.BooleanField(default=True, verbose_name='Prüfung bestanden')),
                ('inspection_notes', models.TextField(blank=True, verbose_name='Prüfnotizen')),
                ('condition_before', models.TextField(blank=True, verbose_name='Zustand vorher')),
                ('condition_after', models.TextField(blank=True, verbose_name='Zustand nachher')),
                ('photos', models.JSONField(blank=True, default=list, verbose_name='Fotos')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_outgoing', to='locations.location', verbose_name='Von Lagerort')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='height_rescue_inspections', to='personnel.person', verbose_name='Prüfer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='height_rescue.heightrescueitem', verbose_name='Ausrüstung')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_incoming', to='locations.location', verbose_name='Nach Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Lagerbewegung Höhenrettung',
                'verbose_name_plural': 'Lagerbewegungen Höhenrettung',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='heightrescueitem',
            index=models.Index(fields=['item_type'], name='height_resc_item_ty_e6d286_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueitem',
            index=models.Index(fields=['next_inspection_date'], name='height_resc_next_in_26a869_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueitem',
            index=models.Index(fields=['inspection_status'], name='height_resc_inspect_d66b13_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueitem',
            index=models.Index(fields=['manufacturing_date'], name='height_resc_manufac_20431b_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueitem',
            index=models.Index(fields=['retirement_date'], name='height_resc_retirem_c18459_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueinspectionlog',
            index=models.Index(fields=['item', 'inspection_date'], name='height_resc_item_id_78f34d_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueinspectionlog',
            index=models.Index(fields=['inspector', 'inspection_date'], name='height_resc_inspect_1376e3_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueinspectionlog',
            index=models.Index(fields=['passed'], name='height_resc_passed_93cdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuestockmovement',
            index=models.Index(fields=['item', 'movement_date'], name='height_resc_item_id_15d26a_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuestockmovement',
            index=models.Index(fields=['fall_arrested'], name='height_resc_fall_ar_911f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuestockmovement',
            index=models.Index(fields=['inspection_performed', 'inspection_passed'], name='height_resc_inspect_405517_idx'),
        ),
    ]
