# Generated by Django 5.0.14 on 2025-10-05 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('height_rescue', '0002_alter_heightrescueitem_unit'),
        ('inventory_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heightrescueitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie'),
        ),
    ]
