# Generated by Django 5.2.7 on 2025-10-06 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('height_rescue', '0003_alter_heightrescueitem_category'),
        ('personnel', '0002_person_id_card_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeightRescueInspectionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_interval_months', models.PositiveIntegerField(blank=True, help_text='Überschreibt Standard-Intervall der Prüfungsart', null=True, verbose_name='Individuelles Intervall (Monate)')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('is_active', models.BooleanField(default=True, help_text='Prüfung wird noch durchgeführt', verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hr_inspection_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_assignments', to='height_rescue.heightrescueitem', verbose_name='Ausrüstung')),
            ],
            options={
                'verbose_name': 'Prüfungszuweisung Höhenrettung',
                'verbose_name_plural': 'Prüfungszuweisungen Höhenrettung',
                'ordering': ['item', 'inspection_type'],
            },
        ),
        migrations.CreateModel(
            name='HeightRescueInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Prüfungsdatum')),
                ('result', models.CharField(choices=[('passed', 'Bestanden'), ('passed_with_remarks', 'Bestanden mit Anmerkungen'), ('failed', 'Nicht bestanden'), ('retired', 'Ausgemustert'), ('incomplete', 'Unvollständig')], max_length=30, verbose_name='Prüfergebnis')),
                ('checklist_results', models.JSONField(blank=True, default=dict, help_text='Detaillierte Ergebnisse der einzelnen Prüfpunkte', verbose_name='Checklisten-Ergebnisse')),
                ('custom_field_values', models.JSONField(blank=True, default=dict, help_text='Werte der benutzerdefinierten Messfelder', verbose_name='Messwerte')),
                ('findings', models.TextField(blank=True, verbose_name='Feststellungen/Mängel')),
                ('recommendations', models.TextField(blank=True, verbose_name='Empfehlungen/Maßnahmen')),
                ('item_retired', models.BooleanField(default=False, help_text='Ausrüstung wurde aufgrund der Prüfung ausgemustert', verbose_name='Ausrüstung ausgemustert')),
                ('retirement_reason', models.TextField(blank=True, verbose_name='Aussonderungsgrund')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung fällig am')),
                ('inspection_sticker_number', models.CharField(blank=True, max_length=100, verbose_name='Prüfplaketten-Nummer')),
                ('inspection_certificate', models.FileField(blank=True, null=True, upload_to='height_rescue/inspection_certificates/', verbose_name='Prüfprotokoll (PDF)')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste der Foto-URLs', verbose_name='Fotos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='height_rescue.heightrescueinspectionassignment', verbose_name='Prüfungszuweisung')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_hr_inspections', to='personnel.person', verbose_name='Prüfer')),
            ],
            options={
                'verbose_name': 'Prüfungsprotokoll Höhenrettung',
                'verbose_name_plural': 'Prüfungsprotokolle Höhenrettung',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='HeightRescueInspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Sichtprüfung, Belastungsprüfung, Jahresprüfung', max_length=200, verbose_name='Prüfungsbezeichnung')),
                ('description', models.TextField(blank=True, help_text='Was wird bei dieser Prüfung geprüft?', verbose_name='Beschreibung')),
                ('inspection_standard', models.CharField(blank=True, help_text='z.B. EN 365, DGUV Vorschrift 3, BetrSichV', max_length=100, verbose_name='Prüfnorm')),
                ('interval_months', models.PositiveIntegerField(blank=True, help_text='Wie oft muss diese Prüfung durchgeführt werden? (Standard: 12)', null=True, verbose_name='Intervall (Monate)')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Liste der zu prüfenden Punkte', verbose_name='Prüfpunkte')),
                ('applicable_item_types', models.JSONField(blank=True, default=list, help_text='Für welche Ausrüstungstypen ist diese Prüfung relevant?', verbose_name='Anwendbar auf Ausrüstungstypen')),
                ('custom_fields', models.JSONField(blank=True, default=list, help_text='Individuelle Felder für Messwerte (z.B. Durchmesser, Länge, Abnutzung)', verbose_name='Benutzerdefinierte Messfelder')),
                ('requires_certification', models.BooleanField(default=False, help_text='Darf nur von zertifizierten Personen durchgeführt werden', verbose_name='Befähigungsnachweis erforderlich')),
                ('requires_external_service', models.BooleanField(default=False, help_text='Muss durch externen Dienstleister durchgeführt werden', verbose_name='Externe Prüfung')),
                ('is_mandatory', models.BooleanField(default=True, help_text='Gesetzlich vorgeschriebene Prüfung (DGUV)', verbose_name='Pflichtprüfung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hr_inspection_types', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Prüfungsart Höhenrettung',
                'verbose_name_plural': 'Prüfungsarten Höhenrettung',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='heightrescueinspectionassignment',
            name='inspection_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_assignments', to='height_rescue.heightrescueinspectiontype', verbose_name='Prüfungsart'),
        ),
        migrations.AlterUniqueTogether(
            name='heightrescueinspectionassignment',
            unique_together={('item', 'inspection_type')},
        ),
    ]
