# Generated by Django 5.2.7 on 2025-10-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('height_rescue', '0005_heightrescuemaintenanceassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='heightrescueitem',
            name='manual_document',
            field=models.FileField(blank=True, help_text='PDF oder Bild (wird per OCR durchsuchbar gemacht)', null=True, upload_to='height_rescue/manuals/%Y/%m/', verbose_name='Handbuch/Dokument'),
        ),
        migrations.AddField(
            model_name='heightrescueitem',
            name='manual_ocr_text',
            field=models.TextField(blank=True, help_text='Automatisch extrahierter Text für Suchfunktion', verbose_name='OCR-Text aus Handbuch'),
        ),
    ]
