# Generated by Django 5.0.14 on 2025-10-17 13:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('height_rescue', '0006_heightrescueitem_manual_document_and_more'),
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0007_add_organization_membership_and_anniversaries'),
        ('vehicles', '0005_vehicle_actual_retirement_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeightRescueItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_number', models.CharField(help_text='Eindeutige Kennzeichnung (z.B. HR-2025-001)', max_length=50, unique=True, verbose_name='Stammdaten-Nummer')),
                ('name', models.CharField(help_text='z.B. Petzl Vertex Helm, Edelrid Rap Line 11mm 50m', max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_type', models.CharField(choices=[('rope', 'Seil'), ('harness', 'Auffanggurt'), ('helmet', 'Helm'), ('carabiner', 'Karabiner'), ('descender', 'Abseilgerät'), ('ascender', 'Steigklemme'), ('pulley', 'Seilrolle'), ('anchor', 'Anschlagpunkt'), ('fall_arrester', 'Falldämpfer'), ('retrieval_device', 'Rettungsgerät'), ('tripod', 'Dreibein'), ('rope_protector', 'Kantenschutz'), ('webbing', 'Bandschlinge'), ('chest_harness', 'Brustgurt'), ('sit_harness', 'Sitzgurt'), ('work_positioning', 'Positionierungsmittel'), ('rescue_stretcher', 'Rettungstrage'), ('edge_roller', 'Kantenrolle'), ('safety_line', 'Sicherheitsleine'), ('belay_device', 'Sicherungsgerät')], max_length=50, verbose_name='Ausrüstungstyp')),
                ('rope_type', models.CharField(blank=True, choices=[('type_a', 'Typ A - Statisches Seil (Rettung)'), ('type_b', 'Typ B - Halbstatisches Seil'), ('dynamic', 'Dynamisches Seil (Klettern)'), ('kernmantle', 'Kernmantelseil'), ('steel_cable', 'Stahlseil')], max_length=50, verbose_name='Seiltyp')),
                ('manufacturer', models.CharField(blank=True, help_text='z.B. Petzl, Edelrid, Kong, DMM', max_length=200, verbose_name='Hersteller')),
                ('model', models.CharField(blank=True, max_length=200, verbose_name='Modell/Artikelnummer')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Liste der Zertifizierungsstandards (z.B. EN 361, EN 1891)', verbose_name='Zertifizierungen')),
                ('certification_number', models.CharField(blank=True, max_length=100, verbose_name='Zertifizierungsnummer')),
                ('max_load_kg', models.PositiveIntegerField(blank=True, help_text='Maximale zulässige Belastung in Kilogramm', null=True, verbose_name='Max. Belastung (kg)')),
                ('breaking_strength_kn', models.DecimalField(blank=True, decimal_places=2, help_text='Bruchfestigkeit in Kilonewton', max_digits=6, null=True, verbose_name='Bruchfestigkeit (kN)')),
                ('working_load_limit_kg', models.PositiveIntegerField(blank=True, help_text='Maximale Arbeitslast (WLL - Working Load Limit)', null=True, verbose_name='Arbeitslast (kg)')),
                ('rope_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Seillänge (m)')),
                ('rope_diameter_mm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Seildurchmesser (mm)')),
                ('max_service_life_years', models.PositiveIntegerField(blank=True, help_text='Maximale Nutzungsdauer laut Hersteller', null=True, verbose_name='Max. Nutzungsdauer (Jahre)')),
                ('inspection_interval_months', models.PositiveIntegerField(default=12, help_text='Standard: 12 Monate nach DGUV', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Prüfintervall (Monate)')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Durchschnittlicher Einkaufspreis', max_digits=10, null=True, verbose_name='Einkaufspreis (€)')),
                ('manual_document', models.FileField(blank=True, help_text='PDF oder Bild', null=True, upload_to='height_rescue/masters/manuals/%Y/%m/', verbose_name='Handbuch/Bedienungsanleitung')),
                ('image', models.ImageField(blank=True, null=True, upload_to='height_rescue/masters/images/%Y/%m/', verbose_name='Produktbild')),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen, Besonderheiten', verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hr_masters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Höhenrettungs-Stammdaten',
                'verbose_name_plural': 'Höhenrettungs-Stammdaten',
                'ordering': ['item_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HeightRescueDeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(help_text='Eindeutige Inventarnummer (z.B. HR-INV-2025-042)', max_length=100, unique=True, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(blank=True, help_text='Seriennummer des Herstellers', max_length=200, verbose_name='Seriennummer')),
                ('manufacturing_date', models.DateField(blank=True, help_text='Wichtig für Alterungsberechnung', null=True, verbose_name='Herstellungsdatum')),
                ('first_use_date', models.DateField(blank=True, help_text='Datum der ersten Nutzung', null=True, verbose_name='Erste Inbetriebnahme')),
                ('retirement_date', models.DateField(blank=True, help_text='Datum der geplanten oder erfolgten Aussonderung', null=True, verbose_name='Aussonderungsdatum')),
                ('retirement_reason', models.TextField(blank=True, help_text='Grund für Aussonderung (z.B. Sturz, Beschädigung, Alter)', verbose_name='Aussonderungsgrund')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, help_text='Mindestens jährlich nach DGUV', null=True, verbose_name='Nächste Prüfung')),
                ('inspection_status', models.CharField(choices=[('not_due', 'Nicht fällig'), ('due_soon', 'Demnächst fällig'), ('overdue', 'Überfällig'), ('failed', 'Nicht bestanden'), ('passed', 'Bestanden'), ('retired', 'Ausgemustert')], default='not_due', max_length=20, verbose_name='Prüfstatus')),
                ('inspection_report', models.FileField(blank=True, upload_to='height_rescue/devices/inspection_reports/%Y/%m/', verbose_name='Prüfprotokoll')),
                ('total_falls_arrested', models.PositiveIntegerField(default=0, help_text='⚠️ Wichtig: Nach Sturz meist Aussonderung!', verbose_name='Anzahl Stürze aufgefangen')),
                ('total_uses', models.PositiveIntegerField(default=0, verbose_name='Anzahl Einsätze')),
                ('last_use_date', models.DateField(blank=True, null=True, verbose_name='Letzter Einsatz')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('fair', 'Befriedigend'), ('poor', 'Schlecht'), ('defective', 'Defekt'), ('retired', 'Ausgemustert')], default='good', max_length=20, verbose_name='Zustand')),
                ('condition_notes', models.TextField(blank=True, help_text='Beschädigungen, Abnutzung, etc.', verbose_name='Zustandsnotizen')),
                ('is_operational', models.BooleanField(default=True, help_text='Gerät ist einsatzbereit', verbose_name='Einsatzbereit')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Pfade zu Fotos für Zustandsdokumentation', verbose_name='Fotos')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hr_devices', to='personnel.person', verbose_name='Zugeordnet an')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='height_rescue_devices', to='vehicles.vehicle', verbose_name='Zugeordnetes Fahrzeug')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_hr_devices', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('last_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_hr_devices', to='personnel.person', verbose_name='Letzter Prüfer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='height_rescue_devices', to='locations.location', verbose_name='Lagerort')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_instances', to='height_rescue.heightrescueitemmaster', verbose_name='Stammdaten')),
            ],
            options={
                'verbose_name': 'Höhenrettungsgerät-Instanz',
                'verbose_name_plural': 'Höhenrettungsgerät-Instanzen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='heightrescueitemmaster',
            index=models.Index(fields=['master_number'], name='height_resc_master__ef235d_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueitemmaster',
            index=models.Index(fields=['item_type'], name='height_resc_item_ty_510bde_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueitemmaster',
            index=models.Index(fields=['manufacturer'], name='height_resc_manufac_833d14_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescueitemmaster',
            index=models.Index(fields=['is_active'], name='height_resc_is_acti_aa4999_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['inventory_number'], name='height_resc_invento_113358_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['serial_number'], name='height_resc_serial__695df0_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['master', 'is_active'], name='height_resc_master__2181cb_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['location'], name='height_resc_locatio_23a3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['next_inspection_date'], name='height_resc_next_in_3e2ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['inspection_status'], name='height_resc_inspect_9a3a98_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['manufacturing_date'], name='height_resc_manufac_d9bb14_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['retirement_date'], name='height_resc_retirem_63ea06_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['assigned_vehicle'], name='height_resc_assigne_77fba4_idx'),
        ),
        migrations.AddIndex(
            model_name='heightrescuedeviceinstance',
            index=models.Index(fields=['assigned_to'], name='height_resc_assigne_b80f7d_idx'),
        ),
    ]
