# Generated by Django 5.0.14 on 2025-10-22 10:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('height_rescue', '0008_alter_heightrescueitem_location'),
        ('locations', '0003_location_technical_equipment'),
        ('personnel', '0015_person_show_private_contact_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HeightRescueInventoryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('check_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Inventur-Nummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('check_type', models.CharField(choices=[('full', 'Vollinventur'), ('partial', 'Teilinventur'), ('spot_check', 'Stichprobe'), ('cycle_count', 'Zykluszählung'), ('annual', 'Jahresinventur')], default='partial', max_length=20, verbose_name='Inventurart')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Bearbeitung'), ('counting_complete', 'Zählung abgeschlossen'), ('review', 'In Prüfung'), ('adjustments_pending', 'Korrekturen ausstehend'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='planned', max_length=30, verbose_name='Status')),
                ('scheduled_start_date', models.DateField(verbose_name='Geplanter Start')),
                ('scheduled_end_date', models.DateField(verbose_name='Geplantes Ende')),
                ('actual_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächlicher Start')),
                ('actual_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Tatsächliches Ende')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Gesamt-Anzahl Artikel')),
                ('counted_items', models.PositiveIntegerField(default=0, verbose_name='Gezählte Artikel')),
                ('items_with_discrepancies', models.PositiveIntegerField(default=0, verbose_name='Artikel mit Abweichungen')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('check_inspections', models.BooleanField(default=True, help_text='DGUV Vorschrift 3 - Jährliche Prüfpflicht!', verbose_name='Prüffristen kontrollieren')),
                ('check_age_limits', models.BooleanField(default=True, help_text='PSA-Alterung und maximale Nutzungsdauer', verbose_name='Altersgrenzen prüfen')),
                ('check_rope_condition', models.BooleanField(default=True, help_text='Abnutzung, Beschädigungen, Kernschäden', verbose_name='Seilzustand prüfen')),
                ('check_retirement', models.BooleanField(default=True, help_text='Nach Sturz oder Beschädigung auszusondern', verbose_name='Aussonderungspflichtige Geräte')),
                ('inspection_overdue_found', models.PositiveIntegerField(default=0, help_text='Anzahl Geräte mit überfälliger Prüfung', verbose_name='Prüfungen überfällig')),
                ('age_limit_exceeded_found', models.PositiveIntegerField(default=0, help_text='Anzahl Geräte über max. Nutzungsdauer', verbose_name='Altersgrenze überschritten')),
                ('rope_damage_found', models.PositiveIntegerField(default=0, help_text='Anzahl beschädigter Seile', verbose_name='Seilschäden gefunden')),
                ('retirement_required_found', models.PositiveIntegerField(default=0, help_text='Anzahl auszusondernder Geräte', verbose_name='Aussonderung erforderlich')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_approved', to='personnel.person', verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(blank=True, help_text='Leer = Alle Lagerorte', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_checks', to='locations.location', verbose_name='Lagerort')),
                ('responsible_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_responsible', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('team_members', models.ManyToManyField(blank=True, related_name='%(app_label)s_%(class)s_team', to='personnel.person', verbose_name='Team-Mitglieder')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Höhenrettungs-Inventur',
                'verbose_name_plural': 'Höhenrettungs-Inventuren',
                'ordering': ['-created_at'],
                'permissions': [('approve_heightrescueinventorycheck', 'Kann Höhenrettungs-Inventur genehmigen')],
            },
        ),
        migrations.CreateModel(
            name='HeightRescueInventoryCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('item_name', models.CharField(max_length=200, verbose_name='Artikelbezeichnung')),
                ('item_number', models.CharField(blank=True, max_length=100, verbose_name='Artikelnummer')),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sollbestand')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Istbestand')),
                ('is_counted', models.BooleanField(default=False, verbose_name='Gezählt')),
                ('counted_date', models.DateTimeField(blank=True, null=True, verbose_name='Zähldatum')),
                ('has_discrepancy', models.BooleanField(default=False, verbose_name='Abweichung')),
                ('variance_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Differenz')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('requires_recount', models.BooleanField(default=False, verbose_name='Nachzählung erforderlich')),
                ('inventory_number', models.CharField(blank=True, max_length=100, verbose_name='Inventarnummer')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='Seriennummer')),
                ('item_type', models.CharField(blank=True, max_length=50, verbose_name='Gerätetyp')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Letzte Prüfung')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Nächste Prüfung')),
                ('inspection_overdue', models.BooleanField(default=False, help_text='Prüffrist abgelaufen', verbose_name='Prüfung überfällig')),
                ('inspection_status', models.CharField(blank=True, max_length=20, verbose_name='Prüfstatus')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='Herstellungsdatum')),
                ('first_use_date', models.DateField(blank=True, null=True, verbose_name='Erste Inbetriebnahme')),
                ('age_in_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Alter (Jahre)')),
                ('age_limit_exceeded', models.BooleanField(default=False, verbose_name='Altersgrenze überschritten')),
                ('rope_length', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Seillänge (m)')),
                ('rope_diameter', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Seildurchmesser (mm)')),
                ('rope_damage_found', models.BooleanField(default=False, verbose_name='Seilschaden gefunden')),
                ('retirement_date', models.DateField(blank=True, null=True, verbose_name='Aussonderungsdatum')),
                ('retirement_required', models.BooleanField(default=False, verbose_name='Aussonderung erforderlich')),
                ('retirement_reason', models.TextField(blank=True, verbose_name='Aussonderungsgrund')),
                ('operational_status', models.CharField(blank=True, max_length=20, verbose_name='Einsatzstatus')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_counted', to='personnel.person', verbose_name='Gezählt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('height_rescue_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='height_rescue.heightrescuedeviceinstance', verbose_name='Höhenrettungsgerät')),
                ('inventory_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='height_rescue.heightrescueinventorycheck', verbose_name='Inventur')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Höhenrettungs-Inventur-Position',
                'verbose_name_plural': 'Höhenrettungs-Inventur-Positionen',
                'ordering': ['item_name', 'inventory_number'],
            },
        ),
    ]
