# Generated by Django 5.0.14 on 2025-11-03 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('height_rescue', '0009_heightrescueinventorycheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heightrescueitemmaster',
            name='item_type',
            field=models.CharField(blank=True, choices=[('rope', 'Seil'), ('harness', 'Auffanggurt'), ('helmet', 'Helm'), ('carabiner', 'Karabiner'), ('descender', 'Abseilgerät'), ('ascender', 'Steigklemme'), ('pulley', 'Seilrolle'), ('anchor', 'Anschlagpunkt'), ('fall_arrester', 'Falldämpfer'), ('retrieval_device', 'Rettungsgerät'), ('tripod', 'Dreibein'), ('rope_protector', 'Kantenschutz'), ('webbing', 'Bandschlinge'), ('chest_harness', 'Brustgurt'), ('sit_harness', 'Sitzgurt'), ('work_positioning', 'Positionierungsmittel'), ('rescue_stretcher', 'Rettungstrage'), ('edge_roller', 'Kantenrolle'), ('safety_line', 'Sicherheitsleine'), ('belay_device', 'Sicherungsgerät')], max_length=50, null=True, verbose_name='Ausrüstungstyp (Legacy)'),
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Eindeutiger Code für den Typ (z.B. rope, harness)', max_length=50, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text='Anzeigename des Typs (z.B. Seil, Auffanggurt)', max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, help_text='Optionale Beschreibung des Typs', verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, help_text='Inaktive Typen werden nicht mehr angezeigt', verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, help_text='Reihenfolge in der Anzeige', verbose_name='Sortierung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ausrüstungstyp',
                'verbose_name_plural': 'Ausrüstungstypen',
                'db_table': 'height_rescue_equipment_type',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['code'], name='height_resc_code_a1187c_idx'), models.Index(fields=['is_active'], name='height_resc_is_acti_8807a0_idx')],
            },
        ),
        migrations.AddField(
            model_name='heightrescueitemmaster',
            name='equipment_type',
            field=models.ForeignKey(blank=True, help_text='Typ aus der Typenverwaltung', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='master_items', to='height_rescue.equipmenttype', verbose_name='Ausrüstungstyp'),
        ),
    ]
