# Generated by Django 5.0.14 on 2025-11-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('height_rescue', '0010_add_equipment_type_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='heightrescuedeviceinstance',
            name='custom_barcode',
            field=models.CharField(blank=True, help_text='Falls leer, wird automatisch generiert aus Stammdaten-Nr + Inventar-Nr + Seriennummer', max_length=200, verbose_name='Benutzerdefinierter Barcode'),
        ),
    ]
