# Generated by Django 5.0.14 on 2025-10-03 09:44

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='Bezeichnung des Lagerorts', max_length=200, verbose_name='Name')),
                ('code', models.CharField(help_text='Eindeutiger Code (z.B. FWN-GH-R1-FA)', max_length=50, unique=True, verbose_name='Kennzeichen/Code')),
                ('location_type', models.CharField(choices=[('building', 'Gebäude'), ('room', 'Raum'), ('rack', 'Regal'), ('shelf', 'Regalboden'), ('box', 'Kiste/Box'), ('vehicle', 'Fahrzeug'), ('container', 'Container'), ('outdoor', 'Außenbereich'), ('other', 'Sonstiges')], default='room', help_text='Art des Lagerorts', max_length=20, verbose_name='Typ')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('description', models.TextField(blank=True, help_text='Zusätzliche Informationen zum Lagerort', verbose_name='Beschreibung')),
                ('capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximale Kapazität (z.B. Volumen in m³, Gewicht in kg)', max_digits=10, null=True, verbose_name='Kapazität')),
                ('capacity_unit', models.CharField(blank=True, help_text='Einheit der Kapazität (z.B. m³, kg, Stück)', max_length=20, verbose_name='Einheit')),
                ('access_restricted', models.BooleanField(default=False, help_text='Ist der Zugriff auf diesen Lagerort beschränkt?', verbose_name='Zugriff beschränkt')),
                ('access_instructions', models.TextField(blank=True, help_text='Informationen zum Zugang (z.B. Schlüsselnummer, Türcode)', verbose_name='Zugangshinweise')),
                ('climate_controlled', models.BooleanField(default=False, help_text='Ist der Lagerort klimatisiert?', verbose_name='Klimatisiert')),
                ('temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Min. Temperatur (°C)')),
                ('temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max. Temperatur (°C)')),
                ('qr_code', models.ImageField(blank=True, help_text='QR-Code für mobilen Zugriff', null=True, upload_to='locations/qr_codes/', verbose_name='QR-Code')),
                ('is_active', models.BooleanField(default=True, help_text='Ist der Lagerort aktiv und nutzbar?', verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, help_text='Interne Notizen', verbose_name='Notizen')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Übergeordneter Lagerort in der Hierarchie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.location', verbose_name='Übergeordneter Standort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Lagerort',
                'verbose_name_plural': 'Lagerorte',
                'ordering': ['tree_id', 'lft'],
                'indexes': [models.Index(fields=['code'], name='locations_l_code_b786f2_idx'), models.Index(fields=['location_type'], name='locations_l_locatio_aa6df5_idx'), models.Index(fields=['is_active'], name='locations_l_is_acti_9f2958_idx'), models.Index(fields=['tree_id', 'lft'], name='locations_location_tree_idf932')],
            },
        ),
    ]
