# Generated by Django 5.0.14 on 2025-10-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('site', 'Standort/Wache'), ('building', 'Gebäude'), ('area', 'Stellfläche/Außenbereich'), ('room', 'Raum'), ('parking_spot', 'Stellplatz'), ('rack', 'Regal/Schrank'), ('cabinet', 'Schrank'), ('shelf', 'Regalboden/Fach'), ('drawer', 'Schublade'), ('box', 'Kiste/Box'), ('vehicle', 'Fahrzeug (mobil)'), ('container', 'Container'), ('other', 'Sonstiges')], default='room', help_text='Art des Lagerorts', max_length=20, verbose_name='Typ'),
        ),
    ]
