# Generated by Django 5.0.14 on 2025-10-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_location_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='technical_equipment',
            field=models.TextField(blank=True, help_text='Vorhandene Technik (z.B. Beamer, Prowise-Board, Soundsystem)', verbose_name='Technische Ausstattung'),
        ),
    ]
