# Generated by Django 5.0.14 on 2026-02-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_technical_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='barcode',
            field=models.CharField(blank=True, help_text='Benutzerdefinierter Barcode. Falls leer, wird aus Code + Raumnummer generiert.', max_length=200, verbose_name='Barcode'),
        ),
        migrations.AddField(
            model_name='location',
            name='room_number',
            field=models.CharField(blank=True, help_text='Raumnummer (z.B. R.102) - wird an Unter-Lagerorte vererbt', max_length=50, verbose_name='Raumnummer'),
        ),
    ]
