# Generated by Django 5.0.14 on 2026-02-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_add_vehicle_hall_type'),
        ('vehicles', '0010_cleanup_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='linked_vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_entry', to='vehicles.vehicle', verbose_name='Verknüpftes Fahrzeug'),
        ),
    ]
