# Generated by Django 5.0.14 on 2026-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_location_linked_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='bereich',
            field=models.CharField(blank=True, choices=[('bund', 'Bund'), ('land', 'Land'), ('kommune', 'Kommune')], help_text='Bund/Land/Kommune', max_length=30, verbose_name='Bereich'),
        ),
        migrations.AddField(
            model_name='location',
            name='bvs_status',
            field=models.CharField(blank=True, choices=[('aktiv', 'Aktiv'), ('inaktiv', 'Inaktiv'), ('geplant', 'Geplant'), ('voruebergehend_geschlossen', 'Vorübergehend geschlossen')], help_text='Status für NIP/Leuchtturm', max_length=40, verbose_name='BvS-Status'),
        ),
        migrations.AddField(
            model_name='location',
            name='capacity_persons',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kapazität (Personen)'),
        ),
        migrations.AddField(
            model_name='location',
            name='communication_available',
            field=models.BooleanField(default=False, verbose_name='Kommunikation vorhanden'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ansprechpartner'),
        ),
        migrations.AddField(
            model_name='location',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='location',
            name='heating_available',
            field=models.BooleanField(default=False, verbose_name='Heizung vorhanden'),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad'),
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.TextField(blank=True, verbose_name='Öffnungszeiten'),
        ),
        migrations.AddField(
            model_name='location',
            name='power_supply_available',
            field=models.BooleanField(default=False, verbose_name='Stromversorgung vorhanden'),
        ),
        migrations.AddField(
            model_name='location',
            name='water_supply_available',
            field=models.BooleanField(default=False, verbose_name='Wasserversorgung vorhanden'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('site', 'Standort/Wache'), ('building', 'Gebäude'), ('area', 'Stellfläche/Außenbereich'), ('vehicle_hall', 'Fahrzeughalle'), ('room', 'Raum'), ('parking_spot', 'Stellplatz'), ('rack', 'Regal/Schrank'), ('cabinet', 'Schrank'), ('shelf', 'Regalboden/Fach'), ('drawer', 'Schublade'), ('box', 'Kiste/Box'), ('vehicle', 'Fahrzeug (mobil)'), ('container', 'Container'), ('nip', 'Notfallinformationspunkt (NIP)'), ('leuchtturm', 'Leuchtturmstandort'), ('other', 'Sonstiges')], default='room', help_text='Art des Lagerorts', max_length=30, verbose_name='Typ'),
        ),
    ]
