# Generated by Django 5.0.14 on 2026-02-20 08:56

from django.db import migrations


def migrate_nip_leuchtturm(apps, schema_editor):
    """
    Migrate existing Notfallinformationspunkt and Leuchtturmstandort records
    to Location objects with appropriate location_type.
    """
    Location = apps.get_model('locations', 'Location')
    Notfallinformationspunkt = apps.get_model('civil_protection', 'Notfallinformationspunkt')
    Leuchtturmstandort = apps.get_model('civil_protection', 'Leuchtturmstandort')

    # Find the next available tree_id
    from django.db.models import Max
    max_tree_id = Location.objects.aggregate(m=Max('tree_id'))['m'] or 0
    next_tree_id = max_tree_id + 1

    # Migrate NIPs
    for nip in Notfallinformationspunkt.objects.all():
        code = f'NIP-{nip.pk}'
        counter = 1
        while Location.objects.filter(code=code).exists():
            code = f'NIP-{nip.pk}-{counter}'
            counter += 1

        loc = Location.objects.create(
            code=code,
            name=nip.name,
            location_type='nip',
            street=nip.address_street,
            postal_code=nip.address_postal_code,
            city=nip.address_city,
            latitude=nip.latitude,
            longitude=nip.longitude,
            contact_name=nip.contact_name,
            contact_phone=nip.contact_phone,
            contact_email=nip.contact_email,
            opening_hours=nip.opening_hours or '',
            capacity_persons=nip.capacity_persons,
            bvs_status=nip.status or 'geplant',
            bereich=nip.bereich or '',
            notes=nip.notes or '',
            description=nip.description or '',
            is_active=nip.is_active,
            # MPTT fields - root node (leaf)
            parent=None,
            level=0,
            lft=1,
            rght=2,
            tree_id=next_tree_id,
        )
        next_tree_id += 1

        # Update equipment instances to point to new location
        for eq in nip.assigned_equipment.all():
            eq.location = loc
            eq.save()

        # Update vehicles to point to new location
        for v in nip.assigned_vehicles.all():
            v.location = loc
            v.save()

    # Migrate Leuchtturm
    for lt in Leuchtturmstandort.objects.all():
        code = f'LT-{lt.pk}'
        counter = 1
        while Location.objects.filter(code=code).exists():
            code = f'LT-{lt.pk}-{counter}'
            counter += 1

        loc = Location.objects.create(
            code=code,
            name=lt.name,
            location_type='leuchtturm',
            street=lt.address_street,
            postal_code=lt.address_postal_code,
            city=lt.address_city,
            latitude=lt.latitude,
            longitude=lt.longitude,
            contact_name=lt.contact_name,
            contact_phone=lt.contact_phone,
            contact_email=lt.contact_email,
            opening_hours=lt.opening_hours or '',
            capacity_persons=lt.capacity_persons,
            bvs_status=lt.status or 'geplant',
            bereich=lt.bereich or '',
            power_supply_available=lt.power_supply_available,
            heating_available=lt.heating_available,
            water_supply_available=lt.water_supply_available,
            communication_available=lt.communication_available,
            notes=lt.notes or '',
            description=lt.description or '',
            is_active=lt.is_active,
            # MPTT fields - root node (leaf)
            parent=None,
            level=0,
            lft=1,
            rght=2,
            tree_id=next_tree_id,
        )
        next_tree_id += 1

        # Update equipment instances to point to new location
        for eq in lt.assigned_equipment.all():
            eq.location = loc
            eq.save()

        # Update vehicles to point to new location
        for v in lt.assigned_vehicles.all():
            v.location = loc
            v.save()


def reverse_migration(apps, schema_editor):
    """Remove migrated NIP/Leuchtturm Location entries."""
    Location = apps.get_model('locations', 'Location')
    Location.objects.filter(location_type__in=['nip', 'leuchtturm']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_location_bereich_location_bvs_status_and_more'),
        ('civil_protection', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_nip_leuchtturm, reverse_migration),
    ]
