# Generated by Django 5.0.14 on 2025-12-01 08:36

import django.db.models.deletion
from django.db import migrations, models


# Die alten Kategorien mit ihren Daten
OLD_CATEGORIES = [
    {'slug': 'general', 'name': 'Allgemein', 'icon': '📋', 'color': '#6B7280', 'order': 1},
    {'slug': 'it', 'name': 'IT & Technik', 'icon': '💻', 'color': '#3B82F6', 'order': 2},
    {'slug': 'equipment', 'name': 'Ausrüstung', 'icon': '🧰', 'color': '#F59E0B', 'order': 3},
    {'slug': 'vehicle', 'name': 'Fahrzeuge', 'icon': '🚒', 'color': '#EF4444', 'order': 4},
    {'slug': 'facility', 'name': 'Gebäude & Räume', 'icon': '🏢', 'color': '#8B5CF6', 'order': 5},
    {'slug': 'personnel', 'name': 'Personal', 'icon': '👥', 'color': '#10B981', 'order': 6},
    {'slug': 'other', 'name': 'Sonstiges', 'icon': '📁', 'color': '#6B7280', 'order': 7},
]


def create_categories_and_migrate(apps, schema_editor):
    """Erstellt die Kategorien und migriert bestehende Tickets"""
    TicketCategory = apps.get_model('tickets', 'TicketCategory')
    Ticket = apps.get_model('tickets', 'Ticket')

    # Erstelle die Kategorien
    category_map = {}
    for cat_data in OLD_CATEGORIES:
        cat, created = TicketCategory.objects.get_or_create(
            slug=cat_data['slug'],
            defaults={
                'name': cat_data['name'],
                'icon': cat_data['icon'],
                'color': cat_data['color'],
                'order': cat_data['order'],
                'is_active': True,
            }
        )
        category_map[cat_data['slug']] = cat

    # Migriere bestehende Tickets
    for ticket in Ticket.objects.all():
        if ticket.category_old and ticket.category_old in category_map:
            ticket.category = category_map[ticket.category_old]
            ticket.save()
        elif not ticket.category:
            # Fallback zu 'Allgemein'
            ticket.category = category_map.get('general')
            ticket.save()


def reverse_migration(apps, schema_editor):
    """Umkehrmigration - speichert Kategorie-Slug zurück in category_old"""
    Ticket = apps.get_model('tickets', 'Ticket')

    for ticket in Ticket.objects.select_related('category').all():
        if ticket.category:
            ticket.category_old = ticket.category.slug
            ticket.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_add_ticket_and_comment_images'),
    ]

    operations = [
        # 1. Erstelle das neue TicketCategory Model
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('icon', models.CharField(blank=True, default='📋', help_text='Emoji für die Kategorie', max_length=50, verbose_name='Icon')),
                ('color', models.CharField(default='#6B7280', help_text='Hex-Farbcode (z.B. #3B82F6)', max_length=7, verbose_name='Farbe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Ticket-Kategorie',
                'verbose_name_plural': 'Ticket-Kategorien',
                'ordering': ['order', 'name'],
            },
        ),

        # 2. Benenne das alte category-Feld um
        migrations.RenameField(
            model_name='ticket',
            old_name='category',
            new_name='category_old',
        ),

        # 3. Füge das neue category ForeignKey-Feld hinzu
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tickets',
                to='tickets.ticketcategory',
                verbose_name='Kategorie'
            ),
        ),

        # 4. Datenmigration: Erstelle Kategorien und migriere Tickets
        migrations.RunPython(create_categories_and_migrate, reverse_migration),

        # 5. Entferne das alte category_old Feld
        migrations.RemoveField(
            model_name='ticket',
            name='category_old',
        ),
    ]
