# Generated by Django 5.0.14 on 2026-02-19 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_add_watch_division'),
        ('tickets', '0003_convert_category_to_model'),
        ('vehicles', '0013_alter_vehicle_rubrik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bereitschaft_o_amt', models.CharField(blank=True, max_length=200, verbose_name='Ordnungsamt')),
                ('bereitschaft_g_amt', models.CharField(blank=True, max_length=200, verbose_name='Gesundheitsamt')),
                ('bereitschaft_veterinaeramt', models.CharField(blank=True, max_length=200, verbose_name='Veterinäramt')),
                ('bereitschaft_vet_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Veterinäramt Datum/Uhrzeit')),
                ('personal_fw1_loeschzug', models.PositiveIntegerField(default=0, verbose_name='FW1 Löschzug')),
                ('personal_fw1_ergaenzung', models.PositiveIntegerField(default=0, verbose_name='FW1 Ergänzung')),
                ('personal_fw1_5_rtw', models.PositiveIntegerField(default=0, verbose_name='FW1 RTW')),
                ('personal_fw1_ktw', models.PositiveIntegerField(default=0, verbose_name='FW1 KTW')),
                ('personal_fw1_taucher', models.PositiveIntegerField(default=0, verbose_name='FW1 Taucher')),
                ('personal_fw1_hoehenretter', models.PositiveIntegerField(default=0, verbose_name='FW1 Höhenretter')),
                ('personal_fw2_loeschzug', models.PositiveIntegerField(default=0, verbose_name='FW2 Löschzug')),
                ('personal_fw2_ergaenzung', models.PositiveIntegerField(default=0, verbose_name='FW2 Ergänzung')),
                ('personal_fw2_5_rtw', models.PositiveIntegerField(default=0, verbose_name='FW2 RTW')),
                ('personal_fw2_ktw', models.PositiveIntegerField(default=0, verbose_name='FW2 KTW')),
                ('personal_fw2_taucher', models.PositiveIntegerField(default=0, verbose_name='FW2 Taucher')),
                ('personal_fw2_hoehenretter', models.PositiveIntegerField(default=0, verbose_name='FW2 Höhenretter')),
                ('geraete', models.TextField(blank=True, verbose_name='Geräte')),
                ('sonstiges_1', models.TextField(blank=True, verbose_name='Sonstiges 1')),
                ('sonstiges_2', models.TextField(blank=True, verbose_name='Sonstiges 2')),
                ('sonstiges_3', models.TextField(blank=True, verbose_name='Sonstiges 3')),
                ('sonstiges_4', models.TextField(blank=True, verbose_name='Sonstiges 4')),
                ('sonstiges_5', models.TextField(blank=True, verbose_name='Sonstiges 5')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('bereitschaft_c_dienst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='personnel.person', verbose_name='C-Dienst')),
                ('bereitschaft_lna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='personnel.person', verbose_name='LNA')),
                ('ersetzt_mit_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle', verbose_name='Ersetzt mit 1')),
                ('ersetzt_mit_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle', verbose_name='Ersetzt mit 2')),
                ('ersetzt_mit_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle', verbose_name='Ersetzt mit 3')),
                ('fahrzeug_ad_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle', verbose_name='Außer Dienst 1')),
                ('fahrzeug_ad_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle', verbose_name='Außer Dienst 2')),
                ('fahrzeug_ad_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle', verbose_name='Außer Dienst 3')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Info-Monitor',
                'verbose_name_plural': 'Info-Monitor',
                'permissions': [('edit_infomonitor', 'Kann LST Infomonitor bearbeiten')],
            },
        ),
    ]
