# Generated by Django 5.0.14 on 2026-02-19 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_infomonitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BereitschaftPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Bereitschaftsperson',
                'verbose_name_plural': 'Bereitschaftspersonen',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='bereitschaft_c_dienst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='C-Dienst'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='bereitschaft_lna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='LNA'),
        ),
    ]
