# Generated by Django 5.0.14 on 2026-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_bereitschaft_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='bereitschaftperson',
            name='kategorie',
            field=models.CharField(choices=[('c_dienst', 'C-Dienst'), ('lna', 'LNA'), ('ordnungsamt', 'Ordnungsamt'), ('gesundheitsamt', 'Gesundheitsamt'), ('veterinaeramt', 'Veterinäramt')], default='c_dienst', max_length=20, verbose_name='Kategorie'),
        ),
        # Alte CharField-Spalten entfernen (Daten sind nicht mehr relevant)
        migrations.RemoveField(
            model_name='infomonitor',
            name='bereitschaft_o_amt',
        ),
        migrations.RemoveField(
            model_name='infomonitor',
            name='bereitschaft_g_amt',
        ),
        migrations.RemoveField(
            model_name='infomonitor',
            name='bereitschaft_veterinaeramt',
        ),
    ]
