# Generated by Django 5.0.14 on 2026-02-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_bereitschaft_kategorie_und_fk'),
    ]

    operations = [
        # Neue FK-Spalten hinzufügen
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_o_amt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='Ordnungsamt'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_g_amt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='Gesundheitsamt'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_veterinaeramt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='Veterinäramt'),
        ),
    ]
