# Generated by Django 5.0.14 on 2026-02-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_infomonitor_bereitschaft_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappeAnleitung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Anleitung / Maßnahme',
                'verbose_name_plural': 'Anleitungen / Maßnahmen',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MappeKontakt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('funktion', models.CharField(max_length=200, verbose_name='Funktion / Rolle')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Wichtiger Ansprechpartner',
                'verbose_name_plural': 'Wichtige Ansprechpartner',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MappeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Wichtiger Link',
                'verbose_name_plural': 'Wichtige Links',
                'ordering': ['order', 'title'],
            },
        ),
    ]
