# Generated by Django 5.0.14 on 2026-02-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_mappeanleitung_mappekontakt_mappelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitor',
            name='hoehenretter_im_dienst',
            field=models.BooleanField(default=False, verbose_name='Höhenretter im Dienst'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='taucher_im_dienst',
            field=models.BooleanField(default=False, verbose_name='Taucher im Dienst'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw1_5_rtw',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW1 RTW'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw1_ergaenzung',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW1 Ergänzung'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw1_hoehenretter',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW1 Höhenretter'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw1_ktw',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW1 KTW'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw1_loeschzug',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW1 Löschzug'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw1_taucher',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW1 Taucher'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw2_5_rtw',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW2 RTW'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw2_ergaenzung',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW2 Ergänzung'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw2_hoehenretter',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW2 Höhenretter'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw2_ktw',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW2 KTW'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw2_loeschzug',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW2 Löschzug'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='personal_fw2_taucher',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='FW2 Taucher'),
        ),
    ]
