# Generated by Django 5.0.14 on 2026-02-23 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_create_grossveranstaltungen_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomonitorvehicle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='GrossveranstaltungDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('dashboard_type', models.CharField(choices=[('pdf', 'PDF-Dokument'), ('dynamic', 'Dynamisches Layout')], default='dynamic', max_length=10, verbose_name='Dashboard-Typ')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='grossveranstaltungen/pdfs/%Y/%m/', verbose_name='PDF-Datei')),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='grossveranstaltungen/maps/%Y/%m/', verbose_name='Kartenausschnitt')),
                ('einheiten_text', models.TextField(blank=True, verbose_name='Einheiten / Fahrzeuge')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Großveranstaltung-Dashboard',
                'verbose_name_plural': 'Großveranstaltung-Dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrossveranstaltungAbschnitt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Überschrift')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abschnitte', to='tickets.grossveranstaltungdashboard', verbose_name='Dashboard')),
            ],
            options={
                'verbose_name': 'Dashboard-Abschnitt',
                'verbose_name_plural': 'Dashboard-Abschnitte',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
