# Generated by Django 5.0.14 on 2026-02-23 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_infomonitorvehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infomonitor',
            options={'permissions': [('edit_infomonitor', 'Kann LST Infomonitor bearbeiten'), ('edit_mappe', 'Kann Digitale Mappe bearbeiten')], 'verbose_name': 'Info-Monitor', 'verbose_name_plural': 'Info-Monitor'},
        ),
    ]
