# Generated by Django 5.0.14 on 2026-02-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_infomonitor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_c_dienst_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='C-Dienst geändert am'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_g_amt_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gesundheitsamt geändert am'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_lna_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='LNA geändert am'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_o_amt_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ordnungsamt geändert am'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_veterinaeramt_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Veterinäramt geändert am'),
        ),
    ]
