# Generated by Django 5.0.14 on 2026-02-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_add_bereitschaft_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossveranstaltungdashboard',
            name='info_datei',
            field=models.FileField(blank=True, help_text='Funkskizze, Lagekarte o.ä. als Bild oder PDF', null=True, upload_to='grossveranstaltungen/info/%Y/%m/', verbose_name='Info-Datei (Bild/PDF)'),
        ),
    ]
