# Generated by Django 5.0.14 on 2026-02-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_add_info_datei_to_gv_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoMonitorSonstiges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitor_sonstiges', to='tickets.infomonitor', verbose_name='Info-Monitor')),
            ],
            options={
                'verbose_name': 'Info-Monitor Sonstiges',
                'verbose_name_plural': 'Info-Monitor Sonstiges',
                'ordering': ['position'],
            },
        ),
    ]
