# Generated by Django 5.0.14 on 2026-02-23 12:06

from django.db import migrations


def migrate_sonstiges_data(apps, schema_editor):
    """Migriert bestehende sonstiges_1..5 Daten in die neue InfoMonitorSonstiges-Tabelle."""
    InfoMonitor = apps.get_model('tickets', 'InfoMonitor')
    InfoMonitorSonstiges = apps.get_model('tickets', 'InfoMonitorSonstiges')

    for monitor in InfoMonitor.objects.all():
        position = 0
        for field_name in ['sonstiges_1', 'sonstiges_2', 'sonstiges_3', 'sonstiges_4', 'sonstiges_5']:
            text = getattr(monitor, field_name, '').strip()
            if text:
                InfoMonitorSonstiges.objects.create(
                    monitor=monitor,
                    text=text,
                    position=position,
                )
                position += 1


def reverse_migration(apps, schema_editor):
    """Schreibt Sonstiges-Einträge zurück in die festen Felder."""
    InfoMonitor = apps.get_model('tickets', 'InfoMonitor')
    InfoMonitorSonstiges = apps.get_model('tickets', 'InfoMonitorSonstiges')

    for monitor in InfoMonitor.objects.all():
        entries = InfoMonitorSonstiges.objects.filter(monitor=monitor).order_by('position')[:5]
        for i, entry in enumerate(entries, start=1):
            setattr(monitor, f'sonstiges_{i}', entry.text)
        monitor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_add_infomonitor_sonstiges_model'),
    ]

    operations = [
        migrations.RunPython(migrate_sonstiges_data, reverse_migration),
    ]
