# Generated by Django 5.0.14 on 2026-02-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_migrate_sonstiges_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitorvehicle',
            name='bemerkung',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Bemerkung'),
        ),
    ]
