# Generated by Django 5.0.14 on 2026-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_add_vehicle_bemerkung'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitor',
            name='ff_koe_status',
            field=models.CharField(choices=[('einsatzbereit', 'Einsatzbereit'), ('im_anmarsch', 'Im Anmarsch'), ('nicht_einsatzbereit', 'Nicht Einsatzbereit')], default='einsatzbereit', max_length=25, verbose_name='FF KÖ'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='ff_mitte_status',
            field=models.CharField(choices=[('einsatzbereit', 'Einsatzbereit'), ('im_anmarsch', 'Im Anmarsch'), ('nicht_einsatzbereit', 'Nicht Einsatzbereit')], default='einsatzbereit', max_length=25, verbose_name='FF Mitte'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='ff_sterkrade_status',
            field=models.CharField(choices=[('einsatzbereit', 'Einsatzbereit'), ('im_anmarsch', 'Im Anmarsch'), ('nicht_einsatzbereit', 'Nicht Einsatzbereit')], default='einsatzbereit', max_length=25, verbose_name='FF Sterkrade'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='ff_sued_status',
            field=models.CharField(choices=[('einsatzbereit', 'Einsatzbereit'), ('im_anmarsch', 'Im Anmarsch'), ('nicht_einsatzbereit', 'Nicht Einsatzbereit')], default='einsatzbereit', max_length=25, verbose_name='FF Süd'),
        ),
    ]
