# Generated by Django 5.0.14 on 2026-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ff_zuege_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bereitschaftperson',
            name='kategorie',
            field=models.CharField(choices=[('a1_dienst', 'A1-Dienst'), ('a2_dienst', 'A2-Dienst'), ('b_dienst', 'B-Dienst'), ('c_dienst', 'C-Dienst'), ('lagedienst', 'Lagedienst'), ('lna', 'LNA'), ('ordnungsamt', 'Ordnungsamt'), ('gesundheitsamt', 'Gesundheitsamt'), ('veterinaeramt', 'Veterinäramt')], default='c_dienst', max_length=20, verbose_name='Kategorie'),
        ),
    ]
