# Generated by Django 5.0.14 on 2026-04-30 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_add_bereitschaft_kategorien_a_b_lage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomonitor',
            name='bereitschaft_vet_datetime',
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_a1_dienst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='A1-Dienst'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_a1_dienst_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='A1-Dienst geändert am'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_a2_dienst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='A2-Dienst'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_a2_dienst_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='A2-Dienst geändert am'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_b_dienst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='B-Dienst'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_b_dienst_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='B-Dienst geändert am'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_lagedienst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tickets.bereitschaftperson', verbose_name='Lagedienst'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_lagedienst_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lagedienst geändert am'),
        ),
    ]
