# Generated by Django 5.0.14 on 2026-04-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_add_bereitschaft_a_b_lage_remove_vet_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomonitor',
            name='personal_fw1_ktw',
        ),
        migrations.RemoveField(
            model_name='infomonitor',
            name='personal_fw2_ktw',
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='personal_fw1_gal_hlf',
            field=models.BooleanField(default=False, verbose_name='FW1 GAL-HLF'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='personal_fw2_gal_hlf',
            field=models.BooleanField(default=False, verbose_name='FW2 GAL-HLF'),
        ),
    ]
