# Generated by Django 5.0.14 on 2026-04-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_personal_remove_ktw_add_gal_hlf'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitor',
            name='ff_koe_fahrzeuge',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='FF KÖ Fahrzeuge'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='ff_mitte_fahrzeuge',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='FF Mitte Fahrzeuge'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='ff_sterkrade_fahrzeuge',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='FF Sterkrade Fahrzeuge'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='ff_sued_fahrzeuge',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='FF Süd Fahrzeuge'),
        ),
    ]
