# Generated by Django 5.0.14 on 2026-04-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_ff_zuege_fahrzeuge'),
        ('vehicles', '0014_vehicle_bereich'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_a1_dienst_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='A1-Dienst Notiz'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_a2_dienst_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='A2-Dienst Notiz'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_b_dienst_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='B-Dienst Notiz'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_c_dienst_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='C-Dienst Notiz'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_g_amt_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Gesundheitsamt Notiz'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_lagedienst_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Lagedienst Notiz'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_lna_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='LNA Notiz'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_o_amt_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ordnungsamt Notiz'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_veterinaeramt_note',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Veterinäramt Notiz'),
        ),
        migrations.AlterField(
            model_name='infomonitorvehicle',
            name='ersetzt_mit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vehicles.vehicle', verbose_name='Ersatz'),
        ),
    ]
