# Generated by Django 5.0.14 on 2026-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_bereitschaft_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitorsonstiges',
            name='highlighted',
            field=models.BooleanField(default=False, verbose_name='Hervorgehoben'),
        ),
    ]
