# Generated by Django 5.2.15 on 2026-07-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_bereitschaft_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitor',
            name='show_bereitschaft',
            field=models.BooleanField(default=True, verbose_name='Kachel „Bereitschaft“ anzeigen'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='show_fahrzeuge',
            field=models.BooleanField(default=True, verbose_name='Kachel „Fahrzeuge / Geräte“ anzeigen'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='show_ff_zuege',
            field=models.BooleanField(default=True, verbose_name='Kachel „FF Züge“ anzeigen'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='show_laufband',
            field=models.BooleanField(default=True, verbose_name='Kachel „Laufband“ anzeigen'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='show_personal',
            field=models.BooleanField(default=True, verbose_name='Kachel „Personal“ anzeigen'),
        ),
        migrations.AddField(
            model_name='infomonitor',
            name='show_sonstiges',
            field=models.BooleanField(default=True, verbose_name='Kachel „Sonstiges“ anzeigen'),
        ),
    ]
