# Generated by Django 5.2.15 on 2026-07-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_infomonitor_show_bereitschaft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappeanleitung',
            name='pdf_datei',
            field=models.FileField(blank=True, help_text='Optionales PDF-Dokument zur Anleitung', null=True, upload_to='mappe/anleitungen/%Y/%m/', verbose_name='PDF-Datei'),
        ),
        migrations.AlterField(
            model_name='mappeanleitung',
            name='content',
            field=models.TextField(blank=True, verbose_name='Inhalt'),
        ),
    ]
