# Generated by Django 5.2.15 on 2026-08-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_ff_fahrzeuge_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomonitorvehicle',
            name='ersetzt_mit',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ersatz'),
        ),
        migrations.AlterField(
            model_name='infomonitorvehicle',
            name='fahrzeug_ad',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Außer Dienst'),
        ),
    ]
