# Generated by Django 5.2.15 on 2026-08-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_gal_hlf_gemeinsam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infomonitor',
            name='ff_koe_status',
            field=models.CharField(choices=[('einsatzbereit', 'Grün'), ('nicht_einsatzbereit', 'Rot'), ('grau', 'Grau')], default='einsatzbereit', max_length=25, verbose_name='FF KÖ'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='ff_mitte_status',
            field=models.CharField(choices=[('einsatzbereit', 'Grün'), ('nicht_einsatzbereit', 'Rot'), ('grau', 'Grau')], default='einsatzbereit', max_length=25, verbose_name='FF Mitte'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='ff_sterkrade_status',
            field=models.CharField(choices=[('einsatzbereit', 'Grün'), ('nicht_einsatzbereit', 'Rot'), ('grau', 'Grau')], default='einsatzbereit', max_length=25, verbose_name='FF Sterkrade'),
        ),
        migrations.AlterField(
            model_name='infomonitor',
            name='ff_sued_status',
            field=models.CharField(choices=[('einsatzbereit', 'Grün'), ('nicht_einsatzbereit', 'Rot'), ('grau', 'Grau')], default='einsatzbereit', max_length=25, verbose_name='FF Süd'),
        ),
    ]
