# Generated by Django 5.2.15 on 2026-08-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_ff_status_grau'),
    ]

    operations = [
        migrations.AddField(
            model_name='grossveranstaltungdashboard',
            name='layout_split',
            field=models.CharField(choices=[('25', '25 % / 75 %'), ('33', '33 % / 67 %'), ('50', '50 % / 50 %')], default='25', help_text='Breite der linken Spalte im dynamischen Layout', max_length=2, verbose_name='Aufteilung Karte/Text'),
        ),
    ]
