# Generated by Django 5.2.15 on 2026-08-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_gv_layout_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grossveranstaltungdashboard',
            name='layout_split',
            field=models.CharField(choices=[('25', '25 % / 75 %'), ('33', '33 % / 67 %'), ('50', '50 % / 50 %'), ('75', '75 % / 25 %')], default='25', help_text='Breite der linken Spalte im dynamischen Layout', max_length=2, verbose_name='Aufteilung Karte/Text'),
        ),
    ]
