# Generated by Django 5.2.15 on 2026-09-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_gv_layout_split_75'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappekontakt',
            name='phone_mobil_dienst',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mobil dienstlich'),
        ),
        migrations.AddField(
            model_name='mappekontakt',
            name='phone_mobil_privat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mobil privat'),
        ),
        migrations.AlterField(
            model_name='mappekontakt',
            name='phone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Festnetz'),
        ),
    ]
