# Generated by Django 5.2.15 on 2026-09-03 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_mappekontakt_mehrere_telefonnummern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='infomonitor',
            name='bereitschaft_freitext',
            field=models.TextField(blank=True, default='', help_text='Wird in der Kachel „Bereitschaft“ neben dem Veterinäramt angezeigt', verbose_name='Freitext Bereitschaft'),
        ),
        migrations.CreateModel(
            name='Grossereignis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200, verbose_name='Ereignis')),
                ('beschreibung', models.TextField(blank=True, default='', verbose_name='Hinweise')),
                ('beginn', models.DateTimeField(verbose_name='Beginn')),
                ('ende', models.DateTimeField(blank=True, null=True, verbose_name='Ende')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Angelegt am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Angelegt von')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Beendet von')),
            ],
            options={
                'verbose_name': 'Großereignis',
                'verbose_name_plural': 'Großereignisse',
                'ordering': ['-beginn'],
            },
        ),
    ]
