# Generated by Django 5.2.15 on 2026-09-08 05:33

import django.db.models.deletion
from django.db import migrations, models


def uebernahme_bestehender_fahrzeuge(apps, schema_editor):
    """Bisherige Freitext-Fahrzeuge der FF-Züge werden zu Stammfahrzeugen
    und mit dem aktiven Monitor-Eintrag verknüpft."""
    InfoMonitorFFFahrzeug = apps.get_model('tickets', 'InfoMonitorFFFahrzeug')
    FFStammfahrzeug = apps.get_model('tickets', 'FFStammfahrzeug')
    positionen = {}
    for eintrag in InfoMonitorFFFahrzeug.objects.order_by('zug', 'position', 'id'):
        name = (eintrag.fahrzeug or '').strip()
        if not name:
            continue
        stamm = FFStammfahrzeug.objects.filter(zug=eintrag.zug, name=name).first()
        if stamm is None:
            pos = positionen.get(eintrag.zug, 0)
            positionen[eintrag.zug] = pos + 1
            stamm = FFStammfahrzeug.objects.create(zug=eintrag.zug, name=name, position=pos)
        eintrag.stammfahrzeug = stamm
        eintrag.fahrzeug = name
        eintrag.save(update_fields=['stammfahrzeug', 'fahrzeug'])


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_grossereignis_bereitschaft_freitext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FFStammfahrzeug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zug', models.CharField(choices=[('sterkrade', 'FF Sterkrade'), ('mitte', 'FF Mitte'), ('sued', 'FF Süd'), ('koe', 'FF KÖ')], max_length=20, verbose_name='Zug')),
                ('name', models.CharField(max_length=100, verbose_name='Fahrzeug')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'FF-Stammfahrzeug',
                'verbose_name_plural': 'FF-Stammfahrzeuge',
                'ordering': ['zug', 'position', 'name'],
                'unique_together': {('zug', 'name')},
            },
        ),
        migrations.AddField(
            model_name='infomonitorfffahrzeug',
            name='stammfahrzeug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitor_eintraege', to='tickets.ffstammfahrzeug', verbose_name='Stammfahrzeug'),
        ),
        migrations.RunPython(uebernahme_bestehender_fahrzeuge, migrations.RunPython.noop),
    ]
