# Generated by Django 5.0.14 on 2025-10-03 12:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        ('personnel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('receipt_number', models.CharField(help_text='Automatisch generiert, z.B. GR-2025-0001', max_length=50, unique=True, verbose_name='Wareneingangs-Nummer')),
                ('receipt_date', models.DateTimeField(verbose_name='Wareneingangsdatum')),
                ('delivery_note_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferschein-Nummer')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='Spediteur/Kurier')),
                ('quality_check_passed', models.BooleanField(default=True, verbose_name='Qualitätsprüfung bestanden')),
                ('quality_check_notes', models.TextField(blank=True, verbose_name='Qualitätsprüfungs-Notizen')),
                ('has_discrepancies', models.BooleanField(default=False, verbose_name='Abweichungen festgestellt')),
                ('discrepancy_notes', models.TextField(blank=True, help_text='z.B. falsche Menge, beschädigte Ware, etc.', verbose_name='Abweichungs-Notizen')),
                ('delivery_note_file', models.FileField(blank=True, null=True, upload_to='procurement/delivery_notes/%Y/%m/', verbose_name='Lieferschein-Datei')),
                ('photos', models.JSONField(blank=True, default=list, help_text='Liste von Foto-URLs (z.B. bei Schäden)', verbose_name='Fotos')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='personnel.person', verbose_name='Empfangen von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Wareneingang',
                'verbose_name_plural': 'Wareneingänge',
                'db_table': 'procurement_goods_receipt',
                'ordering': ['-receipt_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('item_name', models.CharField(max_length=200, verbose_name='Artikelbezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('inventory_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lager-Artikel-ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Menge')),
                ('unit', models.CharField(default='Stück', max_length=50, verbose_name='Einheit')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Einzelpreis (€)')),
                ('quantity_received', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Erhaltene Menge')),
                ('supplier_item_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Artikelnummer')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('inventory_content_type', models.ForeignKey(blank=True, help_text='z.B. MagazineItem, MedicalItem, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Lager-Artikeltyp')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='locations.location', verbose_name='Ziel-Lagerort')),
            ],
            options={
                'verbose_name': 'Bestellposition',
                'verbose_name_plural': 'Bestellpositionen',
                'db_table': 'procurement_order_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('quantity_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Erhaltene Menge')),
                ('condition', models.CharField(choices=[('good', 'Gut'), ('acceptable', 'Akzeptabel'), ('damaged', 'Beschädigt'), ('defective', 'Defekt')], default='good', max_length=20, verbose_name='Zustand')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Chargennummer')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Ablaufdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.goodsreceipt', verbose_name='Wareneingang')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='locations.location', verbose_name='Eingelagert in')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='procurement.orderitem', verbose_name='Bestellposition')),
            ],
            options={
                'verbose_name': 'Wareneingangs-Position',
                'verbose_name_plural': 'Wareneingangs-Positionen',
                'db_table': 'procurement_goods_receipt_item',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('order_number', models.CharField(help_text='Automatisch generiert, z.B. PO-2025-0001', max_length=50, unique=True, verbose_name='Bestellnummer')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, help_text='Zweck und Details der Bestellung', verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('pending_approval', 'Wartet auf Freigabe'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt'), ('ordered', 'Bestellt'), ('partially_received', 'Teilweise geliefert'), ('received', 'Vollständig geliefert'), ('cancelled', 'Storniert'), ('closed', 'Abgeschlossen')], default='draft', max_length=30, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('normal', 'Normal'), ('high', 'Hoch'), ('urgent', 'Dringend')], default='normal', max_length=20, verbose_name='Priorität')),
                ('requested_date', models.DateField(verbose_name='Anforderungsdatum')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigungsdatum')),
                ('ordered_date', models.DateField(blank=True, help_text='Datum der tatsächlichen Bestellung beim Lieferanten', null=True, verbose_name='Bestelldatum')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Erwartetes Lieferdatum')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Tatsächliches Lieferdatum')),
                ('delivery_status', models.CharField(choices=[('not_shipped', 'Noch nicht versandt'), ('shipped', 'Versandt'), ('in_transit', 'Unterwegs'), ('delivered', 'Geliefert'), ('delayed', 'Verspätet')], default='not_shipped', max_length=20, verbose_name='Lieferstatus')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Zwischensumme (€)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Steuersatz (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Steuerbetrag (€)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Versandkosten (€)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtkosten (€)')),
                ('budget_code', models.CharField(blank=True, help_text='Interner Budgetcode für Kostenstelle', max_length=50, verbose_name='Budgetcode')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Rechnungsnummer')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Rechnungsdatum')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='procurement/invoices/%Y/%m/', verbose_name='Rechnungsdatei')),
                ('order_confirmation_file', models.FileField(blank=True, null=True, upload_to='procurement/confirmations/%Y/%m/', verbose_name='Auftragsbestätigung')),
                ('notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Ablehnungsgrund')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Tracking-Nummer')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_approved', to='personnel.person', verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='locations.location', verbose_name='Lieferadresse')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_requested', to='personnel.person', verbose_name='Angefordert von')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'db_table': 'procurement_purchase_order',
                'ordering': ['-requested_date', '-order_number'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaseorder', verbose_name='Bestellung'),
        ),
        migrations.CreateModel(
            name='OrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('approval_level', models.PositiveIntegerField(help_text='1 = Erste Stufe (z.B. Teamleiter), 2 = Zweite Stufe (z.B. Abteilungsleiter), etc.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Freigabestufe')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt'), ('expired', 'Abgelaufen')], default='pending', max_length=20, verbose_name='Status')),
                ('requested_date', models.DateTimeField(auto_now_add=True, verbose_name='Angefordert am')),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Entschieden am')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('deadline', models.DateTimeField(blank=True, help_text='Bis wann muss die Freigabe erfolgen?', null=True, verbose_name='Frist')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_approvals', to='personnel.person', verbose_name='Genehmiger')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='procurement.purchaseorder', verbose_name='Bestellung')),
            ],
            options={
                'verbose_name': 'Freigabe',
                'verbose_name_plural': 'Freigaben',
                'db_table': 'procurement_order_approval',
                'ordering': ['approval_level', 'requested_date'],
            },
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='procurement.purchaseorder', verbose_name='Bestellung'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_number'], name='procurement_order_n_d58847_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='procurement_status_cd035f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['-requested_date'], name='procurement_request_d47e63_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier', '-requested_date'], name='procurement_supplie_1e804e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['requested_by', '-requested_date'], name='procurement_request_0058a6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['priority', 'status'], name='procurement_priorit_e9aab7_idx'),
        ),
        migrations.AddIndex(
            model_name='orderapproval',
            index=models.Index(fields=['purchase_order', 'approval_level'], name='procurement_purchas_c8acc0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderapproval',
            index=models.Index(fields=['approver', 'status'], name='procurement_approve_bed459_idx'),
        ),
        migrations.AddIndex(
            model_name='orderapproval',
            index=models.Index(fields=['status', 'deadline'], name='procurement_status_e15383_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderapproval',
            unique_together={('purchase_order', 'approval_level')},
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['receipt_number'], name='procurement_receipt_5d918a_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['purchase_order', '-receipt_date'], name='procurement_purchas_d7a06c_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['received_by', '-receipt_date'], name='procurement_receive_755be8_idx'),
        ),
    ]
