# Generated by Django 5.0.14 on 2026-02-11 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-requested_date', '-order_number'], 'permissions': [('create_order_request', 'Kann Bestellanforderung erstellen'), ('view_own_orders', 'Kann eigene Bestellungen anzeigen'), ('approve_order_low', 'Kann Bestellungen bis 1.000 EUR freigeben'), ('approve_order_medium', 'Kann Bestellungen bis 5.000 EUR freigeben'), ('approve_order_high', 'Kann Bestellungen über 5.000 EUR freigeben'), ('cancel_order', 'Kann Bestellungen stornieren')], 'verbose_name': 'Bestellung', 'verbose_name_plural': 'Bestellungen'},
        ),
    ]
