# Generated by Django 5.0.14 on 2026-02-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_url',
            field=models.URLField(blank=True, help_text='Link zum Artikel, z.B. im Online-Shop des Lieferanten', max_length=500, verbose_name='Artikel-URL'),
        ),
    ]
