# Generated by Django 5.0.14 on 2026-02-11 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0020_add_watch_division'),
        ('procurement', '0003_orderitem_item_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='z.B. Atemschutz, Fahrzeugtechnik', max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(blank=True, help_text='Optionales Kürzel, z.B. AS, FT', max_length=20, verbose_name='Kürzel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('budget_code', models.CharField(blank=True, help_text='Standard-Budgetcode für diesen Fachbereich', max_length=50, verbose_name='Budgetcode')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_departments', to='personnel.person', verbose_name='Verantwortliche Person')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Fachbereich',
                'verbose_name_plural': 'Fachbereiche',
                'db_table': 'procurement_department',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.procurementdepartment', verbose_name='Fachbereich'),
        ),
    ]
