# Generated by Django 5.0.14 on 2026-02-11 14:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_base', '0003_category_module'),
        ('locations', '0006_location_linked_vehicle'),
        ('personnel', '0020_add_watch_division'),
        ('procurement', '0004_procurementdepartment_purchaseorder_department'),
        ('vehicles', '0011_auto_create_vehicle_locations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='gesamtpreis_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtpreis Netto (EUR)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='anbieter_freitext',
            field=models.CharField(blank=True, help_text='Alternative zum Lieferanten-Dropdown', max_length=200, verbose_name='Anbieter (Freitext)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='beschaffungsgrund',
            field=models.CharField(blank=True, choices=[('vertrag', 'Vertragliche Vereinbarung'), ('dienstlich', 'Dienstliche Notwendigkeit')], max_length=20, verbose_name='Beschaffungsgrund'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='beschaffungsstatus',
            field=models.CharField(blank=True, choices=[('bestellt', 'Bereits bestellt'), ('abgeholt', 'Bereits abgeholt'), ('durchgefuehrt', 'Bereits durchgeführt'), ('geliefert', 'Bereits geliefert'), ('rechnung', 'Rechnung liegt vor')], max_length=20, verbose_name='Beschaffungsstatus'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='eilt_begruendung',
            field=models.TextField(blank=True, help_text='Begruendung falls Lieferzeit "Eilt" gewaehlt', verbose_name='Eilt-Begruendung'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='gesamtsumme_netto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtsumme Netto (EUR)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='lieferzeit',
            field=models.CharField(choices=[('normal', 'Normal'), ('eilt', 'Eilt')], default='normal', max_length=20, verbose_name='Lieferzeit'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vertreter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_vertreter', to='personnel.person', verbose_name='Vertreter'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verwendung_bs_fzg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_bs', to='vehicles.vehicle', verbose_name='Verwendung BS Fzg.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verwendung_rd_fzg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_rd', to='vehicles.vehicle', verbose_name='Verwendung RD Fzg.'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Menge'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Einzelpreis (EUR)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='locations.location', verbose_name='Lieferort'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders_requested', to='personnel.person', verbose_name='Ansprechpartner'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory_base.supplier', verbose_name='Lieferant'),
        ),
        migrations.CreateModel(
            name='Mengeneinheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='z.B. Stck., Pack, Liter', max_length=50, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Mengeneinheit',
                'verbose_name_plural': 'Mengeneinheiten',
                'db_table': 'procurement_mengeneinheit',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NKFNummer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('nummer', models.CharField(help_text='z.B. 610002150100', max_length=20, unique=True, verbose_name='Nummer')),
                ('bezeichnung', models.CharField(blank=True, help_text='Optionale Beschreibung', max_length=200, verbose_name='Bezeichnung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'NKF-Nummer',
                'verbose_name_plural': 'NKF-Nummern',
                'db_table': 'procurement_nkf_nummer',
                'ordering': ['sort_order', 'nummer'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='nkf_nummer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.nkfnummer', verbose_name='NKF-Nummer'),
        ),
        migrations.CreateModel(
            name='Sachkonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('typ', models.CharField(help_text='z.B. KFZ-Aufwendungen, Beschaffungswesen', max_length=100, unique=True, verbose_name='Typ')),
                ('nummer', models.CharField(help_text='z.B. 525135, 543188', max_length=20, verbose_name='Nummer')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Sachkonto',
                'verbose_name_plural': 'Sachkonten',
                'db_table': 'procurement_sachkonto',
                'ordering': ['sort_order', 'typ'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sachkonto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.sachkonto', verbose_name='Sachkonto'),
        ),
        migrations.CreateModel(
            name='VerwendungAllgemein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(help_text='z.B. Atemschutz, Kfz-Werkst.', max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sortierung')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Verwendung (Allgemein)',
                'verbose_name_plural': 'Verwendungen (Allgemein)',
                'db_table': 'procurement_verwendung_allgemein',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='verwendung_allgemein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.verwendungallgemein', verbose_name='Verwendung Allgemein'),
        ),
    ]
