# Generated by Django 5.0.14 on 2026-02-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_orderitem_gesamtpreis_netto_and_more'),
        ('vehicles', '0013_alter_vehicle_rubrik'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='verwendung_ks_fzg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_ks', to='vehicles.vehicle', verbose_name='Verwendung KS Fzg.'),
        ),
    ]
