# Generated by Django 5.0.14 on 2026-02-19 06:37

import django.db.models.deletion
from django.db import migrations, models


def copy_departments_and_save_mapping(apps, schema_editor):
    """
    Schritt 1 (vor AlterField):
    - Kopiere ProcurementDepartment-Daten nach organization.Department
    - Erstelle temporaere Mapping-Tabelle fuer PurchaseOrder-Zuordnung
    - Setze PurchaseOrder.department_id auf NULL
    """
    ProcurementDepartment = apps.get_model('procurement', 'ProcurementDepartment')
    OrgDepartment = apps.get_model('organization', 'Department')
    PurchaseOrder = apps.get_model('procurement', 'PurchaseOrder')

    # Mapping aufbauen: ProcurementDepartment.pk -> OrgDepartment.pk
    pk_mapping = {}

    for proc_dept in ProcurementDepartment.objects.all():
        org_dept = OrgDepartment.objects.filter(name=proc_dept.name).first()
        if not org_dept:
            org_dept = OrgDepartment.objects.create(
                name=proc_dept.name,
                abbreviation=proc_dept.code or '',
                description=proc_dept.description or '',
                budget_code=proc_dept.budget_code or '',
                is_active=proc_dept.is_active,
                sort_order=proc_dept.sort_order,
            )
        else:
            updated = False
            if proc_dept.budget_code and not org_dept.budget_code:
                org_dept.budget_code = proc_dept.budget_code
                updated = True
            if proc_dept.code and not org_dept.abbreviation:
                org_dept.abbreviation = proc_dept.code
                updated = True
            if updated:
                org_dept.save()

        pk_mapping[proc_dept.pk] = org_dept.pk

    # Temporaere Tabelle fuer Mapping erstellen
    schema_editor.execute(
        "CREATE TABLE IF NOT EXISTS _temp_dept_mapping "
        "(order_id INTEGER PRIMARY KEY, new_dept_id INTEGER)"
    )

    # PurchaseOrders mit department_id merken
    for order in PurchaseOrder.objects.filter(department_id__isnull=False):
        old_dept_id = order.department_id
        new_dept_id = pk_mapping.get(old_dept_id)
        if new_dept_id:
            schema_editor.execute(
                "INSERT INTO _temp_dept_mapping (order_id, new_dept_id) VALUES (%s, %s)",
                [order.pk, new_dept_id],
            )

    # department_id auf NULL setzen (damit AlterField keine FK-Fehler wirft)
    PurchaseOrder.objects.filter(department_id__isnull=False).update(department_id=None)


def reassign_departments(apps, schema_editor):
    """
    Schritt 3 (nach AlterField):
    - Weise PurchaseOrders die gemappten organization.Department-IDs zu
    - Loesche temporaere Mapping-Tabelle
    """
    # Mapping aus temp-Tabelle lesen und zuweisen
    schema_editor.execute(
        "UPDATE procurement_purchase_order po "
        "SET department_id = tm.new_dept_id "
        "FROM _temp_dept_mapping tm "
        "WHERE po.id = tm.order_id"
    )

    # Temp-Tabelle loeschen
    schema_editor.execute("DROP TABLE IF EXISTS _temp_dept_mapping")


def reverse_noop(apps, schema_editor):
    """Reverse: Temp-Tabelle loeschen falls vorhanden"""
    schema_editor.execute("DROP TABLE IF EXISTS _temp_dept_mapping")
    PurchaseOrder = apps.get_model('procurement', 'PurchaseOrder')
    PurchaseOrder.objects.all().update(department_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_add_department_head_deputy_budget'),
        ('procurement', '0006_purchaseorder_verwendung_ks_fzg'),
    ]

    operations = [
        # Schritt 1: Departments kopieren, Mapping speichern, FKs nullen
        migrations.RunPython(
            copy_departments_and_save_mapping,
            reverse_noop,
        ),
        # Schritt 2: FK-Constraint auf organization.Department umstellen
        migrations.AlterField(
            model_name='purchaseorder',
            name='department',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='purchase_orders',
                to='organization.department',
                verbose_name='Fachbereich',
            ),
        ),
        # Schritt 3: Departments neu zuweisen aus Mapping
        migrations.RunPython(
            reassign_departments,
            reverse_noop,
        ),
    ]
