# Generated by Django 5.0.14 on 2026-05-06 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0020_add_watch_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_portrait', models.BooleanField(default=False, help_text='Hochformat (54x85,6mm) statt Querformat (85,6x54mm)', verbose_name='Hochformat')),
                ('front_layout', models.JSONField(blank=True, default=list, verbose_name='Layout Vorderseite')),
                ('back_layout', models.JSONField(blank=True, default=list, verbose_name='Layout Rückseite')),
                ('is_system', models.BooleanField(default=False, help_text='Vom Code mitgeliefert; im Editor schreibgeschützt.', verbose_name='System-Vorlage')),
                ('is_default', models.BooleanField(default=False, help_text='Standard-Vorlage für neue Karten.', verbose_name='Standard')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Ausweis-Vorlage',
                'verbose_name_plural': 'Ausweis-Vorlagen',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('card_number', models.CharField(help_text='Format: STATION-JAHR-LFD', max_length=50, unique=True, verbose_name='Ausweisnummer')),
                ('type', models.CharField(choices=[('regular', 'Standard'), ('leadership', 'Führungsdienst'), ('trainee', 'Praktikant'), ('honorary', 'Ehrenmitglied'), ('special', 'Sonder')], default='regular', max_length=20, verbose_name='Ausweistyp')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('active', 'Aktiv'), ('revoked', 'Gesperrt'), ('expired', 'Abgelaufen'), ('replaced', 'Ersetzt')], default='active', max_length=20, verbose_name='Status')),
                ('function_label', models.CharField(blank=True, help_text='Optional: überschreibt den Dienstgrad auf der Karte.', max_length=100, verbose_name='Funktionsbezeichnung')),
                ('issued_at', models.DateField(verbose_name='Ausgestellt am')),
                ('valid_until', models.DateField(verbose_name='Gültig bis')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Gesperrt am')),
                ('revoke_reason', models.CharField(blank=True, choices=[('lost', 'Verloren'), ('stolen', 'Gestohlen'), ('left', 'Ausgetreten'), ('damaged', 'Beschädigt'), ('other', 'Sonstiges')], max_length=20, verbose_name='Sperrgrund')),
                ('revoke_note', models.TextField(blank=True, verbose_name='Sperrnotiz')),
                ('pdf_file', models.FileField(blank=True, help_text='Optionaler Snapshot der zuletzt gedruckten Version.', null=True, upload_to='idcards/snapshots/', verbose_name='PDF-Snapshot')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_cards', to='personnel.person', verbose_name='Person')),
                ('replaced_by', models.OneToOneField(blank=True, limit_choices_to={'status': 'active'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='idcards.idcard', verbose_name='Ersetzt durch')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_id_cards', to=settings.AUTH_USER_MODEL, verbose_name='Gesperrt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='idcards.idcardtemplate', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Dienstausweis',
                'verbose_name_plural': 'Dienstausweise',
                'ordering': ['-issued_at', '-id'],
                'permissions': [('manage_idcards', 'Kann Dienstausweise verwalten (anlegen, sperren, ersetzen, drucken)')],
            },
        ),
        migrations.CreateModel(
            name='IdCardAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('action', models.CharField(choices=[('create', 'Erstellt'), ('edit', 'Bearbeitet'), ('print', 'Gedruckt'), ('revoke', 'Gesperrt'), ('replace', 'Ersetzt')], max_length=20, verbose_name='Aktion')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadaten')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idcard_audit_entries', to=settings.AUTH_USER_MODEL, verbose_name='Aktor')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='idcards.idcard', verbose_name='Ausweis')),
            ],
            options={
                'verbose_name': 'Ausweis-Audit-Eintrag',
                'verbose_name_plural': 'Ausweis-Audit-Einträge',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['card', '-created_at'], name='idcards_idc_card_id_a78b74_idx'), models.Index(fields=['action'], name='idcards_idc_action_1b172c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='idcardtemplate',
            constraint=models.UniqueConstraint(fields=('name',), name='idcards_template_unique_name'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['status'], name='idcards_idc_status_7f73f2_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['valid_until'], name='idcards_idc_valid_u_71ffed_idx'),
        ),
        migrations.AddIndex(
            model_name='idcard',
            index=models.Index(fields=['person', 'status'], name='idcards_idc_person__1ac2ba_idx'),
        ),
    ]
