# Generated by Django 5.0.14 on 2025-10-03 10:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory_base', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('name', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_number', models.CharField(help_text='Eindeutige Artikelnummer', max_length=100, unique=True, verbose_name='Artikelnummer')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Hersteller-Artikelnummer')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestand')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, Meter, kg', max_length=50, verbose_name='Einheit')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Warnung bei Unterschreitung', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maximalbestand')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('good', 'Gut'), ('used', 'Gebraucht'), ('worn', 'Abgenutzt'), ('damaged', 'Beschädigt'), ('defect', 'Defekt')], default='new', max_length=20, verbose_name='Zustand')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Barcode/EAN')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR-Code')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='inventory/images/', verbose_name='Bild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('item_type', models.CharField(choices=[('hose', 'Schläuche'), ('fitting', 'Armaturen'), ('tool', 'Werkzeug'), ('consumable', 'Verbrauchsmaterial'), ('chemical', 'Chemikalien'), ('cleaning', 'Reinigungsmittel'), ('spare_part', 'Ersatzteile'), ('fastener', 'Befestigungsmaterial'), ('electrical', 'Elektromaterial'), ('other', 'Sonstiges')], default='consumable', max_length=20, verbose_name='Artikeltyp')),
                ('size', models.CharField(blank=True, help_text='z.B. "C-52", "3/4 Zoll", "M8"', max_length=100, verbose_name='Größe/Maße')),
                ('material', models.CharField(blank=True, help_text='z.B. "Stahl", "Kunststoff", "Aluminium"', max_length=100, verbose_name='Material')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Farbe')),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=3, help_text='Gewicht einer einzelnen Einheit in kg', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Gewicht pro Einheit (kg)')),
                ('volume_per_unit', models.DecimalField(blank=True, decimal_places=3, help_text='Volumen einer einzelnen Einheit in Litern', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Volumen pro Einheit (Liter)')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Gefahrgut')),
                ('hazard_class', models.CharField(choices=[('none', 'Keine'), ('explosive', 'Explosiv'), ('flammable', 'Entzündbar'), ('oxidizing', 'Oxidierend'), ('compressed_gas', 'Unter Druck stehende Gase'), ('corrosive', 'Ätzend'), ('toxic', 'Giftig'), ('harmful', 'Gesundheitsschädlich'), ('environmental', 'Umweltgefährlich')], default='none', max_length=20, verbose_name='Gefahrenklasse')),
                ('safety_data_sheet', models.FileField(blank=True, help_text='PDF-Datei des Sicherheitsdatenblatts', null=True, upload_to='magazine/sds/', verbose_name='Sicherheitsdatenblatt')),
                ('has_expiry_date', models.BooleanField(default=False, verbose_name='Hat Verfallsdatum')),
                ('shelf_life_months', models.PositiveIntegerField(blank=True, help_text='Standard-Haltbarkeit in Monaten', null=True, verbose_name='Haltbarkeit (Monate)')),
                ('storage_temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Min. Lagertemperatur (°C)')),
                ('storage_temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max. Lagertemperatur (°C)')),
                ('storage_instructions', models.TextField(blank=True, help_text='Spezielle Anweisungen zur Lagerung', verbose_name='Lageranweisungen')),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=2, help_text='Bei Unterschreitung automatische Bestellung auslösen', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestellpunkt')),
                ('standard_order_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Standard-Bestellmenge')),
                ('last_ordered_date', models.DateField(blank=True, null=True, verbose_name='Zuletzt bestellt am')),
                ('technical_specifications', models.TextField(blank=True, verbose_name='Technische Spezifikationen')),
                ('usage_instructions', models.TextField(blank=True, verbose_name='Verwendungshinweise')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_items', to='locations.location', verbose_name='Lagerort')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_items', to='inventory_base.supplier', verbose_name='Lieferant')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Magazin-Artikel',
                'verbose_name_plural': 'Magazin-Artikel',
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='MagazineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Chargen-Nummer')),
                ('received_date', models.DateField(verbose_name='Eingangsdatum')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Verfallsdatum')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Eingangsmenge')),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Restmenge')),
                ('supplier_batch_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Chargen-Nr.')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magazine_batches', to='locations.location', verbose_name='Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='magazine.magazineitem', verbose_name='Artikel')),
            ],
            options={
                'verbose_name': 'Charge/Batch',
                'verbose_name_plural': 'Chargen/Batches',
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
        migrations.CreateModel(
            name='MagazineStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('movement_type', models.CharField(choices=[('incoming', 'Wareneingang'), ('outgoing', 'Warenausgang'), ('transfer', 'Umlagerung'), ('inventory', 'Inventur-Korrektur'), ('damage', 'Beschädigung/Schwund'), ('return', 'Rückgabe'), ('disposal', 'Entsorgung')], max_length=20, verbose_name='Bewegungstyp')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('reference_number', models.CharField(blank=True, help_text='z.B. Lieferschein-Nr., Bestellnummer', max_length=100, verbose_name='Referenznummer')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Bewegungsdatum')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Chargen-/Batch-Nummer')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Verfallsdatum')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückkosten (EUR)')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Gesamtkosten (EUR)')),
                ('purpose', models.CharField(blank=True, help_text='z.B. "Einsatz", "Übung", "Wartung"', max_length=200, verbose_name='Verwendungszweck')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='Empfänger')),
                ('delivery_note', models.CharField(blank=True, max_length=100, verbose_name='Lieferschein-Nr.')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Rechnungsnummer')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_outgoing', to='locations.location', verbose_name='Von Lagerort')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='magazine.magazineitem', verbose_name='Artikel')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_incoming', to='locations.location', verbose_name='Nach Lagerort')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Lagerbewegung',
                'verbose_name_plural': 'Lagerbewegungen',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.AddIndex(
            model_name='magazineitem',
            index=models.Index(fields=['item_type', 'category'], name='magazine_ma_item_ty_5b5d20_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineitem',
            index=models.Index(fields=['is_hazardous'], name='magazine_ma_is_haza_6e8896_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineitem',
            index=models.Index(fields=['has_expiry_date'], name='magazine_ma_has_exp_525e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='magazinebatch',
            index=models.Index(fields=['item', 'expiry_date'], name='magazine_ma_item_id_882ea8_idx'),
        ),
        migrations.AddIndex(
            model_name='magazinebatch',
            index=models.Index(fields=['batch_number'], name='magazine_ma_batch_n_3b7167_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='magazinebatch',
            unique_together={('item', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='magazinestockmovement',
            index=models.Index(fields=['item', '-movement_date'], name='magazine_ma_item_id_ecee33_idx'),
        ),
        migrations.AddIndex(
            model_name='magazinestockmovement',
            index=models.Index(fields=['movement_type', '-movement_date'], name='magazine_ma_movemen_fbfc09_idx'),
        ),
        migrations.AddIndex(
            model_name='magazinestockmovement',
            index=models.Index(fields=['batch_number'], name='magazine_ma_batch_n_d8931e_idx'),
        ),
        migrations.AddIndex(
            model_name='magazinestockmovement',
            index=models.Index(fields=['expiry_date'], name='magazine_ma_expiry__24dc7a_idx'),
        ),
    ]
