# Generated by Django 5.0.14 on 2025-10-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazineitem',
            name='item_type',
            field=models.CharField(choices=[('battery', 'Batterien'), ('cleaning', 'Reinigungsmittel/Waschmittel'), ('gloves', 'Handschuhe'), ('fastener', 'Schrauben/Befestigungsmaterial'), ('chemical', 'Chemikalien'), ('office', 'Büromaterial'), ('hygiene', 'Hygieneartikel'), ('electrical', 'Elektromaterial/Leuchtmittel'), ('packaging', 'Verpackungsmaterial'), ('adhesive', 'Klebebänder/Klebstoffe'), ('consumable', 'Sonstiges Verbrauchsmaterial'), ('other', 'Sonstiges')], default='consumable', max_length=20, verbose_name='Artikeltyp'),
        ),
    ]
