# Generated by Django 5.0.14 on 2025-10-05 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_alter_magazineitem_category'),
        ('personnel', '0002_person_id_card_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazinestockmovement',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Person, die den Artikel erhält/zurückgibt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazine_movements', to='personnel.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='magazinestockmovement',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='Nur falls Person nicht in der Personaldatenbank vorhanden ist', max_length=200, verbose_name='Empfänger (alternativ)'),
        ),
    ]
