# Generated by Django 5.0.14 on 2025-10-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_magazinestockmovement_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazineitem',
            name='manual_document',
            field=models.FileField(blank=True, help_text='PDF oder Bild-Datei (wird automatisch per OCR durchsuchbar gemacht)', null=True, upload_to='magazine/manuals/', verbose_name='Handbuch / Produktinformation'),
        ),
    ]
