# Generated by Django 5.0.14 on 2025-11-24 08:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_base', '0002_add_vehicle_fields_to_supplier'),
        ('magazine', '0008_magazineinventorycheck_magazineinventorycheckitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinebatch',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='magazine.magazineitem', verbose_name='Artikel (Legacy)'),
        ),
        migrations.CreateModel(
            name='MagazineItemMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_number', models.CharField(help_text='Eindeutige Nummer für diese Stammdaten (z.B. MAG-0001)', max_length=50, unique=True, verbose_name='Stammdaten-Nr.')),
                ('name', models.CharField(max_length=200, verbose_name='Produktname')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('item_type', models.CharField(choices=[('battery', 'Batterien'), ('cleaning', 'Reinigungsmittel/Waschmittel'), ('gloves', 'Handschuhe'), ('fastener', 'Schrauben/Befestigungsmaterial'), ('chemical', 'Chemikalien'), ('office', 'Büromaterial'), ('hygiene', 'Hygieneartikel'), ('electrical', 'Elektromaterial/Leuchtmittel'), ('packaging', 'Verpackungsmaterial'), ('adhesive', 'Klebebänder/Klebstoffe'), ('consumable', 'Sonstiges Verbrauchsmaterial'), ('other', 'Sonstiges')], default='consumable', max_length=20, verbose_name='Artikeltyp')),
                ('manufacturer', models.CharField(blank=True, max_length=200, verbose_name='Hersteller')),
                ('manufacturer_part_number', models.CharField(blank=True, max_length=100, verbose_name='Hersteller-Artikelnummer')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Lieferant')),
                ('supplier_part_number', models.CharField(blank=True, max_length=100, verbose_name='Lieferanten-Artikelnummer')),
                ('unit', models.CharField(default='Stück', help_text='z.B. Stück, Liter, kg, Packung', max_length=20, verbose_name='Einheit')),
                ('size', models.CharField(blank=True, help_text='z.B. "C-52", "3/4 Zoll", "M8"', max_length=100, verbose_name='Größe/Maße')),
                ('material', models.CharField(blank=True, help_text='z.B. "Stahl", "Kunststoff", "Aluminium"', max_length=100, verbose_name='Material')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Farbe')),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Gewicht pro Einheit (kg)')),
                ('volume_per_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Volumen pro Einheit (Liter)')),
                ('is_hazardous', models.BooleanField(default=False, verbose_name='Gefahrgut')),
                ('hazard_class', models.CharField(choices=[('none', 'Keine'), ('explosive', 'Explosiv'), ('flammable', 'Entzündbar'), ('oxidizing', 'Oxidierend'), ('compressed_gas', 'Unter Druck stehende Gase'), ('corrosive', 'Ätzend'), ('toxic', 'Giftig'), ('harmful', 'Gesundheitsschädlich'), ('environmental', 'Umweltgefährlich')], default='none', max_length=20, verbose_name='Gefahrenklasse')),
                ('safety_data_sheet', models.FileField(blank=True, null=True, upload_to='magazine/sds/', verbose_name='Sicherheitsdatenblatt')),
                ('has_expiry_date', models.BooleanField(default=False, verbose_name='Hat Verfallsdatum')),
                ('shelf_life_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Standard-Haltbarkeit (Monate)')),
                ('storage_temperature_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Min. Lagertemperatur (°C)')),
                ('storage_temperature_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Max. Lagertemperatur (°C)')),
                ('storage_instructions', models.TextField(blank=True, verbose_name='Lageranweisungen')),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mindestbestand')),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bestellpunkt')),
                ('standard_order_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Standard-Bestellmenge')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stückpreis (EUR)')),
                ('technical_specifications', models.TextField(blank=True, verbose_name='Technische Spezifikationen')),
                ('usage_instructions', models.TextField(blank=True, verbose_name='Verwendungshinweise')),
                ('manual_document', models.FileField(blank=True, null=True, upload_to='magazine/manuals/', verbose_name='Handbuch / Produktinformation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='magazine/masters/', verbose_name='Produktbild')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazine_masters', to='inventory_base.category', verbose_name='Kategorie')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_magazine_masters', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_magazine_masters', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Magazin-Stammdaten',
                'verbose_name_plural': 'Magazin-Stammdaten',
                'ordering': ['master_number'],
            },
        ),
        migrations.AddField(
            model_name='magazinebatch',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='magazine.magazineitemmaster', verbose_name='Stammdaten'),
        ),
        migrations.AddIndex(
            model_name='magazineitemmaster',
            index=models.Index(fields=['master_number'], name='magazine_ma_master__9b475b_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineitemmaster',
            index=models.Index(fields=['name'], name='magazine_ma_name_635cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineitemmaster',
            index=models.Index(fields=['item_type'], name='magazine_ma_item_ty_25d11c_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineitemmaster',
            index=models.Index(fields=['manufacturer'], name='magazine_ma_manufac_0df156_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineitemmaster',
            index=models.Index(fields=['is_hazardous'], name='magazine_ma_is_haza_bdfbd7_idx'),
        ),
        migrations.AddIndex(
            model_name='magazineitemmaster',
            index=models.Index(fields=['is_active'], name='magazine_ma_is_acti_f819fe_idx'),
        ),
    ]
