# Generated by Django 5.0.14 on 2025-10-03 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='E-Mail-Benachrichtigungen aktiviert')),
                ('email_on_expiry', models.BooleanField(default=True, verbose_name='E-Mail bei Ablauf (Prüfungen, Qualifikationen)')),
                ('email_on_low_stock', models.BooleanField(default=True, verbose_name='E-Mail bei niedrigem Lagerbestand')),
                ('email_on_approval_needed', models.BooleanField(default=True, verbose_name='E-Mail bei Freigabe-Anfragen')),
                ('inapp_enabled', models.BooleanField(default=True, verbose_name='In-App-Benachrichtigungen aktiviert')),
                ('notify_inventory', models.BooleanField(default=True, verbose_name='Lagerbestand-Benachrichtigungen')),
                ('notify_vehicles', models.BooleanField(default=True, verbose_name='Fahrzeug-Benachrichtigungen')),
                ('notify_personnel', models.BooleanField(default=True, verbose_name='Personal-Benachrichtigungen')),
                ('notify_inspections', models.BooleanField(default=True, verbose_name='Prüfungs-Benachrichtigungen')),
                ('notify_qualifications', models.BooleanField(default=True, verbose_name='Qualifikations-Benachrichtigungen')),
                ('notify_orders', models.BooleanField(default=True, verbose_name='Bestellungs-Benachrichtigungen')),
                ('notify_system', models.BooleanField(default=True, verbose_name='System-Benachrichtigungen')),
                ('daily_summary', models.BooleanField(default=False, verbose_name='Tägliche Zusammenfassung per E-Mail')),
                ('weekly_summary', models.BooleanField(default=False, verbose_name='Wöchentliche Zusammenfassung per E-Mail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Benachrichtigungs-Einstellung',
                'verbose_name_plural': 'Benachrichtigungs-Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warnung'), ('error', 'Fehler'), ('success', 'Erfolg'), ('reminder', 'Erinnerung'), ('expiry', 'Ablauf'), ('approval', 'Freigabe erforderlich'), ('system', 'System')], db_index=True, default='info', max_length=20, verbose_name='Typ')),
                ('category', models.CharField(choices=[('general', 'Allgemein'), ('inventory', 'Lagerbestand'), ('vehicle', 'Fahrzeuge'), ('personnel', 'Personal'), ('inspection', 'Prüfungen'), ('qualification', 'Qualifikationen'), ('order', 'Bestellungen'), ('system', 'System')], db_index=True, default='general', max_length=20, verbose_name='Kategorie')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Objekt-ID')),
                ('action_url', models.CharField(blank=True, help_text='Link zur Detail-Seite oder Aktion', max_length=500, verbose_name='Aktions-URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Gelesen')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Gelesen am')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Archiviert')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt am')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Benachrichtigung wird nach diesem Datum automatisch archiviert', null=True, verbose_name='Läuft ab am')),
                ('priority', models.IntegerField(default=0, help_text='Höhere Zahl = höhere Priorität', verbose_name='Priorität')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Objekttyp')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger')),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_d8746a_idx'), models.Index(fields=['category', '-created_at'], name='notificatio_categor_6dc2ff_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_4f3289_idx')],
            },
        ),
    ]
