# Generated by Django 5.2.15 on 2026-09-30 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_lat', models.DecimalField(decimal_places=6, default=51.4963, max_digits=9, verbose_name='Mitte Breitengrad')),
                ('center_lng', models.DecimalField(decimal_places=6, default=6.8637, max_digits=9, verbose_name='Mitte Längengrad')),
                ('zoom', models.PositiveSmallIntegerField(default=13, verbose_name='Start-Zoom')),
                ('min_zoom', models.PositiveSmallIntegerField(default=11, verbose_name='Kleinster Zoom')),
                ('max_zoom', models.PositiveSmallIntegerField(default=17, verbose_name='Größter Zoom')),
                ('attribution', models.CharField(blank=True, default='© OpenStreetMap-Mitwirkende', max_length=300, verbose_name='Quellenangabe der Kacheln')),
                ('bbox', models.CharField(blank=True, help_text='z.B. 51.44,6.78,51.56,6.95 – Vorlage für den Kachel-Download', max_length=100, verbose_name='Stadtgebiet (Süd,West,Nord,Ost)')),
                ('show_objects', models.BooleanField(default=True, verbose_name='Objekte der Objektverwaltung auf der Karte anzeigen')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Karteneinstellungen',
                'verbose_name_plural': 'Karteneinstellungen',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('title', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('hazard_type', models.CharField(choices=[('baustelle', 'Baustelle'), ('sperrung', 'Vollsperrung'), ('teilsperrung', 'Teilsperrung / Engstelle'), ('veranstaltung', 'Veranstaltung'), ('loeschwasser', 'Löschwasser eingeschränkt'), ('gefahrstoff', 'Gefahrstoffe / besondere Gefahr'), ('sonstiges', 'Sonstiges')], default='baustelle', max_length=20, verbose_name='Art')),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('active', 'Aktiv'), ('ended', 'Beendet')], default='active', max_length=10, verbose_name='Status')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('start_date', models.DateField(db_index=True, verbose_name='Beginn')),
                ('end_date', models.DateField(blank=True, help_text='Leer = bis auf Weiteres', null=True, verbose_name='Ende')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('house_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hausnummer von')),
                ('house_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hausnummer bis')),
                ('house_side', models.CharField(choices=[('both', 'beide Seiten'), ('even', 'nur gerade Hausnummern'), ('odd', 'nur ungerade Hausnummern')], default='both', max_length=5, verbose_name='Straßenseite')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breitengrad')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Längengrad')),
                ('radius_m', models.PositiveIntegerField(blank=True, help_text='Objekte mit Koordinaten innerhalb dieses Umkreises gelten als betroffen', null=True, verbose_name='Umkreis (m)')),
                ('geometry', models.JSONField(blank=True, help_text='Auf der Karte gezeichnete Linie oder Fläche ({"type": "line"|"polygon", "coords": [[lat, lng], …]})', null=True, verbose_name='Linie / Fläche')),
                ('access_restricted', models.BooleanField(default=False, verbose_name='Zufahrt für Einsatzfahrzeuge eingeschränkt')),
                ('detour', models.TextField(blank=True, verbose_name='Umleitung / Anfahrt')),
                ('hydrants_note', models.TextField(blank=True, verbose_name='Löschwasser / Hydranten')),
                ('leitstelle_note', models.TextField(blank=True, help_text='Erscheint hervorgehoben im Info-Monitor-Widget', verbose_name='Hinweis für die Leitstelle')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='Ansprechpartner')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('source', models.CharField(blank=True, help_text='z.B. Straßenverkehrsbehörde, verkehrsrechtliche Anordnung Nr. …', max_length=200, verbose_name='Quelle')),
                ('attachment', models.FileField(blank=True, help_text='z.B. Verkehrsrechtliche Anordnung oder Lageplan (PDF/Bild)', null=True, upload_to='einsatzvorbereitung/%Y/', verbose_name='Anlage')),
                ('show_on_monitor', models.BooleanField(default=True, verbose_name='Auf Info-Monitoren (Leitstelle) anzeigen')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('created_by', models.ForeignKey(help_text='Benutzer, der diesen Eintrag erstellt hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('updated_by', models.ForeignKey(help_text='Benutzer, der die letzte Aenderung vorgenommen hat', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Aktualisiert von')),
            ],
            options={
                'verbose_name': 'Gefahrenstelle',
                'verbose_name_plural': 'Gefahrenstellen',
                'ordering': ['-start_date', 'title'],
                'permissions': [('einsatz_view', 'Einsatzvorbereitung: Gefahrenstellen und Karte ansehen'), ('einsatz_edit', 'Einsatzvorbereitung: Gefahrenstellen anlegen und bearbeiten'), ('einsatz_manage', 'Einsatzvorbereitung: löschen, Karteneinstellungen und Kacheln verwalten')],
            },
        ),
        migrations.CreateModel(
            name='HazardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Zeitpunkt der Erstellung', verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Zeitpunkt der letzten Aenderung', verbose_name='Aktualisiert am')),
                ('text', models.TextField(verbose_name='Rückmeldung')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Von')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_log', to='einsatzvorbereitung.hazard', verbose_name='Gefahrenstelle')),
            ],
            options={
                'verbose_name': 'Rückmeldung',
                'verbose_name_plural': 'Rückmeldungen',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
    ]
