# Generated by Django 5.2.15 on 2026-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatzvorbereitung', '0001_einsatzvorbereitung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapconfig',
            name='attribution',
            field=models.CharField(blank=True, default='© GeoBasis-DE / BKG (TopPlusOpen), dl-de/by-2-0', max_length=300, verbose_name='Quellenangabe der Kacheln'),
        ),
    ]
