# Generated by Django 5.2.15 on 2026-09-30 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einsatzvorbereitung', '0002_mapconfig_attribution_default'),
        ('objektverwaltung', '0010_firesafetystatement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('object_new', 'Neues Objekt'), ('object_changed', 'Objekt geändert'), ('contact_new', 'Neuer Ansprechpartner'), ('contact_changed', 'Ansprechpartner geändert'), ('contact_deleted', 'Ansprechpartner entfernt'), ('bmz_new', 'Neue Brandmeldezentrale'), ('bmz_changed', 'Brandmeldezentrale geändert'), ('bmz_deleted', 'Brandmeldezentrale entfernt'), ('fsd_new', 'Neues Schlüsseldepot'), ('fsd_changed', 'Schlüsseldepot geändert'), ('fsd_deleted', 'Schlüsseldepot entfernt'), ('hazard_new', 'Neue Gefahrenstelle'), ('hazard_changed', 'Gefahrenstelle geändert'), ('hazard_ended', 'Gefahrenstelle beendet')], max_length=20, verbose_name='Art')),
                ('ref', models.CharField(db_index=True, help_text='Modell und ID des Auslösers, z.B. buildingcontact:12 (für Zusammenfassung)', max_length=60, verbose_name='Bezug')),
                ('title', models.CharField(max_length=250, verbose_name='Titel')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('link_url', models.CharField(blank=True, max_length=300, verbose_name='Link')),
                ('urgent', models.BooleanField(default=False, verbose_name='Dringend')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('done', 'Erledigt')], db_index=True, default='open', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('done_note', models.CharField(blank=True, help_text='z.B. „im ELS eingetragen“', max_length=250, verbose_name='Vermerk')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_items', to='objektverwaltung.buildingobject', verbose_name='Objekt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ausgelöst von')),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Erledigt von')),
                ('hazard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handover_items', to='einsatzvorbereitung.hazard', verbose_name='Gefahrenstelle')),
            ],
            options={
                'verbose_name': 'Übergabepunkt Leitstelle',
                'verbose_name_plural': 'Übergabepunkte Leitstelle',
                'ordering': ['-created_at'],
                'default_permissions': (),
            },
        ),
    ]
